### PR TITLE
[WIP] ZEPPELIN-2986. Add hadoop-aws and hadoop-azure to zeppelin server

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Trivial fix. 

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2986

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
notebook storage is in module zeppelin-zengine. Just found it has jar conflicts with the native azure and s3 storage. Will keep it pending for now.

**Comment by steveloughran** [comment]
# Spark 2.3 has a spark-hadoop-cloud module which adds a set of dependencies on the hadoop cloud modules, throwing out all the transitive conflicting modules. Either pick that up or lift all the exclusion logic there to keep out things like: jackson, guava, joda-time which will only cause pain. Hadoop 2.9+ will move to a shaded aws JAR here.

Do be aware, hadoop-aws is very fussy about aws-SDK versions: that library is a moving target. You can't expect to change versions and not expect to have the code link, let alone run.

**Comment by felixcheung** [comment]
I agree this is going to be a huge moving target to include in the release of the project
Can this be just a list of steps people can follow? Dockerfile or actual Docker images people can use, instead?

**Comment by steveloughran** [comment]
bq. Can this be just a list of steps people can follow?

It's a very brittle list of steps. It's easier at build time as you already have your hadoop version fixed, the hadoop-aws and hadoop-azure poms give you the library versions they need. All you need is to add them *and evict all conflict with the later stuff Spark has chosen*. It's really hard to get this right.

The spark work adds a new optional module and profile to set this up. I'd recommend doing the same thing for now, using the code in spark's POMs to tell you what to exclude

**Pull request closed without merging**
