### PR TITLE
[ZEPPELIN-1686] Added clear output to keyboard shortcut

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
This PR Added "Clear output" of paragraph to the keyboard shortcut.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1686

### How should this be tested?
Click in paragraph and press Ctrl+Shift+c

### Screenshots (if appropriate)
screenshot from 2016-11-27 06-29-27

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@soralee Thanks for your contribution! Tested and it works well as expected 👍

**Comment by Leemoonsoo** [comment]
Thanks @soralee for the contribution.
LGTM

**Comment by 1ambda** [comment]
@soralee This is cool! 👍 

a small suggestions here :) 

- usually, many tools use `CTRL + L` to clear output. Can we use this familiar key instead?

**Comment by soralee** [comment]
@1ambda Thanks for suggestion. :smile: 

I tried that but current `CTRL+L` short key is already worked by editor(ace) as the following picture.
screenshot from 2016-11-28 11-27-57

Furthermore, those short key such as `CTRL+L`, `CTRL+SHIFT+L` `ALRT+L` seem to be interrupt by editor(ace) or browser or OS system.

**Comment by 1ambda** [comment]
Ace users also issued about it. https://github.com/ajaxorg/ace/issues/210 

- I think this is a good feature and will be used so many times by so many people. Thus we should carefully design this shortcut.
- it is hard and not usual to stroke `CTRL + SHIFT + C` for me at least. What about others opinion? we might find better key for this.

**Comment by soralee** [comment]
@1ambda Thanks for sharing issue!!

I guess `CTRL+L` short key is being used by some ace editor users.

So, I removed `CTRL-ALT-L` key binding and I changed **Clear output** short key from `CTRL + SHIFT + C` to `CTRL-ALT-L`

What do you think?

**Comment by soralee** [comment]
Thanks for review @AhyoungRyu  @Leemoonsoo, and could you check this PR again, please?

**Comment by Leemoonsoo** [comment]
Ctrl+Alt+L sounds good to me.

**Comment by AhyoungRyu** [comment]
@soralee Tested again with `ctrl + option(alt) + l` and it works well. LGTM 👍

**Comment by AhyoungRyu** [comment]
Merge into master if there are no more comments

**Comment by AhyoungRyu** [comment]
@soralee I just merged this into master branch. Could you update PR description with latest change? Maybe one day, someone wants to refer this PR to add another keyboard shortcut I think :)
And what is your Jira ID? I need to assign you as `Assignee` to https://issues.apache.org/jira/browse/ZEPPELIN-1686.

**Comment by soralee** [comment]
@AhyoungRyu Thanks for guidance. 
Okay, Let me notify you after updating PR description.
And my JIRA username is `sora`.

**Comment by soralee** [comment]
@AhyoungRyu I updated this PR :smiley:

**Pull request closed without merging**
