### PR TITLE
Adding Boxplot

### PR DESCRIPTION
**Pull request by rookalkar**
This feature adds a BoxPlot. It works seamlessly for about 10,000 rows of data.

I am currently also working on crunching the data required in the back end and pushing it to front end which will then render the chart.

screen shot 2015-09-21 at 11 22 52 am

### CODE REVIEW

**Comment by deepujain** [comment]
1. Please explain what kind of data will render this plot.
2. Please explain the code changes (code documentation) so it will enable other graph support seamlessly.

**Comment by deepujain** [comment]
I see build errors with this patch.

[INFO] Running "jshint:all" (jshint) task
[INFO] 
[INFO] src/app/notebook/paragraph/paragraph.controller.js
[INFO]   line 724  col 0   Identifier 'col_name' is not in camel case.
[INFO]   line 725  col 0   Identifier 'box_column' is not in camel case.
[INFO]   line 725  col 0   Identifier 'col_name' is not in camel case.
[INFO]   line 846  col 4   Missing semicolon.
[INFO]   line 941  col 30  'pivotDataToBoxFormat' was used before it was defined.
[INFO]   line 943  col 0   Identifier 'col_index' is not in camel case.
[INFO]   line 945  col 0   Identifier 'box_column' is not in camel case.
[INFO]   line 945  col 0   Identifier 'col_index' is not in camel case.
[INFO]   line 945  col 28  Expected '!==' and instead saw '!='.
[INFO]   line 947  col 0   Identifier 'col_index' is not in camel case.
[INFO]   line 950  col 0   Identifier 'col_index' is not in camel case.
[INFO]   line 955  col 0   Identifier 'col_index' is not in camel case.
[INFO]   line 963  col 0   Identifier 'whisker_high' is not in camel case.
[INFO]   line 963  col 0   Identifier 'whisker_low' is not in camel case.
[INFO]   line 966  col 49  Expected '===' and instead saw '=='.
[INFO]   line 968  col 50  Expected '===' and instead saw '=='.
[INFO]   line 980  col 0   Identifier 'whisker_low' is not in camel case.
[INFO]   line 982  col 0   Identifier 'whisker_high' is not in camel case.
[INFO]   line 988  col 0   Identifier 'whisker_low' is not in camel case.
[INFO]   line 988  col 0   Identifier 'whisker_low' is not in camel case.
[INFO]   line 989  col 0   Identifier 'whisker_high' is not in camel case.
[INFO]   line 989  col 0   Identifier 'whisker_high' is not in camel case.
[INFO]   line 996  col 34  Expected '===' and instead saw '=='.
[INFO]   line 998  col 6   Missing semicolon.
[INFO]   line 725  col 5   'box_column' is not defined.
[INFO]   line 945  col 15  'box_column' is not defined.
[INFO]   line 983  col 34  'secondHalfOfArrr' is not defined.
[INFO] 
[INFO] ✖ 27 problems
[INFO] 
[INFO] Warning: Task "jshint:all" failed. Use --force to continue.

**Comment by AntoineAugusti** [comment]
I want to try this locally but so far I haven't been able to do it.

I've pulled your branch and run `mvn package` in the `zeppelin-web` folder, after disabling the linting task in Grunt to let the build success. But even after restarting Zeppelin with `bin/zeppelin-daemon.sh restart`, nothing is showing up in the web UI. Am I missing something?

**Comment by rookalkar** [comment]
Hi,

Apologies for the delayed response.
As the BoxPlot model was unavailable for nvd3 version 1.5.1-beta which was
being used, I updated it to version 1.8.1. This has created a d3 conflict
which I'm currently trying to resolve.
However, if you resolve the dependancy conflict manually, it should work.


On 1 October 2015 at 18:11, Antoine Augusti <notifications@github.com>
wrote:

> I want to try this locally but so far I haven't been able to do it.
>
> I've pulled your branch and run mvn package in the zeppelin-web folder,
> after disabling the linting task in Grunt to let the build success. But
> even after restarting Zeppelin with bin/zeppelin-daemon.sh restart,
> nothing is showing up in the web UI. Am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/incubator-zeppelin/pull/321#issuecomment-144715001>
> .
>



-- 
Regards,
Ruchi Ookalkar

**Comment by deepujain** [comment]
Ruchi,
Could you take time to respond to other queries as well. Also am looking to add support for candle stick and unable to get a dev setup to test changes (like console.log and static candle stick code). Appreciate if you can spare time. (@deepujain) on gmail dot com

**Comment by corneadoug** [comment]
There is issue with version 1.8.1 and don't plan on updating it yet.
Also, this PR is a mix of box plot and donut.
Lets close it

**Pull request closed without merging**
