### PR TITLE
[ZEPPELIN-3264] Notebook Snapshot feature.

### PR DESCRIPTION
**Pull request by SleepyThread**
### What is this PR for?
Currently, a user can share the notebook with other users. There is a usage pattern where data analyst creates notebook report and then share with other stakeholders. Meanwhile, they would like to update/change the report and re-publish the results.  

We need a shareable url like,
 /notebook/{**Notebook ID**}/view/{**Snapshot Name**}

which can be shared to other users and can be updated with a logical sharable report. 

### What type of PR is it?
[ Feature | Documentation]

### Todos
* [ ] - CSS and assets changes. 

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3264

### How should this be tested?
* Create git based Notebook. 
* Create 1st commit. 
* Add a snapshot ID. 
* View the snapshot. 

### Screenshots (if appropriate)

create_snapshot

### Questions:
* Does the licenses files need update?
 - No
* Is there breaking changes for older versions?
 - No.
* Does this needs documentation?
 - Yes. Already updated.

### CODE REVIEW

**Comment by mebelousov** [comment]
@SleepyThread thank you! This is a nice feature.

If the PR will be approved it would be great to have next functionality:
- limit the number of snapshots and/or life time of snapshot
- create snapshot for each cron run

**Comment by felixcheung** [comment]
hmm, interesting. how is this different or work with notebook revision on storage like git?

**Comment by SleepyThread** [comment]
@felixcheung this feature just adds a mapping of Snapshot ID to revision id in storage like git. This helps in sharing a static URL by user /notebook/**{Notebook ID}**/view/**{Snapshot Name}** which can be mapped to any revision id in the background. 

This will give the flexibility to have a static report to stakeholders while updates on Notebook can be done in parallel.

**Comment by Tagar** [comment]
@SleepyThread - great feature!

Building on @felixcheung's comment, it would be good if Snapshot feature would use org.apache.zeppelin.notebook.repo.GitNotebookRepo to store a snapshot/revision, so then you could compare revisions etc. 

ps. Looks like commits should be slashed? It shows unrelated commits in this PR.

**Comment by Leemoonsoo** [comment]
Interesting feature, thanks @SleepyThread for the contribution.

**Comment by SleepyThread** [comment]
@Tagar - It is using the revision feature from org.apache.zeppelin.notebook.repo.GitNotebookRepo
in nutshell, a snapshot is like a CNAME to the revision. People can share the CNAME to the external audience and owner can change to snapshot name to any revision they like. 

@Leemoonsoo By mistake, I have rebased some commit from master to make the build pass. I will close this pull request and open a clean one.

**Comment by SleepyThread** [comment]
I have created a [clean pull request](https://github.com/apache/zeppelin/pull/2852). Closing this pull request.

**Pull request closed without merging**
