### PR TITLE
ZEPPELIN-2197. Interpreter Lifecycle Manager

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This PR implement the lifecycle manager. There're 2 implementions.
* NullLifecycleManager.     Nothing is done as before. User has to start/stop interpreter explicitly in UI. 
* TimeoutLifecycleManager.    Interpreter will be closed after idle for one threshold of time. By default it is 1 hour.

### What type of PR is it?
[ Feature]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2197

### How should this be tested?
Unit test is added.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@Leemoonsoo @jongyoul @Tagar  Please help review. Thanks

**Comment by jongyoul** [comment]
I have a basic question. Does it work in `scoped` and `isolated`?

**Comment by Tagar** [comment]
Thank you @zjffdu.
I just thought about this scenario: a Spark job runs for 1.5 hours, would it be killed by the LifeCycleManager in this case? (assuming here default timeout of 1 hour)
If it is, then might be nice also to have a grace period when an interpreter wouldn't be killed if it has a running job?
In the above example, let's say timeout=1 hour and grace period=1 hour. So an interpreter would be killed if it is completely inactive for 1 hour, or in 2 hours if it had a Spark job that was still spinning.
Thoughts?

**Comment by zjffdu** [comment]
@Tagar It won't be killed, because LifecycleManager will know client is polling job progress via api Interpreter.getProgress.  https://github.com/apache/zeppelin/pull/2631/files#diff-f55969c5887615d2142806214747bba9R330

**Comment by zjffdu** [comment]
@jongyoul For now, only Interpreter Process's lifecycle is controlled in TimeoutLifecycleManager. session level control will be done in future if necessary. https://github.com/apache/zeppelin/pull/2631/files#diff-53b72da47096c21dca5f395fe86761b3R16

**Comment by Gauravshah** [comment]
@zjffdu what if I am not on my desk and not polling the job ?

**Comment by zjffdu** [comment]
@Gauravshah It won't be killed. Because JobRunner in zeppelin server process will poll the job status periodically .  Add one more test to verify it.

**Comment by Tagar** [comment]
@zjffdu got it - thank you.

**Comment by Tagar** [comment]
One last thing - from user experience it would be convenient to know when their interpreters timed out. 
Something like a popup or just some sort of a graphical flag would do, I guess?
Not sure how hard it'll be add this at this point.

**Comment by zjffdu** [comment]
@Tagar Good point, Currently there's no such things in frontend. For now, what user see in frontend is that a new interpreter group is created. (For spark interpreter, a new spark app is started)

**Comment by jongyoul** [comment]
Got it. Thanks. I will be able to help you for the future feature.

**Comment by zjffdu** [comment]
Will merge it if no more comments

**Comment by felixcheung** [comment]
could we add some documentation on this? this sounds important...

**Comment by zjffdu** [comment]
Make sense, will add document for this feature.

**Pull request closed without merging**
