### PR TITLE
[HOTFIX] Fix flaky AuthenticationIT

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?

This is hotfix for CI failing for 

Tests in error: 
  AuthenticationIT.testGroupPermission:177->authenticationUser:109->AbstractZeppelinIT.pollingWait:114 Â» Timeout

### What type of PR is it?
[Hot Fix]

### Todos
* [x] -  Add check for request.status === 500, while logout

### What is the Jira issue?
 - [ZEPPELIN-1009](https://issues.apache.org/jira/browse/ZEPPELIN-1009)

### How should this be tested?
Check for CI green 

### Questions:
* Does the licenses files need update? n/a
* Is there breaking changes for older versions? n/a
* Does this needs documentation? n/a

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
CI green ready for review!

**Comment by minahlee** [comment]
Awesome!!! let's merge it

**Comment by prabhjyotsingh** [comment]
Thanks a lot, I'll merge this as a hot fix.

**Comment by prabhjyotsingh** [comment]
@minahlee @bzz @Leemoonsoo After merging this CI is now failing (Build #5323.1) with  

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.zeppelin.python.PythonInterpreterTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/travis/build/apache/zeppelin/zeppelin-interpreter/target/zeppelin-interpreter-0.6.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/travis/build/apache/zeppelin/zeppelin-interpreter/target/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/travis/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (org.apache.zeppelin.interpreter.Interpreter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.365 sec <<< FAILURE! - in org.apache.zeppelin.python.PythonInterpreterTest
testClose(org.apache.zeppelin.python.PythonInterpreterTest)  Time elapsed: 0.262 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.apache.zeppelin.python.PythonInterpreterTest.testClose(PythonInterpreterTest.java:168)


Results :

Failed tests: 
  PythonInterpreterTest.testClose:168 null
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/140172363/log.txt

**Pull request closed without merging**
