### PR TITLE
[ZEPPELIN-5601]Make the page update after excuse the clear output paragraph action

### PR DESCRIPTION
**Pull request by jasmine-song**
### What is this PR for?
The page is not updated after excuse action of clear output paragraph, because the backend don't responese  the column of results when frented send the websocket command PARAGRAPH_CLEAR_OUTPUT. So add the initial value  make sure enter reload logical

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5601

### How should this be tested?
I have problems with CI, but I am able to run them successfully locally.

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Reamer** [comment]
Hi @jasmine-song,
I tried to verify your PR.
If I remove
```
    if (!newPara.results.msg) {
      newPara.results.msg = [];
    }
```
from the codebase, it is possible to clean up the paragraph, because the method `isUpdateRequired(oldPara: ParagraphItem, newPara: ParagraphItem)` now returns `true` because `isEmpty(newPara.results) !== isEmpty(oldPara.results)` returns `true`.

Unfortunately, the paragraph is not filled after a run because `notebookParagraphResultComponents` is empty.

I have tested the behaviour with the following commands.
```
cd zeppelin-web-angular
npm install
SERVER_PROXY=https://my-zeppelin-server.company.com npm start
```

**Comment by Reamer** [comment]
> > Unfortunately,  the paragraph is not filled after a run because notebookParagraphResultComponents is empty'
> 
> is there a problem with running after the clearout paragraphs ?

Not directly, I think it's a different problem. When I execute a paragraph, the result is not displayed until you click in the paragraph.
But this should be fixed in other other PR. Thanks for your Contribution.
I will merge this into master and branch-0.10 on Monday (20/12) if no further comments are received.

**Review by Reamer — APPROVED** [review]

**Comment by jasmine-song** [comment]
@Reamer Oh, what's your code version,  I can't reproduce that phenomenon on my 0.10.0 code version, sounds that the result is
And the PR is run failed, whether you can force merge it

**Comment by Reamer** [comment]
> And the PR is run failed, whether you can force merge it

The failed tests are not related to this PR. Thank you for your contribution. I have merged the changes into master and branch-0.10.

**Pull request closed without merging**
