### PR TITLE
ZEPPELIN-3313 z.getInterpreterContext().out().clear() fails to clear table data

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
z.getInterpreterContext().out().clear() fails to clear table data

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Fix visualizations in a separate ticket

### What is the Jira issue?
[ZEPPELIN-3313](https://issues.apache.org/jira/browse/ZEPPELIN-3313)

### How should this be tested?
see jira description

#### before
before

#### after
after

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @r-kamath , I try another example, but the result seems unstable (sometimes it would display 2 elements), see screenshot.
table_streaming

Another issue is that if I select another chart type, the result would be even more unstable.

**Comment by r-kamath** [comment]
@zjffdu the issue in the second screenshot will not occur when viz switching is enabled, I'm working on it

**Comment by r-kamath** [comment]
@zjffdu currently data update and refresh timing in ui grid is not guaranteed. This issue persists only when the interval is below 1sec. I modified your example with 2sec delay and the rendering is fine.

However, frequent refreshing of ui table is causing too many
`[Violation] 'setTimeout' handler took <N>ms` and
`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>`

About support for Passive Event Listeners: https://stackoverflow.com/a/39187679

**Comment by r-kamath** [comment]
> @zjffdu the issue in the second screenshot will not occur when viz switching is enabled, I'm working on it

Patch will be send in a different PR.

**Comment by zjffdu** [comment]
LGTM

**Comment by r-kamath** [comment]
will merge this if there are no more discussions

**Pull request closed without merging**
