### PR TITLE
[HOTFIX] Fix testWidth selnium test

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Last profile of CI test fails after #1461. This PR fixes it.
```
Tests run: 9, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 110.883 sec <<< FAILURE! - in org.apache.zeppelin.integration.ParagraphActionsIT
testWidth(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 20.055 sec  <<< FAILURE!
java.lang.AssertionError: New Width is : 4
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.apache.zeppelin.integration.ParagraphActionsIT.testWidth(ParagraphActionsIT.java:314)

testWidth(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 20.056 sec  <<< FAILURE!
java.lang.AssertionError: New Width is : 8
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.apache.zeppelin.integration.ParagraphActionsIT.testWidth(ParagraphActionsIT.java:314)
```
### What type of PR is it?
Test fix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Oh it's my bad ㅠ_ㅠ Tested and looks good. Thanks @minahlee for taking care of this!

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by minahlee** [comment]
No worry @AhyoungRyu. Every profile passed on CI, I will merge it as hot fix.

**Pull request closed without merging**
