### PR TITLE
[ZEPPELIN-3191] Update to a current flink version.

### PR DESCRIPTION
**Pull request by jan0sch**
* update to flink 1.4.1
* update flink.akka version to 2.4.20

### What is this PR for?
The currently included flink version is rather old. For that reason we're required to compile zeppelin according to our needs. Because using the current flink (updating akka is important for that) works fine for us in production we're hereby providing a pull request.

### JIRA Issue

[ZEPPELIN-3191](https://issues.apache.org/jira/browse/ZEPPELIN-3191)

### What type of PR is it?
[Improvement]

### CODE REVIEW

**Comment by felixcheung** [comment]
can you open a JIRA
and Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration

**Comment by zjffdu** [comment]
@jan0sch Could you retrigger the build ?

**Comment by jan0sch** [comment]
I'll adjust to the current flink version (1.4.1) before. ;-)

**Comment by felixcheung** [comment]
@jan0sch thanks, could you take a look at the failed tests?

**Comment by jongyoul** [comment]
Flink is updated to 1.5.0 recently. @jan0sch Can you update the version to follow up?

**Comment by jan0sch** [comment]
Closed because overcome by events. See https://github.com/apache/zeppelin/pull/3054 for details.

**Pull request closed without merging**
