### PR TITLE
[ZEPPELIN-1575] Notebook Repo settings UI

### PR DESCRIPTION
**Pull request by anthonycorbacho**
### What is this PR for?
The idea behind this feature is to bring flexibility to the user to let him configure his repo via UI without restarting Apache Zeppelin.
This is flexible enough to handle most of the basic needs, but more complex case can be added in the future. I will not implement all NotebookRepo, this should be done in different PR since it will depend on special needs. I will just provide a simple example with VFS notebook repo.

***NB***: this scope of the PR doesn't include save change in the configuration file of zeppelin as well as implementation of every notebook repo, git, s3 etcetc, this will be added later if needed.

### What type of PR is it?
 * **Improvement**

### Todos
* [x] - Implement backend.
* [x] - Implement frontend.
* [x] - Implement LocalVFS directory change as exemple.

### What is the Jira issue?
 * [ZEPPELIN-1575](https://issues.apache.org/jira/browse/ZEPPELIN-1575)

### How should this be tested?
Go to notebook repo setting page, edit the notebook path and save.

### Screenshots (if appropriate)
notebook_repo_settings

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? YES

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
@anthonycorbacho thanks for suggesting to change repo settings via UI. before testing, do you think we need some unit tests for repo settings feature?

**Comment by anthonycorbacho** [comment]
@khalidhuseynov added some tests

**Comment by anthonycorbacho** [comment]
Please review this PR

**Comment by anthonycorbacho** [comment]
If no more discussion i am going to merge it.

**Comment by khalidhuseynov** [comment]
@anthonycorbacho thanks for tests! tested and LGTM.

**Comment by fcg190677081** [comment]
@anthonycorbacho thanks for your woker very much  ! however,a little problem confused me. I am looking forward to getting your help.
      Notebook Repo could be changed by every user,  Assume that userA and userB, when userA change his Notebook Repo, userB's Notebook Repo will be changed as well.
      Especially in this circumstance，user A and userB keep use  default Repo for a long time. when user A alter Repo,user B find his notebook gone all, that's a bad experience. 
      It will be greatfull if every user has their own Notebook Repo.

**Pull request closed without merging**
