### PR TITLE
[ZEPPELIN-1695] Apply regular maven indent

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

**First of all, this PR doesn't affect on runtime application behaivor and existing build processes. Just styling all pom.xml files**

We have not standardized maven indent currently. I referred [maven code convention](https://maven.apache.org/developers/conventions/code.html) and applied it to this PR.

This is the sub issue of https://github.com/apache/zeppelin/pull/1662

### What type of PR is it?
[Improvement]

### What is the Jira issue?

[ZEPPELIN-1695](https://issues.apache.org/jira/browse/ZEPPELIN-1695)

### How should this be tested?

CI will be enough.

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
\cc @bzz for reviewing this issue. (related to https://github.com/apache/zeppelin/pull/1662)

thanks!

**Comment by bzz** [comment]
AFAIK there is going to be at least few other changes that will most probably affect this PR i.e #1674  and #1339 - may be we should prioritize those smaller ones, and then rebase\merge this guy?

What do you think, @1ambda ?

**Comment by 1ambda** [comment]
@bzz We can rebase and merge smaller PRs first like https://github.com/apache/zeppelin/pull/1668 and #1339 you mentioned. 

I will rebase #1668 first.

**Comment by bzz** [comment]
Sounds good, let's take care of small parts first, and then rebase and merge this guys in a bulk!

**Comment by 1ambda** [comment]
Let's close. Since it's outdated.

**Pull request closed without merging**
