### PR TITLE
ZEPPELIN-3239. unicode characters in an iPython paragraph makes Spark interpreter irresponsive

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

Fix the unicode issues in python2.

### What type of PR is it?
[Bug Fix | Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3239

### How should this be tested?
* Unit test is added

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@Tagar Could you help try verify this PR ? Thanks

**Comment by Tagar** [comment]
thanks @zjffdu! will give this a try today.

**Comment by Tagar** [comment]
Verified manually. Works as expected. Thanks a lot @zjffdu

**Comment by zjffdu** [comment]
Awesome，will merge it soon

**Pull request closed without merging**
