### PR TITLE
[ZEPPELIN-1110] Catch Exception in ZeppelinIT. testSparkInterpreterDependencyLoading

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Catch Exception in case dialog is removed from dom to fix flaky test of `ZeppelinIT. testSparkInterpreterDependencyLoading`

### What type of PR is it?
Hot Fix

### What is the Jira issue?
[ZEPPELIN-1110](https://issues.apache.org/jira/browse/ZEPPELIN-1110)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by bzz** [comment]
Looks good to me

**Comment by prabhjyotsingh** [comment]
👍

**Comment by minahlee** [comment]
Let me merge this into master as hotfix once the selenium test of last commit becomes green.

**Comment by bzz** [comment]
CI is green now! :shipit:

**Pull request closed without merging**
