### PR TITLE
[MINOR] Move tutorial notes under one folder

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Change title of tutorial notes so all of them can be placed under one folder.

### What type of PR is it?
Documentation

### Screenshots (if appropriate)
Before
screen shot 2016-11-17 at 4 01 45 pm

After
screen shot 2016-11-18 at 5 34 30 pm

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Comment by Leemoonsoo** [comment]
Shell we give little more information in the title about the tutorials? like

* Zeppelin Tutorial
    * Basic features (Spark)
    * Matplotlib (Python/pyspark)
    * R (sparkR)
    * Using Mahout

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge to master if there're no more comments.

**Pull request closed without merging**
