### PR TITLE
[Refactoring] some opportunities to use diamond operator

### PR DESCRIPTION
**Pull request by desmorto**
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

[Bug Fix | Improvement | Feature | Documentation | Hot Fix | Refactoring]

* [x] - Task

* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* Put link here, and add [ZEPPELIN-*Jira number*] in PR title, eg. [ZEPPELIN-533]

Outline the steps to test the PR here.

* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by desmorto** [comment]
already signed with travis

**Comment by 1ambda** [comment]
@desmorto  thanks for the contribution. 

1. Could you create a JIRA ticket?
2. files under `/thrift` are auto-generated, so we can't modify. 
3. You need to the forked repository for Zeppelin. The name must be `zeppelin`. Please read http://zeppelin.apache.org/contribution/contributions.html#continuous-integration

**Comment by desmorto** [comment]
i added the zeppelin to my travis

**Comment by 1ambda** [comment]
@desmorto Then could you close and reopen this PR to retrigger jenkins again?

https://builds.apache.org/job/zeppelin-pull-request/2363/console

**Comment by desmorto** [comment]
i will try it

**Comment by desmorto** [comment]
i really don't understand whats is going on

```
+ python ./travis_check.py desmorto 75791b8656e38f8b361ed02fb9e4f29e9c086298
[2017-07-19 19:17:25] Author: desmorto, commit: 75791b8656e38f8b361ed02fb9e4f29e9c086298
[2017-07-19 19:17:25] --------------------------------
[2017-07-19 19:17:30] Get build status ...
[2017-07-19 19:17:30] Can't find build for commit 75791b8656e38f8b361ed02fb9e4f29e9c086298 from desmorto
+ RET_CODE=2
+ '[' 2 -eq 2 ']'
+ set +x
-----------------------------------------------------
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
And then make sure 'Build branch updates' option is enabled in the settings https://travis-ci.org/desmorto/zeppelin/settings.

To trigger CI after setup, you will need ammend your last commit with
git commit --amend
git push your-remote HEAD --force
```

do i need execute these lines in my repo?

```
git commit --amend
git push your-remote HEAD --force
```

**Comment by 1ambda** [comment]
It says `Looks like travis-ci is not configured for your fork.`

If you set already travis CI for your fork, could you provide the link? i can help u.

**Pull request closed without merging**
