### PR TITLE
[ZEPPELIN-2168] Fix typo on Elasticsearch interpreter help

### PR DESCRIPTION
**Pull request by juanpaulo**
### What is this PR for?
Fix typo on Elasticsearch interpreter help

### What type of PR is it?
Documentation

### Todos
* Fix typo (ndex to index)

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2168

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
LGTM

**Comment by tae-jun** [comment]
LGTM 😄

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by AhyoungRyu** [comment]
Merge into branch-0.7 and master if there are no more comments on this.

**Pull request closed without merging**
