### PR TITLE
MINOR Update asf.yaml to link with JIRA

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Update asf.yaml from https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

### What type of PR is it?
[Improvement]

### Todos
* [x] - Add notification section

### What is the Jira issue?
N/A

### How should this be tested?
After merging it, all new PR will be link with JIRA automatically

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
This PR also includes a limitation for the merge button to `Squash and merge` only

**Review by Reamer — APPROVED** [review]
LGTM
Can you please update the link to the wiki page
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

**Comment by zjffdu** [comment]
LGTM

**Comment by jongyoul** [comment]
@Reamer 
>Can you please update the link to the wiki page
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

I might not understand clearly your comment. Could you please explain more about it?

**Comment by Reamer** [comment]
> @Reamer
> 
> > Can you please update the link to the wiki page
> > https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
> 
> I might not understand clearly your comment. Could you please explain more about it?

In the same file we have a link to the cwiki. Take a look into [line 18](https://github.com/apache/zeppelin/blob/5bbefdba4ea1d06559d6f79f8abd9b651ff7634f/.asf.yaml#L18). We should also correct the link to the cwiki.

**Comment by jongyoul** [comment]
@Reamer Fixed the comment.

**Pull request merged**
