### PR TITLE
ZEPPELIN-2982. Copy interpreter-setting.json to interpreter dir

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
2 main changes.
* Introduce `interpreter-parent` module, so that all the interpreter can reuse the plugin defined in `interpreter-parent`
* Add new plugin for `copying interpreter-setting.json` to interpreter dir

### What type of PR is it?
[ Improvement | Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2982

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Each release, interpreter jars are published in maven repository and `bin/install-interpreter.sh` lets user download and install interpreters. Is this change keeps capability to both publish and download interpreter jars?

**Comment by zjffdu** [comment]
Yes, it keeps capability. The interpreter is not changed. interpreter-setting.json is still packaged into interpreter jar, but copied to interpreter dir as well in this PR. And interpreter-setting.json under interpreter dir take precedence over that in interpreter jar.  see https://github.com/apache/zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSettingManager.java#L263

**Comment by Leemoonsoo** [comment]
I see. Could you also explain little bit about why you decided to make `interpreter-parent` module instead of just add copy plugin to existing common parents `zeppelin-interpreter` ?

This may require some additional update

  - [Interpreter dev guide](https://github.com/apache/zeppelin/blob/master/docs/development/writing_zeppelin_interpreter.md#make-your-own-interpreter) - which parent module should use to create new interpreter
  - [Interpreter list in Helium menu](https://github.com/apache/zeppelin/blob/gh-pages/helium_packages.md) - Interpreter's are collected using on dependency `zeppelin-interpreter`. (see https://github.com/apache/zeppelin/pull/2037)

**Comment by zjffdu** [comment]
@Leemoonsoo parent project must be pom type, but zeppelin-interpreter is jar. So I have to introduce module `interpreter-parent`.  Interpreter dev guide is updated in the new commit.

**Comment by Leemoonsoo** [comment]
Ah, i see. I think i have confused between parent project and dependency.

**Comment by zjffdu** [comment]
will merge if no more discussion

**Pull request closed without merging**
