### PR TITLE
[ZEPPELIN-1245] Focus first paragraph after notebook creation

### PR DESCRIPTION
**Pull request by rajarajan-g**
### What is this PR for?
Once the notebook is created, cursor should focus on the first paragraph

### What type of PR is it?
Bug Fix 

### Todos
* [ ] - None

### What is the Jira issue?
 https://issues.apache.org/jira/browse/ZEPPELIN-1245

### How should this be tested?
Once the Zeppelin server is started , Create a new notebook
check if cursor blinks on the first paragraph of the notebook

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@rajarajan-g Thanks! for the contribution.

Tested this PR and it focuses the first paragraph after the note creation. Works great!
However, if i open existing note, the focus goes to the last paragraph.

Do you have any idea about default focusing behavior when existing note open?

**Comment by rajarajan-g** [comment]
@Leemoonsoo : Thanks for reviewing the code

I did check the existing behaviour , for existing note it doesn't focus to any paragraph.

So,I did code changes now in such way, if we create notebook/open an existing notebook, it will focus on the first paragraph.

For existing notebook, i do focus to end of the paragraph.I hope those changes are fine.

**Comment by rajarajan-g** [comment]
Reopening the pull request to trigger CI build.

**Comment by rajarajan-g** [comment]
CI build is success now. Please do review and let me in know in comments

**Comment by corneadoug** [comment]
I just tested this branch, but it isn't doing anything in my case

**Comment by corneadoug** [comment]
Erratum, I was testing master branch

**Comment by corneadoug** [comment]
In the case that the 1st paragraph's editor is hidden, it doesn't select. Do we care?

**Comment by rajarajan-g** [comment]
In my opinion, since the editor itself is not available, it shouldn't focus that paragraph which is also behaviour after this PR

If you/other folks have any other opinions, please let me know.

**Comment by corneadoug** [comment]
I agree too.
LGTM

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by corneadoug** [comment]
@rajarajan-g Can you tell me your Jira username?

**Comment by rajarajan-g** [comment]
its 'thinktank'

**Pull request closed without merging**
