### PR TITLE
ZEPPELIN-3136. IPython Code Completion Improvement

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

This is for better code completion support for IPythonInterpreter

### What type of PR is it?
[Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3136

### How should this be tested?
* Unit test is updated and Manually verified. 

### Screenshots (if appropriate)
code_completion

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@prabhjyotsingh @felixcheung Mind to help review it ?

**Comment by mebelousov** [comment]
I have tested.
It's very useful bug fix.
@zjffdu thank you!

**Comment by zjffdu** [comment]
Thanks @mebelousov for testing it.

**Comment by prabhjyotsingh** [comment]
Tried it on local, works well.

**Pull request closed without merging**
