### PR TITLE
[ZEPPELIN-890] Cache downloaded file from 'maven-download-plugin' 

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Cache downloaded file from 'maven-download-plugin' to improve CI build speed and reduce build failure due to network issue.

### What type of PR is it?
Improvement

### Todos
* [x] - Cache '.m2/repository/.cache/maven-download-plugin' directory

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-890

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
One more suggestion not sure if that is relevant to this PR should we have `<retries>5</retries>` near https://github.com/apache/zeppelin/blob/master/spark-dependencies/pom.xml#L827 and
https://github.com/apache/zeppelin/blob/master/spark-dependencies/pom.xml#L907 ?

**Comment by Leemoonsoo** [comment]
@prabhjyotsingh Thanks for suggestion. Once travis caches '.m2/repository/.cache/maven-download-plugin' directory, 'maven-download-plugin' will not even try to download files from internet. So i think i'll be okay without increasing retry count.

**Comment by prabhjyotsingh** [comment]
Thank you for the explanation, I understand it now.

**Comment by Leemoonsoo** [comment]
Merge if there're no further discussions

**Comment by prabhjyotsingh** [comment]
Sure, I think we can merge this as a hotfix.

**Comment by khalidhuseynov** [comment]
LGTM

**Pull request closed without merging**
