### PR TITLE
ZEPPELIN-3699. Remove the logic of converting single result to multiple results

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
It is a refactoring PR. Zeppelin introduce multiple interpreter result in 0.7, and also introduce logic of converting single result to multiple results. I think it it good time to remove that for 0.9, as I believe no one is using zeppelin before 0.7 for now.

### What type of PR is it?
[Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3699

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Which api do you mean ? @felixcheung

**Comment by felixcheung** [comment]
Paragraph or REST API.
though looks like it will break all existing notebook saved since it changes the persistent json. is there a way to make them compatible?

**Comment by zjffdu** [comment]
It doesn't change the persistent json. In the current code, we have already save the note json via multiple interpreter result. The side effect of this PR is that zeppelin 0.9 can not read the note json format before 0.6

**Comment by zjffdu** [comment]
Will merge if no more comments

**Pull request closed without merging**
