### PR TITLE
[ZEPPELIN-2202] Disable personalized mode btn when note is running (master)

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Disable the personalized mode button when a note is running.

- This improvement is done in https://github.com/1ambda/zeppelin/commit/0afacbf45e9d4e96121b662da87d4b7e3c655838.
- The second commit https://github.com/1ambda/zeppelin/commit/305ad05790c09920539f3e5b4e4763d04ccabfab is about refactoring.
- So please review https://github.com/1ambda/zeppelin/commit/0afacbf45e9d4e96121b662da87d4b7e3c655838 first.

### What type of PR is it?
[Improvement]

### Todos

NONE

### What is the Jira issue?

[ZEPPELIN-2202](https://issues.apache.org/jira/browse/ZEPPELIN-2202)

### How should this be tested?

Refer the screenshot below.

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
@jongyoul Can you help review this?

**Comment by jongyoul** [comment]
Tested. LGTM. Merging if there's no more discussion

**Comment by 1ambda** [comment]
I'v just updated code. @Leemoonsoo Could you review again? Thanks!

**Comment by 1ambda** [comment]
This is the same fix for branch-0.7 

- https://github.com/apache/zeppelin/pull/2115/files

**Pull request closed without merging**
