### PR TITLE
[ZEPPELIN-5229] - bump flink 1.10 minor version

### PR DESCRIPTION
**Pull request by omrisk**
### What is this PR for?
Bumping flink minor version, fixing minor flink doc typos

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5229

### How should this be tested?
Automation and builds 

### Questions:
* Does the licenses files need update? - no 
* Is there breaking changes for older versions? - no
* Does this needs documentation? - no

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @omrisk, there's another place needs to update flink version.
https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/FlinkIntegrationTest110.java#L32

**Comment by omrisk** [comment]
@zjffdu, thanks, missed that, fixed.
Newbie question, should parameters like that be extracted to a `.properties` file (in a seperate issue/PR)?
So that versions can be fully managed for builds in tests with a single source for the values?

**Comment by zjffdu** [comment]
That's would be better, @omrisk maybe put them in project root pom.xml. 
If that is possible, we should do the same thing for spark as well.

**Comment by omrisk** [comment]
@zjffdu , opened this separate ticket for that https://issues.apache.org/jira/browse/ZEPPELIN-5247.
I'll try to handle soon

**Comment by zjffdu** [comment]
LGTM, will merge if no more comment.

**Pull request closed without merging**
