### PR TITLE
ZEPPELIN-2459 Zeppelin Usability Improvement for new paragraph

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
Move cursor to second line for new paragraphs

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
ZEPPELIN-2459

### How should this be tested?
For a new paragraph he initial cursor position should be on the second line.

### Screenshots (if appropriate)
**Before**
screen shot 2017-04-26 at 10 27 48 pm

**After**
screen shot 2017-04-26 at 10 27 33 pm

### Questions:
* Does the licenses files need update? n/a
* Is there breaking changes for older versions? n/a
* Does this needs documentation? n/a

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Tested locally, LGTM.

**Comment by zjffdu** [comment]
BTW, could we change the cursor to a slim line ? I heard people complain about the cursor too thick

**Comment by r-kamath** [comment]
@zjffdu I think we should handle the cursor style in a different jira

**Comment by zjffdu** [comment]
@r-kamath Yeah, no problem.

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
