### PR TITLE
[ZEPPELIN-3091] Correct aggregation functionality in charts

### PR DESCRIPTION
**Pull request by namanmishra91**
### What is this PR for?
The aggregation functions interpret NaN columns as 1 which leads to incorrect output being shown in charts. This PR fixes this by correcting the sum, min, max and average aggregation method.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3091

### How should this be tested?
* Update the data field of a paragraph results with %table to contain null values, e.g.
`"data": "age\tvalue\n19\t4\n20\t3\n21\t7\n22\t9\n23\t20\n24\t24\n25\t44\n26\t77\n27\t94\n28\t103\n29\t97\n20\t5\n20\tnull\n"`

The "null" values should be ignored for sum, min, max but included for count (and hence average).

### Screenshots (if appropriate)
correct_sum

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by namanmishra91** [comment]
Ping

**Comment by Leemoonsoo** [comment]
Thanks @namanmishra91 for important fix. Do you think you can add test case like https://github.com/apache/zeppelin/pull/2685, to ensure no future change break this aggregation behavior? Let me know if you need any help.

**Comment by namanmishra91** [comment]
@Leemoonsoo Thanks. I have added a test case as you mentioned. Please have a look.

**Comment by Leemoonsoo** [comment]
Thanks @namanmishra91. Looks great to me!
Merge to master if no further comment.

**Pull request closed without merging**
