### PR TITLE
[ZEPPELIN-1144]Zeppelin home page should only list notebooks with read or write permission

### PR DESCRIPTION
**Pull request by mwkang**
### What is this PR for?
If logged in user does not have Read and Write permission for a notebook, user should not see the notebook in the zeppelin home page.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1144

### How should this be tested?
* unit test
* online test

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by mwkang** [comment]
CI error
```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 76.102 sec - in org.apache.zeppelin.integration.SparkParagraphIT

Results :

Tests in error: 
  ZeppelinIT.testAngularDisplay:118->AbstractZeppelinIT.waitForParagraph:70->AbstractZeppelinIT.pollingWait:96 쨩 Timeout
  AuthenticationIT.testGroupPermission:179->AbstractZeppelinIT.pollingWait:96 쨩 Timeout

Tests run: 15, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by bzz** [comment]
Thank you for fixing it @mwkang 

CI failure looks somehow relevant, you can not reproduce it locally?

**Comment by mwkang** [comment]
@bzz I will check it. Thanks for review.
When I fix CI, I'll mention you.

**Comment by mwkang** [comment]
@bzz https://github.com/apache/zeppelin/pull/1330#issuecomment-239997747 It did not reproduce in local. Can you check this?

**Comment by bzz** [comment]
@mwkang could you please try close and then re-open this PR to trigger the CI and see if the same issue persists? Thanks!

\cc @khalidhuseynov for review.

**Comment by khalidhuseynov** [comment]
@mwkang thanks for the contribution! actually this is related to multi-user note management and there's some work going on under #1392 or #1390 . 

In your case, i tested it, and there's a bit tricky moment with notes reloading and broadcasting. For example if you login as user1 with noteA and user2 with noteB and initially everything looks as expected, and then you reload your notes as shown below with refresh icon:
screen shot 2016-09-02 at 5 52 10 pm
then if you refresh for user1 then noteA will appear in the list of all users, including user2 in our case. Same would happen if you reload for user2, meaning noteB will appear in the list of user1.

**Comment by echarles** [comment]
If the current single `notebook-authorization.json`  is managed by user (with multiple files, and no more with a single one), how would you handle it?

**Comment by khalidhuseynov** [comment]
@mwkang could you re-trigger CI?

**Comment by khalidhuseynov** [comment]
I think it doesn't solve all problems, but definitely in the roadmap. LGTM

**Comment by bzz** [comment]
Thank you @mwkang @khalidhuseynov !

Will merge to master, if there is no further discussion.

**Comment by Leemoonsoo** [comment]
@mwkang @khalidhuseynov Could you handle or at least create issues for expected problems after merge this PR? I can at least think following two issues,

- Note list broadcasting message is not aware user session, so notebook list can display notes that supposed to not see when other user refresh the notebook list.
- When a user changes the permission of a note, note list need to be broadcasted immediately so all connected users can have updated list of notebook. Otherwise, there's still some chances that a user able to see some note on notebook list that they can not access.

**Comment by khalidhuseynov** [comment]
@Leemoonsoo issues are created under [ZEPPELIN-1437](https://issues.apache.org/jira/browse/ZEPPELIN-1437) and [ZEPPELIN-1438](https://issues.apache.org/jira/browse/ZEPPELIN-1438) correspondingly

**Comment by Leemoonsoo** [comment]
Thanks, Merge to master if there're no further discussions.

**Comment by mwkang** [comment]
I'm sorry for no-reply long time. my plate was full.
I will finish other 2 PRs and then If ZEPPELIN-1437 and ZEPPELIN-1438 are status is unresolved, I will 
try to resolve.
If is it okay..

**Pull request closed without merging**
