### PR TITLE
[ZEPPELIN-6011] fix `zeppelin/scripts/docker/zeppelin/bin/Dockerfile` Dockerfile JAVA_HOME to openjdk11 

### PR DESCRIPTION
**Pull request by flowy0**
### What is this PR for?
To update `zeppelin/scripts/docker/zeppelin/bin/Dockerfile` to OpenJDK 11

Follow up PR from https://github.com/apache/zeppelin/pull/4751

### What type of PR is it?
Bug Fix

### What is the Jira issue?
* [ZEPPELIN-6011](https://issues.apache.org/jira/browse/ZEPPELIN-6011)

### How should this be tested?
* Outline any manual steps to test the PR here.
  * Not too sure how to automate this testing as i'm new at this.

### CODE REVIEW

**Comment by jongyoul** [comment]
@flowy0 Hello, you don't have to make a pro for branch-0.11 directly. After the PR is merged, committers can cherry-pick for the commit into release branches. However, the opposite way is impossible. so could you please make a PR that is based on the master branch?

**Comment by flowy0** [comment]
> @flowy0 Hello, you don't have to make a pro for branch-0.11 directly. After the PR is merged, committers can cherry-pick for the commit into release branches. However, the opposite way is impossible. so could you please make a PR that is based on the master branch?

Understood, opened PR #4753

**Comment by jongyoul** [comment]
Could you please close this PR?

**Comment by jongyoul** [comment]
I saw you open a new PR for this issue for the master branch #4753

**Pull request closed without merging**
