### PR TITLE
[WIP] ZEPPELIN-209 Folder structure for notebook

### PR DESCRIPTION
**Pull request by Leemoonsoo**
https://issues.apache.org/jira/browse/ZEPPELIN-209

Treating '/' as path separator and navigating notebook using submenu

### CODE REVIEW

**Comment by nberserk** [comment]
don't we need some kind of folder browser just like the nbviewer of ipython ?

**Comment by zhongneu** [comment]
What is the status of this pr now?

**Comment by Leemoonsoo** [comment]
I'm not working on it at the moment.
Basically this PR works, but it need to be polished and there're some bugs.
If somebody have better front-end skill can look at it, that would be really helpful.

**Comment by zhongneu** [comment]
@Leemoonsoo I am working on some refinements of this pr on this branch: https://github.com/zhongneu/incubator-zeppelin/tree/test-folder

There are still some bugs:
1. need a better "folder opened" icon. Any recommendation on this? it seems the current icon library doesn't' include one...
2. the mouse cursor is not correct over folders on homepage
3. the first item inside a folder in the pull-down list doesn't work well

I have almost no experience in front-end development, so any guidance will be really appreciated.

**Comment by zhongneu** [comment]
@Leemoonsoo @corneadoug I've made a coupe of fixes, and now it works pretty well, but still have one problem: we can click the folder in dropdown, and goes into an empty notebook. I am not sure about how to resolve this properly. Besides, the css styles for dropdown-menu and dropdown-submenu seems a little bit mess. I am not sure whether it is OK.

I don't want to introduce any bad smells into the frontend code, so I will be really appreciate your review and guidance.

**Comment by corneadoug** [comment]
@zhongneu How about creating a PR instead?
It will be easier to comment on the code. You can always base your PR on this one.
Once it's done, ping me in it and I will check your code and try to provide some guidance, and also try to provide some solutions to your problems.

**Pull request closed without merging**
