### PR TITLE
[ZEPPELIN-2112] Disable keyboard shortcut in "Link this paragraph" URL on 0.7.0 version

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
If using a `Link this paragraph`, new window works the keyboard shortcut on the 0.7.0 version.
So that this is the keyboard shortcut should not work in `Link this paragraph` URL on branch-0.7.

Also, I remove border and margin of paragraph in new window of "Link this paragraph". this would be more useful.

This issue is related to [ZEPPELIN-1808](https://issues.apache.org/jira/browse/ZEPPELIN-1808) and this [comment](https://github.com/apache/zeppelin/pull/1983#issuecomment-279395050) suggestion by @Leemoonsoo. 

### What type of PR is it?
[Bug Fix | Improvement]

### Todos
* [x] - Disable keyboard shortcut in new window of "Link this paragraph" on 0.7.0 version
* [x] - Fix layout about border and margin in paragraph website

### What is the Jira issue?
* [ZEPPELIN-2112](https://issues.apache.org/jira/browse/ZEPPELIN-2112)

### How should this be tested?
1. Build `branch-0.7` branch and run Zeppelin
2. Click `Link this paragraph` or Use Ctrl+Alt(command)+w in a paragraph.
3. Use some keyboard shortcut in new window which is created by `Link this paragraph`.
4. Check text and title shape of the paragraph such like text, title, graph.. etc.

### Screenshots (if appropriate)
[ Before ]
z_2112_b

[ After ]
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by soralee** [comment]
Ping! @Leemoonsoo

**Comment by Leemoonsoo** [comment]
Tested and LGTM.

Merge to branch-0.7 if no more comment.

**Comment by Leemoonsoo** [comment]
@soralee I merged this PR to `branch-0.7`. But somehow this PR can not be closed by `asfgit`. Can you close this PR manually?

**Comment by soralee** [comment]
@Leemoonsoo Sure, I'll close this PR.

**Pull request closed without merging**
