### PR TITLE
[ZEPPELIN-1062] Get original InterpreterSetting when there is no change

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
When we update interpreter property values, we edit some values and click "save" button. Then a bootstrap dialog is show up. In this step, if we click "cancel", the updated value is still existed in the table. This new value is not stored actually. After refresh, the original value will be shown. 

I just get original InterpreterSetting(`getInterpreterSettings()`) when there is no change(`result`) for fixing this bug.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
[ZEPPELIN-1062](https://issues.apache.org/jira/browse/ZEPPELIN-1062)

### How should this be tested?
It's really simple. Just see the below attached screenshots. 

### Screenshots (if appropriate)
 - Before
interpreter_setting

- After
after

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
IMO, when user clicks on cancel after clicking on save; user should see the edit view back.

**Comment by prabhjyotsingh** [comment]
Also what happens when user clicks on close ("x") button, instead of "OK" or "Close" ?

**Comment by AhyoungRyu** [comment]
@prabhjyotsingh Sorry for my late response. You're right. After  just clicking `cancel`, it should focus on textbox again as you said. And regarding your second comment, I blocked ESC back drop & `x` closing. Could you check this again?

**Comment by prabhjyotsingh** [comment]
Thank you for taking care of it. LGTM.

**Pull request closed without merging**
