### PR TITLE
[ZEPPELIN-5354]  Inconsistent bold markdowns of keywords in 'binding mode" document 

### PR DESCRIPTION
**Pull request by cuspymd**
### What is this PR for?
Fix bold markdowns of keywords in "interpreter binding mode" document for consistency

### What type of PR is it?
[Documentation]

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5354

### How should this be tested?
* Checked updated document locally

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @cuspymd for the contribution, BTW could you create an umbrella ticket for the document related issues ? so that you can put all the documentation fix as the subtask of this umbrella ticket

**Comment by cuspymd** [comment]
> Thanks @cuspymd for the contribution, BTW could you create an umbrella ticket for the document related issues ? so that you can put all the documentation fix as the subtask of this umbrella ticket

Can you tell me how to create an umbrella ticket? I will refer to it in the next PR.

**Comment by zjffdu** [comment]
@cuspymd It is the same as general jira ticket, just naming it as umbrella ticket and link other tickets as its subtask. https://issues.apache.org/jira/browse/ZEPPELIN-4936

**Comment by zjffdu** [comment]
Will merge if no more comment

**Pull request closed without merging**
