### PR TITLE
[ZEPPELIN-5527] Remove the dependency of `markdown` from `zeppelin-jupyter`

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Simplifying dependences.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Remove the dependency of `markdown` and implement a markdown parser directly

### What is the Jira issue?
* Jira https://issues.apache.org/jira/browse/ZEPPELIN-5527

### How should this be tested?
Import Jupyter notebook

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
This is just cloning markdown parser from `zeppelin-markdown`. I'll merge it if there's no critical problem.

**Comment by Reamer** [comment]
I think we should manage the flexmark version globally in the zeppelin parent pom.xml. After that we can use the same dependency in zeppelin-markdown and zeppelin-jupyter.
It would be nice if you could remove `pegdown` from `markdown/README.md`. I have forgotten this in my PR.

**Comment by jongyoul** [comment]
@Reamer I've updated some docs about deprecation on `Pegdown`.

**Comment by Reamer** [comment]
> @Reamer I've updated some docs about deprecation on `Pegdown`.

Thanks :+1:

**Comment by jongyoul** [comment]
Will merge it if there's no issue.

**Review by Reamer — APPROVED** [review]
LGTM

**Pull request closed without merging**
