### PR TITLE
[ZEPPELIN-2365] button to create note into folder

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Added button to create new note into folder (home page)

### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2365

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by soralee** [comment]
Thanks for improvement @tinkoff-dwh!
Let me test and I'll give you feedback!

**Comment by tae-jun** [comment]
Cool feature! LGTM 👍

**Comment by soralee** [comment]
@tinkoff-dwh, Before testing, could you rebase for resolving conflicts, too? :slightly_smiling_face:

**Comment by soralee** [comment]
Thanks @tinkoff-dwh for quick resolving!
Let me check again if CI become green.

**Comment by soralee** [comment]
Tested and it's work well, LGTM!

**Comment by Leemoonsoo** [comment]
Thanks for the new feature. LGTM and merge to master if no further discussions.

**Pull request closed without merging**
