### PR TITLE
ZEPPELIN-1027: Python - add basic matplotlib example notebook

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
It adds basic [python matplotlib example notebook](https://www.zeppelinhub.com/viewer/notebooks/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2J6ei9pbmN1YmF0b3ItemVwcGVsaW4vMTkyZjU3YjZjMGZkMjc4NzgwZDI3NDAzMGY1YmJlOTZlZThkNzdiYi9ub3RlYm9vay8yQlFBMzVDSlovbm90ZS5qc29u).

### What type of PR is it?
Improvement | Documentation

### What is the Jira issue?
[ZEPPELIN-1027](https://issues.apache.org/jira/browse/ZEPPELIN-1027)

### How should this be tested?
New [zeppelin notebook](https://www.zeppelinhub.com/viewer/notebooks/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2J6ei9pbmN1YmF0b3ItemVwcGVsaW4vMTkyZjU3YjZjMGZkMjc4NzgwZDI3NDAzMGY1YmJlOTZlZThkNzdiYi9ub3RlYm9vay8yQlFBMzVDSlovbm90ZS5qc29u) shows up in the list.

### Screenshots (if appropriate)
screen shot 2016-06-17 at 14 49 31

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
I'm planning to add at least one more tutorial notebook of using python, something similar to what we have for Apache Spark but with pandas and matplotlib etc.

Do you guys think advanced one should be incorporated in here - :confused:, or shall we have a separate one 😄  , say title "Zeppelin Tutorial: Python - pandas, matplotlib".

**Comment by minahlee** [comment]
I hope we have more example notebooks. Once we have a lot of example notebooks, it won't be efficient to keep all of them embedded in Zeppelin by default. I guess we will manage most of example notebooks on the website in the end. IMO better to separate them by usage so that user can find example notebooks easily on his demand.

**Comment by bzz** [comment]
Makes perfect sense to me

**Comment by AhyoungRyu** [comment]
Yeah  👍  for @minahlee. And it looks good! :)

**Comment by prabhjyotsingh** [comment]
Good one, we should have it. LGTM.

**Comment by bzz** [comment]
Thank you for prompt reviews!

Merging fi there is no further discussion

**Pull request closed without merging**
