### PR TITLE
[ZEPPELIN-2274] - update cron UI

### PR DESCRIPTION
**Pull request by Savalek**
### About PR
This PR change cron ui on more user-friendly.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
[ZEPPELIN-2274](https://issues.apache.org/jira/browse/ZEPPELIN-2274)

### Screenshots (if appropriate)
peek 2019-01-24 11-47

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by liuxunorg** [comment]
The effect is good. It means that the color matching of the interface is not well coordinated with zeppelin, and the background color of the editing area on the right may be better.

**Comment by prabhjyotsingh** [comment]
The theme does not match our notebook UI, otherwise looks good.

**Comment by felixcheung** [comment]
@liuxunorg can you consider an update on the UI color scheme?

**Comment by felixcheung** [comment]
ping @Savalek

**Comment by Savalek** [comment]
I'm not strong in the front end)
Do you want me to replace all selections with input?

**Pull request closed without merging**
