### PR TITLE
pom.xml change

### PR DESCRIPTION
**Pull request by hunylee**
## pom.xml is plugin version change
- pom.xml
- beam/pom.xml
- cassandra/pom.xml
- flink/pom.xml
- ignite/pom.xml
- r/pom.xml
- scalding/pom.xml
- spark/pom.xml
- spark-dependencies/pom.xml
- zeppelin-display/pom.xml

### What type of PR is it?

[Improvement | Feature | Documentation]
### Todos
- [ ] zeppelin is pom.xml in the plugin version change [ZEPPELIN-1569]
### How should this be tested?

- Is there breaking changes for older versions?

### CODE REVIEW

**Comment by hunylee** [comment]
pom.xml is

**Comment by AhyoungRyu** [comment]
@hunylee Thanks for your contribution. Could you edit the PR description so that other ppl can understand what you intended easily? 😀

**Comment by jongyoul** [comment]
@hyonzin We should discuss Zeppelin's major scala version because it affects a lot of users' behavior. Can you close it and raise a discussion in a dev@ first?

**Comment by hunylee** [comment]
@jongyoul Sorry. I thought I did.
Version're the problem.
I'm sorry again.

**Comment by AhyoungRyu** [comment]
@hunylee Yeah I think the version is not the problem now. 
Did you reopen the PR on purpose? If not, could you close this then?

**Comment by hunylee** [comment]
@AhyoungRyu Yeah PR purpose reopen. 
Now Closing?

**Comment by hunylee** [comment]
@AhyoungRyu Closed.

**Pull request closed without merging**
