### PR TITLE
ZEPPELIN-3484. sc.setJobGroup() shows up in error stack and shifts line numbering

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This PR would call sc.setJobGroup and the user code separately.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3483

### How should this be tested?
* CI pass

### Screenshots (if appropriate)
screen shot 2018-05-23 at 8 56 40 am

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@Tagar Could you help review it ? Thanks

**Comment by zjffdu** [comment]
Ideally, setJobGroup would not fail. I check it just in case. And the error message will be propagated to frontend via streaming

**Comment by Tagar** [comment]
Thanks @zjffdu - I will test this today.

**Comment by Tagar** [comment]
works as expected.
thanks for quick turnaround! 
LGTM.

**Pull request closed without merging**
