### PR TITLE
[ZEPPELIN-6102] Fix cron disabling and refresh issue

### PR DESCRIPTION
**Pull request by Li-GL**
### What is this PR for?
1. fix the cron disabling issue where zeppelin frontend was unable to disable cron, i.e., after setting the cron, e.g., every 1m, 5m, when you change it to "None", it didn't take effect when you refresh the notebook. 
2. fixes the cron refresh issue, i.e., when you update the cron setting, it always triggered the cron with the old cron expression,  because the cron setting was refreshed before notebook  updating.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6102

### How should this be tested?

1. Open Zeppelin Web UI
2. Open any Notebook
3. Click the Cron Icon
4. set any cron expression
5. refresh the notebook and see if it worked as expected
6. set it to None
7. refresh the notebook and see if it worked as expected

### Screenshots (if appropriate)
image

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by tbonelee — APPROVED** [review]
Code looks good to me! I verified that the note gets properly updated whenever a cron job is modified or disabled.
Also tested that the cron job runs with the updated settings after changes.

Although I'm still getting familiar with the project, the code changes seem easier to follow, with clear steps for 'permission check', 'note update' and 'post-update action'.

**Comment by Reamer** [comment]
The code looks good to me. Can you write a unit test for it?

**Review by Reamer — DISMISSED** [review]

**Comment by Li-GL** [comment]
> The code looks good to me. Can you write a unit test for it?

Thanks for your review, the unit tests have been added and tested in a local development environment

**Review by Reamer — APPROVED** [review]
LGTM
@jongyoul What is your opinion?

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/0.12

**Pull request merged**
