### PR TITLE
[ZEPPELIN-922] New interpreter registration mechanism for Scalding

### PR DESCRIPTION
**Pull request by DrIgor**
### What is this PR for?
Applies the new interpreter registration mechanism to Alluxio interpreter.

### What type of PR is it?
Improvement

### Todos
- [x] Remove static registration in org.apache.zeppelin.scalding.ScaldingInterpreter
- [x] Create interpreter-setting.json

### What is the Jira issue?
[ZEPPELIN-922](https://issues.apache.org/jira/browse/ZEPPELIN-922)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
lgtm

**Comment by AhyoungRyu** [comment]
@DrIgor Thanks for your contribution!

Currently 1 test profile failed like below, but it looks irrelevant with this change/
```

Results :

Failed tests: 
  SparkParagraphIT.testDep:234 First paragraph from SparkParagraphIT of testDep status: 
Expected: "FINISHED"
     but: was "ERROR"

Tests in error: 
  ZeppelinIT.testSparkInterpreterDependencyLoading:234->AbstractZeppelinIT.waitForParagraph:70->AbstractZeppelinIT.pollingWait:96 » Timeout

Tests run: 18, Failures: 1, Errors: 1, Skipped: 0

```

LGTM

**Comment by DrIgor** [comment]
Ping-ping! :-)

What should I do to complete pull request?

**Comment by AhyoungRyu** [comment]
As I posted the reason of CI failure in the above, it's not relevant. So will merge into master if there are no more comments. Thanks @DrIgor!

**Pull request closed without merging**
