### PR TITLE
[ZEPPELIN-2374] sorting notes tree

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Updated angular version to 1.5.7 (added comparator to orderBy). Sorting notes tree, order:
1. folders (alphabetically)
2. notes (alphabetically)
3. Trash

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2374

### How should this be tested?
see screenshots

### Screenshots (if appropriate)
home page
before   -   after
tree_1

navbar
before   -   after

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by soralee** [comment]
Nice feature @tinkoff-dwh 
Tested and it works well. LGTM!

image

image

**Comment by soralee** [comment]
@tinkoff-dwh, Could you rebase for resolving conflicts?

**Comment by tinkoff-dwh** [comment]
ready to review

**Comment by soralee** [comment]
@Leemoonsoo could you review this?

**Comment by Leemoonsoo** [comment]
Let me take a look and come back

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no further discussions!

**Pull request closed without merging**
