### PR TITLE
[DOC] Proxy build - removed Bower note

### PR DESCRIPTION
**Pull request by fvaleri**
### What is this PR for?
Final version of the proxy setup paragraph on main README.
Removed Bower note beacuse it works with the last checkout from master. 

See also #1069 and #876.

### What type of PR is it?
Documentation

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* Put link here, and add [ZEPPELIN-*Jira number*] in PR title, eg. [ZEPPELIN-533]

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

Final setup for building behind a proxy.

### CODE REVIEW

**Comment by jongyoul** [comment]
It's very helpful to edit your title with [DOC] prefix.

**Comment by fvaleri** [comment]
@jongyoul ok, thank you

**Comment by jongyoul** [comment]
The failure is irrelevant. @fvaleri Could you please link the previous work to refer it?

**Comment by fvaleri** [comment]
Sure, reported in PR description.

**Comment by jongyoul** [comment]
@Leemoonsoo Please review this PR. You were the reviewer of previous PRs. LGTM

**Comment by Leemoonsoo** [comment]
LGTM. If someone behind proxy can provide additional review, that would be helpful.

**Comment by fvaleri** [comment]
What about this?
Someone can confirm?

**Comment by Leemoonsoo** [comment]
I'm merging it into master, if there is no further discussions, verification.

**Pull request closed without merging**
