### PR TITLE
[ZEPPELIN-5982] Merge flink-scala-parent module into flink-scala-2.12

### PR DESCRIPTION
**Pull request by pan3793**
### What is this PR for?

Merge `flink-scala-parent` module into `flink-scala-2.12` to simplify the project module structure.

Currently, Zeppelin supports Flink 1.15~1.17, these versions of Flink only support Scala 2.12(specifically, 2.12.7), and the Flink community decided to make the project scala-free instead of supporting new versions of Scala in the future;

This change also simplifies the IDEA project importing, without this change, IDEA can not recognize `flink-scala-2.12` module automatically, the developer needs to follow the README to manually fix it.

### What type of PR is it?

Improvement

### Todos
* [ ] - Task

### What is the Jira issue?

ZEPPELIN-5982

### How should this be tested?

Pass GA

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes, updated the docs correspondingly

### CODE REVIEW

**Comment by pan3793** [comment]
cc @huage1994

**Comment by jongyoul** [comment]
As you noticed, we selected the current structure as we should support multiple Scala versions for Flink.

>Currently, Zeppelin supports Flink 1.15~1.17, these versions of Flink only support Scala 2.12(specifically, 2.12.7), and the Flink community decided to make the project scala-free instead of supporting new versions of Scala in the future;

How do you know they support Scala 2.13 or 3 in the future then?

**Comment by pan3793** [comment]
@jongyoul Flink community decided to remove Scala, so there is no Scala 2.13/3 support in the future.

The detailed discussion occurred at [FLINK-13414](https://issues.apache.org/jira/browse/FLINK-13414)

The vote-passed proposal [FLIP-265 Deprecate and remove Scala API support](https://cwiki.apache.org/confluence/display/FLINK/FLIP-265+Deprecate+and+remove+Scala+API+support)

**Comment by f-lab-lyan** [comment]
@pan3793 Thank you for the information. I read and understood the situation.

**Comment by jongyoul** [comment]
@pan3793 Thank you for the information. I read and understood the situation.

**Review by huage1994 — APPROVED** [review]
Great!  Thanks for your contribution.

**Pull request merged**
