### PR TITLE
[HOTFIX] Fix CI build failure on branch-0.6

### PR DESCRIPTION
**Pull request by hammertank**
### What is this PR for?
Fix CI build failure on branch-0.6. 

### What type of PR is it?
Hot Fix

### Todos
- Modified [.travis.yml](https://github.com/apache/zeppelin/blob/branch-0.6/.travis.yml) according to #1774 
- Merged PR #1920 #1911
- Update spark version and hadoop version in [.travis.yml](https://github.com/apache/zeppelin/blob/branch-0.6/.travis.yml) since older spark version below 1.6.2 can not be downloaded from remote server any more.

### What is the Jira issue?
No related Jira issue

### How should this be tested?
See if CI becomes green

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by hammertank** [comment]
@Leemoonsoo , Ready to review. Please help.

**Comment by jongyoul** [comment]
@hammertank Hi, thanks for the contribution but do you or your team use zeppelin 0.6.x?

**Comment by hammertank** [comment]
@jongyoul ,yes, we are using 0.6.2. At the time we started our project, it is the latest released version.

**Comment by jongyoul** [comment]
Merging it if there's no more discussion

**Comment by hammertank** [comment]
@jongyoul currently, our project is using zeppelin as a restful webservice  to execute spark code. zeppelin-0.6.2 has got everything we need. Anyway, we'll consider to upgrade zeppelin in the next version of our own project. Thank you for your suggestion. :)

**Comment by jongyoul** [comment]
@hammertank Good to know. Thanks.

**Comment by Leemoonsoo** [comment]
Thanks @hammertank for the contribution.
I can see commits included in this PR came from other branch.
In this case we'd like to cherry-pick and preserve original author to keep contribution history and credit.

@hammertank Could you cherry-pick necessary commits and keep author information?

**Comment by hammertank** [comment]
@Leemoonsoo  Updated commits' original author info.  Please review again.

**Comment by Leemoonsoo** [comment]
LGTM and merge to branch-0.6 if no further comment!

**Comment by Leemoonsoo** [comment]
Merged to branch-0.6.
But somehow @asfgit does not close it automatically. @hammertank please close this PR manually.

**Comment by hammertank** [comment]
@Leemoonsoo maybe only PR merged into master branch can be closed automatically.

**Pull request closed without merging**
