### PR TITLE
[ZEPPELIN-1351]Paragraph status should be ERROR if Paragraph is terminated with SIGTERM

### PR DESCRIPTION
**Pull request by mwkang**
### What is this PR for?
When Paragraph received a SIGTERM. ExitValue: 143, Status of the paragraph should be marked as "ERROR" instead of "FINISHED".

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1351

### How should this be tested?
I have online test.
But hope to get some advice or guides from reviewers or committer.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
is it possible to add some unit test for this?

**Comment by mwkang** [comment]
@felixcheung Okay! I will add unit test. Thanks for your comment!

**Comment by mwkang** [comment]
I added test. Please review PR, thanks for your consideration.

**Comment by Leemoonsoo** [comment]
Thanks for the contribution.
@mwkang Could you elaborate little bit more how this code change is related to ZEPPELIN-1351?

ZEPPELIN-1351 is about displaying paragraph status when it fails with "Paragraph received a SIGTERM. ExitValue: 143". But code change here is displaying paragraph status 'ERROR' when interpreter result is incomplete. So i'm bit confusion how they're related. Could you help me to understand?

**Comment by mwkang** [comment]
@Leemoonsoo When paragraph received a SIGTERM, Job result code is INCOMPLETE.
Before When Job result code is INCOMPLETE, Status is FINISHED.
I think in this situation user can not realize paragraph received a SIGTERM. Because Status is FINISHED.

**Comment by mwkang** [comment]
Can anyone help this PR?
I don't know the next step.

**Comment by mwkang** [comment]
I am not sure what is my next step. And this PR was created very long time ago. So enviroment changed before. I think other contributor can resolve better than me. So I closed this PR.
Thanks for your patient.

**Pull request closed without merging**
