### PR TITLE
[ZEPPELIN-1982] When using the 'Select * ...' statement doesn't show …

### PR DESCRIPTION
**Pull request by del680202**
### What is this PR for?
In this ticket [ZEPPELIN-212](https://issues.apache.org/jira/browse/ZEPPELIN-212)，``InterpreterOutput.java`` will filter out '\n'.
It causes ``tabledata.js`` couldn't recognize the comment in the paragraphResult. If column number of sql query exceed 2 columns and row number over ``maxResult`` will show nothing.
Therefore, I suppose to modify comment statement from ''  to ``TABLE_COMMENT``for this issue.

### What type of PR is it?
Bug Fix

### Todos
* None

### What is the Jira issue?
[ZEPPELIN-1982](https://issues.apache.org/jira/browse/ZEPPELIN-1982)

### How should this be tested?
try  to execute ``%sql  SELECT * FROM bank`` on  tutorial

### Screenshots (if appropriate)
Before

After

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by jongyoul** [comment]
@zjffdu Can you also verify it?

**Comment by zjffdu** [comment]
This PR works for me. But I feel it is kind of hacking using `<!--TABLE_COMMENT-->`.  I think the better approach is to using multiple `InterpreterResult`. But we could do that in a following up PR.

**Comment by soralee** [comment]
Thank @del680202 for fixing this bug!

I just tested it out and this problem works well.
But, some existing sample paragraphs have the following problems. 
image

and, when I run one paragraph among those paragraph
z_1942


@del680202 Could you check and run this paragraph?

**Comment by del680202** [comment]
@soralee @zjffdu
I also figure out that i missed the last new line character, i use the a simple way to handle it.

**Comment by Leemoonsoo** [comment]
Thanks @del680202  for the fix!

Although it fixes problem from of output from SparkInterpreter, outputs from other interpreters may have the same problem unless other interpreter changes code.

So, I think we need follow up PR that fixes InterpreterOutput.java 's table data comment handling.

**Comment by soralee** [comment]
@del680202 I tested this again and I can't the above error in chrome.
It's working well now.

**Comment by zjffdu** [comment]
Jdbc interpreter may be effected. Livy interpreter would return a list of InterpreterResult so it is fine for livy.

**Comment by del680202** [comment]
I test Jdbc interpreter and livy interpreter by my test database.

jdbc interpreter working well.


But there a problem in livy interpreter 


And then, I test livy interpreter  by master branch again, the same problem occurred
I suppose it is a livy interpreter  issue.

**Comment by zjffdu** [comment]
@del680202 Thanks for verifying. livy interpreter works in master, so I guess it is affected by this PR.

**Comment by felixcheung** [comment]
I think we need this for 0.7 RC?

**Comment by del680202** [comment]
@zjffdu 
I  verify this issue again for double check. 
This PR working well, Maybe I miss something.
But master branch still occur problem.

There are two test cases:
* Select table from spark temp table
* Select real table from hive

If my target is hive table, it will show ``1`` in master branch.

-master branch



-This PR

**Comment by del680202** [comment]
@zjffdu 
I  verify this issue again for double check.

Livy version: branch-0.3

There are two test cases:
1. Select temp table from spark
2. Select real table from hive


In the previous, My PR occur problem because livy interpreter use '\n' for comment part but it doesn't filter out '\n'.
Therefore, I fix it at first.
I suppose it is a policy problem, does '\n' in interpreter result need to be filtered out?

Another problem
In master branch, when my target is hive table, it will show ``1`` in result.

-master branch



-This PR(after fixing)

**Comment by del680202** [comment]
I try to hack livy interpreter source code, when I query my hive table, I got a ``TABLE`` result and a ``TEXT`` result  ``Output exceeds 102400. Truncated``.  
The ``TEXT`` part cause this issue.  Therefore, I suppose it need to create a new jira ticket for this issue?

**Comment by zjffdu** [comment]
@del680202  I create ZEPPELIN-2015 and will try to fix that.

**Comment by minahlee** [comment]
@del680202 thanks for the contribution, do you mind to retrigger CI to be sure?
You can retrigger it by closing and opening this PR or `git commit --amend ## ; git push -f repoName branchName`

**Comment by minahlee** [comment]
Merging if there is no more discussion

**Pull request closed without merging**
