### PR TITLE
[ZEPPELIN-2081] Prettify input, textarea in interpreter setting page

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Fix small details in interpreter setting page about inputboxes, textareas

- Set align middle for `td`
- Keep same min-height between input and textarea
- Add border-radius 3px;

### What type of PR is it?
[Improvement]

### What is the Jira issue?

[ZEPPELIN-2081](https://issues.apache.org/jira/browse/ZEPPELIN-2081)

### How should this be tested?

Open the browser and check manually.

#### Before: Invalid align

image

#### Before: Inconsistent min-height

image

#### After: align

image

#### After: min-height

image

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
Thanks for taking care this @1ambda! Tested and looks nice.

**Comment by 1ambda** [comment]
@AhyoungRyu thanks for review. CI failed but irrelavent

**Comment by AhyoungRyu** [comment]
Merge into master and branch-0.7 if there are no comments

**Comment by AhyoungRyu** [comment]
@1ambda CI is failed only in Selenium test like below 
```
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//i[@tooltip='WebSocket Connected']"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'testing-docker-88bd8952-3a71-4bd6-9ab2-4b1a5ee75b91', ip: '172.17.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.12-040812-generic', java.version: '1.7.0_76'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous5623099368356690573webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///tmp/anonymous5623099368356690573webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:621)
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 75.142 sec <<< FAILURE! - in org.apache.zeppelin.integration.InterpreterIT
```

Seems it's not directly related to this change, but can we retrigger again just to make sure?

**Comment by felixcheung** [comment]
Could or should the front size to be the same in the left and right boxes?
https://cloud.githubusercontent.com/assets/4968473/22731456/15f295ee-ee2e-11e6-915d-e9d7d6236bbd.png

**Comment by 1ambda** [comment]
@AhyoungRyu Passed selenium tests. 

- https://travis-ci.org/apache/zeppelin/builds/200883455

**Comment by 1ambda** [comment]
@felixcheung Fixed. (`font-size: 12`)

image

**Comment by AhyoungRyu** [comment]
@1ambda Looks good! Will merge after CI tests are done if there are no comments.

**Comment by AhyoungRyu** [comment]
Some CI tests are failed but it's not related to this change. I'm merging now.

**Pull request closed without merging**
