### PR TITLE
[MINOR] Support aarch for frontend plugin

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Fixing build error when using aarch jdk for mac OS. our version of node doesn't support amd64 arch but the old plugin tries to download arm version.

### What type of PR is it?
Bug Fix

### Todos
* [x] - Update `frontend-maven-plugin`

### What is the Jira issue?
N/A

### How should this be tested?
* Pass to build with arm jdk in macOS

### Screenshots (if appropriate)
image

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No 
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
BTW, as mentioned in #4523, The compilation time becomes faster if we use arm jdk in m1 mac

**Review by huage1994 — DISMISSED** [review]

**Comment by huage1994** [comment]
It looks good to me 👍

**Comment by jongyoul** [comment]
@huage1994 Thank you. BTW, it has a dependency issue. It's related to Helium feature because it uses frontend-core to download npm package for custom visualization feature. I think we'd better reinvent the Helium with minimum but it's a problem anyway. I'll fix it and let you know. Please review it again after fixing the issue.

```
Dependency convergence error for com.fasterxml.jackson.core:jackson-core:2.13.0 paths to dependency are:
+-org.apache.zeppelin:zeppelin-interpreter-integration:0.11.0-SNAPSHOT
  +-org.apache.zeppelin:zeppelin-zengine:0.11.0-SNAPSHOT
    +-com.github.eirslett:frontend-plugin-core:1.12.1
      +-com.fasterxml.jackson.core:jackson-core:2.13.0
and
+-org.apache.zeppelin:zeppelin-interpreter-integration:0.11.0-SNAPSHOT
  +-org.apache.zeppelin:zeppelin-server:0.11.0-SNAPSHOT
    +-com.fasterxml.jackson.core:jackson-databind:2.12.6.1
      +-com.fasterxml.jackson.core:jackson-core:2.12.6
```

**Review by Reamer — CHANGES_REQUESTED** [review]
CI is broken, because of dependency-convergence. I added the review so no one would accidentally click merge.

**Comment by pan3793** [comment]
I roughly remember that NodeJS officially supported Apple Silicon in v16(actually in v15, but it's not an LTS, and was EOL), and eventually, they decided to port this feature to v14 but does not publish the binary artifacts.

So I suppose upgrading NodeJS v16 is necessary.

Sorry I can not take this because I don't have much knowledge in frontend stacks.

**Comment by jongyoul** [comment]
Thank you for the description. I also checked it and found the latest version is supporting that way. In our current version, the plugin tries to add suffix for arm64 to download proper node binary but in the latest version, it checks if the our node version is below 16 or not.

**Comment by jongyoul** [comment]
@Reamer The CI becomes back as the previous so it's ok. Could you please recheck it?

**Review by Reamer — APPROVED** [review]
LGTM

**Pull request merged**
