### PR TITLE
[ZEPPELIN-2008] Introduce Spell

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Implemented **Spell** as one of Helium categories. *Technically, it's the frontend interpreter* runs on browser not backend.

Spell can provide many benefits.

1. Anyone can install, remove easily using helium package registry by #1936 
2. Implementing spell is extremely easier rather than adding backend interpreter
3. Can use existing javsacript libraries. (e.g [flowchart.js](http://flowchart.js.org/), [sequence diagram js](https://github.com/bramp/js-sequence-diagrams), ...). This enable us to add many visualization tools. Imagine that you can implement some custom interpreters with few lines of code like [flowchart-spell-example](https://github.com/apache/zeppelin/compare/master...1ambda:ZEPPELIN-2008/introduce-spell?expand=1#diff-364845b20d68e4d94688e44fef03da98)
4. The most important thing is, spell is not only interpreter but also display system. Because it runs on browser. So we can use spell display system with another spell **Display System with Spell** (see the screenshot section below)

 **In future**, we will be able to combine existing backend interpreters with spell like (**not supported in this PR cause we need to modify backend code a lot**)

```
// if we have markdown spell, we can use `%markdown` display in the spark interpreter

%spark

val calculated = doSomething()
println(s"%markdown _${calculated})
```

I added some examples. Checkout `echo`, `markdown`, `translator`, `flowchart` spells.

### What type of PR is it?
[Feature]

### Todos
* [x] - Add `SPELL` as one of Helium categories.
* [x] - Implement framework code (`zeppelin-spell`)
* [x] - Make some examples (flowchart, google translator, markdown, echo)
* [x] - Support custom display system
* [x] - Fix some bugs in `HeliumBundleFactory`
* [x] - Save spell rendering result into `note.json` while broadcasting to other websocket clients
* [x] - Fix `renderText` for stream output

### What is the Jira issue?

[ZEPPELIN-2008](https://issues.apache.org/jira/browse/ZEPPELIN-2008)

### How should this be tested?

- Build `mvn clean package -Phelium-dev -Pexamples -DskipTests;`
- Go to helium page `http://localhost:8080/#/helium`
- Enable all spells
- Go to a notebook and refresh
- Follow actions in the screenshots below.

#### Flowchart Spell (Sample)

flowchart-spell

#### Google Translator Spell (Sample)

translator-spell

#### Display System with Spell

display-spell

### Questions:
* Does the licenses files need update - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - YES, but framework can be enhanced so i would like to defer to write document right now.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @1ambda for contributing very interesting new feature.
I've play around with it and have couple of feedbacks.

### Couldn't make Spell as display system work
> The most important thing is, spell is not only interpreter but also display system. Because it runs on browser. This enable us to combine existing backend interpreters with spell like

So i tried following but couldn't make it work. Am i missing something?
image

### Configuring Display order of Spell doesn't make sense

Enabled spells are displayed in 'Helium' menu like below.
image

Which is designed to change display order of visualization package when they displayed in chart selector inside of the paragraph.
As far as i understand, Spell does not have to be listed in the chart selector and does not have to be listed there and change order. So i think reordering should be only for 'Visualization' type package.

I think Spell can create another section just below enabled visualization buttons, to list enabled spells.

### Display keyword of the spell

Each spell has keyword to invoke. For example `markdown-spell`'s keyword is `%markdown`, `flowchart-spell`'s keyword is `%flowchart`. However, i couldn't find these keyword anywhere but the source code.

So it'll be nice if 'Helium' menu displays keyword of the Spell type packages. 


### Example for example spells 

If there's some informations or example that how to use (syntax, etc) included example Spells, (e.g. in description section or somewhere) it'll be more convenient.

**Comment by 1ambda** [comment]
rebased to resolve conflict with master.

@Leemoonsoo Thanks for detailed review! I updated code according to your comment.

(1) **Couldn't make Spell as display system work:** Let's handle in following PRs.

originally, i meant "we can use spell display with backend interpreter **if we modify some backend code**". Sorry for confusing. I tried to fix it in this PR, but it's not that easy as i expected since current `InterpreterResult.Type` is enum, not string. IMO, it can be handled in following PRs. (I modified this PR description too)

- https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/InterpreterOutput.java#L225

(2) **Configuring Display order of Spell doesn't make sense**: Fixed.

(3, 4) **Display keyword of the spell**, **Example for example spells** 

Now `#/helium` page displays `spell.magic`, `spell.usage` which are saved helium package json.

screen shot 2017-01-30 at 9 32 42 am

```
{
  "type" : "SPELL",
  "name" : "translator-spell",
  ...
  "spell": {
    "magic": "%translator",
    "usage": "%translator <source>-<target> <access-key> <TEXT>"
  }
}
```

**Comment by Leemoonsoo** [comment]
Thanks addressing the comments. Tested and it works well as expected.
Agree, 1) can be handled in separate issue while this PR already quite big.

CI fails on RAT check profile

```
  /home/travis/build/apache/zeppelin/zeppelin-interpreter/src/main/java/org/apache/zeppelin/helium/HeliumType.java
  /home/travis/build/apache/zeppelin/zeppelin-interpreter/src/main/java/org/apache/zeppelin/helium/SpellPackageInfo.java
  /home/travis/build/apache/zeppelin/zeppelin-interpreter/src/test/java/org/apache/zeppelin/helium/HeliumPackageTest.java
```

Looks like above 3 file need license header. @1ambda could you check?

**Comment by 1ambda** [comment]
finally, CI is green. :)

**Comment by Leemoonsoo** [comment]
@1ambda Awesome new feature! LGTM

**Comment by Leemoonsoo** [comment]
Merge to master if no further comments.

**Comment by AhyoungRyu** [comment]
From now, `SPELL` type pkg info fetched from [Helium registry](https://s3.amazonaws.com/helium-package/helium.json) is also shown in GUI :)
screen shot 2017-02-01 at 6 24 38 pm

**Pull request closed without merging**
