### PR TITLE
[ZEPPELIN-2587] allow logging in if you're anonymous

### PR DESCRIPTION
**Pull request by herval**
### What is this PR for?

The login button is not showing (since 0.7.1) if you allow anonymous access. This shows it again.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN/ZEPPELIN-2587

### How should this be tested?
- Start Zeppelin with anonymous support
- The login button should now show on the bar

### Questions:
* Does the licenses files need update?
No
* Is there breaking changes for older versions?
No
* Does this needs documentation?
No

### CODE REVIEW

**Comment by zjffdu** [comment]
Could we add a simple selenium test for this ? Regression issue is bad thing.

**Comment by herval** [comment]
@zjffdu added one, let me know if that covers it

**Comment by jongyoul** [comment]
I don't know the purpose of this PR. If username is anonymous, it means shiro is off. What's your intention?

**Comment by cfries** [comment]
Hi @jongyoul : I don't understand your comment. You can have "anonymous" when shirt is on. This is even in the shiro example (note: If I understood the shiro example correctly: until the user is not logged in, he is "anonymous" and hence the login page is allowed for "anonymous").

The issue https://issues.apache.org/jira/browse/ZEPPELIN-2587 is real, but I have not yet checked if this PR fixes it.

**Comment by jongyoul** [comment]
I got it. I didn't recognize actual username is "anonymous" in production case. If it can be, it will be a problem.

**Comment by herval** [comment]
any additional thoughts on this? Is it mergeable? @jongyoul @cfries

**Comment by jongyoul** [comment]
@1ambda can you check this issue?

**Comment by 1ambda** [comment]
@herval 

1. Could you rebase? base branch is quite old
2. We need to pass CI. Please the failed tests.

**Comment by herval** [comment]
hmm I'm finding it difficult to get all the integration tests to pass. Inclined to test only for the presence of the button.

**Comment by herval** [comment]
This is now passing all tests - please advise

**Comment by herval** [comment]
Hi folks,

Please let me know if I should close this. Tks!

**Pull request closed without merging**
