### PR TITLE
typo

### PR DESCRIPTION
**Pull request by OutOfBedlam**
### What is this PR for?
bin/zeppelin.sh - typo fix

### CODE REVIEW

**Comment by jongyoul** [comment]
@OutOfBedlam Thanks for the fix. LGTM. The failure of CI looks irrelevant.

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by corneadoug** [comment]
@OutOfBedlam Could you reverse the last commit? I can't merge it now.
Also, when doing a PR, it is better to use a branch instead of master

**Comment by bzz** [comment]
Last commit needs to be removed by using git interactive rebase, as it's been taken care of under #1009 

It would also be great to have more descriptive PR title like `Fix typo in bin/zeppelin.sh`

**Pull request closed without merging**
