### PR TITLE
Save all repos, and not just the first two

### PR DESCRIPTION
**Pull request by dirceusemighini**
This PR modify the save repos method.
Now it is saving only the first two backend repos of the list, which is OK because this is the current behavior.
The code change this to save all the bachend repos , and it will be usefull when more than 2 backend repos is supported.

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
Existing implementation gives more focus on the existence of maximum of two backend repos. The change makes it look more logical in case we add more backend repos. Looks good except need to address the following issues:
- Fix `log` to reflect which repo index saving fails
- Fix styling to pass CI

**Comment by dirceusemighini** [comment]
I used getSimple name in the repo class, do you think that someone could use an anonymous class in here?

**Comment by Leemoonsoo** [comment]
Nice improvement! Could you update https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/repo/NotebookRepoSyncTest.java to test with more than 3 notebook repo?

**Comment by khalidhuseynov** [comment]
@dirceusemighini I believe `getSimpleName` should be fine

**Comment by khalidhuseynov** [comment]
I think this PR doesn't add synchronization for more than 2 repos, it just saves to all available repos. The reason is that there's still limit on the number of repos which is 2 currently (https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/NotebookRepoSync.java#L42). So basically we still don't get more than 2 repo `saves`. On the other hand, it's good idea to be able to handle more than 2 repos, and it'll be coming soon probably

**Comment by dirceusemighini** [comment]
Hi Guys, I was on vacation and just returned.
So, we still can't open more than two repos, but does this code will help
on saving when the option to open more than one is available, right?

2015-10-04 4:54 GMT-03:00 Khalid Huseynov <notifications@github.com>:

**Comment by hsaputra** [comment]
Hi @dirceusemighini, could you also update the description of this PR with more info of what is the intended change and the desired behavior?

It will help reviewers and others to look at it and in the future when we need to revisit old PRs.

**Comment by dirceusemighini** [comment]
Hi @Leemoonsoo latter this week I will update the test to assure that the code is running fine.

**Comment by Leemoonsoo** [comment]
Thanks @dirceusemighini. Please take your time.

As @khalidhuseynov commented, I think [sync()](https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/NotebookRepoSync.java#L159) also need to aware of more than 3 repos.

**Comment by corneadoug** [comment]
@khalidhuseynov Is this still an issue with our current implementation?

**Comment by khalidhuseynov** [comment]
@corneadoug it can still be rebased, however more than two repos concurrently still not supported, so basically it wouldn't change anything. so it can be closed safely as well in case no activity

**Pull request closed without merging**
