### PR TITLE
Notebook: (Web) HDFS as a backend storage (Read & Write Mode)

### PR DESCRIPTION
**Pull request by hayssams**
### What is this PR for ?
This PR replaces the PR-1479 by removing any hadoop dependency using WEBHDFS as a communication protocol (code borrowed from PR1600)
Zeppelin currently supports many backends for storing notes through Apache Commons VFS.
Apache Commons VFS supports HDFS in readonly mode.
This PR makes HDFS a first class citizen by allowing users to load notes from / save notes to HDFS.

### Task
What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1515

### How should this be tested?

Update zeppelin.notebook.dir property to a value like hdfs://localhost:9000/tmp/notebook and the property zeppelin.notebook.storage to the value org.apache.zeppelin.notebook.repo.HdfsNotebookRepo

check that your notes are loaded from and stored to HDFS by listing notes using the command :
hdfs dfs -ls /tmp/notebook

### Questions:

* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by jongyoul** [comment]
I don't think it's good idea to include some interpreters as dependencies onto zeppelin-zengine.

**Comment by hayssams** [comment]
@jongyoul moved HDFSCommand to zeppelin-interpreter

**Comment by felixcheung** [comment]
it might be important to call this `webHdfs` instead of `hdfs`
there are significant and important differences on what is supported esp. with cloud providers

**Comment by hayssams** [comment]
@felixcheung  
HDFSCommand exists without the prefix Web since the beginning

**Comment by felixcheung** [comment]
Is this HDFS or  WebHDFS protocol?

**Comment by hayssams** [comment]
@felixcheung Do you want me to update the docs and the code or the docs only ?

**Comment by felixcheung** [comment]
both of them if it makes sense?

**Comment by hayssams** [comment]
@felixcheung 
Renaming done.

**Comment by zjffdu** [comment]
sorry @hayssams I create another PR #2455 to use hdfs library directly.  Because I think it is a little complicated to using webhdfs library and hard to do test. Maybe also lose some features, not sure whether webhdfs works with kerberized cluster.

**Comment by hayssams** [comment]
Hello @jongyoul 
OK got it.
However keep in mind that Webhdfs works in a kerberized env without any change to the source code. It simply needs to be executed in a JAAS context which is nothing else than a jaas.conf file passed as a parameter to the Zeppelin JVM

**Comment by felixcheung** [comment]
I see perhaps value in both web hdfs and hdfs (jar client)?

**Comment by zjffdu** [comment]
maybe add one property to allow user to choose which method to use. And HdfsNoteBookRepo can delegate the real work to `WebHdfsNotebookRepo` and `NativeHdfsNotebookRepo`

**Pull request closed without merging**
