### PR TITLE
[ZEPPELIN-1045] Apply new mechanism to PythonInterpreter

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
This PR is applying new interpreter register mechanism to python interpreter.

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZEPPELIN-1045](https://issues.apache.org/jira/browse/ZEPPELIN-1045)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by minahlee** [comment]
\cc @bzz @jongyoul for review

**Comment by bzz** [comment]
Looks great to me, thank you @minahlee !

Will merge, if there is no more discussion

**Comment by bzz** [comment]
BTW while we are here, how do you think shall we also set `zeppelin.python.maxResult` to 1000?

**Comment by minahlee** [comment]
@bzz Good suggestion! This will be useful to display dataframe in table view. I addressed it in 66b8f73

**Comment by bzz** [comment]
Looks awesome to me, thank you!

I think it's ready to merge, if there is no further discussion

**Pull request closed without merging**
