### PR TITLE
[ZEPPELIN-1399] Refactor automatic interpreter name insert

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Refine automatic interpreter name insert. See below jira issue for detailed description

### What type of PR is it?
Improvement | Refactoring

### What is the Jira issue?
[ZEPPELIN-1399](https://issues.apache.org/jira/browse/ZEPPELIN-1399)

### Screenshots (if appropriate)
- Do not insert interpreter name if previous interpreter name is not specified
**Before**
aug-30-2016 17-28-06
**After**
aug-30-2016 17-24-23

- Insert interpreter name of previous paragraph without running
**Before**
aug-30-2016 17-33-25
**After**
aug-30-2016 17-24-32

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested and LGTM.
Thanks @minahlee for the great improvement.

**Comment by corneadoug** [comment]
@minahlee For the first case, it is actually the default interpreter.
For example, In Master when you create a new Note you will have '%spark' in the paragraph.
In this Branch, it will stay empty.

Another example would be using: `sc.version` in a paragrah without `%spark`

**Comment by minahlee** [comment]
@corneadoug actually I made it empty intentionally. please check out the discussion [here] (https://issues.apache.org/jira/browse/ZEPPELIN-707?focusedCommentId=15358493&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15358493)

**Comment by corneadoug** [comment]
@minahlee Making a new line is a good improvement because some interpreters do not handle same line typing.

For removing the default interpreter, I don't have a strong opinion.
If we plan on having the backend provide the interpreter information in the paragraph and always show it outside of the text editor, we would remove this feature anyway.

However it could feel weird to have Release 0.6.1 have the default interpreter shown, 0.6.2 not showing it, then 0.6.3 or 0.7.0 have Interpreter always shown again but this time as part of the paragraph (not in text editor)

**Comment by minahlee** [comment]
I totally agree that we shouldn't make ux change often. But showing default interpreter in text is implemented only in master branch but not in previous release so I think it won't bring much of confusion.

**Comment by minahlee** [comment]
Reverted #1248 during the rebase since this PR already has implemented same functionality in [this line](https://github.com/apache/zeppelin/pull/1388/commits/c777135ea66e80d2ea01e18578eaa6540814c7a7#diff-199a5155679a305a544902edda0c6fb7R584).

**Comment by minahlee** [comment]
CI is green. Merge if there is no more discussuion

**Pull request closed without merging**
