### PR TITLE
[ZEPPELIN-1627] - Fix latency on notebook save in ZeppelinHubNotebookRepo

### PR DESCRIPTION
**Pull request by anthonycorbacho**
### What is this PR for?
Fix latency issue when user save a notebook while using zeppelinhub notebook storage.

### What type of PR is it?
[Improvement]

### Jira issue
[ZEPPELIN-1627](https://issues.apache.org/jira/browse/ZEPPELIN-1627)

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
@anthonycorbacho Thanks for bringing back async nature for note saves, LGTM!

**Comment by bzz** [comment]
Looks great to me, thank you for fix and prompt response! 

Let's merge after CI is green, if there is no further discussions.

**Comment by anthonycorbacho** [comment]
travis is super slow today

Amerika is working to hard today :)

**Comment by anthonycorbacho** [comment]
CI is failing due to `testEditOnDoubleClick`, and it is not related to this PR.

So i am merging it :)

**Pull request closed without merging**
