### PR TITLE
[WIP] Multi-Language UI for ZeppelinWebApp

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
This PR has for goal to provide an initial implementation of Multi-Language UI for Zeppelin.
This feature will allow the user to switch language using a Language Switch Button.
Contributors will be able to create new language translations, and a set of documentation will be made to guide them.

The Feature is set to have English as both default and fallback language, and a French translation will be included in this PR as an example.

### What type of PR is it?
Feature

### Todos
* [x] - Inital plugin configuration
* [ ] - Finish transferring UI text to english translation
* [ ] - Finish French translation
* [ ] - Add Language Switch Button
* [ ] - Remember language choice
* [ ] - Modify license file for angular-translate
* [ ] - Create documentation on how to make a new translation & tips

### Is there a relevant Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-512

### How should this be tested?
No guidelines yet since it is still a work in progress

### Screenshots (if appropriate)

In English:
screen shot 2015-12-17 at 11 35 40 am

In French:
screen shot 2015-12-17 at 11 33 48 am

### Questions:
* Does the licenses files need update? (Yes, not yet updated)
* Is there breaking changes for older versions? (No)
* Does this needs documentation? (Yes, not yet created)

### CODE REVIEW

**Comment by corneadoug** [comment]
Closing this PR, there would be too much to rebase, better make a new one

**Comment by djKooks** [comment]
@corneadoug Good job!
One more suggestion, how about putting multi language resource into json files to manage easily? Maybe it could be easy to update for who wants to support translation string.

You could use $translateProvider.useStaticFilesLoader for this.

**Comment by corneadoug** [comment]
@djKooks Not sure it would make a difference.
In the way it is implemented, each language already have its own .js file.
And inside, the translations are set as an object/json format.

**Comment by djKooks** [comment]
@corneadoug Oh okay, I see. Thanks for the guide.

**Pull request closed without merging**
