### PR TITLE
[MINOR] remove the duplicate property username in RemoteInterpreter

### PR DESCRIPTION
**Pull request by wary**
### What is this PR for?

* Remove the username property in class RemoteInterpreter, instead reuse the username property in class Interpreter， to avoid get null value with method getUserName in the super class Interpreter

* Overwrite username get/set method  in class LazyOpenInterpreter

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
* [ZEPPELIN-2981]

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by zjffdu** [comment]
Thanks @wary Merge it if no more discussion.

**Comment by zjffdu** [comment]
@wary Before I merge this, could you update the title and add '[MINOR]' ?

**Comment by wary** [comment]
@zjffdu done！thx for code review

**Comment by zjffdu** [comment]
@wary Sorry for late response, the CI seems failed, could you help check that ? It may due to flaky test, you can try to rerun it.

**Comment by wary** [comment]
@zjffdu  all check passed!

**Comment by wary** [comment]
@zjffdu  as I checked, the reason of the ci failure is not related to this change， maybe need to create a new pull request to resolve

**Comment by zjffdu** [comment]
CI Failure is fixed, please rebase and rerun CI, thanks @wary

**Comment by zjffdu** [comment]
@wary CI is stuck, could you try again ?

**Comment by wary** [comment]
@zjffdu  done! please help review my another pull request [ZEPPELIN-3021]  If you are convenient， thank you very much

**Comment by wary** [comment]
@zjffdu  done!

**Comment by zjffdu** [comment]
@wary Your PR is mixed with other PR, could you clean it ? Thanks

**Pull request closed without merging**
