### PR TITLE
[MINOR] Change url in pom.xml files

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Set project url to `http://zeppelin.apache.org` in pom.xml files

### What type of PR is it?
Refactoring

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by minahlee** [comment]
merge if there is no more discussion

**Comment by zjffdu** [comment]
lgtm

**Comment by lresende** [comment]
If the URLs are all the same, and we set on the parent pom, wouldn't they be inherited ? In this case, we can actually remove all the child ones, and make future maintenance easier.

**Comment by bzz** [comment]
Looks good to me. 
The idea for inheriting URL from parent to reduce duplication sounds really good.

**Comment by minahlee** [comment]
I removed URLs from all child pom. Merge if there is no further comment

**Pull request closed without merging**
