### PR TITLE
[ZEPPELIN-3252] Update the Apache Flink version to 1.4.1

### PR DESCRIPTION
**Pull request by jan0sch**
Update the flink version to 1.4.1 and the related akka version to 2.4.20.

### What is this PR for?

This updates the flink interpreter to the latest Flink version which is 1.4.1.

### What type of PR is it?
[Improvement]

### What is the Jira issue?

* https://issues.apache.org/jira/browse/ZEPPELIN-3252

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
[Multiple builds](https://travis-ci.org/wegtam/zeppelin/builds/344196467) fails with 

```
artifacts could not be resolved: org.apache.flink:flink-clients_2.10:jar:1.4.1, org.apache.flink:flink-runtime_2.10:jar:1.4.1, org.apache.flink:flink-scala_2.10:jar:1.4.1, org.apache.flink:flink-scala-shell_2.10:jar:1.4.1, com.typesafe.akka:akka-actor_2.10:jar:2.4.20, com.typesafe.akka:akka-remote_2.10:jar:2.4.20, com.typesafe.akka:akka-slf4j_2.10:jar:2.4.20, com.typesafe.akka:akka-testkit_2.10:jar:2.4.20: Could not find artifact org.apache.flink:flink-clients_2.10:jar:1.4.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-flink_2.10
```

Can we check this error?

**Comment by jan0sch** [comment]
It seems that flink 1.4 is build for scala 2.11 only.

There are two options:

1. switch zeppelin to scala 2.11
2. downgrade the "update" to flink version 1.3.2 which was the last one cross published for scala 2.10

I would prefer option 1 as scala is currently at 2.12 with 2.13 on the horizon.

**Comment by jan0sch** [comment]
Some CI jobs still give dependency errors even with flink forced to scala 2.11:

https://travis-ci.org/wegtam/zeppelin/builds/348578784

```
[ERROR] Failed to execute goal on project zeppelin-flink_2.11: 
  Could not resolve dependencies for project org.apache.zeppelin:zeppelin-flink_2.11:jar:0.8.0-SNAPSHOT: 
  The following artifacts could not be resolved: 
    org.apache.flink:flink-clients_2.10:jar:1.4.1, 
    org.apache.flink:flink-runtime_2.10:jar:1.4.1, 
    org.apache.flink:flink-scala_2.10:jar:1.4.1, 
    org.apache.flink:flink-scala-shell_2.10:jar:1.4.1, 
    com.typesafe.akka:akka-actor_2.10:jar:2.4.20, 
    com.typesafe.akka:akka-remote_2.10:jar:2.4.20, 
    com.typesafe.akka:akka-slf4j_2.10:jar:2.4.20, 
    com.typesafe.akka:akka-testkit_2.10:jar:2.4.20: 
  Could not find artifact org.apache.flink:flink-clients_2.10:jar:1.4.1 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by felixcheung** [comment]
that's because of the references to `${scala.binary.version}` in the pom file?

**Comment by felixcheung** [comment]
where are we on this?

**Comment by jan0sch** [comment]
Currently I'm low on time for this. State so far:

* "downgrading" the upgrade to Flink 1.3.x seems to fix a build problem with an older spark version
* on my travis the other branches (master, branch-0.8) error out therefore it is hard to look at failed tests

It would be cool to go for Flink 1.4.x (as 1.5.x is on the horizon) but that would require switching to scala 2.11 which breaks older spark stuff, so this is not an option right now.

**Comment by ricobergmann** [comment]
Hi guys.
I have patched Zeppelin to work with Flink 1.4.2. If you like I can share this with you in order to integrate this into Zeppelin. The only drawback of my current solution is, that you would need to compile this with scala-2.11 profile. May be someone can help with integrating different profiles for flink?

Best, Rico.

**Comment by jan0sch** [comment]
Hi,

thanks for you offer. This actually started out with an update to 1.4.2 (we use such a patch in production) but that collides with the way zeppelin is currently build. Therefore the downgrade to 1.3 was made to keep compatibility.

Using different profiles might be the best approach, thanks for that. I'll try to take a look into that when I've got some time.

**Comment by jongyoul** [comment]
@jan0sch Can you keep one of PR related to this issue? Please check #2742

**Comment by jan0sch** [comment]
@jongyoul Upgrading to Flink > 1.3 is sadly not possible because it requires Scala >= 2.11 which would break the Spark 1.x stuff in Zeppelin. :-(

**Comment by jongyoul** [comment]
@jan0sch Thanks for letting me know that. Let's find a way to solve it.

**Comment by zjffdu** [comment]
@jan0sch @jongyoul  I created pr #3054 for flink interpreter improvement. But it still WIP, I will refine it later.

**Comment by jan0sch** [comment]
@zjffdu Awesome! If this works then maybe we should target Flink 1.5.

**Comment by jan0sch** [comment]
@zjffdu Cool. I'll close my pull-requests then because it makes way more sense to bring your stuff into the project.

**Comment by jan0sch** [comment]
Closed because overcome by events. See https://github.com/apache/zeppelin/pull/3054 for details.

**Pull request closed without merging**
