### PR TITLE
Small cleanup of zeppelin-server tests

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
Small cleanup of zeppelin-server tests

### What type of PR is it?
Refactoring

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
CI failed due to [ZEPPELIN-1264](https://issues.apache.org/jira/browse/ZEPPELIN-1264)

Rebasing on latest master and merging, if there is no further discusison

**Comment by bzz** [comment]
CI failure

```
Results :

Failed tests: 
  ZeppelinSparkClusterTest.sparkRTest:116 expected:<[[1] 3]> but was:<[<pre><code>Error in getSparkSession(): SparkSession not initialized
</code></pre>

<pre><code>Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'count' for signature '&quot;function&quot;'
</code></pre>]>

Tests run: 65, Failures: 1, Errors: 0, Skipped: 0
````

Fixed in #1259 so rebasing again

**Comment by jongyoul** [comment]
I like this kind of PR. LGTM. Thanks for cleaning tests and removing unnecessary class.

**Comment by bzz** [comment]
Thank you for review @jongyoul !

CI fails on spark 1.6 profile, same as master, handled under [ZEPPELIN-1286](https://issues.apache.org/jira/browse/ZEPPELIN-1286)

Merging if there is no further discussion.

**Pull request closed without merging**
