### PR TITLE
ZEPPELIN-204 make scala code completion work again

### PR DESCRIPTION
**Pull request by pellmont**
### What is this PR for?
Spark Scala interpreter didn't show any useful completion proposals (besides some keywords)

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-204

### How should this be tested?
Open a note with spark interpreter. Write some (multiline) code. Open code completion with ctrl-.
There are also some additional unit tests...

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested manually and it works well.

@pellmont could you setup CI and see all tests become green?
```
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
And then make sure 'Build branch updates' option is enabled in the settings https://travis-ci.org/pellmont/zeppelin/settings.

To trigger CI after setup, you will need ammend your last commit with
git commit --amend
git push your-remote HEAD --force

See http://zeppelin.apache.org/contribution/contributions.html#continuous-integration.
```

**Comment by pellmont** [comment]
Hey guys

I finally found why some integration tests fail!
In scala 2.11.8 the REPL had been improved a lot. So the tests work well with either scala 2.10 (with SparkJLineCompletion) or scala >=2.11.8 (with cala.tools.nsc.interpreter.JLineCompletion).

I'll investigate further to see whether I find a solution for scala 2.11 <=2.11.7.
Otherwise I'll disable the (extended) tests for the scala versions below 2.11.8 (via Assume)

**Comment by pellmont** [comment]
finally a green build :-)

**Comment by Leemoonsoo** [comment]
@pellmont Cool!

LGTM and merge to master if no further comment.

**Comment by pellmont** [comment]
do I have to do something else before it can be merged? or just wait?

**Comment by felixcheung** [comment]
we are just wrapping up, shouldn't need anything at this point.

**Pull request closed without merging**
