### PR TITLE
Branch 0.6 Groovy Interpreter

### PR DESCRIPTION
**Pull request by dlukyanov**
### What is this PR for?
Groovy Interpreter

### What type of PR is it?
Feature 

### Todos
* [Code] - Task
* [Samples] - Task
* [Documentation] - Task
* [Test cases] - Task

### What is the Jira issue?
TODO

### How should this be tested?
Outline the steps to test the PR here.

### Samples

```groovy
%groovy
//get a parameter defined as z.angularBind('ngSearchParam', value, 'paragraph_id')
//g is a context object for groovy to avoid mix with z object?
def param = g.angular('ngSearchParam')
//send request https://www.googleapis.com/customsearch/v1?q=ngSearchParam_value
def r = HTTP.get(
  //assume you defined groovy interpreter property `search_baseurl`='https://www.googleapis.com/customsearch/v1'
  //in groovy object o.getProperty('A') == o.'A' == o.A == o['A']
  url : g.search_baseurl,
  query: [ q: param ],
  headers: [
    'Accept':'application/json',
    //'Authorization:' : g.getProperty('search_auth'),
  ] 
)
//check response code
if( r.response.code==200 ) {
  g.html().with{ 
    //g.html() renders %angular to output and returns groovy.xml.MarkupBuilder
    h2("the response ${r.response.code}")
    span( r.response.body )
    h2("headers")
    pre( r.response.headers.join('\n') )
  }
} else {
  //just to show that it's possible to use println with multiline groovy string to render output
  println("""%angular
    <script> alert ("code=${r.response.code} \n msg=${r.response.message}") </script>
  """)
}
```

```groovy
%groovy

//renders a table with headers a, b, c  and two rows
g.table(
  [
    ['a','b','c'],
    ['a1','b1','c1'],
    ['a2','b2','c2'],
  ]
)
```

### Questions:
* Does the licenses files need update?
no
* Is there breaking changes for older versions?
no
* Does this needs documentation?
yes

### CODE REVIEW

**Comment by jongyoul** [comment]
Thanks for contributing new Groovy interpreter but we didn't manage the branch-0.6 anymore. Can you rebase your contribution onto current master?

**Comment by dlukyanov** [comment]
Hello 

Current - is it next to 0.7 ? 

30 January 2017, 08:02:58, by Jongyoul Lee < notifications@github.com >: 
Thanks for contributing new Groovy interpreter but we didn't manage the branch-0.6 anymore. Can you rebase your contribution onto current master? — 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 

-- Regards, Dmitry

**Comment by jongyoul** [comment]
If you contribute code based on master, we will review and merge it into master and branch-0.7 if necessary.

**Comment by felixcheung** [comment]
Right - please develop against master and open a new PR.

**Comment by felixcheung** [comment]
and please add interpreter documentation .md file and update license information as suggested in the PR template `Does the licenses files need update?` should be yes.

**Comment by dlukyanov** [comment]
created a new pull request [#2068](https://github.com/apache/zeppelin/pull/2068)

**Pull request closed without merging**
