### PR TITLE
ZEPPELIN-1308 Apache Ignite version upgraded up to 1.7

### PR DESCRIPTION
**Pull request by agura**
### What is this PR for?
Apache Ignite 1.7 release contains contains many improvements and fixes. What is important for Ignite interpreter it support of distributed joins for non colocated data (IGNITE-3563).

### What type of PR is it?
[ Improvement ]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1308

### How should this be tested?
Unit-tests under `org.apache.zeppelin.ignite` package are enough/

### CODE REVIEW

**Comment by agura** [comment]
It seems that falied tests are not related with Ignite or Ignite dependencies. Could somebody take a look please?

**Comment by bzz** [comment]
@agura thank you for taking care!

CI fails on 2 profiles for Spark 1.5 and 1.6 with

```
#1.6
[INFO] Zeppelin: Display system apis ...................... FAILURE [ 15.213 s]
....
32mAngularElem[0m
[31m- should provide onclick method *** FAILED ***[0m
[31m  The code passed to eventually never returned normally. Attempted 1 times over 6.556017119 seconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m

and 1.5

[INFO] Zeppelin: Display system apis ...................... FAILURE [  4.087 s]
.....
[31m- should provide onclick method *** FAILED ***[0m
[31m  The code passed to eventually never returned normally. Attempted 1 times over 327.498544 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m
[32mAngularElem[0m
```

This looks very suspicious and reproducible.. before digging any deeper - could you please close and re-open this PR in order to trigger the CI one more time?

**Comment by agura** [comment]
@bzz Thanks for assistance. PR reopened.

**Comment by minahlee** [comment]
CI is green now. Shall we merge this one?

**Comment by minahlee** [comment]
Merge if there is no more discussion

**Pull request closed without merging**
