### PR TITLE
ZEPPELIN-2834 Show Interpreter list as expand collapse blocks

### PR DESCRIPTION
**Pull request by malayhm**
### What is this PR for?
Previously, it's hard to find particular interpreter as a user hast to scroll down a long page to find out the interpreter. After this change, all the interpreter will be collapsed and the user can expand an interpreter and change the setting.

See the attached GIFs for comparison.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2834

### How should this be tested?
1. Build: mvn clean package -Denforcer.skip -DskipTests -Drat.skip
2. Open a paragraph
3. Check the cursor

### Screenshots (if appropriate)

Before
interpreter-expand-collapse-before

After
interpreter-expand-collapse-after

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by 1ambda** [comment]
Thanks for the contribution. Really nice and useful feature.

I guess you introduced new property `isExpanded` in setting. It would be nice to include newly added the property in existing settings as we did in https://github.com/apache/zeppelin/pull/2268/files. It will be more explicit.

**Comment by prabhjyotsingh** [comment]
Also, can you add a functionality expand/collapse all setting (button)?

**Comment by malayhm** [comment]
@prabhjyotsingh Added expand / collapse all:

interpreter-expand-collapse-after-2

**Comment by malayhm** [comment]
@1ambda Do you mean that it should also persist the setting value so that whenever user go to interpreter page, it will open from the last state or just explicit declaration without persistence?

**Comment by malayhm** [comment]
@1ambda Could you please check my comment above?

**Comment by malayhm** [comment]
@1ambda Can we merge this to master if there are no more comments?

**Comment by malayhm** [comment]
@1ambda @prabhjyotsingh @Leemoonsoo Can we merge this to master if there are no discussions?

**Comment by malayhm** [comment]
@1ambda @prabhjyotsingh @Leemoonsoo Can we merge this to master if there are no discussions?

**Comment by Leemoonsoo** [comment]
@malayhm I tested this manually and it works well.
https://travis-ci.org/malayhm/zeppelin/builds/272626975 some CI jobs are failing. could you restart them and see they become green?

**Comment by malayhm** [comment]
@Leemoonsoo I tried restarting the CI, but no luck.

**Pull request closed without merging**
