### PR TITLE
[ZEPPELIN-5898]fix:down csv data error

### PR DESCRIPTION
**Pull request by zhugezifang**
### What is this PR for?

This pull request fix the bug of download csv data error

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5898

### How should this be tested?
* CI

### Questions:
* Does the license files need to update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by Reamer** [comment]
Still

> Thanks for the contribution @zhugezifang , could you update the PR description?

**Comment by zhugezifang** [comment]
> Still
> 
> > Thanks for the contribution @zhugezifang , could you update the PR description?

ok，updated it

**Comment by Reamer** [comment]
I do not understand the fix. Could you please explain it.

**Comment by zhugezifang** [comment]
> I do not understand the fix. Could you please explain it.

let we look the example of https://issues.apache.org/jira/browse/ZEPPELIN-5898 

when i query the result in zeppelin，the result is

image

and click download
image


but the data of downloaded has problems

image


the column of params_value is json，but  open  in  csv, it is not ，so it has a bug

this pr is to fix the bug

**Comment by zhugezifang** [comment]
>

**Comment by zhugezifang** [comment]
> I do not understand the fix. Could you please explain it.

excuce me，the is a webchat group or other group of zeppelin，we can discuss it more timely。

and i want to add the feature to zeppelin ，it is a brief description in https://issues.apache.org/jira/browse/ZEPPELIN-5896

i discuss the feature with @zjffdu ,he say i can try it

**Comment by Reamer** [comment]
I don't think it's a specific JSON problem, but rather a delimiter problem.
The CSV is broken because in the JSON example there is a `,` in the text field and this is also used as a delimiter.
What do you think about it?

**Comment by zhugezifang** [comment]
> I don't think it's a specific JSON problem, but rather a delimiter problem. The CSV is broken because in the JSON example there is a `,` in the text field and this is also used as a delimiter. What do you think about it?

yes ,the code solve the  ',' of delimiter, but it solved not perfect，it also exist bug

image

**Comment by zhugezifang** [comment]
> > I do not understand the fix. Could you please explain it.
> 
> excuce me，there is a webchat group or other group of zeppelin，we can discuss it more timely。
> 
> and i want to add the feature to zeppelin ，it is a brief description in https://issues.apache.org/jira/browse/ZEPPELIN-5896
> 
> i discuss the feature with @zjffdu ,he say i can try it

@Reamer  hi，i also want to add this feature into zeppelin，and could I get your support？

**Comment by zhugezifang** [comment]
> > @Reamer hi，i also want to add this feature into zeppelin，and could I get your support？
> 
> Of course. I was able to reproduce the problem and understood the problem. Your change definitely solves the problem. It's just not a JSON specific problem, but a general masking problem.
> 
> I would remove the if statement. It is not necessary because replaceAll also looks for the quotes.
> 
> ```
> // Mask all quotes
> stringValue = stringValue.replaceAll('"', '""');
> ```

ok,i update it later and then add a new pr

**Pull request closed without merging**
