### PR TITLE
Add force layout visualization in paragraphs for SQL queries

### PR DESCRIPTION
**Pull request by davidtzoor**
### What is this PR for?
Add force layout (graph) visualization to the existing set of visualizations in Zeppelin Web notp. 

### What type of PR is it?
[Feature]

### What is the Jira issue?
[ZEPPELIN-1011]

### How should this be tested?
The testes are incorporated within the existing test suite. 

### Screenshot
eeffbb58-3238-11e6-92ea-148a4063d353

### Questions:
* Does the licenses files need update?
No.
* Is there breaking changes for older versions?
No.
* Does this needs documentation?
We can add some documentation explaining about the different fields that need to be selected in order to generate the force layout component.

### CODE REVIEW

**Comment by davidtzoor** [comment]
@corneadoug Have you seen this new PR? let me know if everything's good

**Comment by davidtzoor** [comment]
Hi @bzz, is there is issue with my PR? Please let me know if there is something I can do to help get it done. Thanks :smile:

**Comment by corneadoug** [comment]
@davidtzoor Can you rebase?

**Comment by davidtzoor** [comment]
@corneadoug do you want me to rebase to the master on my fork?

**Comment by corneadoug** [comment]
@davidtzoor Right, there has been some changes that brings conflicts

**Comment by bzz** [comment]
RIght, in you fork you need to pull the master from apache git and then rebase this branch on top of it, resolving the conflicts.

**Comment by davidtzoor** [comment]
@bzz I fixed the conflict

**Comment by AhyoungRyu** [comment]
@davidtzoor It seems many unrelated commits are included in this PR after you rebased. Could you check again?

**Comment by davidtzoor** [comment]
@AhyoungRyu I just did a pull from the zeppelin repo to my fork, rebase and resolved the conflicts.
What did I do wrong?

**Comment by davidtzoor** [comment]
I think these are all the PR that were accepted since my initial pull request.

**Comment by AhyoungRyu** [comment]
@davidtzoor I'm not sure what you missed, your local master branch seems quite outdated. Zeppelin follows [fork & pull](https://github.com/apache/zeppelin/blob/master/CONTRIBUTING.md#source-control-workflow) model as a source control workflow. 

##### 1. In your forked local repository

```
git checkout master
```

##### 2. set upstream and update local master

```
git remote add upstream git://github.com/apache/zeppelin.git
git fetch upstream
git pull upstream master
```

##### 3. rebase your branch `forcelayout` with latest master

```
git checkout forcelayout
git rebase master
```
Did you do as the above steps?

**Comment by davidtzoor** [comment]
I am closing this PR and creating a new one (again). sorry for all the mess

**Comment by AhyoungRyu** [comment]
@davidtzoor Never mind. Please feel free to do that :)

**Comment by davidtzoor** [comment]
@AhyoungRyu I created a new PR (#1135) and closing this one. I hope this time it will work.

**Pull request closed without merging**
