### PR TITLE
[ZEPPELIN-3882] Neo4jInterpreter - Support Point and Date Types

### PR DESCRIPTION
**Pull request by conker84**
### What is this PR for?
Add the support for Point and Date data types introduced since Neo4j 3.4

### What type of PR is it?
[Improvement] In order to allow users to use the Neo4j Interpreter with the last introduced Data types

### Todos
* [x] - Bumped Neo4j dependecies version
* [x] - Added new data types to test

### What is the Jira issue?
* Put link here, and add [ZEPPELIN-3882](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-3882)

### How should this be tested?
* Execute the unit tests

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by conker84** [comment]
@felixcheung I'm back.

**Comment by felixcheung** [comment]
looks like you are blocked by https://github.com/apache/zeppelin/pull/3243

https://api.travis-ci.org/v3/job/461718800/log.txt

**Comment by conker84** [comment]
Can you give me a ping when it's ready?

**Comment by zjffdu** [comment]
@conker84 #3243 is fixed, could you rebase this PR ?

**Comment by conker84** [comment]
I did it, and travis it's green now:
https://travis-ci.org/conker84/zeppelin

**Comment by conker84** [comment]
@zjffdu ping

**Comment by conker84** [comment]
@zjffdu @felixcheung ping

**Comment by conker84** [comment]
Still no news?

**Comment by felixcheung** [comment]
I see it's green. not sure why the report above is not.

**Comment by felixcheung** [comment]
merging if no more comment

**Comment by felixcheung** [comment]
it looks like the github rebase and merge option is picking the last commit description

**Comment by felixcheung** [comment]
Github doesn’t let me edit title. I think committer should use the merge script and not the github Web UI.

If you think this is a problem, let me know

**Comment by jongyoul** [comment]
I've tested my wip pr by clicking squash and merge button on the pr page. I saw we could edit a title and commit messages as well. Could you please check it again?

**Comment by felixcheung** [comment]
Squash and merge seems like the right option,
https://help.github.com/articles/merging-a-pull-request/

**Comment by felixcheung** [comment]
@conker84 sorry, could you see if you could re open this PR so I can merge again?

**Comment by jongyoul** [comment]
@felixcheung Thanks a lot 👍

**Comment by felixcheung** [comment]
@conker84 ping - this was reverted, could you re-open

**Comment by felixcheung** [comment]
hm, this is a bit tricky - could you open a new branch and cherry-pick the commits to it, then open a new PR? @conker84

**Comment by conker84** [comment]
@felixcheung I created the #3284. Let me know if I have to do something else

**Comment by felixcheung** [comment]
thanks!

**Pull request merged**
