### PR TITLE
[ZEPPELIN-429] Replaced explicit types with diamonds

### PR DESCRIPTION
**Pull request by HorizonNet**
### What is this PR for?

Changed all occurrences of explicit types to diamonds in the different modules.
### What type of PR is it?

Improvement
## 
### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-429
### How should this be tested?

Run the normal Maven build process.
### Questions:
- Does the licenses files need update? No
- Is there breaking changes for older versions? No
- Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
Thank for the contribution. I like this kind of contribution to make code clean. LGTM. I'll merge it.

**Comment by HorizonNet** [comment]
@jongyoul Quick question regarding the merge conflict: Should I solve it or do you do it during the integration?

**Comment by minahlee** [comment]
@HorizonNet It's better to be handled here. Could you resolve it please?

**Comment by HorizonNet** [comment]
@minahlee Done.

**Comment by minahlee** [comment]
Merging it there is no more discussion

**Pull request closed without merging**
