### PR TITLE
[ZEPPELIN-919] Apply new mechanism to Markdown

### PR DESCRIPTION
**Pull request by rerngvit**
### What is this PR for?
This PR applies the new interpreter registration mechanism to Markdown

### What type of PR is it?
Improvement

### Todos
- Move interpreter registration properties from static block to interpreter-setting.json

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-919

### How should this be tested?
1. apply patch
2. rm -r interpreter/md
3. rm conf/interpreter.json
4. mvn clean package -DskipTests
5. bin/zeppelin-daemon.sh start
6. run some paragraph with markdown

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by rerngvit** [comment]
@bzz @jongyoul

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by rerngvit** [comment]
@prabhjyotsingh Just did.

**Comment by prabhjyotsingh** [comment]
CI green. 
Merging this if no more discussion.

**Pull request closed without merging**
