### PR TITLE
ZEPPELIN-2137 Changed "show line chart with focus" to "zoom" so that …

### PR DESCRIPTION
**Pull request by samthebest**
https://issues.apache.org/jira/browse/ZEPPELIN-2137

Improvement

### How should this be tested?
Run it, look at it (UX change)

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by felixcheung** [comment]
Hmm ok :)
it looks like there's an issue with the Jenkins check
```
[zeppelin-pull-request] $ /bin/bash -xe /tmp/hudson1411217650836319294.sh
+ '[' -f travis_check.py ']'
+ echo 'travis_check.py does not exists'
travis_check.py does not exists
```

@Leemoonsoo I assume this means CI tests are not actually run, correct?

**Comment by Leemoonsoo** [comment]
Yes, Jenkins couldn't run 'travis_check.py' because of this PR is based on folk before 'travis_check.py' exists.

**Comment by Leemoonsoo** [comment]
The change LGTM.

**Comment by felixcheung** [comment]
@samthebest could you rebase this PR to get it to run CI tests?

**Comment by samthebest** [comment]
@felixcheung  I guess that means `branch-0.7` isn't up to date with `master`?  Not sure what your workflow is, but it sounds like I made a mistake, and should be PRing `master`.  I don't think you want a small commit like this to rebase `branch-0.7`?! (`master` conflicts with `branch-0.7` so rebasing would indiscriminately wipe away changes to `branch-0.7`)

So I created another PR from my fork straight into master https://github.com/apache/zeppelin/pull/2050

**Comment by felixcheung** [comment]
ah, yes, I didn't realize this is based of branch-0.7 - we should create PR off master instead.

**Pull request closed without merging**
