### PR TITLE
[ZEPPELIN-1714] Build error of scio Intepreter on Centos

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes build error of scio Intepreter on CentOS.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1714

### How should this be tested?
Run `mvn clean package -DskipTest' on CentOS

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@astroshim Thanks for your contribution. 
Tested with master branch in `CentOS release 6.8 (Final)`, but I can successfully build latest master branch.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 13.677 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  5.024 s]
[INFO] Zeppelin: Scio ..................................... SUCCESS [01:08 min]
[INFO] Zeppelin: Server ................................... SUCCESS [ 19.772 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2016-11-26T20:17:22+09:00
[INFO] Final Memory: 137M/3563M
[INFO] ------------------------------------------------------------------------
```
```
[fbdkdud93@worker9 zeppelin]$ lsb_release -d
Description:	CentOS release 6.8 (Final)
```
Could you elaborate which version you are using now?

**Comment by astroshim** [comment]
@AhyoungRyu Thank you for reviewing. I am using Zeppelin master on CentOS-7.

**Comment by AhyoungRyu** [comment]
@astroshim Tested on CentOS 7 again and faced the issue you described. 
Also I checked the other files that contains `import scala.tools.nsc.*` (e.g. [FlinkInterpreter.java](https://github.com/apache/zeppelin/blob/master/flink/src/main/java/org/apache/zeppelin/flink/FlinkInterpreter.java), [DepInterpreter.java](https://github.com/apache/zeppelin/blob/master/spark/src/main/java/org/apache/zeppelin/spark/DepInterpreter.java), [IgniteInterpreter.java](https://github.com/apache/zeppelin/blob/master/ignite/src/main/java/org/apache/zeppelin/ignite/IgniteInterpreter.java) and etc etc.. ) are all importing not `tools.nsc..` but `scala.tools.nsc...`. 
So anyway LGTM :D 👍

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Merge into master if there are no more comments.

**Pull request closed without merging**
