### PR TITLE
[ZEPPELIN-5898]fix:download csv data error

### PR DESCRIPTION
**Pull request by zhugezifang**
### What is this PR for?

This pull request fix the bug of download csv data error

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5898

### How should this be tested?
* CI

### Questions:
* Does the license files need to update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Review by Reamer — APPROVED** [review]
LGTM

**Comment by zhugezifang** [comment]
> LGTM

thanks, and i also want to add the feature  of  sql-debug  to zeppelin ，it is a brief description in https://issues.apache.org/jira/browse/ZEPPELIN-5896

**Comment by Reamer** [comment]
Thank you for your participation. I am looking forward to your PullRequest.

**Review by jongyoul — APPROVED** [review]

**Comment by jongyoul** [comment]
Thank you for the contribution, especially in frontend part :-) We are looking forward to your continuous contributions.

**Pull request merged**
