### PR TITLE
[ZEPPELIN-1251] Update interpreter artifact option list for netinst package

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Add scala 2.11 artifact options for netinst package

### What type of PR is it?
Documentation

### What is the Jira issue?
[ZEPPELIN-1251](https://issues.apache.org/jira/browse/ZEPPELIN-1251)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
What will happen with `./bin/install-interpreter.sh --all` ?
@minahlee Do you have any good idea to not install xxx_2.10 and xxx_2.11 together with `--all` option?

**Comment by Leemoonsoo** [comment]
Instead of listing all xxx_2.10 and xxx_2.11 in `conf/interpreter_list`, i think just listing one version that is included in `zeppelin-bin-all` package would be fine, i think.

User can always manually install the other version of interpreter using `-n` and `-t` option of `bin/install-interpreter.sh` command.

**Comment by minahlee** [comment]
Addressed your comment in 63509c0. Please review

**Comment by Leemoonsoo** [comment]
Looks good to me

**Comment by minahlee** [comment]
Merge if there is no more discussion

**Comment by bzz** [comment]
Looks great to me. :shipit:

**Pull request closed without merging**
