### PR TITLE
[ZEPPELIN-3478] Download Data as CSV downloads data as a single line

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
All data is in one single line - lines separated with backslash and "n" sequence and not actual newline characters "\n".

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [ZEPPELIN-3478](https://issues.apache.org/jira/browse/ZEPPELIN-3478)

### How should this be tested?
All the exports should work in all browsers
 * Export this notebook
 * Export as CVS
 * Export as TSV

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@Tagar @r-kamath  can you help review this.

**Comment by Tagar** [comment]
thanks for prompt response @prabhjyotsingh 
I will give this a try today.

**Comment by Tagar** [comment]
LGTM 
Verified manually - this patch fixes the issue.
Thanks a lot @prabhjyotsingh

**Comment by r-kamath** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Thanks for the review will merge this to master and branch-0.8 if no more discussion.

**Pull request closed without merging**
