### PR TITLE
[ZEPPELIN-1743] Use explicit arguments in functions in paragraph.controller.js

### PR DESCRIPTION
**Pull request by felizbear**
### What is this PR for?
This is `paragraph.controller.js` maintenance PR. It refactors most functions in paragraph controller to accept explicit parameters instead of getting data from `$scope`. It is a first - simple and safe - step in making paragraph controller more maintainable.

### What type of PR is it?
Refactoring

### Todos
* [x] - Call functions explicitly with parameters when makes sense
* [x] - Do minor refactoring when makes sense

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1743

### How should this be tested?
Make sure that paragraph works as expected by interacting with it;

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me, thank you @felizbear for frontend code improvements! 

Let's wait for CI, meanwhile, would you mind creating a JIRA issue please?

**Comment by Leemoonsoo** [comment]
LGTM!

**Comment by bzz** [comment]
Looks great to me!

@felizbear In my experience, if the contribution author followup on CI failure - that speeds up the merge time tremendously.

It looks like at least CI is failing on `npm run test` (which fails on the `grunt test`? ), could you please double-check\digg into it?

```
ERROR] 
[ERROR] npm ERR! Linux 4.8.7-040807-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "run" "test"
[ERROR] npm ERR! node v6.9.1
[ERROR] npm ERR! npm  v3.10.8
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! zeppelin-web@0.0.0 test: `grunt test`
[ERROR] npm ERR! Exit status 3
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the zeppelin-web@0.0.0 test script 'grunt test'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the zeppelin-web package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     grunt test
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs zeppelin-web
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls zeppelin-web
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/zeppelin/zeppelin-web/npm-debug.log
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (npm test) on project zeppelin-web: Failed to run task: 'npm run test' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by felizbear** [comment]
this backend test currently fails

```
- should provide onclick method *** FAILED ***

  The code passed to eventually never returned normally. Attempted 1 times over 516.964883 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:64)
```

investingating why

**Comment by felizbear** [comment]
All checks have passed. Let's merge it please

**Comment by bzz** [comment]
Thank you @felizbear !

Merging to master if there is no further discussion

**Pull request closed without merging**
