### PR TITLE
[ZEPPELIN-2058] Reduce travis build time

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR reduces travis build time

| Test profile        | Before (rough avg min)          | After (rough avg min) |
| ------------- |:-------------:| -----:|
| RAT check    | 1.5 | 1.5 |
| All modules with spark 2.1 and scala 2.11   | 35  | 35 |
| All modules with spark 2.0 and scala 2.10   | 35  | 35 |
| Spark 1.6 with scala 2.10 | 35 | **15** |
| Spark 1.6 with scala 2.11 | 35 | **15** |
| Spark 1.5 | 25 | **removed** |
| Spark 1.4 | 25 | **removed** |
| Selenium | 25 | 25 |
| Python2 | 8 | 8 |
| Python3 | 8 | 8 |
| Livy | 15 | **8** |
| Total | 247.5 |  149 | 

### What type of PR is it?
Improvement

### Todos
* [x] - Remove spark 1.5 profile and 1.4 profile
* [x] - optimize profiles

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2058

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
The [test passes](https://travis-ci.org/Leemoonsoo/zeppelin/builds/200218542) in my travis account.

Recently, travis concurrent build assigned to Zeppelin is reduced to 5 from 11. [INFRA-13469](https://issues.apache.org/jira/browse/INFRA-13469).

And today i see a CI triggering waits almost 10 hours to start. 
This PR reduces CI build time by 60%, i'd like to merge it to master and see how it helps.

**Comment by zjffdu** [comment]
+1

**Comment by prabhjyotsingh** [comment]
👍

**Comment by jongyoul** [comment]
+1

**Pull request closed without merging**
