### PR TITLE
[ZEPPELIN-3076]Chart field is also draggable and sortable in the 'keys', 'groups' and 'values'

### PR DESCRIPTION
**Pull request by liguohuicmss**
### What is this PR for?
Current the `keys`, `groups` and `values` is only droppable. It is a little inconvenient if I want to drag it to other place or sort it.
This feature let `keys`, `groups` and `values` not only `droppable`, but also `draggable` and `sorttable`.

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3076 [ZEPPELIN-3076]

### How should this be tested?
I have Add the Screenshots for the test. Just as the Screenshots showing, all the element in `keys`, `groups` and `values` is draggable and sorttable.

untitled project4

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @liguohuicmss for the improvement!
I manually tested this branch and it works really well.

It seems Jenkins somehow failed to start a build job for this pullrequest.
@liguohuicmss Could you try setup [Continuous Integration](http://zeppelin.apache.org/contribution/contributions.html#continuous-integration) and trigger the build? push new commit or close/reopen pullrequest will trigger the job.

**Comment by liguohuicmss** [comment]
Thanks you. I have done according to your suggestion. But the Jenkins still failed.
I cannot find the commit message in `https://travis-ci.org/profile` and the JSON from `https://api.travis-ci.org/repos/liguohuicmss/zeppelin/builds` is empty.

**Comment by Leemoonsoo** [comment]
Looks like you have setup CI correctly.
Job profile #4 fails https://travis-ci.org/liguohuicmss/zeppelin/builds/308472149.
It is probably due to flaky test. But could you try restart #4 and see if it becomes green? just in case.

**Comment by liguohuicmss** [comment]
Not easy. All is succeed. Thank you very much. @Leemoonsoo 

https://travis-ci.org/liguohuicmss/zeppelin/builds/308472149

By the way. I don't know why the Traivs-ci always has no commit message when I close/reopen the PR several times, But  adding a new empty ccommit is useful.

**Comment by Leemoonsoo** [comment]
Thanks! LGTM and merge to master if no further discussions.

Ah, you're right. close/reopen will not trigger travis. Zeppelin github repo configured to trigger Jenkins, not travis directly. Jenkins  does not actually build the project but check travis build of individual contributor. So, close/reopen will trigger Jenkins again, check travis build status but does not trigger travis build. Apologies for inaccurate information.

**Pull request closed without merging**
