### PR TITLE
[ZEPPELIN-4657] update to commons-compress 1.21

### PR DESCRIPTION
**Pull request by pjfanning**
### What is this PR for?

Related to https://issues.apache.org/jira/browse/ZEPPELIN-4657

commons-compress 1.20 has CVEs - see https://mvnrepository.com/artifact/org.apache.commons/commons-compress

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4657

### How should this be tested?
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by pjfanning** [comment]
@zjffdu done - some jobs failed but they seem to be failing on trunk anyway (if I am not mistaken).

**Comment by zjffdu** [comment]
Thanks @pjfanning Frontend CI failure is not related

**Comment by pjfanning** [comment]
@zjffdu I found some other usages of commons-compress. Updating them dragged me down the rabbit hole somewhat. The latest CI build has some server jobs failing but they appear to mainly down to connectivity issues when retrieving jars.

**Comment by zjffdu** [comment]
spark-integration-test fails consistently, but I don't see this error in CI of other PRs, need to look into it further.

**Comment by pjfanning** [comment]
closing in favour of https://github.com/apache/zeppelin/pull/4315

**Pull request closed without merging**
