### PR TITLE
[ZEPPELIN-1461] Doesn't display "description" value in interpreter creation page

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
#1522 tried to fix same issue by making as least change as possible, but fixing it in backend side looks like more proper approach as https://github.com/apache/zeppelin/pull/1522#issuecomment-255109922.

This PR fixes ZEPPELIN-1461 by changing `properties` field of `InterpreterSetting` class from `Properties` -> `Object`.
### What type of PR is it?

Bug Fix
### What is the Jira issue?

[ZEPPELIN-1461](https://issues.apache.org/jira/browse/ZEPPELIN-1461)
### Screenshots (if appropriate)

Before
screen shot 2016-10-24 at 8 42 02 pm

After
screen shot 2016-10-24 at 8 37 17 pm
### Questions:
- Does the licenses files need update? no
- Is there breaking changes for older versions? no
- Does this needs documentation? no

### CODE REVIEW

**Comment by minahlee** [comment]
\cc @jongyoul @cloverhearts @kjhong for review

**Comment by jongyoul** [comment]
LGTM. Please rebase it.

**Comment by minahlee** [comment]
@jongyoul Done :)

**Comment by cloverhearts** [comment]
Tested.
Looks good to me!
Very good and clear code!
+1

**Comment by jongyoul** [comment]
I'll merge it.

**Pull request closed without merging**
