### PR TITLE
ZEPPELIN-3161. Fixed Checkstyle issues in lens module

### PR DESCRIPTION
**Pull request by HorizonNet**
### What is this PR for?
Fixes the Checkstyle issues in the lens module.

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3161

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
merging if no more comment

**Comment by HorizonNet** [comment]
Let me have a look into it (also in the other PRs). Don't know yet why this file was changed.

**Comment by HorizonNet** [comment]
Reverted `zeppelin-web/package-lock.json` to the one from the `master` branch.

**Comment by felixcheung** [comment]
merging if no more comment

**Pull request closed without merging**
