### PR TITLE
[ZEPPELIN-1940] lint rule set is NOT applied at all.

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

eslint ruleset is NOT applied at all due to invalid `.eslintrc`.

This PR includes

- fixes which are automatically done by eslint (`eslint --fix src`)
- modification in `.eslintrc`, `package.json`
- while removing eslint conf in `gruntfile.js`

As a result of this PR, we can have more strict and modernized rulesets which can help us to prevent bugs.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Setup rules
* [x] - Remove grunt eslint config
* [x] - Ignore useless rules
* [x] - Fix code for applied rules

### What is the Jira issue?

[ZEPPELIN-1940](https://issues.apache.org/jira/browse/ZEPPELIN-1940)

### How should this be tested?

- `cd zeppelin-web`
- `npm install` (or `yarn install` if you have yarn)
- `npm run lint:once`

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
@AhyoungRyu Could you help review this?

**Comment by 1ambda** [comment]
@AhyoungRyu Could you help review this?

**Comment by AhyoungRyu** [comment]
@1ambda Great work! Quickly looked through the most of file changes and it looks good. Zeppelin web is getting bigger, everyone will feel the necessity of this kind of lint rule. 

btw I saw the below some warning msgs when I ran `npm run lint:once`,
```
$ npm run lint:once

> zeppelin-web@0.0.0 lint:once /Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web
> eslint src


/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/src/app/notebook/notebook.controller.js
  52:34  warning  Unnecessary escape character: \/  no-useless-escape
  52:44  warning  Unnecessary escape character: \/  no-useless-escape
  52:59  warning  Unnecessary escape character: \/  no-useless-escape
  52:69  warning  Unnecessary escape character: \/  no-useless-escape

/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/src/app/visualization/builtins/visualization-nvd3chart.js
  131:37  warning  Unexpected mix of '&&' and '||'  no-mixed-operators
  131:54  warning  Unexpected mix of '&&' and '||'  no-mixed-operators

/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/src/components/noteListDataFactory/noteList.datafactory.js
  38:40  warning  Unnecessary escape character: \/  no-useless-escape
  38:45  warning  Unnecessary escape character: \/  no-useless-escape

✖ 8 problems (0 errors, 8 warnings)

```

Is there any particular reason for not fixing them? If you just worried about the side effect, I think it's okay with as is :)

**Comment by 1ambda** [comment]
@AhyoungRyu Thanks for detailed review!

Those things are about regex and mixed boolean condition (without parens), so I am sure i can keep the original intention. 😭..

**Comment by AhyoungRyu** [comment]
@1ambda Yeah makes sense. Looks GOOD to me 👍

**Comment by 1ambda** [comment]
rebased to resolve conflict with #2203, #2248

**Comment by 1ambda** [comment]
rebased to resolve conflict with #2203, #2248

**Comment by 1ambda** [comment]
rebased to resolve conflict with #2133

**Comment by AhyoungRyu** [comment]
Merge into master if there are no more comments on this.

**Comment by 1ambda** [comment]
rebased to resolve conflict with #2244

**Comment by 1ambda** [comment]
rebase to resolve conflict with #2245

**Comment by AhyoungRyu** [comment]
Oh.. Will merge into master right after CI turns into green

**Comment by AhyoungRyu** [comment]
@1ambda CI checks has been failed sadly. Can you check again?

**Comment by 1ambda** [comment]
@AhyoungRyu Ci is now green!

**Pull request closed without merging**
