### PR TITLE
Python interpreter and doc cleanup

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
This is first step improving current Python interpreter implementation. 
It has just a cleanup, style and docs improvements.

### What type of PR is it?
Improvement

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
CI failure is not related and is taken care of under #1015 

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.3 sec - in org.apache.zeppelin.integration.SparkParagraphIT

Results :

Tests in error: 
  ParagraphActionsIT.testRemoveButton:153 Â» NoSuchElement Unable to locate eleme...
  ParagraphActionsIT.testCreateNewButton:86 Â» NoSuchElement Unable to locate ele...

Tests run: 14, Failures: 0, Errors: 2, Skipped: 0
```

Ready to be merged to master now.

**Comment by felixcheung** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Comment by astroshim** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by bzz** [comment]
Thank you for prompt reviews!

Merging if there is no more discussion.

**Pull request closed without merging**
