### PR TITLE
[ZEPPELIN-3098] Livy Interpreter fails if row contains newline or tab

### PR DESCRIPTION
**Pull request by bushnoh**
### What is this PR for?
This PR fixes the issue of newlines and tabs breaking results in the SQL interpreter in Livy.

The Livy interpreter will return incorrect results if a row contains \n or \t characters.
In the case of the newline, the result will be:
Line is missing from results if the \n appears anywhere but the end of a cell
`String index out of range: 17` if it appears at the end of a cell
In the case of the tab, the result will be misaligned columns if the tab appears in the middle of a cell
The output showing these error is attached to the Jira.

I have changed the parsing and any newline or tab characters will be escaped

### What type of PR is it?
Bug Fix 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3098

### How should this be tested?
Unittests have been added

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@bushnoh thanks for the contribution, could you check the CI, some tests fails.

**Comment by bushnoh** [comment]
@zjffdu The CI errors look unrelated. They're for the IPythonInterpreter and are the same ones that are failing on master.

**Comment by zjffdu** [comment]
@bushnoh I have fixed the CI failure, could you rebase this PR and retrigger the travis build ?

**Comment by bushnoh** [comment]
@zjffdu I have merged in the changed from master however there are still CI failures. They are again both unrelated and are the ones that are happening on master: https://travis-ci.org/apache/zeppelin/builds/315822086

**Comment by zjffdu** [comment]
@bushnoh https://travis-ci.org/apache/zeppelin/builds/315822086 This build doesn't include your PR, and some flaky test is known issue of zeppelin, but IPython related failure should be fixed.

**Comment by bushnoh** [comment]
@zjffdu I was trying to show that the tests failing in master (that don't include my changes) are the same ones with the same errors that are failing on my branch with the changes

**Comment by felixcheung** [comment]
I think test passed? it's too long and jenkins no longer has the build
@zjffdu

**Comment by bushnoh** [comment]
@zjffdu @felixcheung I merged changes from master into the branch to trigger another build however it looks like master is failing in Jenkins again. The previous build did pass though.

**Comment by zjffdu** [comment]
@bushnoh Travis build issue has been fixed, could you retrigger the build of this PR ?

**Pull request closed without merging**
