### PR TITLE
[ZEPPELIN-1451] Bug fix of Embedding %html within %table.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?

This PR fixes the bug of Embedding %html within %table.
It doesn't print properly when the `%html` is the first line.
### What type of PR is it?

Bug Fix
### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-1451
### How should this be tested?

Run following code in your paragraph.

```
print(s"""%table
name\tsize\tquantity
%html <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Sun_symbol.svg/50px-Sun_symbol.svg.png' />sun\t100\t50
%html <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Moon_symbol_crescent.svg/25px-Moon_symbol_crescent.svg.png' />moon\t10\t20""")
```
### Screenshots (if appropriate)
- before
  image
- after
  image
### Questions:
- Does the licenses files need update? no
- Is there breaking changes for older versions? no
- Does this needs documentation? no

### CODE REVIEW

**Comment by corneadoug** [comment]
@astroshim Tested, nice fix. LGTM
Can you rebase to have a green CI?
@Leemoonsoo @jongyoul @felixcheung Can one of you guys take a quick look at the code?

**Comment by astroshim** [comment]
@corneadoug Thank you for your review. I just re-based.

**Comment by Leemoonsoo** [comment]
@astroshim Currently only the last display system directive (%text, %html, ...) in the output is effective. Which is behavior of both InterpreterResult (static output) and InterpreterOutput (streaming output). 

This patch fixes problem but break current behavior. That's why following test is failing on CI.

```
Results :

Failed tests: 
  InterpreterOutputTest.testType:92 expected:<HTML> but was:<TEXT>

Tests run: 68, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin ........................................... SUCCESS [  7.135 s]
[INFO] Zeppelin: Interpreter .............................. FAILURE [02:08 min]
```

@astroshim What do you think? will there a easy way to fix the problem without changing current behavior? (pass unittest without changing test)

**Comment by astroshim** [comment]
@Leemoonsoo Thank you for pointing out the problem. Let me check.

**Comment by astroshim** [comment]
@Leemoonsoo CI has passed, please review.

**Comment by astroshim** [comment]
re-trigger CI

**Comment by corneadoug** [comment]
@astroshim CI failure is irrelevant
@Leemoonsoo any feedback?

**Comment by astroshim** [comment]
@Leemoonsoo ping

**Comment by Leemoonsoo** [comment]
Now CI on master has fixed. @astroshim Could you rebase and see if it pass the test?

**Comment by astroshim** [comment]
I did rebase and CI has passed. thanks.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Pull request closed without merging**
