### PR TITLE
Update twittr maven to HTTPS [ZEPPELIN-4156]

### PR DESCRIPTION
**Pull request by dbanda**
fix twittr maven URL to HTTPS as HTTP is now broken

### What is this PR for?
SBT fails to resolve dependencies from twittr maven. The http is now redirected to https.
see https://github.com/sbt/sbt/issues/3670

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-4156

### CODE REVIEW

**Comment by liuxunorg** [comment]
hi @dbanda ,  Welcome your contribution！👍 
Reading the [Contribution guidelines](https://zeppelin.apache.org/contribution/contributions.html) will help you contribute code better.  :-)

**Comment by zjffdu** [comment]
@dbanda Thanks for the contribution, please create jira and update the PR title.

**Comment by zjffdu** [comment]
ping @dbanda Could you address the comments ?

**Comment by dbanda** [comment]
> ping @dbanda Could you address the comments ?

Addressed. Added the Jira and updated PR title

**Pull request closed without merging**
