### PR TITLE
[ZEPPELIN-1940] most of eslint rules are NOT applied at all

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

<br />

**Most fixes are about fixing lint errors. It's automatically applied by executing `eslint --fix` command.**
**So please review `Gruntfile.js`, `.eslint`, `package.json` and `webpack.config.js` in `zeppelin-web` directory**

As a result of the PR,

- Restored javascript lint system
- Fixed 1200+ lint errors automatically
- Found some buggy code (e.g `Unexpected 'this' no-invalid-this` See the screenshot section)

We are using google style guide but it is not used at all because of invalid `.eslint` configuration. Thus I made some changes to fix it.

- Moved eslint from grunt to webpack (faster)
- Changed invalid config `"preset": "google"` to `"extends": ["google"]`
- Fixed 1200+ lint errors automatically using `eslint --fix` command
- Left some lint errors i cannot fix immediately as warnings or disabled

```
    "guard-for-in": [1],             // warning
    "no-invalid-this": [1],         // warning
    "prefer-rest-params": [1], // warning
    "require-jsdoc": [0], // disabled
    "valid-jsdoc": [0]      // disabled
```

- Also, Modified 20+ lint errors by hand

```

@ ./src/index.js 29:0-65

ERROR in ./src/app/visualization/builtins/visualization-areachart.js
Module build failed: Duplicate declaration "self"

  73 |     this.chart.style(this.config.style || 'stack');
  74 |
> 75 |     let self = this;
     |         ^

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/visualization.js
  134:14  error  Unexpected var, use let or const instead  no-var
  138:14  error  Unexpected var, use let or const instead  no-var

...
```

- Additionally, introduced `eslint:recommended` ruleset for several rules which google style is not opinionated so that we can keep clear, unified rules.

### What type of PR is it?

[Bug Fix | Improvement]

### Todos
* [x] - Moved eslint (build) task from grunt to npm (package.json)
* [x] - Brought eslint (dev) task from grunt to webpack
* [x] - Fixed `.eslint` to applied google ruleset
* [x] - Modifed some lint errors while leaving others as warning which i cannot fix right now (e.g docs)
* [x] - Introduced eslint recommended ruleset

### What is the Jira issue?

[ZEPPELIN-1940](https://issues.apache.org/jira/browse/ZEPPELIN-1940)

### How should this be tested?

- execute `npm run dev` and `npm run build` to check whether lint works well

### Image: found some invalid code using restored lint

image

### Image: found some errors using restored lint

image

### Image: Some code fixed by hand

```
➜  zeppelin-web git:(remove-grunt-eslint) npm run lint:js -- --quiet

> zeppelin-web@0.0.0 lint:js /Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web
> eslint src test Gruntfile.js "--quiet"

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/handsontable/handsonHelper.js
  159:58  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
  163:55  error  Use the rest parameters instead of 'arguments'  prefer-rest-params

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/notebook/notebook.controller.js
  635:20  error  Unexpected var, use let or const instead  no-var
  648:20  error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  929:28  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
  930:66  error  Use the rest parameters instead of 'arguments'  prefer-rest-params

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/notebook/paragraph/result/result.controller.js
  386:9   error  Unexpected var, use let or const instead        no-var
  433:9   error  Unexpected var, use let or const instead        no-var
  453:9   error  Unexpected var, use let or const instead        no-var
  867:28  error  Use the rest parameters instead of 'arguments'  prefer-rest-params
  868:66  error  Use the rest parameters instead of 'arguments'  prefer-rest-params

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/tabledata/transformation.js
  52:7   error  Unexpected var, use let or const instead  no-var
  54:14  error  Unexpected var, use let or const instead  no-var
  58:14  error  Unexpected var, use let or const instead  no-var
  77:7   error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/builtins/visualization-areachart.js
  61:5  error  Unexpected var, use let or const instead  no-var
  73:5  error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/builtins/visualization-barchart.js
  59:5  error  Unexpected var, use let or const instead  no-var
  67:5  error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/builtins/visualization-nvd3chart.js
  225:12  error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/builtins/visualization-scatterchart.js
  134:10  error  Unexpected var, use let or const instead  no-var

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/visualization.js
  134:14  error  Unexpected var, use let or const instead  no-var
  138:14  error  Unexpected var, use let or const instead  no-var

✖ 23 problems (23 errors, 0 warnings)

ERROR in ./src/app/visualization/builtins/visualization-barchart.js
Module build failed: Duplicate declaration "self"

  65 |     this.chart.stacked(this.config.stacked);
  66 |
> 67 |     let self = this;
     |         ^
  68 |     this.chart.dispatch.on('stateChange', function(s) {
  69 |       self.config.stacked = s.stacked;
  70 |

@ ./src/index.js 29:0-65

ERROR in ./src/app/visualization/builtins/visualization-areachart.js
Module build failed: Duplicate declaration "self"

  73 |     this.chart.style(this.config.style || 'stack');
  74 |
> 75 |     let self = this;
     |         ^
  76 |     this.chart.dispatch.on('stateChange', function(s) {
  77 |       self.config.style = s.style;
  78 |

/Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/src/app/visualization/builtins/visualization-nvd3chart.js
  52:25  error  Empty block statement  no-empty

✖ 1 problem (1 error, 0 warnings)
```

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@1ambda Could you resolve the conflicts? Then I will review this one.

**Comment by 1ambda** [comment]
@AhyoungRyu Thanks for caring this! 

- It would be easier to start from scratch i think. 😭 
- I will work on after #1982 is handed!

**Comment by AhyoungRyu** [comment]
@1ambda Sure. No worries!

**Comment by 1ambda** [comment]
I will open another PR for this. Too many conflicts 😞

**Pull request closed without merging**
