### PR TITLE
[ZEPPELIN-5685] upgrade shiro due to cve

### PR DESCRIPTION
**Pull request by pjfanning**
### What is this PR for?

https://issues.apache.org/jira/browse/ZEPPELIN-5685

Security concern over existing jar

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?

* https://issues.apache.org/jira/browse/ZEPPELIN-5685

### How should this be tested?
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Review by Reamer — CHANGES_REQUESTED** [review]
Please also update the license file.
https://github.com/apache/zeppelin/blob/9cecd2319024dccebe2768d9e6383140fd24a91f/zeppelin-distribution/src/bin_license/LICENSE#L106-L107

**Comment by pjfanning** [comment]
@Reamer thanks - I updated those 2 entries just now

**Review by Reamer — APPROVED** [review]
LGTM

**Comment by Reamer** [comment]
The PR needs a rebase to current master.

**Comment by pjfanning** [comment]
@Reamer I did the rebase

**Comment by zjffdu** [comment]
@pjfanning  Could you do rebase do solve the conflict?

**Comment by jongyoul** [comment]
The failed CI is unrelated?

**Comment by pjfanning** [comment]
not sure - it may that there is an issue with the shiro upgrade affecting the spark 3.7 test (but not spark 3.8 test)

**Comment by pjfanning** [comment]
@jongyoul @zjffdu I ran this change with bouncycastle also updated to 1.68 (again) on my fork and the spark 3.7 tests pass there - https://github.com/pjfanning/zeppelin/runs/5725316041?check_suite_focus=true

Would it make sense to try to upgrade shiro and bouncycastle in the same PR?

**Comment by zjffdu** [comment]
Thanks @pjfanning , I think it is better to separate them in different PR

**Comment by pjfanning** [comment]
@zjffdu you already reverted the bouncycastle upgrade in https://github.com/apache/zeppelin/commit/49b2e59625f54e29d787e94c8483980a90952014 but it appears that for when upgrading shiro it is better to have the bouncycastle upgrade put back

**Comment by zjffdu** [comment]
@pjfanning shiro depends on bouncycastle?

**Comment by pjfanning** [comment]
@zjffdu looks like the rerun passed - so it does look like bouncycastle has no effect

**Comment by zjffdu** [comment]
LGTM

**Pull request closed without merging**
