### PR TITLE
[ZEPPELIN-908] Apply new mechanism to CassandraInterpreter

### PR DESCRIPTION
**Pull request by kavinkumarks**
### What is this PR for?
This handles replacing the registration of interpreter with static block by the interpreter-setting.json file

### What type of PR is it?
Sub-ask

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-908

### How should this be tested?
* There shouldn't be any warning like below on starting the server

`INFO [2016-09-29 00:25:46,247] ({main} CassandraInterpreter.java[<clinit>]:155) - Bootstrapping Cassandra Interpreter
 WARN [2016-09-29 00:25:46,250] ({main} Interpreter.java[register]:347) - Static initialization is deprecated for interpreter cassandra, You should change it to use interpreter-setting.json in your jar or interpreter/{interpreter}/interpreter-setting.json
 INFO [2016-09-29 00:25:46,250] ({main} InterpreterFactory.java[init]:204) - Interpreter cassandra.cassandra found. class=org.apache.zeppelin.cassandra.CassandraInterpreter`

* And ensure that the cassandra related paragraphs run without any error

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kavinkumarks** [comment]
Reopening to trigger the CI build.

**Comment by doanduyhai** [comment]
The code looks good to me

**Comment by jongyoul** [comment]
@doanduyhai Can you commit this PR? I think it's good starting point. :-)

**Comment by doanduyhai** [comment]
@jongyoul I would like too but I don't have the commit right ...

**Comment by kavinkumarks** [comment]
Thanks @doanduyhai  for reviewing it and the CI build is green!

- Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by jongyoul** [comment]
@doanduyhai Do you try to do it via https://cwiki.apache.org/confluence/display/ZEPPELIN/Committer+Guide ? AFAIK, there's no more step except creating account.

**Comment by doanduyhai** [comment]
Thank you @jongyoul it works like a charm 👍

**Comment by kavinkumarks** [comment]
Thanks @doanduyhai and @jongyoul 

Kavin
MailTo: kavin.kumar@imaginea.com

**Pull request closed without merging**
