### PR TITLE
ZEPPELIN-3557. Remove interpreter profiles

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Just remove all interpreter profiles, instead of disable them by default. So that we won't forget to build them in travis. 

### What type of PR is it?
[Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3557

### How should this be tested?
* CI

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@jongyoul Could you help review it ? Thanks

**Comment by jongyoul** [comment]
What I thought is to move all interpreters modules to optional. For instance, running `mvn package` will create only zeppelin-* modules, and if users want to build spark, users should do add `-P spark` as an option like `mvn package -Pspark`. What do you think of it? The main reason why I'd like to do it is to make Zeppelin's code more friendly for IDE. WDYT?

**Comment by zjffdu** [comment]
I am afraid currently we can not do this. Because some unit test in zeppelin-zengine & zeppelin-server depends on spark interpreter (ZeppelinSparkClusterTest).

**Comment by jongyoul** [comment]
Agreed. Let's merge it and proceed them with another PR.

**Comment by jongyoul** [comment]
BTW, did you test if sparkR works with `-Pr`?

**Comment by zjffdu** [comment]
Actually this is my long time confusion part. `-Pr` would copy its artifact to `interpreter/spark` folder but it never used. I don't know the history of `-Pr`, is it an existing issue ?

**Comment by jongyoul** [comment]
@zjffdu Yes, it has a very long story. I, personally, don't want to keep both of them, but didn't find any solution to fit both requirements. `-Pr` is pure R interpreter which supported - I didn't test it - spark inside it. AFAIK, no one tests if SparkR works for now with `-Pr`.

**Comment by zjffdu** [comment]
Right, I think no one is using the pure r interpreter. I think we can use it 2 ways.
1. Create a pure r interpreter without spark support.
2. Use it another r implementing of spark and make option to allow user to choose whatever r implementation they want to use. (Because I don't know which r implementation is better, so I don't want to remove anyone of them)

**Comment by jongyoul** [comment]
We've tried to option 1 before but failed. We'd better give options to users like option 2

**Comment by zjffdu** [comment]
Thanks @jongyoul I created ZEPPELIN-3676 for this. and will merge this ticket first.

**Comment by egorklimov** [comment]
@zjffdu, please look, smth went wrong: https://issues.apache.org/jira/browse/ZEPPELIN-3682

**Pull request closed without merging**
