### PR TITLE
[BUILD] Update release script

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
* Change hadoop profile from `hadoop-2.4` to `hadoop-2.6`
* Use `SCALA_VERSION` variable instead of hardcoding
* Specify projects to be built for netinst package instead of excluding unnecessary projects.

### What type of PR is it?
Build

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by jongyoul** [comment]
@minahlee I think `-Pr` doesn't mean anything because users cannot run R interpreter since `-Psparkr` is enabled. How about removing `-Pr` in a script?

**Comment by minahlee** [comment]
@jongyoul you are right, `-Pr` does nothing in `create_release.sh`, so I removed it in a97b5fe. I kept `-Pr` in `publish_release.sh` though for the one who uses zeppelin-zrinterpreter_2.1x.jar in maven central repo.

**Comment by felixcheung** [comment]
LGTM

**Comment by jongyoul** [comment]
Good!! LGTM

**Pull request closed without merging**
