### PR TITLE
ZEPPELIN-1546 - Zeppelin Livy Interpreter 404 Exception not caught Kerberos Enabled

### PR DESCRIPTION
**Pull request by gss2002**
### What is this PR for?

ZEPPELIN-1546: Zeppelin Livy Interpreter 404 Exception not caught with Kerberos
Livy Interpreter gets a NestedRuntimeException when running with Kerberized components.
### What type of PR is it?

[Bug Fix]
### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-1546
### How should this be tested?

Enable Kerberos for Zeppelin to talk to Livy
    "2BXS1CND2": {
      "id": "2BXS1CND2",
      "name": "livy",
      "group": "livy",
      "properties": {
        "livy.spark.driver.cores": "",
        "zeppelin.livy.principal": "zeppelin-clustername@EXAMPLE.COM",
        "zeppelin.livy.keytab": "/etc/security/keytabs/zeppelin.server.kerberos.keytab",
### Questions:
- Does the licenses files need update? n
- Is there breaking changes for older versions? n
- Does this needs documentation? n

### CODE REVIEW

**Comment by gss2002** [comment]
@zjffdu and @prabhjyotsingh here is the 404 NestedRuntime Fix

**Comment by gss2002** [comment]
@zjffdu and @prabhjyotsingh is this safe to be committed at this point?

**Comment by zjffdu** [comment]
@gss2002 CI is failed, could you check whether it is related ?

**Comment by gss2002** [comment]
Reopen to re-check code and error

**Comment by gss2002** [comment]
@zjffdu I re-run the tests. This error doesn't look to have anything to do with the code change here. Let me know your thoughts and how we want to proceed

Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 196.06 sec <<< FAILURE! - in org.apache.zeppelin.integration.ParagraphActionsIT
testEditOnDoubleClick(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 37.614 sec  <<< ERROR!
org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 30.08 seconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'testing-worker-linux-docker-cccaeb55-3455-linux-3', ip: '172.17.1.168', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'
Session ID: 461cd88c-98e9-467e-88bd-e44eab394a92
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=31.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:121)
	at org.apache.zeppelin.integration.ParagraphActionsIT.testEditOnDoubleClick(ParagraphActionsIT.java:443)
Caused by: org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'testing-worker-linux-docker-cccaeb55-3455-linux-3', ip: '172.17.1.168', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'

**Comment by gss2002** [comment]
@zjffdu went and confirmed the previous error from the pull 19 days ago was in a set of tests that ran completely fine this time. So I think this patch is good to go

**Pull request closed without merging**
