### PR TITLE
[ZEPPELIN-5075] Bump up firefox version

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
The firefox version (31) is currently too old and if selenium test cases fail it becomes difficult to repro the issue.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5075

### How should this be tested?
* CI should be green
* Travis link: https://travis-ci.com/github/prabhjyotsingh/zeppelin/builds/187051708
* Travis link: (latest) https://travis-ci.com/github/prabhjyotsingh/zeppelin/builds/190831750

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by Reamer** [comment]
Hi @prabhjyotsingh,
I noticed your changes. I'm working on the same module.
https://github.com/apache/zeppelin/compare/master...Reamer:selenium?diff=unified

My Goals are:
 -> Use an actual Chrome as browser
 -> Use commons-exec to start/stop zeppelin-server and to execute other commands
 -> Remove ant steps, so tests can be execute in an IDE

**Comment by prabhjyotsingh** [comment]
@Reamer The only reason I prefer Firefox over Chrome is because you can sepcify FF-version in travis file. 
May be that was a thing of past but I've seen sometime latest version of Chrome does not work with selenium-web-driver, if that is not the case now, I can possibly close this PR and we can take a look at yours, no problem.

**Comment by Reamer** [comment]
The chome addon will install the newest stable chrome.
```
      addons:
        chrome: stable
```
The package `chromium-chromedriver` will install the newest chromium-chromedriver from ubuntu repository. Theoretically this can break because the binaries are loaded from different sources.

I haven't noticed any problems with chrome, but I have noticed some problems with Firefox. The test ParagraphActionsIT:testFontSize does not work on my computer with Firefox manually and automatically with Selenium.

**Comment by prabhjyotsingh** [comment]
Yes, I agree there are problems with Firefox, but in this way, we can tie up firefox(specific-version)+geckodriver(specific-version). But if you are saying you have not seen any problem with chrome(latest-version)+chromium-chromedriver(latest-version) is past one year, then please feel free to open up your PR, and I'll close this one.

**Comment by Reamer** [comment]
I have split my changes into several commits, which should make it easier to understand what I have changed.
I have seen that you are working on the Selenium execution code, so it would be nice if you could merge some improvements into your branch.

**Comment by Reamer** [comment]
> I'll close this one.
Please don't do this, if you can manage the selenium tests, it would be a great help.

**Comment by prabhjyotsingh** [comment]
Sure I'm fine either ways and yes I agree if chrome works then it's more stable.
If we agree we can switch to Chrome, worst case we will revert back to FF.

**Comment by prabhjyotsingh** [comment]
@Reamer  Have made some fixes, which should get rid of a few flaky test cases. Should we give this a spin while you are working on your PR?

**Comment by Reamer** [comment]
Hi @prabhjyotsingh 
I merged your changes into my branch https://github.com/apache/zeppelin/compare/master...Reamer:selenium?diff=unified
and it is working now. https://travis-ci.org/github/Reamer/zeppelin/jobs/731234230

Because of the bugs in Firefox, I would switch to Chrome. In addition we are using chrome also for [`Run e2e tests in zeppelin-web`](https://github.com/apache/zeppelin/blob/2e69f712329ff0ce1af964df08c89328f0be84aa/.travis.yml#L71) and [`Run tests in zeppelin-web-angular`](https://github.com/apache/zeppelin/blob/2e69f712329ff0ce1af964df08c89328f0be84aa/.travis.yml#L102)

I will open PR.

**Comment by prabhjyotsingh** [comment]
Sure that sounds good.

**Comment by prabhjyotsingh** [comment]
@Reamer if yours is going to take time, should we merge this? I mean this is ready and hopefully, this should reduce some of flaky test reports.

**Comment by Reamer** [comment]
> @Reamer if yours is going to take time, should we merge this? I mean this is ready and hopefully, this should reduce some of flaky test reports.

Of course we should merge this.

**Comment by prabhjyotsingh** [comment]
Thanks for the review @Reamer.
@zjffdu  does that works for you as well? 
Will merge this if no more discussion.

**Pull request closed without merging**
