### PR TITLE
[ZEPPPELIN-1009] Trying to Fix selenium modal error

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
This is to check Selenium test failing on Master and #979

### What type of PR is it?
Flacky test fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1009

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
@corneadoug as a first step, how about re-open the PR to trigger CI and see, which ones are reproducible by posting same report for new CI build results?

**Comment by corneadoug** [comment]
Only both errors about delete button are there after running the CI again

**Comment by corneadoug** [comment]
No problem running the test locally

**Comment by bzz** [comment]
on #1021 in [logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/137973583/log.txt) I can see

**ParagraphActionsIT.testRemoveButton**
```
org.apache.zeppelin.integration.ParagraphActionsIT.testRemoveButton(ParagraphActionsIT.java:152)
03:13:23,791  INFO org.apache.zeppelin.AbstractZeppelinIT:59 - Finished.
03:13:53,820 ERROR org.apache.zeppelin.AbstractZeppelinIT:153 - Exception in ParagraphActionsIT while testRemoveButton 
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[@class='modal-dialog'][contains(.,'delete this paragraph')]//div[@class='modal-footer']//button[contains(.,'OK')]"}
Command duration or timeout: 30.03 seconds
```

when the browser gets trapped in this state, as one can see - there is indeed no modal dialog on the screen
screen shot 2016-06-17 at 00 53 42

So may be its [previous line](https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/integration/ParagraphActionsIT.java#L146),  `//ul/li/a[@ng-click='removeParagraph()']` that fails to trigger paragrpah removal here?

**Comment by corneadoug** [comment]
@bzz where did you get the screenshot from?

The modal is supposed to show, I modified the test in this PR to have a check on that, and current scenario looks like this:

* Find the paragraph icon-setting and click on it
* Find the remove paragraph button and click on it
* Does Modal Exist? -> True
* Find the Modal Ok button and Click on It -> failed

**Comment by bzz** [comment]
@corneadoug sounds good! Screenshot is in the logs in base64.
Could you post current CI failure in the same way as I did above? Then we could iterate faster on it

**Comment by corneadoug** [comment]
@bzz Do you know in which case it takes a screenshot?
I see this in the log before the screenshot
```
09:14:21,371 ERROR org.apache.zeppelin.AbstractZeppelinIT:155 - ScreenShot::
```

However, the log place the error at line 166
cf:
```
Tests in error: 
  ParagraphActionsIT.testRemoveButton:166 Â» NoSuchElement Unable to locate eleme...
  ParagraphActionsIT.testCreateNewButton:92 Â» NoSuchElement Unable to locate ele...
```

```
09:11:54,159  INFO org.apache.zeppelin.AbstractZeppelinIT:51 - Caller: org.apache.zeppelin.integration.ParagraphActionsIT.testRemoveButton(ParagraphActionsIT.java:158)
09:11:55,160  INFO org.apache.zeppelin.AbstractZeppelinIT:59 - Finished.
09:12:55,241 ERROR org.apache.zeppelin.AbstractZeppelinIT:153 - Exception in ParagraphActionsIT while testRemoveButton 
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"xpath","selector":"//div[@class='bootstrap-dialog-footer']//button[contains(text() ,'OK')]"}
Command duration or timeout: 30.07 seconds
```

**Comment by Leemoonsoo** [comment]
`handleException()` take screenshot. `ParagraphActionIT` catches all exceptions during test and call `handleException()` to screenshot.

To take screenshot manually, Insert following line where you want,

```java
try { handleException("ANY MSG", new RuntimeException();} catch (Exception e) {};
```

I was working on #1034, it does not fix all the selenium error, but it fixes all errors on `ZeppelinIT`.
Please take a look and feel free to merge #1034.

**Comment by corneadoug** [comment]
@Leemoonsoo Yes we will go with your PR, so I will close this one

**Pull request closed without merging**
