### PR TITLE
fix tiny typos

### PR DESCRIPTION
**Pull request by kepricon**
### What is this PR for?
Recently, I used Zeppelin's interpreter APIs for my project.
While I looked into some test cases, I found some tiny typos.
This is the fixes for it.

### What type of PR is it?
Refactoring

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @kepricon for the contribution!

```
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
And then make sure 'Build branch updates' option is enabled in the settings https://travis-ci.org/kepricon/zeppelin/settings.

To trigger CI after setup, you will need ammend your last commit with
git commit --amend
git push your-remote HEAD --force

See http://zeppelin.apache.org/contribution/contributions.html#continuous-integration.
```

Could you try setup CI and see this changes pass the CI?

**Comment by kepricon** [comment]
I used `optimize import` function from IntelliJ.
does import order can be the matter in this situation?

**Comment by 1ambda** [comment]
@kepricon Hi, Could u restart the failed job? Or Please check the log. 

regarding import order. Of course, it doesn't matter in the feature perspective.

- we want minimal change so that any reviewer (even for the beginner) can review easily.
- and we want not to include the irrelevant changes to prevent the side effect

**Comment by 1ambda** [comment]
Hi, @kepricon Could you resolve the conflict?

**Pull request closed without merging**
