### PR TITLE
[ZEPPELIN-2113] Remove border and margin of Link this paragraph window

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
This PR is for removing border and margin of paragraph shape in new window which is created by "Link this paragraph" operation.
It would be nice and neat to be removed such like that is suggested at [this comment](https://github.com/apache/zeppelin/pull/1983#issuecomment-279395050).

### What type of PR is it?
[Improvement]

### What is the Jira issue?
[ZEPPELIN-2113](https://issues.apache.org/jira/browse/ZEPPELIN-2113)

### How should this be tested?
1. Click `Link this paragraph`
2. Check a paragraph shape

### Screenshots (if appropriate)
[ Before ]
z_2113_b

image

[ After ]
z_2113_a

z_2113_a_t

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by soralee** [comment]
My CI is green! (https://travis-ci.org/soralee/zeppelin/builds/204074604)

**Comment by 1ambda** [comment]
I will review and comment soon. Thanks for fixing bug @soralee!

**Comment by soralee** [comment]
@1ambda Thanks for taking a look this!
Regarding text layout, I don't consider left-pending because it already fixed #1983.

**Comment by 1ambda** [comment]
LGTM

**Comment by soralee** [comment]
@1ambda Thanks for review :+1:

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by soralee** [comment]
@prabhjyotsingh Thanks for review!

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
