### PR TITLE
[ZEPPELIN-3245] checkstyle/eslintrc for zeppelin-web (JavaScript)

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
## What is this PR for?
Have added this PR to add a rule in eslinerc to have semicolons in javascript source

### What type of PR is it?
[Improvement | Refactoring]

### What is the Jira issue?
* [ZEPPELIN-3245](https://issues.apache.org/jira/browse/ZEPPELIN-3245)

### How should this be tested?

```
cd zeppelin-web
npm install (or yarn install if you have yarn)
npm run lint:once
```

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
cc: @1ambda @AhyoungRyu @r-kamath

**Comment by mebelousov** [comment]
@prabhjyotsingh it's great that one of PMC file such PR.
A lot of tests show that JS works faster without syntax warnings.
:+1:

**Comment by prabhjyotsingh** [comment]
@mebelousov I did not follow your comment.

**Comment by felixcheung** [comment]
should this go to `dev@`?

**Comment by r-kamath** [comment]
@prabhjyotsingh please resolve conflicts. Otherwise LGTM.

**Comment by prabhjyotsingh** [comment]
Thanks for the review will merge this if no more discussion.

**Comment by prabhjyotsingh** [comment]
Will merge this to branch-0.8 as well, so that if there are any backports they are convenient.

**Pull request closed without merging**
