### PR TITLE
Add bullet graph support

### PR DESCRIPTION
**Pull request by deepujain**
Plots a box graph.

screen shot 2015-10-04 at 3 39 40 pm

I still could not get console.log to work, could have got even better implementation with it.

### CODE REVIEW

**Comment by deepujain** [comment]
Box plot needs 5 data points as input.
Range : Bad, satisfactory and good
Measure: Actual Value to plot
Target: Compare another actual value (Arrow that is shown on graph).

In below screen shot, it will plot the range against the value 1. 
      var lowRange = 40, midRange = 60, highRange=100;
      lowRange = (lowRange / 100) * values[0];
      midRange = (midRange / 100) * values[0];
      highRange = (highRange / 100) * values[0];
      var actualMeasure = values[1];
      var targetMarker = values[0];

screen shot 2015-10-04 at 7 32 13 pm

**Comment by deepujain** [comment]
Including support for line with focus chart.

screen shot 2015-10-06 at 12 26 42 pm

**Comment by galleon** [comment]
How is that different from #312 - focus chart

**Comment by bzz** [comment]
@deepujain Could you please elaborate, shall this be updated to the latest master and merged or is ~~#312~~ is enough and this one can be closed?

**Comment by corneadoug** [comment]
@bzz this would need to be cleaned to include only bullet graph.
However, as we took a look in #597, we discovered that there is a few problems with version 1.8.1 and therefore it would be better not to use it yet. Sadly bullet graph is part of 1.8.1

**Comment by deepujain** [comment]
Both are different types of charts and this PR is for Bullet Chart. I found this on D3 that i took as a reference to implement in Zeppelin. http://bl.ocks.org/mbostock/4061961

**Comment by corneadoug** [comment]
Going around old PRs.
As stated before, we had issues with version 1.8.1, and have no plan on upgrading.
In case newer versions don't have issues we can create a Jira issue to upgrade.
I will be closing this PR if there is no other discussions

**Pull request closed without merging**
