### PR TITLE
[ZEPPELIN-6018] Update gRPC version from 1.51.0 to 1.55.1 for successful Apache Zeppelin build on s390x architecture

### PR DESCRIPTION
**Pull request by aditi-sharma-1**
This update modifies the grpc-java dependency version from 1.51.0 to 1.55.1. This change ensures compatibility and resolves build issues encountered on the s390x architecture. After implementing this change, the Apache Zeppelin package now builds successfully on the s390x architecture.

Attaching the log file and screenshots while building Apache Zeppelin on s390x:

[build-on-s390x-logs.txt](https://github.com/apache/zeppelin/files/15294068/build-on-s390x-logs.txt)

build-screenshot-1

build-screenshot-2

### CODE REVIEW

**Comment by Reamer** [comment]
Can you please create a JIRA ticket and update the license file.
You can find a complete commit at https://github.com/apache/zeppelin/commit/09bd93877bbb0b352b0ef8efe9d53b227f3c8b87.

**Comment by aditi-sharma-1** [comment]
Sure, I'll create the Jira ticket for this issue and update the license file. Thank you, Reamer.

**Comment by jongyoul** [comment]
By the way, could you please check the CI as well?

**Comment by aditi-sharma-1** [comment]
Sure @jongyoul, I will check the CI.

I have also updated the license file and created the Jira ticket - [6018](https://issues.apache.org/jira/browse/ZEPPELIN-6018) 
Thank you.

**Comment by pan3793** [comment]
Hmm... IIRC, there is a enforced rule to ensure that gRPC protobuf version aligned

**Comment by aditi-sharma-1** [comment]
@pan3793 Could you please elaborate ?

**Comment by pan3793** [comment]
@aditi-sharma-1 ignore my previous comments, please follow the error reported by CI to fix it.

**Comment by aditi-sharma-1** [comment]
Sure @pan3793 ,

I have downgraded the gRPC version from 1.62.2 to 1.55.1. Could you please rerun it once? Thank you.

**Comment by pan3793** [comment]
> Sure @pan3793 ,
> 
> I have downgraded the gRPC version from 1.62.2 to 1.55.1. Could you please rerun it once? Thank you.

Sorry, I'm not a Zeppelin Committer thus I don't have power to rerun the CI. I saw another Committer triggered CI and the result looks good in this round.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
@aditi-sharma-1 please update your PR title to something like `[ZEPPELIN-6018] Update gRPC from  1.51.0 to 1.55.1`, and since the Zeppelin existing CI does not have s390x machines, please update the PR description to mention your local test result on s390x

**Comment by aditi-sharma-1** [comment]
Sure, @pan3793 , I'll make these changes.
Thank you.

**Comment by pan3793** [comment]
CI failure should be irrelative, cc @jongyoul @huage1994 who has write permissions.

**Review by Reamer — APPROVED** [review]
LGTM

**Pull request merged**
