### PR TITLE
[gh-pages][ZEPPELIN-1973] List all available Helium packages under zeppelin.apache.org

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
After #1842 merged, anyone can create his/her own `VISUALIZATION` pkg as described in [Writing a new Visualization](https://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/development/writingzeppelinvisualization.html) and can publish it to npm registry. The below img describes "the current Helium package mechanism(black outline) + proposing from me to list all Helium pkgs published in npm registry(red one) in Zeppelin official website".  So what I did to do this was the red-outlined factors. 

screen shot 2017-01-24 at 4 44 42 pm

> `helium.js` is located in here: [https://s3.amazonaws.com/helium-package/helium.js](https://s3.amazonaws.com/helium-package/helium.js) and it's updated automatically by CloudWatch every 1 hour.

**Possible future work**
Currently to enable/disable the helium VIZ pkg via Helium GUI menu in Zeppelin, user needs to place Helium info json files under `ZEPPELIN_HOME/helium/` manually. But from now, we can substitute this not user friendly way by using `helium.js`. (already opened #1936 by @Leemoonsoo  )

**Any issues?**
But as I mentioned in [ZEPPELIN-1973](https://issues.apache.org/jira/browse/ZEPPELIN-1973), since I used AWS services (Lambda, S3 and CloudWatch), I needed an account. So for continous management, I'm willing to share the information that need to run/packaging/deploy Lambda function with Zeppelin PMCs if you Zeppelin community thinks I need to do it. 

### What type of PR is it?
Improvement | Feature

### Todos
* [x] - make result filtered by type (`VISUALIZATION` & `SPELL` introduced by #1940 )
* [x] - Adjust navbar when screen width is small 

### What is the Jira issue?
[ZEPPELIN-1973](https://issues.apache.org/jira/browse/ZEPPELIN-1973)

### How should this be tested?
Build `gh-pages` branch as described in [here](https://github.com/apache/zeppelin/tree/gh-pages#build-website). Or just see the below gif sreenshot img :)

### Screenshots (if appropriate)
record

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested and works as expected.
LGTM

**Comment by AhyoungRyu** [comment]
@Leemoonsoo Thanks for testing out! 
I saw new type of package "SPELL" was introduced by #1940. So I'd like to make the result filtered by Type (`VISUALIZATION` or `SPELL`) using radio button. Let me update again. It won't take too long :D

**Comment by AhyoungRyu** [comment]
@Leemoonsoo Sorry for my late update. I spent some time to fetch both SPELL and VIZ type pkgs' info and push all them to one [helium.js](https://s3.amazonaws.com/helium-package/helium.js) file. 
And I made radio button to make pkg list selectable. And fixed downflow navbar issue as well. 

@1ambda If you don't mind, can you help review this one? :)

**Comment by 1ambda** [comment]
@AhyoungRyu You are welcome. I will review soon.

**Comment by AhyoungRyu** [comment]
FYI, I added "only available in development version(0.8.0-SNAPSHOT)" msg next to the **SPELL** radio button. Also updated screenshot as well :)

**Comment by 1ambda** [comment]
@AhyoungRyu Thanks for great contribution. This PR increase the number of helium package users significantly. 

I would like to comment about the design of `helium.json`. Basically, It's concise and well designed. 

- It would be great if helium package has `version` field considering local package and `latest`
- If once people start to develop packages, there must be operational things like user complains. For example, "I published package to npm, but it's not collected by helium for last 2 days. What's the problem?" So, it's good for each package to have some information for debug and ops like `createdAt`, `heliumFormatVersion`.

**Comment by AhyoungRyu** [comment]
Thanks for GREAT suggestions @1ambda. 

>It would be great if helium package has version field considering local package and latest

I've just added `version` and `published` field to each pkg version's information. Please check [helium.json](https://s3.amazonaws.com/helium-package/helium.json)(used for Zeppelin Helium GUI menu) and [helium.js](https://s3.amazonaws.com/helium-package/helium.js)(used for zeppelin.apache.org). I also added `published` date for each version, to show latest package first. So now, it'll be look like below 
```
"0.0.3": {
      ...
    },
    "latest": {
      "type": "VISUALIZATION",
      "name": "zeppelin-bubblechart",
      "version": "0.0.4",
      "published": "2017-01-23T20:42:34.373Z",
      "artifact": "zeppelin-bubblechart@0.0.4",
      "author": "leemoonsoo",
      "description": "Animated bubble chart",
      "license": "BSD-2-Clause",
      "icon": "<svg viewBox='0 0 70 70'><circle cx='26' cy='28' stroke='black' style='stroke-width: 1px;' r='25' fill='seagreen'/><circle cx='42' cy='44' stroke='black' style='stroke-width: 1px;' r='20' fill='DodgerBlue'/><circle cx='54' cy='24' stroke='black' style='stroke-width: 1px;' r='15' fill='crimson'/></svg>"
    }
```

And here is the latest update.
record


>If once people start to develop packages, there must be operational things like user complains. For example, "I published package to npm, but it's not collected by helium for last 2 days. What's the problem?" So, it's good for each package to have some information for debug and ops like createdAt, heliumFormatVersion.

Especially for this, totally agree with you. Actually there are lots of things to be improved and can be changed. So I need more time to rethink about how I can do that in Lambda function side. But as it doesn't affect directly to merge this PR, I'll update it later time if it's okay with you. Appreciate again!

**Comment by 1ambda** [comment]
Tested and works well :)

**Comment by AhyoungRyu** [comment]
@1ambda Thanks for testing it out. Merge into `gh-pages` if there are no more comments on this!

**Pull request closed without merging**
