### PR TITLE
ZEPPELIN-1342. Adding dependencies via SPARK_SUBMIT_OPTIONS doesn't work on Spark 2.0.0

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

The root cause is due to the change of repl of scala-2.11. User needs to specify the jars in the repl setting explicitly.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1342

### How should this be tested?
Tested manually as shown in the screenshot. 

### Screenshots (if appropriate)

image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
\cc @Leemoonsoo  Ready for review.

**Comment by astroshim** [comment]
LGTM. :+1:

**Comment by Leemoonsoo** [comment]
Thanks @zjffdu for the fix.

Spark sets `-classpath` with not only `spark.jars` but also `spark.yarn.dist.jars` in case of master is `yarn`. see
https://github.com/apache/spark/blob/v2.0.0/repl/scala-2.11/src/main/scala/org/apache/spark/repl/Main.scala#L57
https://github.com/apache/spark/blob/v2.0.0/core/src/main/scala/org/apache/spark/util/Utils.scala#L2411

Do you think Zeppelin need to do the same?

**Comment by zjffdu** [comment]
I think `spark.jars` & `spark.yarn.dist.jars` are duplicated here. `--packages` will pass all the jars of the package to `args.jars` which will passed to `spark.jars` & `spark.yarn.dist.jars`
Please refer the following code in spark
* https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L297
* https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L461
* https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L476

I also verify the PR in both local mode and yarn-client mode.

**Comment by Leemoonsoo** [comment]
Thanks @zjffdu for explanation.
Some CI test failure looks relevant.

```
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.002 sec <<< FAILURE! - in org.apache.zeppelin.spark.SparkSqlInterpreterTest
test_null_value_in_row(org.apache.zeppelin.spark.SparkSqlInterpreterTest)  Time elapsed: 0.78 sec  <<< ERROR!
java.util.NoSuchElementException: spark.jars
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.SparkConf.get(SparkConf.scala:193)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:597)
	at org.apache.zeppelin.spark.SparkSqlInterpreterTest.setUp(SparkSqlInterpreterTest.java:61)

test(org.apache.zeppelin.spark.SparkSqlInterpreterTest)  Time elapsed: 0.017 sec  <<< ERROR!
java.util.NoSuchElementException: spark.jars
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.SparkConf.get(SparkConf.scala:193)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:597)
	at org.apache.zeppelin.spark.SparkSqlInterpreterTest.setUp(SparkSqlInterpreterTest.java:61)

testStruct(org.apache.zeppelin.spark.SparkSqlInterpreterTest)  Time elapsed: 0.02 sec  <<< ERROR!
java.util.NoSuchElementException: spark.jars
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:193)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.SparkConf.get(SparkConf.scala:193)
	at org.apache.zeppelin.spark.SparkInterpreter.open(SparkInterpreter.java:597)
	at org.apache.zeppelin.spark.SparkSqlInterpreterTest.setUp(SparkSqlInterpreterTest.java:61)
```

Could you take a look?

**Comment by Leemoonsoo** [comment]
Tested, LGTM. 
Merge to master and branch-0.6 if there're no more discussions.

**Pull request closed without merging**
