### PR TITLE
[ZEPPELIN-4188] Upgrade Jetty to 9.4.18.v20190429

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
[ZEPPELIN-4188] Upgrade Jetty to 9.4.18.v20190429

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
[ZEPPELIN-4188](https://jira.apache.org/jira/browse/ZEPPELIN-4188)

### How should this be tested?
Should pass CI

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by r-kamath** [comment]
CI failure is unrelated. 
Will merge this if there are no more discussions.

**Comment by r-kamath** [comment]
@jongyoul ping

**Comment by jongyoul** [comment]
What kind of potential issue will we have?

**Comment by r-kamath** [comment]
@jongyoul there are some security issues in 9.4.14.v20181114. Zeppelin is not directly affected.

**Comment by r-kamath** [comment]
will merge this if there are no more discussions

**Comment by zjffdu** [comment]
@r-kamath Please add description in jira, otherwise it is difficult to track what issue this ticket/PR try to solve.

**Pull request closed without merging**
