### PR TITLE
[ZEPPELIN-5804] support python 3.10

### PR DESCRIPTION
**Pull request by PrimWILL**
### What is this PR for?
Change py4j version (0.10.7 -> 0.10.9.7) in python interpreter directory to support python 3.10

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5804

### How should this be tested?
CI and manual (3.9 and 3.10)

### Screenshots (if appropriate)
python3 10

### Questions:
* Does the licenses files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by jongyoul — APPROVED** [review]

**Comment by Reamer** [comment]
I think this should be tested via CI.

**Comment by PrimWILL** [comment]
> I think this should be tested via CI.

In CI, this already passed python 3.7 and python 3.8 tests . Do I have to add more python tests for 3.10 in CI?

**Comment by jongyoul** [comment]
I'll merge it if there's no further discussion

**Comment by Reamer** [comment]
> Do I have to add more python tests for 3.10 in CI?

Sooner or later we should also test with Python 3.10 in the CI setup. But this can be done in a separate pull request.

**Comment by PrimWILL** [comment]
> Sooner or later we should also test with Python 3.10 in the CI setup. But this can be done in a separate pull request.

Got it. Then I'll register related issue in jira.

**Pull request merged**
