### PR TITLE
[ZEPPELIN-6116] Switch from `npm install --no-lockfile` to `npm ci`

### PR DESCRIPTION
**Pull request by Charlie91**
### What is this PR for?
tiny fix to make code cleaner

### What type of PR is it?
Refactoring

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-6116

### CODE REVIEW

**Comment by Reamer** [comment]
Maybe it makes sense to switch to `npm ci`
https://docs.npmjs.com/cli/v10/commands/npm-ci

**Comment by pan3793** [comment]
@Charlie91 please rebase your PR on the latest master, there were some issues with conda, and got fixed via https://github.com/apache/zeppelin/pull/4857 a few hours ago.

**Comment by Charlie91** [comment]
@pan3793 done

**Review by Reamer — APPROVED** [review]
LGTM
But let's wait for the CI

**Comment by pan3793** [comment]
Thanks, merged to master/0.12

**Pull request merged**
