### PR TITLE
[Pyspark] checking nhooks count.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
if the `nhooks` value is `0` in this(https://github.com/apache/zeppelin/blob/master/spark/src/main/resources/python/zeppelin_pyspark.py#L324) line, python code will run twice.

### What type of PR is it?
Bug Fix | Improvement 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2024

### How should this be tested?
- comment https://github.com/apache/zeppelin/blob/master/spark/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java#L114 line and build.
- run pyspark code(eg, `print("hi")`), then you can see it run twice.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
@astroshim following test failure might related. Could you check?
```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 19.978 sec <<< FAILURE! - in org.apache.zeppelin.spark.PySparkInterpreterMatplotlibTest
testAngular(org.apache.zeppelin.spark.PySparkInterpreterMatplotlibTest)  Time elapsed: 0.252 sec  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:553)
	at java.util.LinkedList.get(LinkedList.java:474)
	at org.apache.zeppelin.spark.PySparkInterpreterMatplotlibTest.testAngular(PySparkInterpreterMatplotlibTest.java:229)

testNoClose(org.apache.zeppelin.spark.PySparkInterpreterMatplotlibTest)  Time elapsed: 0.421 sec  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.checkElementIndex(LinkedList.java:553)
	at java.util.LinkedList.get(LinkedList.java:474)
	at org.apache.zeppelin.spark.PySparkInterpreterMatplotlibTest.testNoClose(PySparkInterpreterMatplotlibTest.java:216)
```

**Comment by astroshim** [comment]
Thank you @felixcheung and @Leemoonsoo for reviewing this.
Let me check the CI.

**Comment by astroshim** [comment]
CI has passed.

**Comment by Leemoonsoo** [comment]
LGTM and merge to master and branch-0.7

**Comment by Leemoonsoo** [comment]
@astroshim do you mind create a JIRA issue?

**Comment by astroshim** [comment]
@Leemoonsoo I just create JIRA issue that is https://issues.apache.org/jira/browse/ZEPPELIN-2024.
Thanks.

**Pull request closed without merging**
