### PR TITLE
ZEPPELIN-278 fix build warnings and rat hang

### PR DESCRIPTION
**Pull request by bzz**
`mvn apache-rat:check` passes

All sub-modules now use same version of:
 - maven-dependency-plugin
 - scala compiler

### CODE REVIEW

**Comment by bzz** [comment]
From CI, seems like Selenium tests hang
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```
Triggering again

**Comment by bzz** [comment]
Something strange going on with TravisCI:

```
WARNING: We were unable to find a .travis.yml file. This may not be what you
  want. Build will be run with default settings.
Using worker: worker-linux-docker-c59fef2c.prod.travis-ci.org:travis-linux-3
Could not find .travis.yml, using standard configuration.
```
Triggering again

**Comment by bzz** [comment]
Same again, it complains on `.travis.yml`, which is clearly present in the codebase... Going to wait and then trigger once again

**Comment by bzz** [comment]
CI is *very unstable* - same command over the same branch passes on my machine

```
mvn package -Pspark-1.1 -Phadoop-2.3 -B -pl 'zeppelin-interpreter,zeppelin-zengine,zeppelin-server' '-Dtest=org.apache.zeppelin.rest.*Test' -DfailIfNoTests=false
....
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 11.548 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  6.093 s]
[INFO] Zeppelin: Server ................................... SUCCESS [01:26 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Build for the same revistion of the same branch, under [my Travis-CI profile](https://travis-ci.org/bzz/incubator-zeppelin/builds/78839035) fails in totaly different way, on `zeppelin-web` compile (!!!)

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:grunt (grunt build) on project zeppelin-web: Failed to run task: 'grunt --no-color' failed. (error code 3) -> [Help 1]
```

**Comment by bzz** [comment]
Giving it one more chance...

**Comment by bzz** [comment]
On CI `mvn package -Pspark-1.1 -Phadoop-2.3 -Ppyspark -B -pl 'zeppelin-interpreter,spark-dependencies,spark`

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
         ....
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/settings/AbsSettings$AbsSetting
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.zeppelin.interpreter.InterpreterFactory.init(InterpreterFactory.java:124)
	at org.apache.zeppelin.interpreter.InterpreterFactory.<init>(InterpreterFactory.java:103)
	at org.apache.zeppelin.interpreter.InterpreterFactory.<init>(InterpreterFactory.java:85)
	at org.apache.zeppelin.server.ZeppelinServer.<init>(ZeppelinServer.java:310)
	... 28 more
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.settings.AbsSettings$AbsSetting
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
```

on local machine build passes.

Can somebody please confirm that?

**Comment by bzz** [comment]
`mvn package -Pspark-1.1 -Phadoop-2.3 -B -pl 'zeppelin-interpreter,zeppelin-zengine,zeppelin-server' '-Dtest=org.apache.zeppelin.rest.*Test' -DfailIfNoTests=false` passes on my machine well.

@Leemoonsoo can you please give it a try and let me know if it works for you too?

**Comment by Leemoonsoo** [comment]
@bzz 

I tried `mvn package -Pspark-1.1 -Phadoop-2.3 -B -DskipTests`

And then `mvn package -Pspark-1.1 -Phadoop-2.3 -B -pl 'zeppelin-interpreter,zeppelin-zengine,zeppelin-server' '-Dtest=org.apache.zeppelin.rest.*Test' -DfailIfNoTests=false`.

It fails with the same exception, `Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/settings/AbsSettings$AbsSetting`

**Pull request closed without merging**
