### PR TITLE
[ZEPPELIN-5178] notebook search not working on JDK11

### PR DESCRIPTION
**Pull request by kkalyan**
### What is this PR for?
On JDK11, Notebook search is throwing this error for any query
We couldn't find any notebook matching 'spark'
Logs Indicate this may be issue with using older version of Lucene (5.3.0)

### What type of PR is it?
Upgrades Lucene to the current latest version 8.7.0 and upgrades the deprecated methods

### Todos
[ ] Verify if Lucene handles the index upgrade seamlessly. 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5178

### How should this be tested?
* Unit Tests
* Manual verification of search 

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the contribution!
LGTM

**Comment by Reamer** [comment]
LGTM - just a small comment. Please update the license file https://github.com/apache/zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE#L83-L96

**Comment by kkalyan** [comment]
@Reamer updated Lucene licenses as well the failing aws-sdk-java License. rat license check still failing. Please suggest how to fix this.

**Comment by Reamer** [comment]
@kkalyan Please rebase your branch. We have a hotfix.
https://github.com/apache/zeppelin/commit/4acccfcbdf7ba24b4c24cc247a7b192594140edf

**Comment by kkalyan** [comment]
@Reamer rebased and all checks passed. please merge.

**Comment by Reamer** [comment]
> @Reamer rebased and all checks passed. please merge. 

I'll take an additional look next week.

**Comment by Reamer** [comment]
@Leemoonsoo 
I noticed that we also have lucene 5.5.2 as a dependency because of the [elasticsearch dependency](https://github.com/apache/zeppelin/blob/136140c85800d1d5b4e0a770b33f7ce82b1c2e99/elasticsearch/pom.xml#L45-L49) in the elasticsearch interpreter. What is needed in our licence file?

@zjffdu 
Can you estimate side effects?

**Comment by zjffdu** [comment]
We don't have CI for JDK11, maybe we should add that

**Comment by Reamer** [comment]
I would like to merge this PR. Does anyone know what we have to write in the licence file?

**Comment by Reamer** [comment]
> We don't have CI for JDK11, maybe we should add that

I have created a ticket for this: https://issues.apache.org/jira/browse/ZEPPELIN-5207

**Comment by Reamer** [comment]
@zjffdu and @Leemoonsoo 
Which version entries should be in the licence file? We use different Lucene versions in the zeppelin-zengine and in the Elasticsearch interpreter.
Does it make sense to remove the version?

@kkalyan 
Can you please do a rebase.

**Comment by kkalyan** [comment]
@Reamer rebased to master.

**Comment by Reamer** [comment]
@zjffdu and @Leemoonsoo 
I am very interested in this PR, what is the right way with our licence file?

**Comment by Reamer** [comment]
@kkalyan I have updated your PR to change the licence file.

@zjffdu and @Leemoonsoo I hope this is a good handling of the licence file.

I will merge this PR on Thursday (01.07) if I receive no further comments.

**Pull request closed without merging**
