### PR TITLE
[ZEPPELIN-1825] Use versioned notebook storage by default 

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
Due to recent work on versioned notes under ZEPPELIN-1044, we can use by default Git storage which extends local storage. so the behaviour will be same as before with additional ability to use versioning out of box without configuring it.

### What type of PR is it?
Improvement |  Refactoring

### Todos
* [x] - change VFS to Git

### What is the Jira issue?
[ZEPPELIN-1825](https://issues.apache.org/jira/browse/ZEPPELIN-1825)

### How should this be tested?
start zeppelin and by default be able to use version control (if git client installed)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM
any documentation to update?

**Comment by khalidhuseynov** [comment]
@felixcheung i didn't see much places to update docs, but maybe @AhyoungRyu knows if there's something to be updated?

**Comment by Leemoonsoo** [comment]
`VFSNotebookRepo` can be configured to use [other filesystems](https://commons.apache.org/proper/commons-vfs/filesystems.html) instead of local filesystem.
Those user might be confused when (default) notebook repo is changed to `GitNotebookRepo`.

How about add an item in [upgrade.md](https://github.com/apache/zeppelin/blob/master/docs/install/upgrade.md#upgrading-from-zeppelin-06-to-07) for this change?

**Comment by khalidhuseynov** [comment]
@Leemoonsoo makes sense, added in 7cb133c8dc59357b0572c4f462ae04d5bbb55cce

**Comment by Leemoonsoo** [comment]
Thanks @khalidhuseynov for the improvement.

LGTM and merge if no more comments!

**Comment by AhyoungRyu** [comment]
@khalidhuseynov Seems a default value of `ZEPPELIN_NOTEBOOK_STORAGE ` under [Apache Zeppelin configuration](https://github.com/apache/zeppelin/blob/master/docs/install/install.md#apache-zeppelin-configuration)  table also needs to be updated :)

**Comment by khalidhuseynov** [comment]
thanks @AhyoungRyu, updated!

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Pull request closed without merging**
