### PR TITLE
[ZEPPELIN-1812] Ace editor show/hide problem.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
When editor hide is on and page refresh then editor is gone.
I was solve this problem.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1812

### How should this be tested?
1. hide to editor mode on in paragraph configure.
2. page refresh (f5)
3. enable to show editor mode in paragraph configure.
4. if show editor then is correct.
#### before
badeditor

#### after
goodeditor

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
ci reopen

**Comment by minahlee** [comment]
Tested, LGTM

**Comment by astroshim** [comment]
LGTM

**Comment by minahlee** [comment]
@cloverhearts There are some lines that need to be modified in test.

https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/integration/ParagraphActionsIT.java#L466

https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/integration/ParagraphActionsIT.java#L480

Could you change these lines? Once we see the selenium test pass, I will merge it.

**Comment by prabhjyotsingh** [comment]
Tested, LGTM!

**Comment by cloverhearts** [comment]
SELENIUM TEST PASSED

Currently, Current CI issues are irrelevant to my modifications.

```
10:45:01,535 ERROR org.apache.zeppelin.search.LuceneSearch:120 - Failed to open index dir RAMDirectory@4cc68af8 lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@7ecdc728, make sure indexing finished OK
org.apache.lucene.index.IndexNotFoundException: no segments* file found in RAMDirectory@4cc68af8 lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@7ecdc728: files: []
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:726)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at org.apache.zeppelin.search.LuceneSearch.query(LuceneSearch.java:104)
	at org.apache.zeppelin.search.LuceneSearchTest.canNotSearchBeforeIndexing(LuceneSearchTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
10:45:01,544  INFO org.apache.zeppelin.search.LuceneSearch:305 - Indexing 2 notebooks took 4ms
10:45:01,585  INFO org.apache.zeppelin.search.LuceneSearch:305 - Indexing 2 notebooks took 4ms
10:45:01,632  INFO org.apache.zeppelin.search.LuceneSearch:305 - Indexing 2 notebooks took 4ms
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.495 sec - in org.apache.zeppelin.search.LuceneSearchTest
Running org.apache.zeppelin.conf.ZeppelinConfigurationTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/travis/build/apache/zeppelin/zeppelin-interpreter/target/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/travis/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.347 sec - in org.apache.zeppelin.conf.ZeppelinConfigurationTest

Results :

Failed tests: 
  NotebookTest.testAbortParagraphStatusOnInterpreterRestart:760 expected:<ABORT> but was:<RUNNING>

Tests run: 153, Failures: 1, Errors: 0, Skipped: 0
```

**Pull request closed without merging**
