### PR TITLE
[ZEPPELIN-2030] Select statement doesn't work in LivySparkSQLInterpreter

### PR DESCRIPTION
**Pull request by del680202**
### What is this PR for?
I try to execute sql query by ``%livy.sql``, I got a error as below
```
ERROR [2017-01-30 11:15:57,060] ({pool-2-thread-6} LivySparkSQLInterpreter.java[interpret]:143) - Exception in LivySparkSQLInterpreter while interpret
java.lang.StringIndexOutOfBoundsException: String index out of range: 28
        at java.lang.String.substring(String.java:1963)
        at org.apache.zeppelin.livy.LivySparkSQLInterpreter.parseSQLOutput(LivySparkSQLInterpreter.java:177)
        at org.apache.zeppelin.livy.LivySparkSQLInterpreter.interpret(LivySparkSQLInterpreter.java:128)
        at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:94)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:489)
        at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
        at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
I seem ``parseSQLOutput`` method try to filter out ``only showing top 1 row`` but it doesn't.
Therefore, I fix this issue by modifying condition 

### What type of PR is it?
Bug Fix

### Todos
* [x] - none

### What is the Jira issue?
[ZEPPELIN-2030](https://issues.apache.org/jira/browse/ZEPPELIN-2030)

### How should this be tested?
try  to execute ``%livy.sql  SELECT * FROM bank`` on  tutorial

### Screenshots (if appropriate)
Before

After

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by felixcheung** [comment]
@zjffdu

**Comment by felixcheung** [comment]
this is odd, we should have test that catches this condition - could you check if we could add to livy interpreter tests for this?

**Comment by zjffdu** [comment]
Thanks @del680202 Could you add unit test in `LivySQLInterpreterTest.java`?

**Comment by del680202** [comment]
OK, I will add test cases for this issue

**Comment by zjffdu** [comment]
lgtm

**Comment by del680202** [comment]
Oh.. When I test ``%livy.sql`` by my hive table, ``TEXT`` result ``Output exceeds 102400. Truncated.`` causes a failure.

**Comment by zjffdu** [comment]
@del680202 Can you paste the full stacktrace ?

**Comment by del680202** [comment]
@zjffdu  
I got error message as below
```
ERROR [2017-01-31 16:34:34,431] ({pool-2-thread-7} LivySparkSQLInterpreter.java[interpret]:143) - Exception in LivySparkSQLInterpreter while interpret
java.lang.StringIndexOutOfBoundsException: String index out of range: 34
        at java.lang.String.substring(String.java:1963)
        at org.apache.zeppelin.livy.LivySparkSQLInterpreter.parseSQLOutput(LivySparkSQLInterpreter.java:177)
        at org.apache.zeppelin.livy.LivySparkSQLInterpreter.interpret(LivySparkSQLInterpreter.java:128)
        at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:94)
        at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:495)
        at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
        at org.apache.zeppelin.scheduler.FIFOScheduler$1.run(FIFOScheduler.java:139)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Maybe I can replace condition by matching row format ``line.matches("^\\|.*\\|$")`` instead of skipping magic string such as ``only showing..`` or ``Output exceeds...``?

**Comment by zjffdu** [comment]
I am not sure whether that would help, because `Output exceeds ...` is generated by zeppelin, not by livy or spark. https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/InterpreterOutput.java#L189

**Comment by zjffdu** [comment]
I suspect it is caused by other issues rather than `Output exceeds...`. Because message `Output exceeds...` should be generated after the method `parseSQLOutput`

**Comment by del680202** [comment]
Actually, I inject ``LOGGER.info(line)`` into ``parseSQLOutput`` for tracing input.
Then I got string at least line in result 
``INFO [2017-01-31 16:24:19,584] ({pool-2-thread-5} LivySparkSQLInterpreter.java[parseSQLOutput]:175) - Output exceeds 102400. Truncated.``

Anyway, I try to replace condition by matching row format ``line.matches("^\\|.*\\|$")``.
It works well with me now.

**Comment by zjffdu** [comment]
hmm, right. `LivySparkSQLInterpreter` delegate interpret to `LivySparkInterpreter`. So it is possible to get `Output exceeds...` in  `LivySparkSQLInterpreter`. Thanks @del680202

**Comment by zjffdu** [comment]
@del680202 Can you try this on `%spark.sql` as well ? I guess `Output exceeds...` may also cause issues in displaying table format data in `%spark.sql`

**Comment by del680202** [comment]
@zjffdu 
I had try to query sample table by ``%spark.sql``.
Alert message is not red but it works.

**Comment by del680202** [comment]
I test the same query by ``%jdbc``, I got the same result with ``%spark.sql``

**Comment by zjffdu** [comment]
@del680202 Thanks for checking.

**Comment by minahlee** [comment]
@zjffdu @del680202 Is this ready? :)

**Comment by zjffdu** [comment]
Yes, the PR is ready. CI failure is not relevant.  Please help include it in 0.7

**Comment by minahlee** [comment]
Thank you for quick response! Let me merge this.

**Comment by felixcheung** [comment]
LGTM

**Pull request closed without merging**
