### PR TITLE
[ZEPPELIN-2466] Chart resize problem

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
If you change the size of the chart after changing the mode of the chart,
The chart size is not reflected.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2466

### How should this be tested?
1. resize for your browser.
2. chart toggle -> for example, bar chart -> table -> bar chart
3. and try resize for browser.

#### bug
resize-inc

#### fixed
resize-c

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
more fix

**Comment by cloverhearts** [comment]
Fixed nvd3 basic resize event.

**Comment by 1ambda** [comment]
Tested and works as described. LGTM

**Comment by 1ambda** [comment]
Was this merged into master already?

**Comment by cloverhearts** [comment]
@1ambda 
Sorry for my late answer.
Implementation changed.
I will create a new PR. :)

**Pull request closed without merging**
