### PR TITLE
ZEPPELIN-3104. Support Hadoop 3.0

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This is for supporting hadoop3 which is released recently. Adding 2 profiles: hadoop2 and hadoop3 for hadoop 2.x support and hadoop 3.x support

### What type of PR is it?
[ Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3104

### How should this be tested?
* Travis build is pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@prabhjyotsingh Please help review it, thanks

**Comment by prabhjyotsingh** [comment]
Build number 1433.11 fails, assuming it's not related. Rest looks good.

**Comment by zjffdu** [comment]
Right, it is not related

**Comment by zjffdu** [comment]
Merge if no more comments

**Pull request closed without merging**
