### PR TITLE
[ZEPPELIN-1671] Conda interpreter

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Conda interpreter that manages conda environment for PythonInterpreter

### What type of PR is it?
Feature

### Todos
* [x] - Basic impl
* [x] - update doc

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1671

### How should this be tested?
Recreate(or create new) your python interpreter setting in gui.

List all conda env
```
%python.conda
```

Activate env
```
%python.conda activate [name]
```

Deactivate env
```
%python.conda deactivate
```

### Screenshots (if appropriate)
conda

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? yes

### CODE REVIEW

**Comment by tae-jun** [comment]
@Leemoonsoo Awesome! I will test it after updating the doc.

By the way, can I list installed packages of conda?

**Comment by agoodm** [comment]
From what I can tell, the main intent of this PR is to support switching between environments on the fly, which is in of itself a very useful feature. Will this also support creating new environments and installing conda packages into the current environment from within Zeppelin?

**Comment by Leemoonsoo** [comment]
@tae-jun @agoodm Thanks for the interest. 
Yes, the intent is allow user easily switch between environments. 
Supporting more actions like creating new env, installing packages will not be very difficult and make super sense to have. but i'd like to leave them as future work.

**Comment by Leemoonsoo** [comment]
Made some improvement on output formatting with basic documentation and unittest.

conda_improved

Please review this.

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions.

**Comment by nEosAg007** [comment]
This is not working with latest 0.7.2, it gives the same error as earlier, as shown below:

zeppelin_conda_issue

But the https://issues.apache.org/jira/browse/ZEPPELIN-1671 shows fixed in 0.7.0

**Comment by Leemoonsoo** [comment]
Is 'conda' command in your PATH?

**Comment by nEosAg007** [comment]
I have installed Miniconda and it is in my $PATH as shown below:

[root@ip-xx-xxx-xx-xxx ~]# echo $PATH
/root/miniconda2/bin:/opt/maven/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

**Comment by edgarson** [comment]
The same error occurs when User Impersonation is enabled for Python.

**Comment by pauldj54** [comment]
Hi everyone, 
I got the same error as @nEosAg007 . I added conda and all anaconda3 libraries to my path (in my case /opt/anaconda3/bin) but this makes python3 the default python in my environment. That makes Zeppelin start crashing with the error
```
apache.zeppelin.interpreter.InterpreterException:   File "/usr/bin/hdp-select", line 205
    print "ERROR: Invalid package - " + name
                                    ^
SyntaxError: Missing parentheses in call to 'print'
ls: cannot access /usr/hdp//hadoop/lib: No such file or directory
Exception in thread "main" java.lang.IllegalStateException: hdp.version is not set while running Spark under HDP, please set through HDP_VERSION in spark-env.sh or add a java-opts file in conf with -Dhdp.version=xxx
```
My platform is a HDP 2.5 with Zeppelin 0.7.3 and this is my zeppelin.sh configuration for Python
```
export PYTHONPATH="${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.8.2.1-src.zip"
export SPARK_YARN_USER_ENV="PYTHONPATH=${PYTHONPATH}"
export PYSPARK_DRIVER_PYTHON="/var/opt/teradata/anaconda3/envs/py35/bin/ipython"
export PYSPARK_PYTHON="/var/opt/teradata/anaconda3/envs/py35/bin/python"
export PYLIB="/var/opt/teradata/anaconda3/envs/py35/lib"
```
Is there an optimal way to configure Zeppelin to make it fully functional?

Kind Regards, Paul

**Pull request closed without merging**
