### PR TITLE
[ZEPPELIN-2573] Improve navbar style

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Improved navbar style. Refer the screenshots for detail.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Fix nav brand text font-size
* [x] - Fix nav menu text font-weight
* [x] - Removed icon for search input
* [x] - Fix bug in notebook menu (focus state remains after it's closed)

### What is the Jira issue?

[ZEPPELIN-2573](https://issues.apache.org/jira/browse/ZEPPELIN-2573)

### How should this be tested?

1. Build Zeppelin: ` mvn clean package -DskipTests; ./bin/zeppelin-daemon.sh restart`
2. Open the main page

#### Before: Navbar Style

image

#### After: Navbar Style

image

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested and LGTM

**Comment by Leemoonsoo** [comment]
Merge to master if no further discussions

**Comment by Leemoonsoo** [comment]
@1ambda Could you help resolve conflicts?

**Comment by 1ambda** [comment]
Sure.

**Comment by 1ambda** [comment]
Thanks @Leemoonsoo!

- I'v just rebased and 
- fixed navbar displaying in a small browser (a470b94)

### Before

image

### After

image

**Comment by Leemoonsoo** [comment]
Thanks @1ambda. Merging this one to master

**Pull request closed without merging**
