### PR TITLE
ZEPPELIN-3527. replace log4j with reload4j

### PR DESCRIPTION
**Pull request by Samrat002**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

### What type of PR is it?
Improvement
change from log4j to reload4j

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3527

### CODE REVIEW

**Comment by Reamer** [comment]
We should remove `slf4j-log4j12` completely and replace it with the slf4j-api in the zeppelin code.
Instead of `log4j1` we should ship `log4j2`.

**Comment by Samrat002** [comment]
@jongyoul , greetings!!!

I tried changing to log4j2 , and faced some of the issues which need many changes on entire logging 
As you must be aware that log4j2 has many srtructural and breaking changes from log4j1 , it is altering/touching some of the logging that is present / running . 
Even hadoop is moving towards reload4j and it sync with the log4j functionality 
Also i have tried in EMR clusters with zeppelin 0.10.1 version reload changes.

I am working more on it ! i will soon raise changes associted with log4j2.

**Comment by Samrat002** [comment]
@Reamer , greetings !
i am working on it to completely replace log4j with log4j2 and remove the usage of `slf4j-log4j12`
please allow me sometime to fix the error out and raise a pr for the same.

**Comment by Reamer** [comment]
> @Reamer , greetings ! i am working on it to completely replace log4j with log4j2 and remove the usage of `slf4j-log4j12` please allow me sometime to fix the error out and raise a pr for the same.

Please do not be afraid to remove the direct uses of Log4j1 in Zeppelin. I am aware that there will be function loss when working only with API of slf4j and directly with implementation log4j1.

Some code parts, which can be dropped.
https://github.com/apache/zeppelin/blob/8995ff227a44760b7dbb005a85bee4ac7772e1f2/zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java#L56-L85
https://github.com/apache/zeppelin/blob/85ed8e2e51e1ea10df38d4710216343efe218d60/zeppelin-server/src/main/java/org/apache/zeppelin/service/AdminService.java#L32-L77
https://github.com/apache/zeppelin/blob/85ed8e2e51e1ea10df38d4710216343efe218d60/zeppelin-server/src/main/java/org/apache/zeppelin/rest/ZeppelinRestApi.java#L69-L89

**Comment by tangzhankun** [comment]
@Samrat002 thanks for the help. This is a critical fix.
Any update on this? Seems the PR is outdated.

**Comment by Samrat002** [comment]
@tangzhankun I got occupied on my current company deliverables , wasnt able to make much of progress !
i am expecting to get quality time for this task from next week.
If this is critical piece and need urgency , please feel free to pick or else i will be working on it from next week onwards

**Comment by tangzhankun** [comment]
@Samrat002 thanks a lot! I am not an expert as well. So please continue as your plan. Let me know if you have any blockers. I will try to help.

**Comment by tangzhankun** [comment]
@Samrat002 any updates on this?

**Comment by Geetha7891** [comment]
@Samrat002 Thanks a lot for your support. Let me try to work on this.

**Pull request closed without merging**
