### PR TITLE
[ZEPPELIN-3781] Bump up version of npm packages

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
The goal of this PR is to track bump up version on babel, karma-coverage, protractor, and webpack-dev-server packages.

### What type of PR is it?
[Refactoring]

### What is the Jira issue?
* [ZEPPELIN-3781](https://issues.apache.org/jira/browse/ZEPPELIN-3781)

### How should this be tested?
CI shoud be green 

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
CI green.
@zjffdu @felixcheung can you help review this.

**Comment by zjffdu** [comment]
oops, it seems a large change, not sure why node npm package upgrade needs so large change. I am not an frontend expert, just need some explanation. 😄

**Comment by prabhjyotsingh** [comment]
Changes consist of two files; 
 - The larger one being package-lock.json; It stores an exact, versioned dependency tree rather than using starred versioning like package.json itself (e.g. 1.0.*). This means you can guarantee the dependencies for other developers or prod releases, etc. It also has a mechanism to lock the tree but generally will regenerate if package.json changes. https://docs.npmjs.com/files/package-lock.json
 - package.json contains the actual changes that needs upgrade.

**Comment by prabhjyotsingh** [comment]
Sure, thanks for the review will merge this soon to both master and branch-0.8

**Comment by zjffdu** [comment]
Is it necessary to backport to branch-0.8 ? Does it fix some critical issue ?

**Comment by prabhjyotsingh** [comment]
On second thought, this doesn't really require a backport.

**Pull request closed without merging**
