### PR TITLE
ZEPPELIN-1473. It is not necessary to create SQLContext in LivyInterpreter

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Livy will create SQLContext/HiveContext internally, (LIVY-94), so it is not necessary to create that in LivyInterpreter. Otherwise sqlContext in zeppelin will override that in livy. 

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1473

### How should this be tested?
Tested manually.  HiveContext is created properly in livy (with proper livy configuration), and can access hive data. 

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@prabhjyotsingh Mind to help review it ? Thanks

**Comment by prabhjyotsingh** [comment]
Tested with latest version of LIVY, works as expected.
LGTM.

**Comment by felixcheung** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
