### PR TITLE
[ZEPPELIN-5273] Support Spark 3.1.1

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR makes Zeppelin supports Spark 3.1.1.
In my quick test, the current Spark interpreter seems to work fine with Spark 3.1.1 without modification, when the version check passes. So, this PR simply update `UNSUPPORTED_FUTURE_VERSION` to Spark `3.2.0` from `3.1.0`.

However, if anyone sees a problem with Spark 3.1.1, please comment.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5273
https://issues.apache.org/jira/browse/ZEPPELIN-5278

### How should this be tested?
Configure SPARK_HOME env variable to point Spark 3.1.1 binary and run Spark APIs, such as

```
%spark
println(sc.version)
sc.parallelize(1 to 10).count
```

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Reamer** [comment]
Ich denke, wir sollten auch diese Dateien aktualisieren.
https://github.com/apache/zeppelin/commit/2dfe3dce55290b9a1be1e41029a3b26c07348b8d

**Comment by Leemoonsoo** [comment]
> I think we should update these files as well.
> 2dfe3dc

Addressed the comment. @Reamer @zjffdu A quick question. I added spark 3.1.1 version test to [zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/SparkIntegrationTest30.java](https://github.com/apache/zeppelin/pull/4077/files#diff-416d112f97fe4225d76924c60c647a01394a1e3e295194aecb7babeb13a8585e) and [zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/ZeppelinSparkClusterTest30.java](https://github.com/apache/zeppelin/pull/4077/files#diff-da47473a6df1b34b61acc2612d85f08331f597a0e2652e3ec347c09b8895415d), instead of replacing 3.0.1 to 3.1.1.

@Reamer @zjffdu Which is the preffered way here?

a) Adding `3.1.1` in `ZeppelinIntegrationTest30.java`, in addition to `3.0.1`
b) Replace `3.0.1 -> 3.1.1` in `ZeppelinIntegrationTest30.java`
c) Add new file `ZeppelinIntegrationTest31.java` in addition to `ZeppelinIntegraionTest30.java`

**Comment by zjffdu** [comment]
@Leemoonsoo I think we should add new test for 3.1.x, and also it is time to remove some old spark version test.

**Comment by Reamer** [comment]
> also it is time to remove some old spark version test.

In my opinion, we should only support and test Spark versions that can be downloaded via the standard download page.
https://spark.apache.org/downloads.html

**Comment by zjffdu** [comment]
LGTM

**Comment by Reamer** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Thank @Reamer and @zjffdu for the review and guide this PR.
I'm merging this one to master.

**Pull request closed without merging**
