### PR TITLE
ZEPPELIN-3111. Refactor SparkInterpreter

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This is for the refactoring of SparkInterpreter. See design doc. https://docs.google.com/document/d/1AfGg3aGXonDyri1jrP4MMFT4Y4j3wpN1t8kL-GAKSUc/edit?usp=sharing

### What type of PR is it?
[Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3111

### How should this be tested?
* Unit test is added. 

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@Leemoonsoo @felixcheung @prabhjyotsingh @jongyoul Could you help review it ? Thanks

**Comment by Leemoonsoo** [comment]
in the binary package, how spark/scala-2.11 and spark/scala-2.10 modules will be packaged?

**Comment by zjffdu** [comment]
@Leemoonsoo binary package is the same as before, spark/scala-2.11 and spark/scala-2.10 will be packaged together into `spark-interpreter-0.8.0-SNAPSHOT.jar` which doesn't contain scala library. scala library is in the spark distribution. So SparkInterpreter will load the correct scala version of SparkInterpreter (`SparkScala211Interpreter` or `SparkScala210Interpreter`) based the scala version in your spark distribution (depends on SPARK_HOME you set).

**Comment by Leemoonsoo** [comment]
Thanks @zjffdu for explain. Looks good to me.

**Comment by zjffdu** [comment]
Thanks @Leemoonsoo , will merge it if no more comments

**Comment by alonshoham** [comment]
In this PR a change was made to `bin/interpreter.sh` script. In line 124 `SPARK_APP_JAR="$(ls ${ZEPPELIN_HOME}/interpreter/spark/spark-interpreter*.jar)"` used to be `SPARK_APP_JAR="$(ls ${ZEPPELIN_HOME}/interpreter/spark/zeppelin-spark*.jar)"` 
This change was not updated in `bin/interpreter.cmd`, meaning that spark interpreter fails in windows.

**Comment by zjffdu** [comment]
Thanks @alonshoham  feel free to create a PR for that.

**Comment by zjffdu** [comment]
@alonshoham Sorry I didn't notice you created the ticket, I have fixed via this commit, https://github.com/apache/zeppelin/commit/8b2f4a7bd89aa69661e09ef9ad73c04d862029ff

Could you help verity it ?

**Comment by alonshoham** [comment]
Your commit looks OK.

Notice that I mentioned another problem in the ticket with interpreter.cmd

**Pull request closed without merging**
