### PR TITLE
Zeppelin 26

### PR DESCRIPTION
**Pull request by cfmcgrady**
Base on this branch(https://github.com/Leemoonsoo/incubator-zeppelin/tree/ZEPPELIN-26). add HDFSNotebookRepo.

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Hi, @cfmcgrady. Thanks for contribution.

Constructor type for NotebookRepo is slightly changed.
from NotebookRepo(ZeppelinConfiguration conf, URI uri) to NotebookRepo(ZeppelinConfiguration conf). Please rebase this branch with master branch.

One concern is  
Currently zeppelin-daemon process and interpreter process uses common.sh to construct it's classpath.
Once zeppelin-daemon have HDFS dependencies, then by common.sh, it'll be also loaded into every interpreter process. Especially spark include HDFS related dependency, too, they'll conflict.

And version of HDFS related dependency's is fixed. i think it'll be better if it is configurable.

**Comment by cfmcgrady** [comment]
@Leemoonsoo.
so which is better way make version of HDFS configurable.

**Comment by Leemoonsoo** [comment]
@cfmcgrady I think using maven property is an option for making HDFS version configurable. For example spark interpreter is already doing it.

**Comment by jongyoul** [comment]
@cfmcgrady Do you have any update for this? Otherwise, Could you please close this PR?

**Comment by corneadoug** [comment]
@cfmcgrady Is this PR still relevant?
Otherwise I will close it

**Pull request closed without merging**
