### PR TITLE
Authenticated user aware notebook storage layer

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
This PR is to make available information on the currently authenticated user(subject) in the Notebook storage level. It can be used for multiple purposes (ACL, login to third parties, etc.) once storage layer is user aware. It basically updates NotebookRepo api with additional user info

### What type of PR is it?
Improvement

### Todos
* [x] - add authInfo(subject) to list()
* [x] - add authInfo(subject) to get()
* [x] - add authInfo(subject) to save()
* [x] - add authInfo(subject) to remove()

### How should this be tested?
storage layer should be working as before with and without authenticated user, green CI

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? not breaking, but some api changes
* Does this needs documentation? No

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
somehow selenium tests keep error with 
```
Tests in error: 
  ParagraphActionsIT.testRemoveButton:145->AbstractZeppelinIT.waitForParagraph:84->AbstractZeppelinIT.pollingWait:110 Â» Timeout
  ParagraphActionsIT.testMoveUpAndDown:182->AbstractZeppelinIT.waitForParagraph:84->AbstractZeppelinIT.pollingWait:110 Â» Timeout
  ParagraphActionsIT.testCreateNewButton:77->AbstractZeppelinIT.waitForParagraph:84->AbstractZeppelinIT.pollingWait:110 Â» Timeout
```
which is not related,  will be reopening. 
ready for review

**Comment by echarles** [comment]
LGTM

I have tested and works well for me.
Gone through the code and changes make sense.

Will be useful to get it into 0.6 release (especially if #836 is also in 0.6, as methods are added in the NotebookServer, which will have impact on this PR).

**Comment by Leemoonsoo** [comment]
Thanks @khalidhuseynov for the improvement.
LGTM and merge it into 0.6 and master if there're no more discussions.

**Comment by khalidhuseynov** [comment]
rebased from master

**Comment by vgmartinez** [comment]
LGTM...I have tested and works well for me.

**Pull request closed without merging**
