### PR TITLE
[MINOR] Update deb maintainer information

### PR DESCRIPTION
**Pull request by pan3793**
### What is this PR for?

Update deb maintainer information from the certain developer of this project to Apache Zeppelin PMC, this is a common practice for Apache projects.

### What type of PR is it?

Documentation

### Todos

N/A

### What is the Jira issue?

MINOR

### How should this be tested?

Review

### Questions:
* Does the license files need to update? No.
* Is there breaking changes for older versions? No.
* Does this needs documentation? No.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @Reamer

**Comment by Reamer** [comment]
I have never used the Debian package. I do not know if this change will cause problems. Maybe it is also better if we remove deb support. ping @Leemoonsoo

**Comment by jongyoul** [comment]
This is what I made and it was used in Apache Bigtop before. I checked it now simply and it's not used anymore. I think it could be removed.

**Comment by pan3793** [comment]
@jongyoul do you mean remove whole `zeppelin-distribution/src/deb`?

**Comment by jongyoul** [comment]
@pan3793 Yes, I think so. BTW, to do that, it would be better to make a ticket to handle it.

**Comment by pan3793** [comment]
@jongyoul sure, I'm going to create a JIRA

**Comment by pan3793** [comment]
Close and move to ZEPPELIN-5967 (https://github.com/apache/zeppelin/pull/4670)

**Pull request closed without merging**
