### PR TITLE
[ZEPPELIN-1843] Error on invoking the REST API to run paragraph synchronously

### PR DESCRIPTION
**Pull request by kavinkumarks**
### What is this PR for?
This fixes the validation check of paragraph's note id to match with the Note instance id.

### What type of PR is it?
Bug Fix

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1843

### How should this be tested?
The run para synchronous REST API should be successful.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by kavinkumarks** [comment]
Reopening to trigger the CI build.

**Comment by kavinkumarks** [comment]
Reopening to trigger the CI build.

**Comment by kavinkumarks** [comment]
Reopening to trigger the CI build.

**Comment by kavinkumarks** [comment]
The travis build is green.

**Comment by AhyoungRyu** [comment]
@kavinkumarks Thanks for your contribution! Seems this bug is only shown at the first time after starting Zeppelin. Tested and works well.

**Comment by jongyoul** [comment]
Will merge it if there's no more discussion

**Comment by Leemoonsoo** [comment]
Merge it master and branch-0.7

**Pull request closed without merging**
