### PR TITLE
[minor] Remove incorrect configuration and fix description of LdapRealm

### PR DESCRIPTION
**Pull request by VipinRathor**
### What is this PR for?
There is wrong description and incorrect configuration defined in comment in LdapRealm.java. Since the documentation at (http://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/security/shiroauthentication.html) does not mention LdapRealm, the information should be correct in the code comments at the least.

### What type of PR is it?
Documentation

### What is the Jira issue?
N/A

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@VipinRathor any specific reason for chaning `ldapRealm = org.apache.zeppelin.realm.LdapRealm` to `ldapRealm=org.apache.zeppelin.realm.LdapRealm` in all the lines ?

**Comment by prabhjyotsingh** [comment]
Also, I notice you have removed these two;
 - ldapRealm.contextFactory=$ldapGroupContextFactory
 - ldapRealm.contextFactory.systemAuthenticationMechanism=simple

any specific reason?

**Comment by VipinRathor** [comment]
@prabhjyotsingh 
Thanks for reviewing this.

> any specific reason for chaning ldapRealm = org.apache.zeppelin.realm.LdapRealm to ldapRealm=org.apache.zeppelin.realm.LdapRealm in all the lines ?

Earlier there were lines with mixed spacing, I just wanted to keep it uniform. We can choose any one style that you want.

> I notice you have removed these two;
>
>    ldapRealm.contextFactory=$ldapGroupContextFactory
>    ldapRealm.contextFactory.systemAuthenticationMechanism=simple
>
> any specific reason?

Yes, if you keep the first one, Shiro will throw error that ldapGroupContextFactory is not defined anywhere so can't be used. And in fact, the sample configuration is actually not defining any such ldapGroupContextFactory. Instead `LdapRealm` is using `JndiLdapContextFactory` , so no need to override a contextFactory.

For `systemAuthenticationMechanism`, there is neither such configuration available in `JndiLdapContextFactory` nor `LdapRealm` introduced any. Looks like a left over from earlier configuration set, hence removed.

**Comment by prabhjyotsingh** [comment]
Sure LGTM!

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
