### PR TITLE
[ZEPPELIN-4712]remove paragraph failed due to Interpreter connection refused

### PR DESCRIPTION
**Pull request by xiejiajun**
### What is this PR for?
- an interpreter process refused to connect due to it abnormal stop , which eventually caused the remove paragraph operation to fail to complete when i try remove a paragraph.

### What type of PR is it?
- Bug Fix

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4712

### Questions:
Does the licenses files need update? NO
Is there breaking changes for older versions? NO
Does this needs documentation? NO

### CODE REVIEW

**Comment by zjffdu** [comment]
I think we should add throw Exception for method `removeResourcesBelongsToParagraph` and let the caller decide how to handle the exception. What do you think ?

**Comment by xiejiajun** [comment]
> I think we should add throw Exception for method `removeResourcesBelongsToParagraph` and let the caller decide how to handle the exception. What do you think ?

@zjffdu , i have considered this. If we do this, removeNote, removeFolder, and removeParagraph will need to handle this exception separately.

**Comment by xiejiajun** [comment]
> I think we should add throw Exception for method `removeResourcesBelongsToParagraph` and let the caller decide how to handle the exception. What do you think ?

another purpose of  caught this exception in the removeResourcesBelongsToParagraph method is  in order to make  other running interpreters can  release resources that related to the paragraph that  needs to be removed. @zjffdu

**Comment by zjffdu** [comment]
Sorry for late response, @xiejiajun  Your explanation make sense to me.  I think we need to improve the exception handling where we don't have very well convention. Currently your PR LGTM for fixing this issue

**Pull request closed without merging**
