### PR TITLE
[ZEPPELIN-6047] add setConfig method to action-bar.component.ts

### PR DESCRIPTION
**Pull request by Charlie91**
### What is this PR for?
[[ZEPPELIN-6047](https://issues.apache.org/jira/browse/ZEPPELIN-6047)]
add necessary method so the CRON functionality could be set from the new interface

### What type of PR is it?
Bug Fix

### CODE REVIEW

**Comment by jongyoul** [comment]
@Charlie91 Hello, Sorry for the late check. Thank you for your first contribution. Could you please create a JIRA ticket for it? I started to run CI

**Comment by jongyoul** [comment]
Moreover, it would be helpful to add a screenshot for your change.

**Comment by Reamer** [comment]
Thank you for working on the new web frontend. Screenshots would be very helpful here.

**Comment by Reamer** [comment]
Can you also upload a GIF/screenshot showing the correct function? Many thanks in advance.

**Comment by Charlie91** [comment]
@Reamer sure
Screen Recording 2024-08-07 at 18 03 46

**Review by jongyoul — APPROVED** [review]

**Comment by zlosim** [comment]
Hi @Charlie91 this looks like was fixed only when selecting from predefined presets, when i want to use custom one, its deleted after refresh

**Pull request merged**
