### PR TITLE
[ZEPPELIN-2749] Use scalable file structure for zeppelin web

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

We have improved zeppelin-web, but some parts are still messy. As part of keeping zeppelin-web module healthy ([ZEPPELIN-2725](https://issues.apache.org/jira/browse/ZEPPELIN-2725)), I suggest having these file structure. (Refer the screenshot section)

Here are few reasons.

- unified directory, file name helps us to recognize, find which part we should modify / fix
  * Let's say we need to modify the resize feature of paragraph, where the developer can find it? currently, it's under `component/resizable` not under `paragraph/resizeable` and also it's not the shareable component. There is no reason to keep that files in `component/**`
- [this structure](https://github.com/toddmotto/angularjs-styleguide#file-naming-conventions) is what the angularjs community has verified for few years. so newly joined developers can feel more comfortable.
- this is necessary for [Modular archiecture](https://issues.apache.org/jira/browse/ZEPPELIN-2750) and it eventually helps us to make a smooth transition toward next technologies (even whatever we will use)

Additionally, 

- This is not the meaningless refactoring PR and doesn't block developing new features / fixes (Please refer the `Some Details` section)
- I will handle conflicts for few days would be brought by other WIPs

For your information, 

- https://github.com/toddmotto/angularjs-styleguide#file-naming-conventions
- https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#naming

#### How to Review This PR?

Please follow the commits. I modified submodules by splitting commits. Thus commit message includes what has been done in that PR. For example,

image

#### Some Details

- Didn't change the widely used variable names not to make many conflicts. For example, `websocketMsgSrv`, `arrayOrderingSrv`
- Since there are helium packages already published, didn't change the HTML file names like `pivot_setting.html` (it's better to use `pivot-setting.html` if we following the rule)

### What type of PR is it?
[Improvement | Refactoring]

### Todos

Please refer the commit message.

### What is the Jira issue?

[ZEPPELIN-2749](https://issues.apache.org/jira/browse/ZEPPELIN-2749)

### How should this be tested?

**All functionalities must work** as like before, CI will test it. 

#### Before: messy, mixed directory structure

image

#### After: only the shared components will be placed under `components/`

image

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by soralee** [comment]
Cool, I also experienced as like what your describing at especially filename and messy folders.
And Tested and LGTM. Everything is working.

**Comment by 1ambda** [comment]
@soralee Thanks for the review. We need to keep the zeppelin-web module clean. :) 

Merge if no more discussion.

**Comment by 1ambda** [comment]
rebased to fix some commit message which can't be handled in the merge script. (`*`)

**Comment by 1ambda** [comment]
Rebased to clean commit messages.

**Comment by 1ambda** [comment]
Left a comment for history.

I tried to merge this one before 11 hours ago and at that time it looks merged. (no error on the script) But ASF git didn't reflect the commit. That's the reason why I rebased twice. (I thought long commit message or some invalid chars are the problem). 

image

**Pull request closed without merging**
