### PR TITLE
[ZEPPELIN-4988] fix bug when running zeppelin on the machine where k8s is installed

### PR DESCRIPTION
**Pull request by zhoulii**
### What is this PR for?
solve a issue mentioned in [ZEPPELIN-4988](https://issues.apache.org/jira/browse/ZEPPELIN-4988)

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [ZEPPELIN-4988](https://issues.apache.org/jira/browse/ZEPPELIN-4988)

### How should this be tested?
* covered by the existed unit tests
* travis-ci: https://travis-ci.org/github/zhoulii/zeppelin/builds/715721363
* manually test: run zeppelin on a k8s node, the exception in [ZEPPELIN-4988](https://issues.apache.org/jira/browse/ZEPPELIN-4988) does not appear

### Questions:
* Does the licenses files need update? **NO**
* Is there breaking changes for older versions? **NO**
* Does this needs documentation? **NO**

### CODE REVIEW

**Comment by Reamer** [comment]
Hi @zhoulii,
Thank you very much for your PR. Of course we can change the file path, this should have no side effect.
Your setup with a Zeppelin server running on a Kubernetes node is strange by the way.

LGTM

**Comment by Reamer** [comment]
Offtopic:
Which Docker Images do you use? Help with PR #3859 would be nice.

**Comment by zhoulii** [comment]
Hi @Reamer , thanks for the review. The docker image we used is apache/zeppelin:0.9.0. And in my work, we just start to work with zeppelin on k8s, so it would be nice to have more opportunity to get involved in commuity, I will see what I can do for PR [#3859](https://github.com/apache/zeppelin/pull/3859).

**Comment by Reamer** [comment]
If there are no further comments, I will merge the PR on Monday.

**Comment by Leemoonsoo** [comment]
LGTM

**Pull request closed without merging**
