### PR TITLE
[ZEPPELIN-4319] Fix spell interpreter parse text logic

### PR DESCRIPTION
**Pull request by santosh1994**
### What is this PR for?
Spell interpreter returns incorrect results when paragraph having magic in between text, with current approach to get text without magic 

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-4319

### How should this be tested?
* Enable zeppelin-markdown-spell
* Run %markdown paragraph with containing %markdown as text within it
* Verify if result is valid and complete

### Screenshots (if appropriate)
Before:
image
After:
image

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @santosh1994 for the contribution. Somehow, this PR didn't run Jenkins CI test.
Could you close, re-open this PR (or push a new commit) to trigger CI test again?

**Comment by santosh1994** [comment]
@Leemoonsoo Tried closing and reopen PR . Seems like Jenkins is not picking travis build job - https://travis-ci.org/santosh1994/zeppelin/builds/588286857

**Comment by Leemoonsoo** [comment]
The branch this PR is based on looks like does not have .travis.yml.
I suggest rebase PR to current master branch, so we can make sure everything is okay.

But currently, master branch seems have some broken tests. I'm fixing it now. Let me nofify here once master branch becomes green.

**Comment by Leemoonsoo** [comment]
@santosh1994 Just fixed master branch CI issue. Could you try rebase this to latest master branch and see if it passes all tests?

**Comment by santosh1994** [comment]
@Leemoonsoo Travis build is passing, but however jenkins/karma build is not being triggered, even though I have updated branch with latest master
https://travis-ci.org/santosh1994/zeppelin/builds/597462895

**Comment by Leemoonsoo** [comment]
Looks like Jenkins have a problem not triggering some PR ([INFRA-19249](https://issues.apache.org/jira/browse/INFRA-19249)).

Anyway, I checked your travis link and everything looks good to me.

Thanks @santosh1994 for the contribution. I'm merging this to master.

**Pull request closed without merging**
