### PR TITLE
[ZEPPELIN-4403] Support publishable for paragraph

### PR DESCRIPTION
**Pull request by hsuanxyz**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

### What type of PR is it?
[Feature]

### Todos
*

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-4403

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Screenshots (if appropriate)

publish

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@hsuanxyz It is related with 2 jiras ? If so, please merge them as one jira.

**Comment by zjffdu** [comment]
Overall, PR LGTM, please add description in the PR

**Comment by hsuanxyz** [comment]
@zjffdu The ZEPPELIN-4403 is sub-task, I have removed the main-task link from the PR.

**Comment by zjffdu** [comment]
Thanks @hsuanxyz will merge it soon.

**Pull request closed without merging**
