### PR TITLE
[ZEPPELIN-4695] Bump dependencies to fix CVEs

### PR DESCRIPTION
**Pull request by alexott**
### What is this PR for?

This patch bumps versions of some components that were reported as having (potential?) vulnerabilities.  It also unifies usage of different hadoop versions, etc., moving version configuration to a top-level pom.xml, instead of specification of them inside individual poms. This for example, also fixes #3702. 

### What type of PR is it?
Refactoring

### TODOs

We'll need to followup on the other items, like:
* Check dependencies in the Docker image

### What is the Jira issue?
* ZEPPELIN-4695

### How should this be tested?
* https://travis-ci.org/github/alexott/zeppelin/builds/678099649

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Reamer** [comment]
great pull request!

Only one small question. Why setting a global JVM system property to disable the quartz update check?

I think the following code is better, because:
 1) The compiler checks, if the property is still available.
 1) You have no side-effects, which other threads/tasks
```
    Properties schedulerProperties = new Properties();
    schedulerProperties.setProperty(StdSchedulerFactory.PROP_SCHED_SKIP_UPDATE_CHECK, "true");
    return new StdSchedulerFactory(schedulerProperties).getScheduler();
```

**Comment by alexott** [comment]
I didn't change code much - previous version did use system property. 
But I also tried your variant, and tests were failing for some reason - I think that it makes sense to investigate why this happens, but maybe in follow up JIRA

**Comment by alexott** [comment]
I've created ZEPPELIN-4772 to investigate why configuration via properties doesn't work

**Comment by Leemoonsoo** [comment]
LGTM

**Pull request closed without merging**
