### PR TITLE
[ZEPPELIN-1869] changed the API response to generate to 200.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

### What type of PR is it?
Documentation | change

### Todos
- [x] replace to doc
- [x] change response 201 -> 200

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1869

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? yes

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@cloverhearts I think you need update related unittests, too.

```
Results :

Failed tests: 
  InterpreterRestApiTest.testAddDeleteRepository:352 Test create method:
Expected: HTTP response <201> from /api/interpreter/repository/
     but: got <200> OK
  InterpreterRestApiTest.testCreatedInterpreterDependencies:171 test create method:
Expected: HTTP response <201> from /api/interpreter/setting
     but: got <200> OK
  InterpreterRestApiTest.testSettingsCRUD:124 test create method:
Expected: HTTP response <201> from /api/interpreter/setting/
     but: got <200> OK
  ZeppelinRestApiTest.testCloneNote:329 test note clone method:
Expected: HTTP response <201> from /api/notebook/2C7FSPHN2
     but: got <200> OK
  ZeppelinRestApiTest.testImportNotebook:265 
Expected: HTTP response <201> from /api/notebook/import/
     but: got <200> OK
  ZeppelinRestApiTest.testInsertParagraph:593 Test insert method:
Expected: HTTP response <201> from /api/notebook/2C6FACAQZ/paragraph
     but: got <200> OK
  ZeppelinRestApiTest.testNoteCreateNoName:127->testNoteCreate:175 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  ZeppelinRestApiTest.testNoteCreateWithName:122->testNoteCreate:175 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  ZeppelinRestApiTest.testNoteCreateWithParagraphs:140 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  NotebookRestApiTest.testCloneNote:129 
Expected: HTTP response <201> from /api/notebook/2C6JVYEJD
     but: got <200> OK
  NotebookSecurityRestApiTest.testThatOtherUserCannotAccessNoteIfPermissionSet:81->createNoteForUser:155 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  NotebookSecurityRestApiTest.testThatUserCanSearchNote:115->createNoteForUser:155 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  NotebookSecurityRestApiTest.testThatWriterCannotRemoveNote:98->createNoteForUser:155 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  NotebookSecurityRestApiTest.testThatOtherUserCanAccessNoteIfPermissionNotSet:72->createNoteForUser:155 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK
  NotebookSecurityRestApiTest.testThatUserCanCreateAndRemoveNote:63->createNoteForUser:155 test note create method:
Expected: HTTP response <201> from /api/notebook/
     but: got <200> OK

Tests run: 82, Failures: 15, Errors: 0, Skipped: 1
```

**Comment by cloverhearts** [comment]
@Leemoonsoo Ah! sorry, i will fix!

**Comment by cloverhearts** [comment]
Fixed done.
CI is green :)

**Comment by jongyoul** [comment]
LGTM. Will merge if there's no more discussion

**Pull request closed without merging**
