### PR TITLE
Shorten certain error logs in order to keep CI logs clear

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
This is to shorten certain error logs in order to keep CI clear without polluted logs.

### What type of PR is it?
Improvement

### Todos
* [x] - shorter error log

### What is the Jira issue?
N/A

### How should this be tested?
CI pass

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

not to polute logs

### CODE REVIEW

**Comment by bzz** [comment]
Looks awesome, thank you for cleaning it up!

Let me try it.

**Comment by khalidhuseynov** [comment]
rebased from master and seems like only selenium profile fails with: 
```
Results :

Tests in error: 
  ParagraphActionsIT.testEditOnDoubleClick:443 Â» ElementNotVisible Element is no...

Tests run: 17, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by anthonycorbacho** [comment]
@khalidhuseynov its a know issue: logged here https://issues.apache.org/jira/browse/ZEPPELIN-1623

**Comment by bzz** [comment]
Looks good to me, merging if there is no further discussion

**Pull request closed without merging**
