### PR TITLE
[ZEPPELIN-449] Enhance log messages when interpreter is initializing

### PR DESCRIPTION
**Pull request by lresende**
### What is this PR for?

Enhance log messages when interpreter is initializing to avoid user confusion.
### What type of PR is it?

[Bug Fix]
### What is the Jira issue?
- [ZEPPELIN-449](https://issues.apache.org/jira/browse/ZEPPELIN-449)

### CODE REVIEW

**Comment by bzz** [comment]
Thank you for improvement!

LGTM

@lresende did that actually help you debugging issues similar to ZEPPELIN-449 ?

**Comment by zjffdu** [comment]
@lresende maybe ZEPPELIN-1187 is useful for you. You can edit log4j.properties to add the followign line. This is helpful for me to debug the remote interpreter process. 
```
log4j.logger.org.apache.zeppelin.interpreter.remote=DEBUG
```

**Comment by doanduyhai** [comment]
@bzz 

I don't know why the tests fail on this error message, because this is indeed **a test which expects a failure** because `system.complex_table` does not exist, see below:

```java
    @Test
    public void should_error_describing_non_existing_table() throws Exception {
        //Given
        String query = "USE system;\n" +
                "DESCRIBE TABLE complex_table;";

        //When
        final InterpreterResult actual = interpreter.interpret(query, intrContext);

        //Then
        assertThat(actual.code()).isEqualTo(Code.ERROR);
        assertThat(actual.message()).contains("Cannot find table system.complex_table");
    }

```

**Comment by bzz** [comment]
@lresende shall we merge it or do you find @zjffdu suggestion to work and we can close it for now?

Thank you @doanduyhai ! Let's try to close\open it to trigger the CI and see if the failure presists

**Comment by lresende** [comment]
@bzz Based on the jira, the exception is causing some confusion with users, so I would merge, but it's up to the community, I am fine if there are objections with this change.

And let me force a build.

**Comment by lresende** [comment]
Now the issues seems to be related to build timeout ? 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by bzz** [comment]
RAT service taking too much input seems to be the issue here. I think it is reproducable on local env as under [ZEPPELIN-278](https://issues.apache.org/jira/browse/ZEPPELIN-278)

**Comment by lresende** [comment]
@bzz Are we merging this ? Or should i close it ?

**Comment by bzz** [comment]
@lresende sorry for huge communication delay :\

It's great improvement on ability to debug failures, merging to master ASAP, if there is no further discussion.

**Pull request closed without merging**
