### PR TITLE
[ZEPPELIN-2657] Add group search filter option to LdapRealm

### PR DESCRIPTION
**Pull request by VipinRathor**
### What is this PR for?
Problem:
While performing LDAP authentication, current Shiro module does a group=* search while trying to get group-to-role mapping for any LDAP user. On a large LDAP directory, this is a serious problem which might render RolesByGroup feature not working as expected.

Fix:
Currently while doing LDAP authentication, there is no available option to limit the group search results to the only groups that user is interested in. This bug addresses the same and adds group search filter to Shiro configuration for LdapRealm which will allow user to define a search filter and limit the group search results.

### What type of PR is it?
Improvement

### What is the Jira issue?
* [ZEPPELIN-2657] https://issues.apache.org/jira/browse/ZEPPELIN-2657

### How should this be tested?
1. Use org.apache.zeppelin.realm.LdapRealm as Shiro realm
2. In the shiro_ini configruation, define a group search filter like this:
ldapRealm.groupSearchFilter = (&(objectclass=groupofnames)(member={0}))
or 
ldapRealm.groupSearchFilter = (&(objectclass=groupofnames)(cn=zeppelin-users*))
3. Also define other LdapRealm parameters as necessary like rolesByGroup etc.
4. When an LDAP user, who is part of the group that matches filter above, logs in, then the roles are applied. If the LDAP user is not part these defined groups, then the roles are not applied.

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@VipinRathor can you setup your Travis for this? https://zeppelin.apache.org/contribution/contributions.html#continuous-integration

**Comment by VipinRathor** [comment]
@gss2002 & @weand,
Can you please help with review? Thanks.

**Comment by prabhjyotsingh** [comment]
Tried on local LGTM.

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
