### PR TITLE
[ZEPPELIN-4489] remove zeppelin.anonymous.allowed configuration

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This is a proposal for removing/disabling `zeppelin.anonymous.allowed` when Shiro is configured.
My Proposal in this JIRA is; let us remove this `zeppelin.anonymous.allowed`.
So, when Shiro is configured then Zeppelin server runs with all the auth configured, and if the user wants anonymous access then they should not configure Shiro.ini.

### What type of PR is it?
[Bug Fix | Improvement]

### What is the Jira issue?
* [ZEPPELIN-4489](https://issues.apache.org/jira/browse/ZEPPELIN-4489)

### How should this be tested?
* CI should be green.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? yes
* Does this needs documentation? yes

### CODE REVIEW

**Comment by zjffdu** [comment]
Getting rid of `zeppelin.anonymous.allowed` make sense for me. This property is really confusing. 
+1

**Comment by prabhjyotsingh** [comment]
Thanks for the review @zjffdu. Since this will change the way Zeppelin used to work before, where else should I change the doc? Or can that be handled at the time of release?

**Comment by zjffdu** [comment]
Thanks for reminding, we should add document here http://zeppelin.apache.org/docs/0.8.2/setup/operation/upgrading.html

**Comment by zjffdu** [comment]
LGTM, thanks @prabhjyotsingh , let's wait for the Ci pass

**Comment by zjffdu** [comment]
CI is passed, thanks @prabhjyotsingh

**Comment by prabhjyotsingh** [comment]
Sure, let go ahead and merge this.

**Pull request closed without merging**
