### PR TITLE
[ZEPPELIN-3169] Fix maven version set

### PR DESCRIPTION
**Pull request by necosta**
### What is this PR for?
Bug fix on changing Maven version (0.8.0-SNAPSHOT -> ?)

### What type of PR is it?
[Bug Fix | Hot Fix ]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3169

### How should this be tested?
* Run 'mvn versions:set -DprocessDependencies=false -DnewVersion=0.8.0-SNAPSHOT-123 -DgenerateBackupPoms=false'
* Run 'mvn clean package -DskipTests'
* Expect BUILD SUCCESS

### Questions:
* Does the licenses files need update? N
* Is there breaking changes for older versions? N
* Does this needs documentation? N

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by masyan** [comment]
LGTM

**Comment by necosta** [comment]
Jenkins looks happy. Let me know if you want me to force CI to run again. Thanks

**Comment by zjffdu** [comment]
Thanks @necosta will merge soon

**Pull request closed without merging**
