### PR TITLE
[ZEPPELIN-1650] Add mariadb, redshift configs and useful links to JDBC doc

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Add 2 JDBC configs and useful links to JDBC doc so that users can connect those backends easily :)

### What type of PR is it?

Documentation

### Todos
* [ ] - Task

### What is the Jira issue?

[ZEPPELIN-1650](https://issues.apache.org/jira/browse/ZEPPELIN-1650)

### How should this be tested?

See screenshots.

### Screenshots (if appropriate)

example_redshift
example_mariadb

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
I wanted to add drill settings in this PR but failed to test it. Could anyone recently try drill (1.8)?

**Comment by AhyoungRyu** [comment]
@1ambda Thanks for updating JDBC docs. I added more JDBC Driver docs & Maven repo urls for other examples as you did. Could you check  [https://github.com/1ambda/zeppelin/pull/1](https://github.com/1ambda/zeppelin/pull/1)? :)

**Comment by 1ambda** [comment]
@AhyoungRyu Thanks :) 

I merged it. Additionally, add a postgres section so that we can remove [seperated postgres doc](http://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/interpreter/postgresql.html) easily next time :)

**Comment by 1ambda** [comment]
@AhyoungRyu Updated postgres image :) Thanks again. 

CI is failing but it doens't related this PR i think.

**Comment by AhyoungRyu** [comment]
@1ambda Yeah the changes are looks good to me. Thanks again for taking care of the docs. Definitely will help the JDBC users.
Merge if there are no more discussions.

**Pull request closed without merging**
