### PR TITLE
[ZEPPELIN-759] Spark 2.0 support

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR implement spark 2.0 support based on #747.
This PR has approach from #980 which is reimplementing code in scala.

You can try build this branch

```
mvn clean package -Dscala-2.11 -Pspark-2.0 -Dspark.version=2.0.0-preview -Ppyspark -Psparkr -Pyarn -Phadoop-2.6 -DskipTests
```

### What type of PR is it?
Improvements

### Todos
* [x] - Spark 2.0 support
* [x] - Rebase after #747 merge
* [x] - Update LICENSE file
* [x] - Update related document (build)

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-759

### How should this be tested?

Build and try
```
mvn clean package -Dscala-2.11 -Pspark-2.0 -Dspark.version=2.0.0-preview -Ppyspark -Psparkr -Pyarn -Phadoop-2.6 -DskipTests
```

### Screenshots (if appropriate)
spark2

### Questions:
* Does the licenses files need update? yes
* Is there breaking changes for older versions? no
* Does this needs documentation? yes

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Now CI is green. Review this please.

CI profile for spark 2.0 force spark version `2.0.0-preview` instead of `2.0.0`, because of spark 2.0.0 is not yet released. If this PR merges before spark 2.0.0 release, i'll create a separate issue to change `2.0.0-preview` to `2.0.0`.

**Comment by bzz** [comment]
Looks great to me

**Comment by minahlee** [comment]
Shall we also change spark version in  https://github.com/apache/zeppelin/blob/master/r/pom.xml#L386 and https://github.com/apache/zeppelin/blob/master/r/pom.xml#L398 ?

**Comment by Leemoonsoo** [comment]
@minahlee I was trying to make 'zeppelin-spark' interpreter support spark 2.0 in this PR. If there're user demands, spark 2.0 support in 'zeppelin-zrinterpreter' can be addressed in separate issue.

**Comment by minahlee** [comment]
After I look close the pom files, I don't see clear reason why spark.version is specified in scala-2.11 and scala-2.10 profiles.
https://github.com/apache/zeppelin/blob/master/spark-dependencies/pom.xml#L347
https://github.com/apache/zeppelin/blob/master/r/pom.xml#L386
https://github.com/apache/zeppelin/blob/master/r/pom.xml#L398 

And I think it's always good to ship default spark version as the latest one. Can we also update below lines?
https://github.com/apache/zeppelin/blob/master/spark-dependencies/pom.xml#L39
https://github.com/apache/zeppelin/blob/master/spark/pom.xml#L41

**Comment by echarles** [comment]
Tested this with spark 2.0 and scala 2.11.
Spark 2.0 works well with scala, R and python.

@minahlee comment makes sense - we should ship the latest version.

**Comment by minahlee** [comment]
Changes looks good. Could you rebase to master?

**Comment by Leemoonsoo** [comment]
CI is green. Merge it to master and branch-0.6 if there're no more discussions

**Pull request closed without merging**
