### PR TITLE
ZEPPELIN-1227 change spark-2.0.0-preview to spark-2.0.0

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Change spark-2.0.0-preview to spark-2.0.0

### What type of PR is it?
Improvement

### Todos
* [x] - Update pom.xml and .travis.yml

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1227

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
+1

**Comment by bzz** [comment]
Looks great to me, modulo CI failure

**Comment by minahlee** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge to master and branch-0.6

**Pull request closed without merging**
