### PR TITLE
Alert message when trying to delete last paragraph.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR is for giving proper information to users and blocking unnecessary communication with zeppelin server when trying to delete last paragraph because the last paragraph can't be deleted.

### What type of PR is it?
Improvement 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-979

### How should this be tested?
You can try to remove last paragraph of a notebook.

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
tested.
LGTM +1

**Comment by corneadoug** [comment]
I would like to suggest a different approach:
Not showing the delete button if the paragraph is the last one.

It is also quite easy to do:
Just need to add `ng-hide="$last"` to the remove link in paragraph-control.html

screen shot 2016-06-10 at 3 43 12 pm

Since angular has both `$first` and `$last`, we could even remove 'Move Up' or 'Move Down' option depending on whether the paragraph is the first or the last.

**Comment by astroshim** [comment]
@corneadoug Thank you very much for your review and opinion. I'll follow your advice.

**Comment by minahlee** [comment]
@corneadoug I like the idea, but how do we want to handle paragraph deletion by keyboard shortcut in this case?

**Comment by corneadoug** [comment]
@minahlee Maybe then in that case it would be needed

**Comment by astroshim** [comment]
@minahlee @corneadoug Then we need two ways to solve this issue?

**Comment by corneadoug** [comment]
I guess both methods can cohabitate then

**Comment by astroshim** [comment]
Thank you for clarification.

**Comment by astroshim** [comment]
@corneadoug @minahlee I fixed the code to hide "Remove" menu on the last paragraph menu. please review.

**Comment by minahlee** [comment]
Tested, looks good. How about applying @corneadoug's opinion making the first paragraph not to show `Move Up`, last paragraph not to show `Move Down`?

**Comment by astroshim** [comment]
@minahlee I'll take care about that you mentioned. thanks.

**Comment by astroshim** [comment]
@minahlee Could you tell me how can i get your test failure?

**Comment by corneadoug** [comment]
@astroshim She posted the test failure.
My guess is that the Notebook has only one paragraph, therefore the xpath is on the last paragraph.
Since we removed the delete element from the last paragraph, the test fail.

The exact failing tests and the error lines:
```
ParagraphActionsIT.testRemoveButton:153
ParagraphActionsIT.testCreateNewButton:86
```

**Comment by astroshim** [comment]
@corneadoug Thank you for your kind explanation. 
I know the reason about the error but I couldn't reproduce the error even if i build like ```mvn clean package```. 
Did you build also like i did?

**Comment by corneadoug** [comment]
You need to trigger the selenium test locally, it doesn't by default without some configuration.
(TEST_SELENIUM="true" as env)
Otherwise you can just push your changes and let the CI do it

**Comment by astroshim** [comment]
@corneadoug Okay. Thank you!!

**Comment by corneadoug** [comment]
Tested Selenium Tests locally from original commit:
https://github.com/apache/zeppelin/pull/979/commits/6f181efa09f4d616ac66eec5641df954883af432

And it's working well.

I will create a flacky test issue on JIRA,
@astroshim Could you rewrite history back to the commit I just Mentioned? After that LGTM

**Comment by astroshim** [comment]
@corneadoug I really appreciate for your effort. Thank you. I reset my commits.

**Comment by corneadoug** [comment]
Merging if there's no more discussions

**Pull request closed without merging**
