### PR TITLE
Add force layout visualization in paragraphs for SQL queries

### PR DESCRIPTION
**Pull request by davidtzoor**
### What is this PR for?
Add force layout (graph) visualization to the existing set of visualizations in Zeppelin Web notp. 

### What type of PR is it?
[Feature]

### What is the Jira issue?
[ZEPPELIN-1011]

### How should this be tested?
The testes are incorporated within the existing test suite. 

### Screenshots (if appropriate)
eeffbb58-3238-11e6-92ea-148a4063d353

### Questions:
* Does the licenses files need update?
No.
* Is there breaking changes for older versions?
No.
* Does this needs documentation?
We can add some documentation explaining about the different fields that need to be selected in order to generate the force layout component.

### CODE REVIEW

**Comment by bzz** [comment]
@davidtzoor great to see new visualization! Could you rebase on top of the latest master please?

**Comment by davidtzoor** [comment]
@bzz Thanks! you mean to rebase the current `apache:master` to my forked repo (`datvidtzoor:master`), right? After I do that, what should I do?

**Comment by davidtzoor** [comment]
@bzz I have rebased my repo with the latest master.

**Comment by corneadoug** [comment]
@davidtzoor didn't go well.
Could you try to have your changes in a different branch and re-create a PR?

**Comment by felixcheung** [comment]
something like this might help: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by cloverhearts** [comment]
LGTM! +1
good visualize!

**Comment by corneadoug** [comment]
@davidtzoor Can you close this PR since there is a new one?

**Comment by davidtzoor** [comment]
closing this issue since new PR has been opened (#1024)

**Pull request closed without merging**
