### PR TITLE
[ZEPPELIN-921] Apply new mechanism to KnitR and RRepl

### PR DESCRIPTION
**Pull request by DrIgor**
### What is this PR for?
Applies new registration mechanism for R interpreter

### What type of PR is it?
[Refactoring]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-921

### How should this be tested?
Build zeppelin with R profile enabled and run several R snippets

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by DrIgor** [comment]
Needs this changes: #1937

**Comment by jongyoul** [comment]
I merged #1937. Can you rebase it onto master and make CI green?

**Comment by DrIgor** [comment]
Rebased on master and ran build.

I tried several times:

- https://travis-ci.org/apache/zeppelin/builds/197341657
- https://travis-ci.org/apache/zeppelin/builds/197539698
- https://travis-ci.org/apache/zeppelin/builds/197547341

CI is still red, but every time it had a different failure. I think they are not caused by my changes

**Comment by jongyoul** [comment]
@DrIgor The last failures looks related to this PR. Can you check it?
 - https://api.travis-ci.org/jobs/197657609/log.txt?deansi=true

**Comment by DrIgor** [comment]
@jongyoul sorry for late response!

I checked failure. It's related to PR but I don't know how to fix it

Build profile uses
```
$ export SCALA_VER="2.11"
$ export SPARK_VER="1.6.3"
```

`downloadSpark.sh` downloads spark prebuilt for scala 2.10. So we have incompatible versions of scala.

I tried to build spark 1.6 with scala 2.11 — R interpreter works fine. But spark does not provide such binary distribution.

Does Zeppelin support spark 1.6 with scala 2.11? Then we should provide binary spark distribution for this build profile. I think it affects not only R interpreter

This code https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/rest/AbstractTestRestApi.java#L152 exclude R interpreter during tests. But it doesn't work with new registration mechanist

**Comment by jongyoul** [comment]
Thanks for checking it. As you mentioned, we removed those kind of tests but we should take care of it because we couldn't break to install any of modules. Your comment makes sense to me and thank you for letting me know the scala version issue between them. LGTM and I'll merge it

**Pull request closed without merging**
