### PR TITLE
[ZEPPELIN-1390] SparkInterpreter does not work for Spark2 version of HDP 2.5

### PR DESCRIPTION
**Pull request by tae-jun**
### What is this PR for?
Spark2 version of HDP 2.5 is "2.0.0.2.5.0.0-1245". Currently, Zeppelin parses this version to integer 2002500, which is higher than version "2.0.0" (i.e. 200 in integer). Therefore, Zeppelin thinks it's not supported version and fail.

I fixed some codes to consider major, minor, and patch version. Now, version parsed using only first 3 numbers (major, minor, patch) and parsed into a 5-digit integer. For example, 2.0.0 -> 20000, 1.6.2 -> 10602, 1.10.1 -> 11001. This makes HDP 2.5 compatible, and also make it more robust than before. Since maybe Spark's minor version can be a 2-digit number in the future

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-1390](https://issues.apache.org/jira/browse/ZEPPELIN-1390)

### How should this be tested?
I added SparkVersion test codes.

### CODE REVIEW

**Comment by zjffdu** [comment]
@tae-jun Have you ever tried to start spark-shell to print the spark version in HDP 2.5 ? Because I think if the version is an issue, this should also happen in spark 1.6 in HDP 2.4

**Comment by tae-jun** [comment]
I upgraded HDP to 2.5 from 2.4 today. sc.version printed 1.6.1 when HDP 2.4 and now HDP 2.5 spark.version prints 2.0.0.2.5.0.0-1245

**Comment by Leemoonsoo** [comment]
@tae-jun Thanks for the contribution.

I think there're few more places related to this change

Pyspark interpreter
https://github.com/apache/zeppelin/blob/master/spark/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java#L181
https://github.com/apache/zeppelin/blob/master/spark/src/main/resources/python/zeppelin_pyspark.py#L109

SparkR interpreter
https://github.com/apache/zeppelin/blob/master/spark/src/main/java/org/apache/zeppelin/spark/ZeppelinR.java#L143
https://github.com/apache/zeppelin/blob/master/spark/src/main/resources/R/zeppelin_sparkr.R#L45

**Comment by tae-jun** [comment]
@Leemoonsoo Thanks for comment!

I made some changes.

How does it look?

Thanks again.

**Comment by felixcheung** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
@tae-jun, could you trigger ci (close / reopen pullrequest will trigger ci) and see if it passes?

**Comment by tae-jun** [comment]
@Leemoonsoo Yep, I did it :-)

**Comment by Leemoonsoo** [comment]
First 3 ci test profile fails with the same error.

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

I'm not sure this problem comes from this PR or not, but i think the problem should be resolved before we merge this PR.

@tae-jun, could you rebase or merge master and see how CI-test goes?

**Comment by tae-jun** [comment]
@Leemoonsoo Hi, thanks for your guide.

I merged master branch, but it failed again.

And I tried to build again via reopening, but it fails again as you see.

However, it seems like other PRs fail with the same error.

What should I do???

Thanks for comment ^^

**Comment by Leemoonsoo** [comment]
I think master branch has CI build problem. Let me try to fix it first.

**Comment by tae-jun** [comment]
Ok thanks

Let me know when it is done.

I will reopen PR :-)

**Comment by minahlee** [comment]
CI is green now. Shall we merge this guy?

**Comment by Leemoonsoo** [comment]
Let's merge!

**Comment by prabhjyotsingh** [comment]
Tested on HDP2.5, on executing both spark and pyspark `sc.version` prints `res0: String = 2.0.0.2.5.0.0-1245` and works as expected.
LGTM

**Comment by tae-jun** [comment]
Thanks everyone!

**Pull request closed without merging**
