### PR TITLE
[ZEPPELIN-4210] NotebookAuthorization does not need to synchronize cluster event

### PR DESCRIPTION
**Pull request by liuxunorg**
### What is this PR for?
Because NotebookAuthorization is used to give UpgradeNoteFileTool.
So NotebookAuthorization does not need to synchronize clusterEvent.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4210

### How should this be tested?
[CI Pass](https://travis-ci.org/liuxunorg/zeppelin/builds/553205871)

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by liuxunorg** [comment]
@zjffdu , @felixcheung Please help me review the code, Thanks!

**Comment by liuxunorg** [comment]
[CI Pass](https://travis-ci.org/liuxunorg/zeppelin/builds/556175850)
@zjffdu , @felixcheung Please help me review the code, Thanks!

**Comment by liuxunorg** [comment]
[CI Pass](https://travis-ci.org/liuxunorg/zeppelin/builds/556175850)
@zjffdu , @felixcheung Please help me review the code, Thanks!

**Comment by felixcheung** [comment]
I"m not familiar with this but change seem ok to me..

**Comment by liuxunorg** [comment]
Will merge if no more comments

**Pull request closed without merging**
