### PR TITLE
ZEPPELIN-3406 Travis build failure due to npm error

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
Travis build failure due to npm error
e.g: https://travis-ci.org/TinkoffCreditSystems/zeppelin/jobs/365002217

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3406

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by r-kamath** [comment]
https://travis-ci.org/r-kamath/zeppelin

**Comment by zjffdu** [comment]
Great，Thanks for the fixing @r-kamath

**Comment by zjffdu** [comment]
@r-kamath Is this due to changes in npm side or zeppelin side ? If it is due to npm itself then we need to backport to 0.8 as well

**Comment by r-kamath** [comment]
@zjffdu this is due to a change in npm. We need this go in 0.8 as well.

**Pull request closed without merging**
