### PR TITLE
[ZEPPELIN-1832] Fixed a bug in zombie process when Zeppelin stopped.

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
When Zeppelin stops, there is a problem.
Sometimes this happens to the test as well.
It is related to releasing the resources of the remote remote interpreter, and its order has been modified.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1832
### How should this be tested?
1. Zeppelin start
2. run paragraph for interpreter (for example, %spark println("Hello world")
3. Zeppelin stop
4. check to zombie process 
```
#jps 
```
When Zeppelin exits, the RemoteInterpreter process should not exist.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
@minahlee @AhyoungRyu 
Hello, could you please review for this pr?

**Comment by AhyoungRyu** [comment]
@cloverhearts Nice! Thanks for the patch. Let me try

**Comment by AhyoungRyu** [comment]
It works nicely. Thanks for the fixing @cloverhearts!

**Comment by soralee** [comment]
Test and It works very well!
It was really necessary for me. ! Thanks for taking care of it @cloverhearts

**Comment by cloverhearts** [comment]
@AhyoungRyu @soralee Thank you :)

**Comment by Leemoonsoo** [comment]
multiple ci test profile fails with the same error.

```
09:51:15,163 ERROR org.apache.zeppelin.interpreter.remote.RemoteInterpreterEventPoller:245 - Can't handle event RemoteInterpreterEvent(type:OUTPUT_UPDATE_ALL, data:{"noteId":"2C75F1GM3","paragraphId":"20170104-095114_1076613332","messages":[]})
java.lang.NullPointerException
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterEventPoller.run(RemoteInterpreterEventPoller.java:186)
09:51:15,226  INFO org.apache.zeppelin.interpreter.InterpreterGroup:145 - Close interpreter group 2C8ACKHEJ:shared_process
09:51:15,226  INFO org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess:121 - shutdown interpreter process
09:51:16,226 ERROR org.apache.zeppelin.interpreter.remote.AppendOutputRunner:68 - Wait for OutputBuffer queue interrupted: null
09:51:17,657  INFO org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess:131 - Exception in RemoteInterpreterProcess while synchronized dereference, can safely ignore exception while client.shutdown() may terminates remote process
09:51:17,660  INFO org.apache.zeppelin.interpreter.remote.RemoteInterpreterManagedProcess:164 - Interpreter process exited 0


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

@cloverhearts could you take a look?

**Comment by cloverhearts** [comment]
@Leemoonsoo Yes, I will :)

**Comment by soralee** [comment]
That's sounds good! I agree with @cloverhearts. 
In my opinion, first of all, the zombie process problem is very important so must be removed as soon as possible. Then we must gradually resolve other things!

Anyway, I tested again, it works as expected :+1:

**Comment by jongyoul** [comment]
@cloverhearts The last travis doesn't look related error.

**Comment by minahlee** [comment]
Thx for the fix. I will merge this one as temporary fix, but I will keep the jira issue open until we come up with better solution.

**Pull request closed without merging**
