### PR TITLE
[ZEPPELIN-5630] update to a safe version of atomix

### PR DESCRIPTION
**Pull request by huage1994**
### What is this PR for?
Update to a safe version of atomix
Update from current version (3.0.0-rc4) of atomix to currently recommended version (3.1.10)

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5630

### How should this be tested?
CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Reamer** [comment]
After correcting the tests and compiling, an entry in the following file is also required.
https://github.com/apache/zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE

**Comment by zjffdu** [comment]
@huage1994 CI is failed

**Comment by huage1994** [comment]
Thx for the review! It seems to take more time to update version of atomix, because some interface changed.

> @huage1994 CI is failed

**Comment by huage1994** [comment]
> After correcting the tests and compiling, an entry in the following file is also required. https://github.com/apache/zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE

Thx a lot! Get it

**Pull request closed without merging**
