### PR TITLE
[HOTFIX] Fix compile error caused by merging #1043

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Hotfix for compile error of master, branch-0.6 after merging #1043

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Let's merge this!

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by minahlee** [comment]
Thank you for taking a look. Merging it as hot fix

**Comment by prabhjyotsingh** [comment]
LGTM

**Pull request closed without merging**
