### PR TITLE
Fixed minor formatting issues preventing the full build

### PR DESCRIPTION
**Pull request by zinal**
### What is this PR for?
Fixed minor issues in Java files formatting to make maven-checkstyle-plugin happy

### What type of PR is it?
Improvement

### How should this be tested?
* Regular regressions tests

### Questions:
* Does the license files need to update?
* Is there breaking changes for older versions?
* Does this needs documentation?

No license updates, no breaking changes, no need for extra docs.

### CODE REVIEW

**Comment by Reamer** [comment]
I think it would be good if with this fix the checkstyle plugin is enabled.

**Comment by zinal** [comment]
> I think it would be good if with this fix the checkstyle plugin is enabled.

It seems to be enabled, at least it was complaining without the fixes when I followed the general build instructions from the [docs](https://zeppelin.apache.org/docs/0.10.1/setup/basics/how_to_build.html)

**Comment by Reamer** [comment]
I see. Which Maven command did you run?

**Comment by zinal** [comment]
> I see. Which Maven command did you run?

mvn clean package -DskipTests

**Comment by Reamer** [comment]
I am surprised that there are no errors in the CI. 
Do you see errors in the CI system? Maybe we should adjust the default build.

**Comment by Reamer** [comment]
Thank you, I can reproduce the issue. 
Can you change the Goal `package` to `verify` in the following line? Then the CI system should run checkstyle. Unfortunately the phase `package` is not enough.
https://github.com/apache/zeppelin/blob/1e9c7fd0496f13b73c26dc3eef254c90c4a70ee7/.github/workflows/core.yml#L486

**Review by Reamer — APPROVED** [review]

**Pull request merged**
