### PR TITLE
[ZEPPELIN-4871] Update Livy interpreter to 0.7.1

### PR DESCRIPTION
**Pull request by soicem**
### What is this PR for?
livy interpreter version upgrade

### What type of PR is it?
Improvement

### What is the Jira issue?
(https://issues.apache.org/jira/browse/ZEPPELIN-4871)

### How should this be tested?

- CI should pass

### Questions:
* Does the licenses files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by soicem** [comment]
I checked build and unittest succession of livy interpreter from my local env.  I also saw the codes releted to livy interpreter.  Please let me know if I have missed something or if there is something I need to see more.  Thank you !

cc. @jongyoul

**Comment by zjffdu** [comment]
Thanks for the contribution @soicem , the version here also needs update, https://github.com/apache/zeppelin/blob/master/.github/workflows/core.yml#L434

**Comment by soicem** [comment]
@zjffdu thanks for letting me know :)  I changed it right away !

**Review by jongyoul — APPROVED** [review]

**Comment by zjffdu** [comment]
Another place need to update, https://github.com/apache/zeppelin/blob/master/.github/workflows/core.yml#L407

**Comment by jongyoul** [comment]
@soicem Could you please handle the comment by @zjffdu ?

**Comment by soicem** [comment]
@zjffdu @jongyoul Oh, I changed it right away.  Thanks for the feedback! :)

**Comment by jongyoul** [comment]
@soicem I missed checking the result of CI. Could you please make another PR to fix the issue?

```
+ echo '.livy-dist does not have livy-0.7.1-incubating-bin downloading ...'
+ echo '0.7.1-incubating being downloaded from archives'
.livy-dist does not have livy-0.7.1-incubating-bin downloading ...
0.7.1-incubating being downloaded from archives
++ date +%s
+ STARTTIME=1659266977
+ download_with_retry https://dist.apache.org/repos/dist/release/incubator/livy/0.7.1-incubating/livy-0.7.1-incubating-bin.zip
+ local url=https://dist.apache.org/repos/dist/release/incubator/livy/0.7.1-incubating/livy-0.7.1-incubating-bin.zip
+ wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 3 https://dist.apache.org/repos/dist/release/incubator/livy/0.7.1-incubating/livy-0.7.1-incubating-bin.zip
--2022-07-31 11:29:37--  https://dist.apache.org/repos/dist/release/incubator/livy/0.7.1-incubating/livy-0.7.1-incubating-bin.zip
Resolving dist.apache.org (dist.apache.org)... 13.90.137.153
Connecting to dist.apache.org (dist.apache.org)|13.90.137.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-31 11:29:37 ERROR 404: Not Found.

Error: Process completed with exit code 8.
```

The URL of livy has been changed to `https://dist.apache.org/repos/dist/release/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-bin.zip`

**Comment by soicem** [comment]
@jongyoul OK, I will create another PR and fix the issue soon !

**Pull request merged**
