### PR TITLE
[Zeppelin 3388] Correcting documentation link to zeppelin-context documentation

### PR DESCRIPTION
**Pull request by sanjaydasgupta**
### What is this PR for?
A small change was needed in the documentation of the JDBC interpreter also, but had been missed.

The change required is the same as the change made in the documentation of the Shell interpreter (as seen [here](https://github.com/apache/zeppelin/commit/0c3260e91f4c1ec58e67856d466ea9cba89d0085#diff-5a017ebfb7e890a2b475f9c8c7844fb0))

### What type of PR is it?
[Documentation]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3388

### How should this be tested?
Documentation only.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No, this _is_ documentation.

### CODE REVIEW

**Comment by sanjaydasgupta** [comment]
Yes @felixcheung the other links are ok.

**Comment by felixcheung** [comment]
merging if no more comment

**Comment by sanjaydasgupta** [comment]
Hi @felixcheung could you release this into the next RC for 0.8.0?

Thanks.

**Comment by felixcheung** [comment]
@zjffdu can I merge this to branch-0.8?

**Comment by zjffdu** [comment]
sure，go ahead, @felixcheung

**Comment by felixcheung** [comment]
merged to master and 0.8

**Pull request closed without merging**
