### PR TITLE
[ZEPPELIN-1941] Fix cron job with release resource option dead lock

### PR DESCRIPTION
**Pull request by OopsOutOfMemory**
### What is this PR for?
There is a deadlock in concurrent cron job execution with release resource option.
`Scenario`:
Two notebook run with cron job that release resource after job finished.

In `Notebook.CronJob.execute()` method:

`T1. note.runAll(); // locked paragraphs(lock) and wait to interpreterSettings(lock)`

`T2. notebook.getInterpreterFactory().restart() //locked(interpreterSettings) and wait for paragraphs(lock) during jobAbort.`

This will trigger a deadlock that cause zeppelin hang.

### What type of PR is it?
[Bug Fix ]

### Todos
* [x] - Fix this by avoid acquire lock in job abort method.

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1941

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by jongyoul** [comment]
Thanks for the contribution. Can you make a test case for it?

**Comment by OopsOutOfMemory** [comment]
we already a test case for this https://github.com/apache/zeppelin/blob/9e75f5b50ac1573d423fa937b801df77d6a36f3c/zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java#L734

**Comment by OopsOutOfMemory** [comment]
It seems CI has a network issue
```
[ERROR] Error requesting archive.
[ERROR] Status: 503
[ERROR] Request options: {
[ERROR]   "uri": "https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2",
[ERROR]   "encoding": null,
[ERROR]   "followRedirect": true,
[ERROR]   "headers": {
[ERROR]     "User-Agent": "yarn/0.18.1 npm/? node/v6.9.1 linux x64"
[ERROR]   },
[ERROR]   "strictSSL": true
[ERROR] }
[ERROR] Response headers: {
[ERROR]   "cache-control": "no-cache",
[ERROR]   "connection": "close",
[ERROR]   "content-type": "text/html"
[ERROR] }
[ERROR] Make sure your network and proxy settings are correct.
```

**Comment by jongyoul** [comment]
Does this PR resolve flaky test that current master encounters?

**Comment by OopsOutOfMemory** [comment]
I'm not sure, this PR is intent to fix the dead lock issue.

**Comment by OopsOutOfMemory** [comment]
Flaky test may be another concurrency issue in scheduler execute jobs.

**Comment by OopsOutOfMemory** [comment]
@Leemoonsoo @jongyoul Any comments for this PR ?

**Comment by jongyoul** [comment]
LGTM, I saw your description and it makes sense to me.

**Pull request closed without merging**
