### PR TITLE
[ZEPPELIN-3189] NPE on paragraph run via API

### PR DESCRIPTION
**Pull request by necosta**
### What is this PR for?
Bugfix over NPE when running REST API command to run paragraph synchronously.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3189

### How should this be tested?
1. Build Zep (mvn clean package -DskipTests)
2. Start Zep
3. Run curl command in shell (curl -i -X POST http://localhost:8080/api/notebook/run/{noteId}/{paragraphId}

### Questions:
* Does the licenses files need update? N
* Is there breaking changes for older versions? N
* Does this needs documentation? N

### CODE REVIEW

**Comment by necosta** [comment]
Closed/Reopened to refresh GitHub...
Green CI: https://travis-ci.org/nokia/zeppelin/builds/332846355

**Comment by necosta** [comment]
ping @zjffdu , @Leemoonsoo , @1ambda 
Thanks

**Comment by Leemoonsoo** [comment]
Thanks @necosta for the fix.  LGTM

**Comment by zjffdu** [comment]
LGTM

**Pull request closed without merging**
