### PR TITLE
[HOTFIX] Restart button raises exception in interpreter side

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
This PR is the following one of #2140. It prevent from raising exception in interpreter side while closing interpreter.

### What type of PR is it?
[Hot Fix]

### Todos
* [x] - Remove open() while close()

### What is the Jira issue?
N/A

### How should this be tested?
N/A

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@jongyoul I try it in isolated mode per user, restart button seems still doesn't work.

**Comment by jongyoul** [comment]
@zjffdu Thanks, I'll test it with that mode.

**Comment by jongyoul** [comment]
@zjffdu Can you tell me which interpreter you use? In case of Spark, I found error occurs but it's kind of Spark issue because two separate "metastore_db" located in a same place.

**Comment by jongyoul** [comment]
@zjffdu I've tested it with PythonInterpreter and reproduced it didn't work properly. I'll fix them

**Comment by jongyoul** [comment]
@zjffdu I made a new PR(#2149) for fixing what you mention. Can you check that PR and test it?

**Comment by jongyoul** [comment]
@AhyoungRyu @Leemoonsoo tested it. Will merge it

**Pull request closed without merging**
