### PR TITLE
[HOTFIX] Exclude org/apache/zeppelin/scio/avro/* once at pom.xml

### PR DESCRIPTION
**Pull request by tae-jun**
### What is this PR for?
Previously on #1676, I excluded path **twice**. It's my mistake! @khalidhuseynov pointed that out (Thanks!).

### What type of PR is it?
Hot Fix

### How should this be tested?
Build with command `mvn clean package install -DskipTests -DskipRat`

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by khalidhuseynov** [comment]
LGTM!

**Comment by tae-jun** [comment]
@zjffdu @khalidhuseynov Thanks! 😄

**Comment by astroshim** [comment]
LGTM.

**Comment by Leemoonsoo** [comment]
LGTM and merge to master.

**Comment by tae-jun** [comment]
@astroshim @Leemoonsoo Thanks for review!

**Pull request closed without merging**
