### PR TITLE
[ZEPPELIN-1509] Bug of testcase path in .travis.yml

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes path of spark testcase.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1509

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by minahlee** [comment]
Nice catch! I think it is better to fix CI failures in this PR since it will break CI if we merge this. I am willing to help you if you need any :)

**Comment by astroshim** [comment]
Thank you @minahlee Please help me to solve PR problem.

**Comment by minahlee** [comment]
@astroshim #1483 is just merged, can you rebase master and see if CI failure on spark 1.1 and 1.2 is gone?

**Comment by astroshim** [comment]
@minahlee I just rebased. Thank you for your great efforts.

**Comment by minahlee** [comment]
CI failures looks irrelevant, merging it into master.
profile 2
```
[32m- should able to create AngularObject[0m
[32mAngularModel[0m
[32m- should able to update AngularObject[0m
[32mAngularModel[0m
[32m- should able to remove AngularObject[0m
[32mAngularModelTest:[0m
[32mAngularModel[0m
[32m- should able to create AngularObject[0m
[32mAngularModel[0m
[32m- should able to update AngularObject[0m
[32mAngularModel[0m
[32m- should able to remove AngularObject[0m
[32mAngularElemTest:[0m
[32mAngularElem[0m
[31m- should provide onclick method *** FAILED ***[0m
[31m  The code passed to eventually never returned normally. Attempted 1 times over 530.370455 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m
[32mAngularElem[0m
[32m- should print angular display directive only once in a paragraph[0m
[32mAngularElem[0m
[32m- should bind angularObject to ng-model directive[0m
[32mAngularElem[0m
[32m- should able to disassociate AngularObjects[0m
[32mAngularElem[0m
[32m- should allow access to InterpreterContext inside of callback function[0m
[32mAngularElem[0m
[32m- should able to be created from implicit conversion[0m
[32mAngularElemTest:[0m
[32mAngularElem[0m
[32m- should provide onclick method[0m
[32mAngularElem[0m
[32m- should print angular display directive only once in a paragraph[0m
[32mAngularElem[0m
[32m- should bind angularObject to ng-model directive[0m
[32mAngularElem[0m
[32m- should able to disassociate AngularObjects[0m
[32mAngularElem[0m
[32m- should allow access to InterpreterContext inside of callback function[0m
[32mAngularElem[0m
[32m- should able to be created from implicit conversion[0m
[36mRun completed in 2 seconds, 415 milliseconds.[0m
[36mTotal number of tests run: 18[0m
[36mSuites: completed 5, aborted 0[0m
[36mTests: succeeded 17, failed 1, canceled 0, ignored 0, pending 0[0m
[31m*** 1 TEST FAILED ***[0m
```

Profile 10
```
Tests run: 9, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 108.789 sec <<< FAILURE! - in org.apache.zeppelin.integration.ParagraphActionsIT
testWidth(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 19.995 sec  <<< FAILURE!
java.lang.AssertionError: New Width is : 4
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.apache.zeppelin.integration.ParagraphActionsIT.testWidth(ParagraphActionsIT.java:314)

testWidth(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 19.995 sec  <<< FAILURE!
java.lang.AssertionError: New Width is : 8
Expected: <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.rules.ErrorCollector$1.call(ErrorCollector.java:65)
	at org.junit.rules.ErrorCollector.checkSucceeds(ErrorCollector.java:78)
	at org.junit.rules.ErrorCollector.checkThat(ErrorCollector.java:63)
	at org.apache.zeppelin.integration.ParagraphActionsIT.testWidth(ParagraphActionsIT.java:314)
```

**Comment by felixcheung** [comment]
LGTM, would be great to see Spark profiles passing in CI...

**Comment by minahlee** [comment]
CI is green now, merge if there is no more discussion

**Comment by astroshim** [comment]
@minahlee Thanks.

**Pull request closed without merging**
