### PR TITLE
ZEPPELIN-2189. The order of dynamic forms should be the order that you create them

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
The order of dynamic forms should be the order that you create them. So I made the following 2 changes for this:
* change the type of forms in GUI from TreeMap to LinkedHashMap
*  remove orderBy in paragraph-parameterizedQueryForm.html

Besides, I also did some code refactoring. 

### What type of PR is it?
[Bug Fix | Improvement | Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2189

### How should this be tested?
Tested manually.

### Screenshots (if appropriate)
Before

After 

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
Yeah I saw this as well. Let me take a look :)

**Comment by zjffdu** [comment]
Thanks @AhyoungRyu for review, just fix a code style issue

**Comment by AhyoungRyu** [comment]
Tested and it works well now. Thanks for fixing it. LGTM

**Comment by zjffdu** [comment]
Change it to WIP for adding test.

**Comment by AhyoungRyu** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Merge into master and branch-0.7 if there are no more comments on this.

**Pull request closed without merging**
