### PR TITLE
[WIP][HOTFIX][ZEPPELIN-1286] CI for Spark 1.6 fails on master & all PRs

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Making CI green with spark 1.6

### What type of PR is it?
[Bug Fix | Hot Fix]

### Todos
* [x] - Set spark.version to test specific version of Spark

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1286

### How should this be tested?
CI should be green

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
Error occurs while building zeppelin-web. Building spark seems to be successful but I'll re-trigger it so that CI makes green

**Comment by jongyoul** [comment]
But the second trial fails. https://s3.amazonaws.com/archive.travis-ci.org/jobs/149707456/log.txt

**Comment by jongyoul** [comment]
The third. https://s3.amazonaws.com/archive.travis-ci.org/jobs/149722781/log.txt

**Comment by bzz** [comment]
All build failures are in zeppelin-web, while NPM dependency installation

```
INFO] bower@1.7.2 node_modules/bower
[INFO] â””â”€â”€ semver-utils@1.1.1
[ERROR] npm ERR! argv "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! Callback called more than once.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/zeppelin/zeppelin-web/npm-debug.log
[INFO] ------------------------------------------------------------------------
```

@jongyoul if you want to debug it in this PR - we could add `cat zeppelin-web/npm-debug.lo` to [.travis.yaml](https://github.com/apache/zeppelin/blob/master/.travis.yml#L98)

If not, this patch looks great to me and solves the issue, so we can merge and handle web in separate JIRA issue.

@jongyoul what do you think?

**Comment by minahlee** [comment]
Let's merge it

**Comment by jongyoul** [comment]
@bzz @Leemoonsoo try to fix zeppelin-web issues. How about adding `cat ...` in that PR? #1285

**Pull request closed without merging**
