### PR TITLE
[ZEPPELIN-5241] Typos in spark tutorial

### PR DESCRIPTION
**Pull request by omrisk**
### What is this PR for?
Fixing some typos from the tutorials notebook

### What type of PR is it?
Documentation

### Todos
* [x] - Task

### What is the Jira issue?
[ZEPPELIN-5241](https://issues.apache.org/jira/browse/ZEPPELIN-5241)

### How should this be tested?
* Standard CI tests
### Questions:
* Does the licenses files need update? - no
* Is there breaking changes for older versions? - no
* Does this needs documentation? - no

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks for the contribution @omrisk 
PR LGTM

**Comment by zjffdu** [comment]
Will merge if no more comment

**Comment by omrisk** [comment]
Thanks @zjffdu! Happy to help.
I see that there are still failing build tests.
Couldn't find an open ticket or PR to fix this, is there a way I could help with that ?

**Comment by zjffdu** [comment]
@omrisk Failure of `Neo4jCypherInterpreterTest` is fixed by a recent PR #4050 (You can could rebase this PR to fix it)
but there still some flaky tests in selenium test (frontend test) that needs to fix, but I think it would not be easy, so we could do it separately. BTW, if you are interested in making contribution to zeppelin, you can pick up any tickets in jira, and we will help you in making contribution.

**Comment by omrisk** [comment]
@zjffdu , thanks, could you please merge this?
I'll try to find a beginner friendly jira issue :)

**Comment by zjffdu** [comment]
Will merge it soon, and here's a list of jiras for new contributors
https://issues.apache.org/jira/issues/?jql=labels%20%3D%20newbie%20and%20project%20%3D%20ZEPPELIN

**Pull request closed without merging**
