### PR TITLE
[ZEPPELIN-2730]  compare with maxLength after getting all file status

### PR DESCRIPTION
**Pull request by gaoyang143**
### What is this PR for?
when set hdfs.maxLength to a lower value like 10, get result no such file or directory

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* https://issues.apache.org/jira/browse/ZEPPELIN-2730

### How should this be tested?
set hdfs.maxLength to 10, if it can get right result

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by gaoyang143** [comment]
@felixcheung already added test

**Comment by gaoyang143** [comment]
@Leemoonsoo please reivew this

**Comment by Leemoonsoo** [comment]
@gaoyang143 Thanks for the fix.
Could you try setup [CI](http://zeppelin.apache.org/contribution/contributions.html#continuous-integration) and see it passes the CI?

**Comment by gaoyang143** [comment]
@Leemoonsoo already setup CI

**Comment by Leemoonsoo** [comment]
Thanks @gaoyang143 for the fix.
LGTM and merge to master if no further discussions.

**Pull request closed without merging**
