### PR TITLE
[ZEPPELIN-2409] DON'T block body scrolling in results scrollbar

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

DON'T block body scrolling in results scrollbar. 
See the GIFs below.

### What type of PR is it?
[Improvement]

### Todos

NONE

### What is the Jira issue?

[ZEPPELIN-2409](https://issues.apache.org/jira/browse/ZEPPELIN-2409)

### How should this be tested?

1. Create multiple paragraphs including scrollbar in result. For example,

```
bank.printSchema
bank.show()
```

```
select * from bank limit 1000
```

2. Scrolling down, up

#### Before

2407_before

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
@soralee Please help review this.

**Comment by soralee** [comment]
@1ambda Let me test and come back here :slightly_smiling_face:

**Comment by Leemoonsoo** [comment]
@1ambda Can this be applied to table visualization, too?

**Comment by soralee** [comment]
Tested and it's work nicely!

**Comment by 1ambda** [comment]
@soralee Thanks for review.

@Leemoonsoo I update code and GIF in PR description.

**Comment by Leemoonsoo** [comment]
Tested. Works really nicely! really cool!

LGTM and merge to master if no further discussions!

**Pull request closed without merging**
