### PR TITLE
[DOC] Update documentation: JDK 1.7 -> 1.8

### PR DESCRIPTION
**Pull request by tae-jun**
### What is this PR for?
Zeppelin is built with JDK 1.8 since 0.7.1 as far as I know. But it is still 1.7 on [installation documentation](https://zeppelin.apache.org/docs/0.7.1/install/install.html). Polina Marasanova pointed that out! Thanks!

This PR should be merged into master and 0.7.X in my opinion.

### What type of PR is it?
Documentation

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by 1ambda** [comment]
Hi, @tae-jun Thanks for the contribution. AFAIK,
 
- Zeppelin is built with JDK 1.7 still for release binary. 
- 0.7.1 is built with JDK 1.8 unintentionally.

will be appreciated if someone also verifies JDK version.

**Comment by tae-jun** [comment]
Oh sorry I didn't see the last comment [here](https://issues.apache.org/jira/browse/ZEPPELIN-2405?focusedCommentId=15973784&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15973784).

Then should I close this PR or just merge into only 0.7.1?

**Comment by 1ambda** [comment]
> I think it's better build artifact using jdk7 on 0.7.2

I think we can close this PR. 0.7.2 would like to be built w/ JDK 7 according to the comment.

**Comment by tae-jun** [comment]
OK. Thanks for the review @1ambda!

I'm closing myself 😄

**Pull request closed without merging**
