### PR TITLE
Fix zeppelin-web development mode

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?

After https://github.com/apache/zeppelin/pull/2373, zeppelin-web dev mode does not work properly.
Dev mode always ask user login (even if authentication is turned off) and any login attempt will fail. So it makes difficult to develop front-end.

This PR fixes problem by not adding `X-Requested-With: XMLHttpRequest` header in dev mode.

### What type of PR is it?
Bug Fix

### Todos
* [x] - Fix devmode

### How should this be tested?
run zeppelin-web dev mode and see if you can login / open notebook

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
Tested (dev mode), works fine, LGTM

**Comment by prabhjyotsingh** [comment]
Few days I too was thinking about this, thanks for the fix. LGTM.

**Comment by 1ambda** [comment]
Tested locally, LGTM.

**Comment by soralee** [comment]
Tested and LGTM

**Comment by Leemoonsoo** [comment]
Thanks @tinkoff-dwh  @prabhjyotsingh @1ambda @soralee  for review.

Merge to master

**Pull request closed without merging**
