### PR TITLE
[ZEPPELIN-2711] basic metrics for paragraphs & notebook view/create/run

### PR DESCRIPTION
**Pull request by herval**
### What is this PR for?

This exposes JMX metrics for a few operations on Zeppelin. The first step here is to expose them via JMX, then later introduce a JSON endpoint (which would make it easier to integrate these metrics on common monitoring systems such as Prometheus, Graphite, Influx, etc

I'm putting this out as WIP before finishing the tests & JSON bits in order to kick-off any design discussion and address comments sooner than later

### What type of PR is it?
Feature

### Todos
* [x] - Tests
* [x] - JSON endpoint

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2711

### How should this be tested?
- Run Zeppelin
- Open `localhost:8080/api/metrics` for the JSON metrics
- Use `jconsole` and browse `org.apache.zeppelin.metrics` for the JMX metrics

### Questions:
* Does the licenses files need update?
Yes

* Is there breaking changes for older versions?
No

* Does this needs documentation?
Yes

### CODE REVIEW

**Comment by herval** [comment]
This is the basic set of functionality needed to start monitoring some common metrics - Comments & observations welcome!

**Comment by herval** [comment]
Hi folks - any thoughts on this approach?

**Comment by Leemoonsoo** [comment]
Apologies for late response. @herval It looks great.

While this PR adds dependencies,

```
[INFO] +- org.weakref:jmxutils:jar:1.9:compile
[INFO] +- org.hdrhistogram:HdrHistogram:jar:2.1.4:compile
```

We'll need add their license into `https://github.com/apache/zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE`. Could you update license file?

**Comment by jongyoul** [comment]
Hi, I have a simple question. AFAIK, dropwizard metrics are more popular and have powerful features. Have you consider it?

**Comment by herval** [comment]
@jongyoul good q. I tried another stats libraries I've seen used around (airlift), but had a hard time reconciling dependencies, so went with the smallest footprint one + implementing the servlet myself. It looks like metrics-core is [pretty self contained too](https://mvnrepository.com/artifact/com.codahale.metrics/metrics-core/3.0.2) - I'd be fine giving it a try, if folks prefer it for some reason (I'm honestly not super up-to-speed on what's popular these days, so I'm glad to defer this decision :-))

**Comment by jongyoul** [comment]
Agreed. we can improve this feature after adopting one.

**Comment by jongyoul** [comment]
Can you address with LICENSE issue moon mentioned?

**Pull request closed without merging**
