### PR TITLE
[ZEPPELIN-2297] improvements  to jdbc autocompleter

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
PR contains some improvements for completion (JDBC Interpreter):
- types of completion
- display of long values
- refactoring of search of completions
- uniqness of completions with type `keyword`
- updating data in completer by pressing `Ctrl + .`
- setting the schema filter to generate completions
- fix highlighting code when used not default data source

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2297

### How should this be tested?
try to work with new completer

### Screenshots (if appropriate)
**1. Types of completion**

**2. Display of long values**
before
2297_before_long_caption
after
2297_after_long_caption

**3. Refactoring of search of completions. Updating data in completer by pressing `Ctrl + .`**
before
2297_before_refactoring_search
after
2297_after_refactoring_search

**4. uniqness of completions with type keyword**
before
2297_before_uniq
after
2297_after_uniq

**5. fix highlighting code when used not default data source**
before
2297_before_inrpret_name
after
2297_after_inrpret_name

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Great improvement! LGTM
\cc @cloverhearts @astroshim

**Comment by astroshim** [comment]
Looks awesome to me!
It worked like a charm.

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by Leemoonsoo** [comment]
merge to master if no further comments

**Pull request closed without merging**
