### PR TITLE
ZEPPELIN-1985 Remove user from pig tutorial note

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Should remove the user from pig tutorial note, otherwise it can not be seen in anonymous mode.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1985

### How should this be tested?
Tested it in anonymous mode

### Screenshots (if appropriate)
 
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@AhyoungRyu Please help review

**Comment by felixcheung** [comment]
LGTM

**Comment by felixcheung** [comment]
merging if no more comment

**Comment by AhyoungRyu** [comment]
Sorry for my late response. LGTM

**Comment by AhyoungRyu** [comment]
wait wait, seems the below part was removed by mistake in #1830. There is no part to download `bank.csv` from S3. 
```
%sh

wget https://s3.amazonaws.com/apache-zeppelin/tutorial/bank/bank.csv
hadoop fs -put bank.csv
```
Could you check this one please? 

And actually even if the each paragraph's user stamped as `user1`, I can run this note as `anonymous`(deactivate shiro) or `user2`(activate shiro but another user). But anyway the thing that the all paragraphs' in tutorial note default user is `user1` a bit wired :)

**Comment by zjffdu** [comment]
Thanks @AhyoungRyu for noticing that. I have added the missing part. BTW,

**Comment by AhyoungRyu** [comment]
@zjffdu Thanks! LGTM again :)

**Pull request closed without merging**
