### PR TITLE
[ZEPPELIN-411] JDK8 support

### PR DESCRIPTION
**Pull request by DmytroShkvyra**
### What is this PR for?
Build, test and run with JDK8

### What type of PR is it?
Improvement and Documentation

### Todos
N/A

### What is the Jira issue?
[ZEPPELIN-411]

### How should this be tested?
Travis, test with maven:
export MAVEN_OPTS="-Xmx2g -XX:MaxMetaspaceSize=1024m" && mvn clean verify -Drat.skip=true

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? - No
* Is there breaking changes for older versions? - Older versions can run with JDK8
* Does this needs documentation? - Documentation updated

### CODE REVIEW

**Comment by DmytroShkvyra** [comment]
Could anybody who has write access merge .travis.yml ?

**Comment by jongyoul** [comment]
In case that you encounter conflicts, you have to rebase your changes onto the base branch you start working on. AFAIK, ASF doesn't allow write permission through Github.

**Comment by jongyoul** [comment]
And concerning your contribution, we discussed it before and concluded it's too early to move JDK8. If you think it's right time to move on, please start discussion again in dev@ and user@

**Comment by DmytroShkvyra** [comment]
@jongyoul Should I close ZEPPELIN-411 as "wont fix"?

**Comment by jongyoul** [comment]
You don't have to do it because we eventually will move to further JDK version

**Comment by DmytroShkvyra** [comment]
@jongyoul May be make sense just create PR only for try moving to JDK8 and test this with Travis? Anyway nobody will not merge it to zeppelin without approve.

**Comment by jongyoul** [comment]
I'm not sure who think what now, I just let you know the history. If you really want to move JDK8, open discussion and reach a "consensus" with community first. I think moving to JDK8 doesn't have any technical hurdle but needs to do it with Apache way.

**Pull request closed without merging**
