### PR TITLE
[ZEPPELIN-3665] fix notebook name

### PR DESCRIPTION
**Pull request by Savalek**
### What is this PR for?
Name of notebook incorrectly displayed due to text direction.

Bug Fix

### What is the Jira issue?
[ZEPPELIN-3665](https://issues.apache.org/jira/browse/ZEPPELIN-3665)

### example:
Path: `2_Folder/NoteName`
#### Before
before

#### After
after

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Tagar** [comment]
If there is a very long "folder/subfolder1/subfolder" part, wouldn't this change always to 
display only "folder/subfolder1/subfolder..." and not a notebook name?

**Comment by Savalek** [comment]
@Tagar, thanks! I missed it. I added a property "unicode-bidi: plaintext;". Now it should work fine.

**Comment by felixcheung** [comment]
it might help if you include a before / after screen shots?

**Comment by Savalek** [comment]
@felixcheung, I added scren shots.

**Comment by felixcheung** [comment]
cool
merging if no more comment

**Pull request closed without merging**
