### PR TITLE
ZEPPELIN-1456: Flaky Test: AuthenticationIT

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This started happening after ZEPPELIN-1144, https://github.com/apache/zeppelin/pull/1330.
This test (testGroupPermission) is to validate the group related permission on a notebook.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Fix CI

### What is the Jira issue?
* [ZEPPELIN-1456](https://issues.apache.org/jira/browse/ZEPPELIN-1456)

### How should this be tested?
CI xxx.10 (selenium) should be green

### Questions:
* Does the licenses files need update? n/a
* Is there breaking changes for older versions? n/a
* Does this needs documentation? n/a

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
any possible reason or explanation for its failing? it seems to be erring consistently

**Comment by prabhjyotsingh** [comment]
Sure, so basically #1330 solve the problem: "If logged in user does not have Read and Write permission for a notebook, user should not see the notebook in the zeppelin home page."

And the place where this test case used to fail was trying to click on the link on notebook's homepage. Since, after the fix of above issue the link on which it tried to find and click is not available anymore, it fails consistently.

**Comment by prabhjyotsingh** [comment]
Build #7259.6 (https://travis-ci.org/apache/zeppelin/builds/161286976) fails for 

```
Failed tests: 
  InterpreterRestApiTest.testSettingsCRUD:118 Test delete method:
Expected: HTTP response <200> from /api/interpreter/setting/2BXVE2G5P
     but: got <500> Server Error

Tests run: 45, Failures: 1, Errors: 0, Skipped: 0
```


Build #7256.9 (https://travis-ci.org/apache/zeppelin/builds/161274366) fails for 

```
[31m  The code passed to eventually never returned normally. Attempted 1 times over 186.970371 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m
[32mAngularElem[0m
[36mTests: succeeded 17, failed 1, canceled 0, ignored 0, pending 0[0m
[31m*** 1 TEST FAILED ***[0m
```

But in both xxxxx.10 (Selenium) passes.

**Comment by khalidhuseynov** [comment]
makes sense, LGTM

**Comment by Leemoonsoo** [comment]
Thanks @prabhjyotsingh!
LGTM

**Comment by corneadoug** [comment]
CI failure on this PR is irrelevant and failing on only build profile.
We might want to open a JIRA issue for it, because that build profile normally have `-DskipTest`
But seems to fail on a test.

Merging this one quickly to have other PR's CI green

**Comment by prabhjyotsingh** [comment]
Thank you @corneadoug.

**Pull request closed without merging**
