### PR TITLE
[ZEPPELIN-1421] Fix dead link in docs/README.md

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
There is a dead link in [docs/README.md](https://github.com/apache/zeppelin/blob/master/docs/README.md). 

It should be `https://zeppelin.apache.org/docs/latest/` not `https://zeppelin.apache.org/docs/latest`

### What type of PR is it?
Bug Fix

### What is the Jira issue?
[ZEPPELIN-1421](https://issues.apache.org/jira/browse/ZEPPELIN-1421)

### How should this be tested?
 - Before [https://zeppelin.apache.org/docs/latest](https://zeppelin.apache.org/docs/latest)
 - After [https://zeppelin.apache.org/docs/latest/](https://zeppelin.apache.org/docs/latest/)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM. BTW, I found the docs of 0.7.0-SNAPSHOT is broken, is it a known issue ?
e.g. 
https://zeppelin.apache.org/install/install.html

**Comment by AhyoungRyu** [comment]
@zjffdu Ah it's wired. In `0.7.0-SNAPSHOT`, all the link in the dropdown menu are broken. It should be [https://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/install/install.html](https://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/install/install.html) not [https://zeppelin.apache.org/install/install.html](https://zeppelin.apache.org/install/install.html).

**Comment by kavinkumarks** [comment]
LGTM with the dead link in README.md

Also, shouldn't we need to fix the broken image in shell interpreter doc?

**Comment by AhyoungRyu** [comment]
@kavinkumarks 
The shell interpreter docs in github is just a source not a real docs page. The real one is deployed at [https://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/interpreter/shell.html](https://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/interpreter/shell.html). 

The below tag is for the broken image.
```
<img src="{{BASE_PATH}}/assets/themes/zeppelin/img/docs-img/shell-example.png" />
```
Since it contains `{{BASE_PATH}}`, github can't recognize this variable. That's the reason why the image is broken. Zeppelin is using [Jekyll](https://jekyllrb.com/) to build the documentation site. (See [here](https://zeppelin.apache.org/contribution/documentation.html) for more details). Only Jekyll can recognize the variable. 
Just FYI, that kind of variables(e.g. `BASE_PATH`, `ASSET_PATH`) are defined in [docs/_config.yml](https://github.com/apache/zeppelin/blob/master/docs/_config.yml) :)

**Comment by kavinkumarks** [comment]
@AhyoungRyu thanks for the information but we can use the path https://github.com/apache/zeppelin/blob/master/docs/assets/themes/zeppelin/img/docs-img/shell-example.png to access the image as used in other interpreters.There is no need to use BASE_PATH variable.What do you say?

Thanks,
Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by AhyoungRyu** [comment]
@kavinkumarks Ah right. Although they are just source for the real documentation website, someone might be confused like you. So I checked all docs pages under `/docs`, some link and image path contains `{{BASE_PATH}}`. I removed them and changed to the actual path. Could you check again? :)

**Comment by kavinkumarks** [comment]
@AhyoungRyu the changes look good!

Thanks,
Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by AhyoungRyu** [comment]
@zjffdu Just FYI
>I found the docs of 0.7.0-SNAPSHOT is broken, is it a known issue ?

This issue was resolved today. `docs/0.7.0-SNAPSHOT` site works well like before :)
@kavinkumarks Thanks!

Merging to master if there is no further discussion

**Comment by zjffdu** [comment]
Thanks @AhyoungRyu

**Comment by corneadoug** [comment]
Tested, Merging it

**Pull request closed without merging**
