### PR TITLE
[ZEPPELIN-1091] Disable ace editor's showSettingsMenu in paragraph.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR prevent to show the ace editor's showSettingMenu screen.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1091

### How should this be tested?
Type "Ctrl+." on your paragraph.

### Screenshots (if appropriate)
  - before
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by corneadoug** [comment]
On Mac OSx the shortcut is CMD+,
Tested LGTM

**Comment by astroshim** [comment]
Is this PR going to be merged?

**Comment by corneadoug** [comment]
@astroshim Can you rebase it?

**Comment by astroshim** [comment]
@corneadoug I just rebased. Thanks.

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
