### PR TITLE
[ZEPPELIN-3978] Change Jetty Server to use QueuedThreadPool and make it configurable

### PR DESCRIPTION
**Pull request by fred521**
### What is this PR for?
By default Jetty Server only supports 200 threads.
On our daily use cases, we normally have more than 100 users on the single Zeppelin Server, which will create more than 200 threads in Jetty.

That could cause slowness or stuck because users could not receive WebSocket message.

Add configurable param feature to scale up the performance for Single Zeppelin Server whenever needs it

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3978
[ZEPPELIN-3978]

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
can you take a look at the test failures? https://travis-ci.org/fred521/zeppelin/builds/486180306

**Comment by felixcheung** [comment]
can you update the PR title? should it say "Change Jetty to use threadpool and make it configurable"

**Comment by zjffdu** [comment]
Thanks @fred521 Could you add these configuration into `zeppelin-site.xml.template`

**Comment by fred521** [comment]
> can you update the PR title? should it say "Change Jetty to use threadpool and make it configurable"

Yes, I updated, thanks

**Comment by fred521** [comment]
> Thanks @fred521 Could you add these configuration into `zeppelin-site.xml.template` ?

yep, updated it, thanks

**Comment by fred521** [comment]
> can you take a look at the test failures? https://travis-ci.org/fred521/zeppelin/builds/486180306

checked it and re-run for a few times, each time actually taking for 30mins to 1 hour.
My code changes shouldn't break any unit test, I guess there are configurations not match to the VM box.

And I feel that will stop a lot of contributors, can Apache Zeppelin Community improve this?

Otherwise, new contributors will feel wasting time to spend effort here.

cc @Leemoonsoo @zjffdu

**Comment by Leemoonsoo** [comment]
https://github.com/apache/zeppelin/pull/3296 probably helps. @zjffdu right?

**Comment by zjffdu** [comment]
@fred521 I think ZEPPELIN-3957 solve this issue, Could you do a rebase ? And I create another ticket to improve it as well (ZEPPELIN-3983)

**Comment by fred521** [comment]
> @fred521 I think ZEPPELIN-3957 solve this issue, Could you do a rebase ? And I create another ticket to improve it as well (ZEPPELIN-3983)

Yeah, thanks, finnnnnnally, passed all

**Comment by zjffdu** [comment]
Awesome, thanks @fred521 LGTM

**Pull request closed without merging**
