### PR TITLE
[ZEPPELIN-2716] Change the default value of zeppelin.livy.displayAppInfo to true

### PR DESCRIPTION
**Pull request by jerryshao**
### What is this PR for?

Since it is quite useful to expose the application info for user to monitor and debug, so here propose to enable "zeppelin.livy.displayAppInfo" to true as default.

### What type of PR is it?

Improvement

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-2716

### How should this be tested?

Manual verification.

### CODE REVIEW

**Comment by jerryshao** [comment]
CC @zjffdu , please help to review, thanks!

**Comment by zjffdu** [comment]
Thanks @jerryshao  LGTM

**Comment by jerryshao** [comment]
There's no failure in my local test, please help to check.

**Comment by jerryshao** [comment]
Finally pass the UT @zjffdu , please review again.

**Comment by zjffdu** [comment]
Thanks @jerryshao LGTM will merge it if no more discussion.

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by jerryshao** [comment]
Thanks guys for your review, seems there's always some UT failures. I will reopen this PR to try again.

**Comment by zjffdu** [comment]
Failed test is not related, will merge it if no more discussion.

**Pull request closed without merging**
