### PR TITLE
[ZEPPELIN-5683] upgrade commons-compress and commons-io due to security concerns

### PR DESCRIPTION
**Pull request by pjfanning**
### What is this PR for?

Related to https://issues.apache.org/jira/browse/ZEPPELIN-5683

commons-compress 1.20 has CVEs - see https://mvnrepository.com/artifact/org.apache.commons/commons-compress

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?

* https://issues.apache.org/jira/browse/ZEPPELIN-5683

### How should this be tested?
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @pjfanning Could you update the PR description?

**Comment by pjfanning** [comment]
@zjffdu is the change I made to the PR description ok?

**Comment by zjffdu** [comment]
@pjfanning PR description LGTM, but could you create a separate jira ticket for it. Usually, each PR is associated with one jira ticket. You can create ticket under [ZEPPELIN-4657](https://issues.apache.org/jira/browse/ZEPPELIN-4657) as sub-task.

**Comment by pjfanning** [comment]
I created ZEPPELIN-5683

**Comment by zjffdu** [comment]
PR LGTM, thanks @pjfanning

**Pull request merged**
