### PR TITLE
[ZEPPELIN-1398] Use relative path for search_data.json

### PR DESCRIPTION
**Pull request by lresende**
### What is this PR for?
Use relative path for search_data.json

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [ZEPPELIN-1398](https://issues.apache.org/jira/browse/ZEPPELIN-1398)

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@lresende Wow super fast! That was my bad. I should've thought about the relative path. Thank you for the quick fix and LGTM :)

**Comment by Leemoonsoo** [comment]
Thanks @lresende for contribution.
I have tested this patch, but i still get the same error.

How to test

1) build `gh-pages` (website) branch

```
bundle exec jekyll build --safe
mv _site /tmp/zeppelin_website
```

2) build this patch (docs) and copy it under docs/0.7.0-SNAPSHOT of website

```
cd docs
bundle exec jekyll build --safe
mkdir /tmp/zeppelin-website/docs
mv _site /tmp/zeppelin_website/0.7.0-SNAPSHOT
```

3) start httpserver 

```
cd /tmp/zeppelin_website
python -m SimpleHTTPServer
```

And browse localhost:8000, select 0.7.0-SNAPSHOT doc and try search

**Comment by lresende** [comment]
Thanks for checking @Leemoonsoo , I have followed your steps and provided an updated fix.
Here are the results on my local env.

zeppelin search

**Comment by Leemoonsoo** [comment]
Tested and LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no more discussions

**Comment by AhyoungRyu** [comment]
@Leemoonsoo I tested and also checked the `search_data.json` issue has gone. But just noticed that the searched docs link has path problem as well. Let me configure out.

**Comment by AhyoungRyu** [comment]
@lresende I fixed the another wrong path issue and pushed the patch to your Zeppelin repo. Could you check [https://github.com/lresende/incubator-zeppelin/pull/4](https://github.com/lresende/incubator-zeppelin/pull/4) out? :)

**Comment by AhyoungRyu** [comment]
All the issues are addressed i think. 

IDK the exact reason, but some CI tests are failed with the below unrelated reason. 

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

and in the Selenium test

```
INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 15.898 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [  5.505 s]
[INFO] Zeppelin: Display system apis ...................... FAILURE [  2.439 s]
[INFO] Zeppelin: Spark dependencies ....................... SKIPPED
[INFO] Zeppelin: Spark .................................... SKIPPED
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.675 s
[INFO] Finished at: 2016-09-02T23:15:27+00:00
[INFO] Final Memory: 37M/419M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project zeppelin-display_2.10: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-display_2.10
```

**Comment by AhyoungRyu** [comment]
@lresende Can you close and reopen this PR to re-trigger CI?

**Comment by corneadoug** [comment]
@AhyoungRyu we don't have any Selenium tests on the docs, so it should be unrelated

**Comment by AhyoungRyu** [comment]
@corneadoug I just wanna see the green light :)

I'm merging this one if there is no more discussions.

**Pull request closed without merging**
