### PR TITLE
rename r directory to 2BWJFTXKJ

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
Rename "R" directory to "2BWJFTXKJ" under notebook directory to make it look like all other notebooks.

### What type of PR is it?
[Refactoring]

### Todos
* [x] - Rename

### What is the Jira issue?
* N/A

### How should this be tested?
goto  $ZEPPELIN_HOME/notebook directory, under this there should be no "R" directory.
On starting zeppelin-server, the existing notebook should be listed.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@echarles I'm assuming there was no specific reason to keep name of this directory as "R" and hence, renaming this to look like any other notebook.

**Comment by echarles** [comment]
@prabhjyotsingh yes, assumption is correct. At the time of the R interpreter dev, I was used to manually rename the note folder and edit the json to set the id the same value.

This PR takes it back to the default layout (didn't test it, but checked that the id value in the json was also correct).

LGTM

**Comment by prabhjyotsingh** [comment]
Sure, Thank you. Will merge this if no more discussion.

**Comment by Leemoonsoo** [comment]
Shell we update https://github.com/apache/zeppelin/blob/master/notebook/r/note.json#L1011, too?

**Comment by prabhjyotsingh** [comment]
Yes, I did both, rename the directory and https://github.com/prabhjyotsingh/zeppelin/blob/5993506b77be84d71ab730c2965572edd73e870e/notebook/2BWJFTXKJ/note.json#L1041

**Comment by Leemoonsoo** [comment]
Ah I missed the change. LGTM

**Pull request closed without merging**
