### PR TITLE
[ZEPPELIN-2460] Highlight active line in editor

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Highlight active line.

### What type of PR is it?
[Improvement]

### Todos
* [x] - Added ui-ace option
* [x] - Fix css for paragraph control not to be overrided by active line 

### What is the Jira issue?

[ZEPPELIN-2460](https://issues.apache.org/jira/browse/ZEPPELIN-2460)

### How should this be tested?

1. Build: `mvn clean package -DskipTests; ./bin/zeppelin-daemon.sh restart`
2. Open a note and write some text.

### Screenshots (if appropriate)

2460_active_line

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
@zjffdu Could you help review?

**Comment by zjffdu** [comment]
Awesome @1ambda I love this feature. +1

**Comment by 1ambda** [comment]
Good! What about others?

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
This PR makes unnecessary margin above the Editor inside of Paragraph.

before
image

after
image

@1ambda Could you restore this margin to original?

**Comment by 1ambda** [comment]
@Leemoonsoo Hi, Thanks for the feedback. 

- it is actually intended. otherwise highlight color will override the paragraph setting menus. 
- let me find an another way (e.g applying `z-index`)

**Comment by Leemoonsoo** [comment]
Yeah, that was my guess. I think keeping layout unchanged is more important than prevent overlapping paragraph control and text editor.

**Comment by 1ambda** [comment]
@Leemoonsoo Are you working on this? or writing a commit to rollback layout only?

**Comment by 1ambda** [comment]
@Leemoonsoo I did some experiments to revert the original layout while keeping highlights. But I think it takes a time to fix. So here are few options. 

(A) revert 2356 and then reimplement the highlighting line feature considering original layout later.
(B) keep current layout and refine designs so that new layout goes along with other components.

And #2386 is for `(B)` while fixing some bugs. Could you consider `B` as well?

**Comment by Leemoonsoo** [comment]
@1ambda Layout change impact user experiences a lot and i'd like to be more prudent on change.

I have created PR for reverting it. https://github.com/apache/zeppelin/pull/2409

**Pull request closed without merging**
