### PR TITLE
[ZEPPELIN-2426] Improve graph setting DOMs

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Improve graph setting DOMs. Refer the attached screenshots.

### What type of PR is it?
[Improvement]

### Todos

* [x] - columnselector setting
* [x] - pivot setting

### What is the Jira issue?

[ZEPPELIN-2426](https://issues.apache.org/jira/browse/ZEPPELIN-2426)

### How should this be tested?

1. Display a table.
2. Click charts including scatter chart. (written with columnselector transformation)

#### Before: Pivot

image

#### After: Pivot

image

#### Before: Columnselector

image

#### After: Columnselector

image

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
CI script can't parse `=` in the branch name. 

- https://travis-ci.org/1ambda/zeppelin/builds/230940304

**Comment by 1ambda** [comment]
CI failed but irrelevant.

**Comment by 1ambda** [comment]
@soralee please help review this.

**Comment by 1ambda** [comment]
branch name was updated to make CI pass

- https://github.com/apache/zeppelin/pull/2340

**Comment by soralee** [comment]
Of course! Let me test #2340 out!

**Pull request closed without merging**
