### PR TITLE
[ZEPPELIN-5768] Remove scio interpreter

### PR DESCRIPTION
**Pull request by inkkim**
### What is this PR for?
Removing an interpreter unused by retirement

### What type of PR is it?
Refactoring
*Please leave your type of PR only*

### Todos
* [X] -  Remove scio interpreter and related things from the repository

### What is the Jira issue?
[ZEPPELIN-5768](https://issues.apache.org/jira/browse/ZEPPELIN-5768)

### How should this be tested?
CI
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need to update? Yes, Edited
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes, Edited

### CODE REVIEW

**Review by jongyoul — APPROVED** [review]

**Comment by zjffdu** [comment]
@inkkim Could you resolve the conflicts first?

**Comment by inkkim** [comment]
@zjffdu  Yes, It was resolved.

**Comment by jongyoul** [comment]
@inkkim Sorry for bothering you but could you please resolve the conflict again? We are contributing interpreter maintenance issues recently so it can make conflicts again and again. I'm sorry to make you uncomfortable.

**Comment by inkkim** [comment]
@jongyoul Yes, It was resolved again : )

**Comment by jongyoul** [comment]
@zjffdu Let me merge it after finishing CI

**Pull request merged**
