### PR TITLE
[Zeppelin-1161] Revert precise execution time

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
It had been pointed out in the mailing list that after https://github.com/apache/zeppelin/pull/862, the execution time was changed to humanized fashion, while we would want to keep something more precise in that case.

This PR is rolling back to the old precise time for execution time.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1161

### How should this be tested?
Run a paragraph, after it is finished, it should show: `Took x seconds.` instead of `Took a few seconds` (or Hours, Minutes, Sec)

### Screenshot
screen shot 2016-07-13 at 2 19 45 pm

### Questions:
* Does the licenses files need update? Yes
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@corneadoug Wasn't it intended behaviour because of [https://github.com/apache/zeppelin/pull/862#issuecomment-221474937](https://github.com/apache/zeppelin/pull/862#issuecomment-221474937)? Anyway I prefer to show the precise execution time even if it shows such as `3600 seconds` 👍

**Comment by corneadoug** [comment]
@AhyoungRyu No, that discussion was about the elapsed time.
Right, for long one, maybe we should show something else than seconds. I will modify that.

**Comment by corneadoug** [comment]
@AhyoungRyu Made modifications and added screenshot

**Comment by AhyoungRyu** [comment]
@corneadoug more graceful! Thanks for taking care of this 👍

**Comment by AhyoungRyu** [comment]
@corneadoug When I build this PR in my local, i got this jscs warnings. 

screen shot 2016-07-13 at 3 21 18 pm

**Comment by corneadoug** [comment]
I'm not sure why CI is not green, triggering it once more

**Comment by SachinJanani** [comment]
@corneadoug Will this changes also be available in 0.6.1 ?

**Comment by corneadoug** [comment]
@SachinJanani There should be a thread about 0.6.1.
If we want it to be part of it, I guess it should be added to  https://issues.apache.org/jira/browse/ZEPPELIN-1203

**Comment by SachinJanani** [comment]
@corneadoug Yes you are right.

**Comment by bzz** [comment]
Looks great to me, and CI is green now!

**Comment by corneadoug** [comment]
Merging it now!

**Pull request closed without merging**
