### PR TITLE
[ZEPPELIN-2591] Show user info in spark job description

### PR DESCRIPTION
**Pull request by karuppayya**
### What is this PR for?
Show user info in spark job description in spark UI.
With this info on spark UI, we will be able to find which user's job took most time, which users job is currently consuming the resources etc

### What type of PR is it?
improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2591

### How should this be tested?
Run a spark job(scala, python, sql, R) , check the spark UI jobs page.
The job should display the username in its description.

### Screenshots (if appropriate)
screen shot 2017-05-27 at 15 41 30
Check the description column

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by karuppayya** [comment]
@felixcheung Thanks for the feedback.
Not sure if i got your question.
I will try to elaborate more on the change
The userinfo will give a picture of what is run/being run by whom  and its duration, in the spark application.(Currently, we display **zeppelin**)
The spark web UI will list all jobs, with this user information.

**Comment by karuppayya** [comment]
Ready for reviewing @Leemoonsoo @zjffdu @felixcheung

**Comment by Leemoonsoo** [comment]
Thanks @karuppayya for the improvement. LGTM

**Comment by jongyoul** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge to master if no further comment.

**Comment by karuppayya** [comment]
@Leemoonsoo @jongyoul  can this PR be merged?

**Pull request closed without merging**
