### PR TITLE
[ZEPPELIN-1193] Update Node JS related dependencies to avoid RegExp DoS

### PR DESCRIPTION
**Pull request by lresende**
### What is this PR for?

Update Node JS related dependencies to avoid intermittent build issues that suggest updates to avoid RegExp DoS
### What type of PR is it?

[Bug Fix]
### Todos
- [update minimatch] - Force minimatch to version 3.0.2 and up
### What is the Jira issue?
- [ZEPPELIN-1193](https://issues.apache.org/jira/browse/ZEPPELIN-1193)

### CODE REVIEW

**Comment by bzz** [comment]
CI is failure [logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/145344524/log.txt) is not relevant and is tracked in [ZEPPELIN-862](https://issues.apache.org/jira/browse/ZEPPELIN-862)
```
Running org.apache.zeppelin.rest.ZeppelinSparkClusterTest
13:25:00,290  INFO org.apache.zeppelin.rest.AbstractTestRestApi:98 - Staring test Zeppelin up...
...
13:26:20,423  INFO org.apache.zeppelin.socket.NotebookServer:1248 - Job 20160717-132620_2044341447 is finished
Spark version detected 1.6.1
13:26:20,459  INFO org.apache.zeppelin.notebook.Paragraph:254 - run paragraph 20160717-132620_1544010668 using r org.apache.zeppelin.interpreter.LazyOpenInterpreter@4495b079


No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

\cc @corneadoug @felizbear for review

**Comment by corneadoug** [comment]
@lresende we still get the warning from before
(you can see it in the CI logs)

**Comment by bzz** [comment]
So what do you guys suggest we do @corneadoug @lresende ?

**Comment by lresende** [comment]
I am with limited internet access for the next week, so if anyone want to give it a try on continuing this I am fine, otherwise I can continue when I am back.

**Comment by bzz** [comment]
@corneadoug did you have a chance to look into this one? Or would it require a too much of testing if done all together, what do you think?

**Comment by corneadoug** [comment]
Didn't look into it,

If updating node/npm is supposed to remove this warning, then something is wrong with its install or its usage during the build.

I'm also not really familiar on how the build system install node/npm and if they run the install one or the global one.

**Comment by bzz** [comment]
I do not think that node\npm version update are relevant - I was under impression that it's all about dependency version update.

**Comment by bzz** [comment]
I guess we better close this guy, or is it still WIP?

**Pull request closed without merging**
