### PR TITLE
[ZEPPELIN-1744] replace to movement for paragraph in job menu

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
We should move to editable paragraph move in job menu
currently, moved to readonly mode

### What type of PR is it?
Bug Fix

### Todos
- [x] - fix location address

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1744

### How should this be tested?
click to your paragraph item in job menu.

#### Before
movebefore

#### After
movefix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by astroshim** [comment]
Working well. LGTM!

**Comment by cloverhearts** [comment]
ping

**Comment by cloverhearts** [comment]
Could you please review for this pr?

**Comment by AhyoungRyu** [comment]
Tested and it works well. LGTM 👍

**Comment by AhyoungRyu** [comment]
Will merge this into master if there are no more comments.
@cloverhearts Thanks for your effort to keep maintaining job management :)

**Pull request closed without merging**
