### PR TITLE
[ZEPPELIN-3089] Create user folders under Trash folder

### PR DESCRIPTION
**Pull request by yu74n**
### What is this PR for?
In the situation where multi users a create notebook, "Empty Trash" button next to "Trash" folder on Top page is not working because "Empty Trash" button tries to delete all notebooks in Trash folder. which includes notebook no owner and no writer permission.

For resolving this issue, create a user folder under Trash folder, and "Empty Trash" button deletes all notebooks in a user folder, while "Restore" button restore all notebooks in a user folder.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-3089

### How should this be tested?
1. Login as user 'A' and create a notebook 'A'
2. Move notebook 'A' to Trash
3. Login as user 'B' and create a notebook 'B'
4. Move notebook 'B' to Trash
5. Click 'Empty Trash' button next to 'Trash' folder

### Screenshots (if appropriate)
screen_shot_2017-12-05_at_00_59_05

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by yu74n** [comment]
Yes, the default is anonymous. 
Deleted files will be moved under  ~Trash/anonymous/ folder.

**Comment by tinkoff-dwh** [comment]
A note can be used by a group. 
If user 'A' deletes a note, then the note will be "hided" and it will be hard for user 'B' to find this note.

Our practice to have its own separate folder for each group and each user.

**Comment by felixcheung** [comment]
this https://github.com/apache/zeppelin/pull/2695#issuecomment-349882841 is a good point...

**Comment by yu74n** [comment]
Whether a user can find the notebook in trash or not is based on permission of the notebook, then If user 'B' has properly permission for the notebook deleted by user 'A', user 'B' can find the notebook in trash.
However, I find some issues in this PR. For example, user 'A' delete a notebook, then user 'B' restore the notebook from trash. In this PR, even if user 'B' has 'owner' permission for the notebook, cannot do that.

**Comment by felixcheung** [comment]
what's the next step then?

**Comment by prabhjyotsingh** [comment]
I have created a new PR https://github.com/apache/zeppelin/pull/2872. Let me know if that makes sense, I can close that if required. Have created new as this was stale for 3+ months.

**Pull request closed without merging**
