### PR TITLE
[ZEPPELIN-1070]: Inject Credentials in any Interpreter-Code - Master

### PR DESCRIPTION
**Pull request by jpmcmu**
### What is this PR for?

This PR is a re-submission of the original ZEPPELIN-1070 PR. The original PR seems to be abandoned and I am currently creating custom builds of Zeppelin with the ZEPPELIN-1070 PR included so I am interested in getting the PR merged. I am submitting two PRs one for 0.8X branch and one that includes fixes for merge conflicts to the master branch.

Original PR Description:

> This PR enables a generic syntax for inserting credentials. A username can be inserted by $[user.entry] where "entry" is the name of the credential. A password can be inserted by $[password.entry].
> To avoid output of the password all occurences of the password-String in the Interpreter-output will be replaced by "###". This should not be a really secure feature (since the runner of the notebook knows the password anyway), but it should avoid accidential exposure of the used passwords by any sort of interpreter 

### What type of PR is it?
Feature

### Todos
* [ ] - Documentation

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1070

### How should this be tested?
Unit tests included in PR

### Questions:
* Does the licenses files need update? **No**
* Is there breaking changes for older versions? **Only in very unlikely circumstances. IE: code that matched {user.VALID_CREDENTIAL_ENTITY} or {password.VALID_CREDENTIAL_ENTITY}.**
* Does this needs documentation? **Yes**

### CODE REVIEW

**Comment by zjffdu** [comment]
@jpmcmu Could you update this PR to add supporting local property and docs ?

**Comment by jpmcmu** [comment]
@zjffdu Local property support and docs have been added. I also fixed an issue in the credential injector where passwords with $ or / would cause an exception. I will create a Jira to back port that fix to the 0.8x branch since that PR already has been pulled.

**Comment by zjffdu** [comment]
Thanks @jpmcmu  It looks likes you didn't configure your travis, could you configure that so that the the CI can be enabled ? See guideline here. https://zeppelin.apache.org/contribution/contributions.html#continuous-integration

**Comment by zjffdu** [comment]
ping @jpmcmu

**Comment by zjffdu** [comment]
ping @jpmcmu

**Comment by jpmcmu** [comment]
@zjffdu Sorry for the drop in communication. I will get travis configured for my account and fix the conflict on the 0.8.X PR

**Comment by zjffdu** [comment]
@jpmcmu sorry for response, Could you paste the travis build link here ? Need to make sure CI pass before merging.

**Comment by jpmcmu** [comment]
@zjffdu Added your fix for the test interactions and reran the CI: https://travis-ci.org/jpmcmu/zeppelin/builds/604480943. Two failures but they don't look like they are related to these changes to me

**Comment by zjffdu** [comment]
Thanks @jpmcmu will merge it soon

**Comment by zjffdu** [comment]
@jpmcmu I have merged this PR, what is your apache account ? I will assign the ticket to you.

**Comment by zjffdu** [comment]
@jpmcmu Test is failed on master, could you help check it ?

https://travis-ci.org/apache/zeppelin/jobs/604759403
```
Failed tests: 
  ParagraphTest.credentialReplacement:393 
Wanted but not invoked:
interpreter.interpret(
    "val x = "usr={user.ent}&pass={password.ent}"",
    <any>
);
-> at org.apache.zeppelin.notebook.ParagraphTest.credentialReplacement(ParagraphTest.java:393)
 
However, there were other interactions with this mock:
interpreter.getClassName();
-> at org.apache.zeppelin.notebook.ParagraphTest.credentialReplacement(ParagraphTest.java:392)
 
interpreter.getInterpreterGroup();
-> at org.apache.zeppelin.notebook.ParagraphTest.credentialReplacement(ParagraphTest.java:392)
```

**Comment by jpmcmu** [comment]
@zjffdu Sure, I will take a look at the test failure. My apache account user: jpmcmu

**Comment by zjffdu** [comment]
@jpmcmu Any update ?

**Comment by zjffdu** [comment]
@jpmcmu Do you have bandwidth on this ? If not, I will temporally disable the unit test.

**Pull request closed without merging**
