### PR TITLE
[ZEPPELIN-3350] Don't allow set cronExecutionUser

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This PR just does a quick fix this security issue. 
1. Remove the setting cron user in frontend
2. Run the note via owner.

### What type of PR is it?
[Bug Fix ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3350

### How should this be tested?
* Manually tested

### Screenshots (if appropriate)
screen shot 2018-04-09 at 3 04 06 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@prabhjyotsingh @felixcheung Could you help review this ? Thanks

**Comment by weand** [comment]
@zjffdu are you sure this works when logged out? i followed the call stack and I'm wondering if there would happen NPE if no AuthenticationInfo is present:
org.apache.zeppelin.notebook.Note.runAll(AuthenticationInfo, boolean)
> org.apache.zeppelin.notebook.Paragraph.execute(boolean) : Line 353
> org.apache.zeppelin.notebook.Paragraph.setAuthenticationInfo(AuthenticationInfo) : Line 209 << NPE

**Comment by zjffdu** [comment]
@weand Do you see any issue when logged out ?

**Comment by weand** [comment]
not directly when logged out. instead the NPE happens when Zeppelin gets restartet and next cron runs before the note was run manually, which is a frequent use case IMHO.
> ERROR [2018-04-12 21:11:00,024] ({DefaultQuartzScheduler_Worker-1} QuartzScheduler.java[schedulerError]:2425) - Job (note.2DBFZ9GGT threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException: while trying to invoke the method org.apache.zeppelin.user.AuthenticationInfo.getUser() of a null object loaded from local variable 'authenticationInfo']
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException: while trying to invoke the method org.apache.zeppelin.user.AuthenticationInfo.getUser() of a null object loaded from local variable 'authenticationInfo'
	at org.apache.zeppelin.notebook.Paragraph.setAuthenticationInfo(Paragraph.java:209)
	at org.apache.zeppelin.notebook.Paragraph.execute(Paragraph.java:353)
	at org.apache.zeppelin.notebook.Note.run(Note.java:678)
	at org.apache.zeppelin.notebook.Note.runAll(Note.java:659)
	at org.apache.zeppelin.notebook.Note.runAll(Note.java:648)
	at org.apache.zeppelin.notebook.Notebook$CronJob.execute(Notebook.java:936)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more

**Comment by zjffdu** [comment]
Thanks @weand I have created ZEPPELIN-3404 for it

**Comment by zjffdu** [comment]
Thanks @weand I have created ZEPPELIN-3404 for it

**Pull request closed without merging**
