### PR TITLE
[ ZEPPELIN-1259 ] create ace.editor configuration manager service object

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?

https://github.com/apache/zeppelin/pull/1218
Establish a foundation to personalize the code editor settings.
Remove and set of ace.editor included in paragraph.controller.js.
### What type of PR is it?

Improve
### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-1259
### Questions:
- Does the licenses files need update? no
- Is there breaking changes for older versions? no
- Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
@corneadoug 
please, can you review for this pr?
i divided to  https://github.com/apache/zeppelin/pull/1218 pr.

**Comment by cloverhearts** [comment]
ping

**Comment by corneadoug** [comment]
@cloverhearts Sorry for the delay, I will take a look soon.

**Comment by cloverhearts** [comment]
@corneadoug You're welcome, Thank you!

**Comment by cloverhearts** [comment]
This feature is not mergeable.

**Pull request closed without merging**
