### PR TITLE
[ZEPPELIN-1490]  pass subject while persisting note on running status change

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
This PR makes sure correct subject passed to `note.persist`. The subject is obtained from the paragraph level `authInfo` based on the job running.

### What type of PR is it?
Bug Fix

### Todos
* [x] - pass correct subject

### What is the Jira issue?
[ZEPPELIN-1490](https://issues.apache.org/jira/browse/ZEPPELIN-1490)

### How should this be tested?
CI is green

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Could you make CI green?

**Comment by khalidhuseynov** [comment]
@Leemoonsoo done

**Comment by khalidhuseynov** [comment]
ping

**Comment by bzz** [comment]
Looks good to me. CI is green now.

What do you think, @Leemoonsoo  ?

**Comment by khalidhuseynov** [comment]
there could be another option of casting `Job` into `Paragraph` if the job passed in here is in reality `instanceof` Paragraph. maybe @Leemoonsoo @jongyoul could comment on it more

**Comment by khalidhuseynov** [comment]
@Leemoonsoo changed it to extract from incoming job, that should be normally an instance of Paragraph.

**Comment by khalidhuseynov** [comment]
similar approach was used as a part of #1265 to address this issue and is merged already, closing this one

**Pull request closed without merging**
