### PR TITLE
[ZEPPELIN-3047] Let browser remember login and password

### PR DESCRIPTION
**Pull request by mephi42**
### What is this PR for?
It makes Zeppelin login window compatible with Firefox password manager, as explained here: https://stackoverflow.com/questions/18586938/remember-password-with-angularjs-and-ng-submit

### What type of PR is it?
Improvement

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3047

### How should this be tested?
* Open login window in Firefox, type anything. A suggestion to save username and password should appear.

### Questions:
* Does the licenses files need update? - No
* Is there breaking changes for older versions? - No
* Does this needs documentation? - No

### CODE REVIEW

**Comment by felixcheung** [comment]
this looks reasonable but it is going to work the same in all other browsers?

**Comment by mephi42** [comment]
After some tinkering I managed to make it work in Firefox, Chrome and Safari on Mac.

**Comment by mephi42** [comment]
Improved the implementation: before it used form hiding for Chrome, and now it simply changes that action, which is not used anyway.

Also made sure that even though this change removes the code from the newly added "enter from username" change, the functionality still works: one can use enter from both username and password fields in order to submit the form.

**Comment by Leemoonsoo** [comment]
Thanks @mephi42 for the improvement.

Here's message from CI

```
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
And then make sure 'Build branch updates' option is enabled in the settings https://travis-ci.org/mephi42/zeppelin/settings.

To trigger CI after setup, you will need ammend your last commit with
git commit --amend
git push your-remote HEAD --force

See http://zeppelin.apache.org/contribution/contributions.html#continuous-integration.
```

Could you try setup CI and see if everything goes green?

**Comment by mephi42** [comment]
Looks better this time, but one of sub-builds has timed out. I will push a dummy change to regtigger it.

**Pull request closed without merging**
