### PR TITLE
Groovy Interpreter for Apazhe Zeppelin [ZEPPELIN-2176]

### PR DESCRIPTION
**Pull request by dlukyanov**
### What is this PR for?
Groovy Interpreter

### What type of PR is it?
Feature 

### Todos
* [ Tests ] - Task
* [ Documentation ] - Task

### What is the Jira issue?
[ZEPPELIN-2176]

### How should this be tested?
Follow the groovy interpreter documentation samples

### Questions:
* Does the licenses files need update? YES
* Is there breaking changes for older versions? NO
* Does this needs documentation? YES

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@dlukyanov Is this WIP or ready for review? If it's WIP, then could you update the title to sth like "[WIP][ZEPPELIN-2196] Groovy interpreter"? It'll be helpful to other reviewers to recognize this PR's status. You can remove `WIP` whenever you think it's done :)

**Comment by AhyoungRyu** [comment]
And I think the other interpreter's PR can be helpful to you (e.g. A PR for BigQuery Interpreter: #1170 ). Especially [this comment](https://github.com/apache/zeppelin/pull/1170#issuecomment-232215164) :)

**Comment by dlukyanov** [comment]
Hello, can somebody help me to understand jenkins failure

> Build step 'Execute shell' marked build as failure
> Putting comment on the pull request
> Finished: FAILURE

**Comment by felixcheung** [comment]
Please see https://zeppelin.apache.org/contribution/contributions.html#continuous-integration for setting up CI.

**Comment by dlukyanov** [comment]
@felixcheung , 
it seems that jenkins job looking for travis build under the author, but i made branch under organization... are there any restrictions about author/organization?
and another point - seems there are troubles at travis-ci,i can't see any logs (error while trying to fetch the log), jobs like hanged... https://travis-ci.org/char-com-ua/zeppelin/builds/206271422
any suggestions?

**Comment by felixcheung** [comment]
hmm, I don't know about organization @Leemoonsoo 
as for log, travis was having problems yesterday, perhaps you can try again?

**Comment by Leemoonsoo** [comment]
I've made a patch #2094 to make jenkins check repository under organization. Once #2094 is merged, then Jenkins will able to check this PR build status correctly.

**Comment by dlukyanov** [comment]
@Leemoonsoo I see that #2094 is closed but I still have a problem with build
Should I move from org to user?

```
++ awk '{print $3}'
++ git log -n 1
++ grep '^Merge:'
+ COMMIT=826d1ef
+ '[' -z 826d1ef ']'
+ sleep 30
+ python ./travis_check.py dlukyanov 826d1ef
[2017-03-12 08:59:14] Author: dlukyanov, commit: 826d1ef
[2017-03-12 08:59:14] --------------------------------
[2017-03-12 08:59:19] Get build status ...
[2017-03-12 08:59:19] Can't find build for commit 826d1ef from dlukyanov
Build step 'Execute shell' marked build as failure
```

**Comment by Leemoonsoo** [comment]
Could you try rebase or merge master to this PR, so this PR branch includes update on `travis_check.py` that #2094 made?

**Comment by dlukyanov** [comment]
Closing this pull request because fork under organization can't be checked by jenkins job for now (or smth wrong with my hands))

Created new fork [#2135]
And new pull request [https://github.com/apache/zeppelin/pull/2135]

**Pull request closed without merging**
