### PR TITLE
[HOTFIX][ZEPPELIN-1240] Removed interpreter properties are restored

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Fixing the bug that users cannot delete some interpreter settings from interpreter tab.

### What type of PR is it?
[Bug Fix | Hot Fix]

### Todos
* [x] - Changed `update` to `set`

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1240

### How should this be tested?
1. Make new interpreter via interpreter tab
1. remove some properties

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
@Leemoonsoo I fixed it. Review it, please.

**Comment by Leemoonsoo** [comment]
Thanks for the fix. Tested and LGTM!

**Comment by jongyoul** [comment]
I'll trigger the CI one more, and merge it

**Comment by minahlee** [comment]
Confirm that bug is gone. @jongyoul Could you rebase before merge?

**Comment by jongyoul** [comment]
Rebased it

**Comment by bzz** [comment]
Looks great to me.

CI failure:
```
[INFO] Zeppelin: web Application .......................... FAILURE [02:13 min]
...
[INFO] Running 'grunt build --no-color' in /home/travis/build/apache/zeppelin/zeppelin-web
[INFO] Running "jscs:all" (jscs) task
[INFO] >> 32 files without code style errors.
[INFO] 
[INFO] Running "jscs:test" (jscs) task
[INFO] >> 6 files without code style errors.
[INFO] 
[INFO] Running "eslint:all" (eslint) task
[INFO] Warning: Cannot find module './utils' Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.
[INFO] 
```

**Comment by jongyoul** [comment]
@Leemoonsoo @minahlee Could you please test it?

**Comment by minahlee** [comment]
Tested, looks good to me. I have one question. Seems like the issue exists both in `master` and `branch-0.6` branch, will this patch be applicable to branch-0.6 or shall we create another PR targeting branch-0.6?

**Comment by jongyoul** [comment]
@minahlee Isn't it available to merge this PR into branch-0.6?

**Comment by jongyoul** [comment]
@minahlee I've made a new PR for branch-0.6 #1274

**Comment by minahlee** [comment]
@jongyoul Thanks for the quick response! I will test out #1274 too

**Pull request closed without merging**
