### PR TITLE
[ZEPPELIN-5473] Enable z.show for R

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

Enable `z.show` in `%r.ir` to make it consistent across languages. Unit test and docs are added.

### What type of PR is it?
[Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5473

### How should this be tested?
* Ci pass and manually tested

### Screenshots (if appropriate)
image

image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by cuspymd — APPROVED** [review]
Looks good!!

**Comment by zjffdu** [comment]
Thanks for the review @cuspymd Will merge if no more comment

**Comment by tecgie** [comment]
Can you add a logic to check if the max result size is reached?  If the max is reached, print out a warning message.  Essentially, the same behavior as found in the python interpreter (zeppelin_context.py).

        if exceed_limit:
            print("\n%html <font color=red>Results are limited by {}.</font>".format(self.max_result))

**Comment by zjffdu** [comment]
@tecgie Good catch, let me update it

**Comment by zjffdu** [comment]
@tecgie PR is updated

**Comment by tecgie** [comment]
Thanks for the fix.  Question.  In zeppelin_context.py, it gets the default max_result value from the getMaxResult method of the zeppelin context.  Here we have a hardcoded max (1000).  It seems the behavior is inconsistent, it would be good that if we can get the same default max result.

**Comment by zjffdu** [comment]
@tecgie Thanks for the careful review, PR is updated, now I use `zeppelin.R.maxResult` to configure the max rows to display.

**Comment by tecgie** [comment]
Looks good.  Thank you.

**Comment by zjffdu** [comment]
Thanks for the review @tecgie will merge if no more comment

**Pull request closed without merging**
