### PR TITLE
[ZEPPELIN-2427] Hide navbar and noteAction bar when scrolling down

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Hide navbar and noteAction bar when scrolling down to 

- **widen view area**

Here are few famous services which hiding their navbar too.

- https://www.kaggle.com/c/titanic
- http://github.com/tj (profile page)

### Implementation Details

Since [headroom](wicky.nillia.ms/headroom.js/) functionality makes integration tests fail,
we can't use `headroom` for CI build. to resolve this issue, 

- created new maven profiles: `web-ci` and `web-dist` (default)
- maven will execute `yarn run build:ci` with the `web-ci` profile which doesn't include headroom in `app.js`

### What type of PR is it?
[Improvement]

### Todos
* [x] - Add headroom.js
* [x] - Filter out useless dependencies
* [x] - Apply headroom.js

### What is the Jira issue?

[ZEPPELIN-2427](https://issues.apache.org/jira/browse/ZEPPELIN-2427)

### How should this be tested?

1. Open Zeppelin
2. Scroll down, up to see whether navbar and note action bar are hided or not.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by 1ambda** [comment]
@Leemoonsoo Please help review this.

**Comment by 1ambda** [comment]
@Leemoonsoo Please help review this.

**Comment by Leemoonsoo** [comment]
Tested and it works well!

Although i really really like this improvement because it allow utilize small screen more efficiently, i'd like to open this PR for next few more days for further feedbacks since it's noticeable UX change.

**Comment by AhyoungRyu** [comment]
Cool! 
Then to reach to the menu, some users who have lots of paragraphs have to spend much time to scroll up. Then how about sticky "go to top" like button at bottom-right side instead? I mean in another PR :)

**Comment by 1ambda** [comment]
@AhyoungRyu you can get navbar again by scrolling up few pixels. it's not necessary to go to the top.

**Comment by AhyoungRyu** [comment]
@1ambda Yeah right right I misapprehended actually. It was my bad. 
Btw I wanted to test this locally but failed when I run `yarn install` and got this below 404 error. 
```
[{
  "code": "EHTTP",
  "data": {
    "endpoint": {
      "name": "headroom.js",
      "source": "https://unpkg.com/headroom.js/bower.zip",
      "target": "*"
    },
    "resolver": {
      "name": "headroom.js",
      "source": "https://unpkg.com/headroom.js/bower.zip",
      "target": "*"
    }
  },
  "id": "EHTTP",
  "level": "error",
  "message": "Status code of 404",
  "stacktrace": "Error: Status code of 404\n    at createError (/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/node_modules/bower/lib/util/createError.js:4:15)\n    at Request.<anonymous> (/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/node_modules/bower/lib/util/download.js:91:36)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at Request.onRequestResponse (/Users/ahyoungryu/Dev/zeppelin-development/zeppelin-test/zeppelin-web/node_modules/bower/lib/node_modules/request/request.js:951:10)\n    at emitOne (events.js:96:13)\n    at ClientRequest.emit (events.js:188:7)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)\n    at TLSSocket.socketOnData (_http_client.js:363:20)"
}]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Could you point me how can I install `headroom.js`? Did I miss something?

**Comment by 1ambda** [comment]
It seems that `unpkg.com` is broken. Before, i was able to download it (CI as well)

```
$  headroom.js git:(ZEPPELIN-2427/hide-navbar-and-noteActionBar-scrolling-down) ✗ pwd
/Users/1ambda/github/apache/apache-zeppelin/zeppelin-feature/zeppelin-web/bower_components/headroom.js
$  headroom.js git:(ZEPPELIN-2427/hide-navbar-and-noteActionBar-scrolling-down) ✗ ls
bower.json dist
$ headroom.js git:(ZEPPELIN-2427/hide-navbar-and-noteActionBar-scrolling-down) ✗ cat bower.json| grep version
  "version": "0.9.3"
```

Let me use npm instead of. The maintainer might not support bower.

- https://github.com/WickyNilliams/headroom.js/issues/240#issuecomment-288107664

**Comment by 1ambda** [comment]
@AhyoungRyu I'v just updated code. 

But Jenkins is not triggered. 

- (Travis) https://travis-ci.org/1ambda/zeppelin/builds/224840876

**Comment by AhyoungRyu** [comment]
Tested and it looks great! +1 for this change 

record

**Comment by Leemoonsoo** [comment]
This PR has been opened for last week.
LGTM and Merge to master if no further comments.

**Pull request closed without merging**
