### PR TITLE
Clean unnecessary codes

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR is for cleaning unnecessary codes.

### What type of PR is it?
Refactoring

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tae-jun** [comment]
LGTM 👍

**Comment by astroshim** [comment]
@tae-jun Thank you for your review!

**Comment by minahlee** [comment]
Can you remove unused import clauses too? Seems like [L20](https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterProcess.java#L20), [L24](https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterProcess.java#L24), [L25](https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterProcess.java#L25), [L31](https://github.com/apache/zeppelin/blob/master/zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterProcess.java#L31) are not necessary either.

**Comment by astroshim** [comment]
@minahlee Thank you for proper pointing out! I just fixed it.

**Comment by minahlee** [comment]
LGTM. Merge if there is no more discussion

**Pull request closed without merging**
