### PR TITLE
[MINOR][DOC] Update available interpreters' image in index.html

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
I added available interpreters' logo image to `index.md` by #1004. So I updated this outdated `available_interpreters.png` for [BigQuery](https://cloud.google.com/bigquery/) & [Livy](http://livy.io/) logo.

### What type of PR is it?
Improvement

### What is the Jira issue?
Since it's just for `available_interpreters.png` update, didn't create Jira issue for this.

### Screenshots (if appropriate)
 - Before 
screen shot 2016-08-18 at 4 45 01 pm

 - After 
screen shot 2016-08-22 at 5 23 50 pm

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
Can you order them alphabetically ? :)

**Comment by AhyoungRyu** [comment]
@anthonycorbacho Sure. Let me update then :)

**Comment by AhyoungRyu** [comment]
@anthonycorbacho Updated the image as you said. You can check `before` & `after` in the PR description.

**Comment by minahlee** [comment]
LGTM merge if there is no more discussion

**Pull request closed without merging**
