### PR TITLE
[ZEPPELIN-1009] [HOTFIX] Fix Selenium test error

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
Fix selenium test error described in [ZEPPELIN-1009](https://issues.apache.org/jira/browse/ZEPPELIN-1009)

### What type of PR is it?
Hot Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1009

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by corneadoug** [comment]
@Leemoonsoo Previous errors are gone, nice find

**Comment by bzz** [comment]
Looks great to me

**Comment by Leemoonsoo** [comment]
I'm getting different error ...

```
Results :

Tests in error: 
  ZeppelinIT.testAngularDisplay:151->AbstractZeppelinIT.waitForParagraph:84->AbstractZeppelinIT.pollingWait:110 Â» Timeout
```

**Comment by Leemoonsoo** [comment]
Fixed all error on `Zeppelin.java`


```try { handleException("Debug 1", new RuntimeException()); } catch (Exception e) {};```

now getting errors from `ParagraphIT`

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 88.873 sec - in org.apache.zeppelin.integration.ZeppelinIT

Results :

Tests in error: 
  ParagraphActionsIT.testRemoveButton:149->AbstractZeppelinIT.waitForParagraph:88->AbstractZeppelinIT.pollingWait:114 » Timeout
  ParagraphActionsIT.testMoveUpAndDown:186->AbstractZeppelinIT.waitForParagraph:88->AbstractZeppelinIT.pollingWait:114 » Timeout
  ParagraphActionsIT.testCreateNewButton:80->AbstractZeppelinIT.waitForParagraph:88->AbstractZeppelinIT.pollingWait:114 » Timeout

Tests run: 15, Failures: 0, Errors: 3, Skipped: 0
```

Here's some experiments about `ParagraphIT` error,

- It passes on my local machine with firefox 31.0 (the same version with travis uses)
- It passes on my travis account, constantly
- It fails on apache travis account, constantly

And i tried narrow down what cause the error on apache travis account, and in case of `ParagraphActionIT.testCreateNewButton`, it opens paragraph's setting dropdown menu successfully,

image

And i believe it locates `Inserts New` button and click(), but nothing happens and test fails.

**Comment by bzz** [comment]
Sounds great! Shall we merge this guy then, and handle this nasty click in `ParagraphActionIT.testCreateNewButton` in separate pr?

**Comment by randerzander** [comment]
@bzz @Leemoonsoo, you said "i believe it locates Inserts New button and click(), but nothing happens and test fails".

This may be related to https://issues.apache.org/jira/browse/ZEPPELIN-1033. It's not just integration test which fails, the actual functions seem to be broken.

**Comment by Leemoonsoo** [comment]
@bzz Let me merge this into master and branch-0.6 then
@randerzander Thanks for reporting the problem. yes they might be related!

**Pull request closed without merging**
