### PR TITLE
[ZEPPELIN-3628] HTML anchor links on paragraph don't work in Google Chrome

### PR DESCRIPTION
**Pull request by egorklimov**
### What is this PR for?
Links like [1] work well in Firefox, but don't work in Chrome.
1. http://zeppelin/#/notebook/NOTEID?paragraph=PARAGRAPHID

### What type of PR is it?
Improvement

### What is the Jira issue?
issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-3628

### How should this be tested?
* Manual checking (see screenshot below)

### Screenshots (if appropriate)
* #### Before
Chrome (v67.0.3396.99):

chrome
Firefox (v61.0.1):

firefox
* #### After
Chrome (v67.0.3396.99)

fixed

### Questions:
* Does the licenses files need update? 
Yes, JQuery.scrollTo changed from 1.4.14 to 2.1.2 
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by egorklimov** [comment]
Something went wrong with dependencies: after that update, cursor stopped moving in paragraph text using keyboard arrows.

**Comment by egorklimov** [comment]
@jongyoul I could try to migrate away from bower to npm/yarn

**Comment by egorklimov** [comment]
Seems that in updated `scrollTo()` it's not allowed to pass `undefined `.
Also I found one more error that was fixed after update: keyboard arrows scrolling works in Firefox, and doesn't work in Chrome:
* Before (anchor doesn't work and when cursor reaches end of current viewport page doesn't scroll)
Chrome (v67.0.3396.99)
err mp4
* After
Chrome (v67.0.3396.99)
fixed mp4

**Comment by egorklimov** [comment]
@jongyoul I decided that it would be too hard for me to migrate away from bower to yarn now, maybe I'll try to do this later.

**Comment by jongyoul** [comment]
You need to enable travis for testing this PR. Unfortunately, it only supports user id's travis. Can you handle it?

**Comment by egorklimov** [comment]
@jongyoul 
CI is green https://travis-ci.org/TinkoffCreditSystems/zeppelin/builds/407589455

**Comment by zjffdu** [comment]
Will merge if no more comment

**Pull request closed without merging**
