### PR TITLE
Add custom labels to k8s interpreter

### PR DESCRIPTION
**Pull request by jaegwonseo**
### What type of PR is it?
to run interpreter on eks fargate, add custom labels to k8s interpreter 
here is eks with fargate [doc](https://www.stacksimplify.com/aws-eks/aws-fargate/learn-to-run-kubernetes-workloads-on-aws-eks-and-aws-fargate-serverless-part-2/)

### How should this be tested?
add zeppelin.k8s.interpreter.customLabels to zeppelin-site.xml and deploy on eks 

### Screenshots (if appropriate)
custom label k1:v1 is attached
스크린샷 2022-09-01 오후 10 55 06

### CODE REVIEW

**Comment by Reamer** [comment]
What prevents you from including your own labels in your Jinja template?

**Comment by jaegwonseo** [comment]
In order to deploy with different settings to n k8s clusters, different zeppelin-site.xml files are mounted and used for each cluster.

If Jinja template also needs to be created for each cluster, it seems better to manage it at once in zeppelin-site.xml because the number of management points increases.

**Comment by Reamer** [comment]
I am against the MR, because today it is about labels, tomorrow in annotations and the day after tomorrow about additional initContainers. Please adjust your Jinja2 template. This can be mounted wonderfully into the pod using ConfigMap.

**Comment by ebuildy** [comment]
Templating is very powerfull, you can use jinja conditionnal tags to have some labels for a particular interpreter etc...

**Comment by jaegwonseo** [comment]
> I am against the MR, because today it is about labels, tomorrow in annotations and the day after tomorrow about additional initContainers. Please adjust your Jinja2 template. This can be mounted wonderfully into the pod using ConfigMap.

@Reamer  
I think your opinion is more correct.
It would be better to mount the Jinja2 template. 

@ebuildy 
Unless adding all the k8s options to the Jinja2 template, it would be better to leave it alone.

i'm gonna close this pr.

**Pull request closed without merging**
