### PR TITLE
[Zeppelin - 1152] Listing note revision history

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
This PR addresses ability to view the history of note revisions from the `version control` menu

### What type of PR is it?
Improvement

### Todos
* [x] - backend changes
* [x] - tests
* [x] - propagation to frontend
* [x] -  rendering list

### What is the Jira issue?
[Zeppelin - 1152](https://issues.apache.org/jira/browse/ZEPPELIN-1152)

### How should this be tested?
1. Select Git notebook storage layer as primary (e.g. in `conf/zeppelin-env.sh` add 
``` 
export ZEPPELIN_NOTEBOOK_STORAGE="org.apache.zeppelin.notebook.repo.GitNotebookRepo"
```
2. Select any note in Zeppelin and `commit` it in `version control` menu
3. The list with new commit should be shown in the same menu

### Screenshots (if appropriate)
screen shot 2016-07-21 at 11 35 21 am

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
screen shot 2016-07-12 at 5 42 56 pm

I made a dropdown for the revisions, so that it always show current one.
The caret button is only shown if there is some revisions.

Current dropdown format is: Date - Commit message

**Comment by corneadoug** [comment]
@khalidhuseynov All builds are red, can you check it out?

**Comment by khalidhuseynov** [comment]
@corneadoug thanks for the help with rendering list, and i've fixed the tests. CI is green and ready for review.

**Comment by Leemoonsoo** [comment]
Looks good. Can we display time as well as date in each revision?

**Comment by khalidhuseynov** [comment]
@Leemoonsoo updated code and screenshot with feedback

**Comment by corneadoug** [comment]
Is it better to have the Date potentially hidden or the title hidden?

**Comment by anthonycorbacho** [comment]
@khalidhuseynov what is the benefit of having a new websocket call? will rest api call be enough?

**Comment by khalidhuseynov** [comment]
@corneadoug i'm not sure exactly what you mean, could you provide an example?

@anthonycorbacho because:
* there're cases when backend will send the list triggered by different ws event (checkpoint) for example [here](https://github.com/khalidhuseynov/incubator-zeppelin/blob/f676b741c74d308157e7cf60ab3b1db59d215e95/zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java#L1132)
* to have consistency with original work and provide whole api through websocket, possibly later provide rest-api as well

**Comment by corneadoug** [comment]
@khalidhuseynov Previous order in the list was: Date - Title, now it is Title - Date.
As you can see in your screenshot, when the text gets too long, there is an ellipse:

`add visualiz paragraph - July 19th 2016, 5...`

**Comment by khalidhuseynov** [comment]
@corneadoug yeah i changed the order since it's more intuitive to have name first, and date afterwards. But you're right when too long name, the ellipse doesn't look good. how do you think we can fix it; maybe move date to new line, or any other suggestions?

**Comment by Leemoonsoo** [comment]
@corneadoug @khalidhuseynov 

Or how about align commit message left, and align date right and use fixed length date format?
Then it gives little better readability i think.
 
```
add visualize paragrgraph...    2016-07-06 10:12:34
add tutorial                    2016-07-06 09:11:11
the first commit                2016-05-23 23:31:33
```

**Comment by khalidhuseynov** [comment]
okay, i'll play with it a bit then

**Comment by khalidhuseynov** [comment]
@corneadoug @Leemoonsoo @anthonycorbacho how about this one?
screen shot 2016-07-20 at 4 40 09 pm

**Comment by corneadoug** [comment]
@khalidhuseynov looks good, but i would reduce the font size and spacing

**Comment by khalidhuseynov** [comment]
@corneadoug how about this one 614ed61ab1b47bd5276d64d477983b605a25f6b8 : 
screen shot 2016-07-20 at 5 29 09 pm

**Comment by corneadoug** [comment]
@khalidhuseynov I wanted to change the CSS for it, but I can't create any checkpoints somehow

**Comment by bzz** [comment]
Great improvement! In this case WS protocol improvement makes sense indeed.

👍  for tests

**Comment by khalidhuseynov** [comment]
addressed comments and CI is green. /cc @corneadoug @Leemoonsoo @bzz for review

**Comment by corneadoug** [comment]
LGTM

**Comment by bzz** [comment]
Looks good to me, merging if there is no further discussion

**Pull request closed without merging**
