### PR TITLE
[zeppelin-3639] Add Ipython interpreter prerequisite check for protobuf

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
This is to protobuf prerequisite check when starting ipython kernel. This is required since from grpcio 1.12.0 it's  independent from protobuf

### What type of PR is it?
[ Improvement ]

### Todos
* [x] - add protobuf prerequisite check
* [x] - add to ipython docs

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3639

### How should this be tested?
1. remove grpcio and protobuf 
2. install latest grpcio and try to run ipython interpreter - should fail
3. then install protobuf and try again - should work

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by Tagar** [comment]
Would be nice to check freeze output for tornado version.
tornado 5.x is broken for Zeppelin. https://issues.apache.org/jira/browse/ZEPPELIN-3505

**Comment by khalidhuseynov** [comment]
@Tagar thanks for suggestion, but I think it's better not to include this check for tornado in this function since it's not really pre-requisite check. if we add it, then we need to keep track it, and restore back when the issue with tornado is fixed.

**Comment by Tagar** [comment]
that makes sense. thanks @khalidhuseynov

**Pull request closed without merging**
