### PR TITLE
ZEPPELIN-2219 Apache Ignite version updated to 1.9

### PR DESCRIPTION
**Pull request by agura**
### What is this PR for?
Apache Ignite version update to 1.9 in Ignite interpreter

### What type of PR is it?
[Improvement]

### What is the Jira issue?
ZEPPELIN-2219

### CODE REVIEW

**Comment by agura** [comment]
It seems that build failure isn't related with my changes. Could somebody look at this?

**Comment by AhyoungRyu** [comment]
@agura Thanks always for taking care of up-to-date ignite. Can you set up your own travis as described in [here](https://zeppelin.apache.org/contribution/contributions.html#continuous-integration)?

**Comment by agura** [comment]
@AhyoungRyu Thanks for quick answer. Yes, I can. But IMO it doesn't make sense. There are only two tests related with Ignite interpreter and this tests are finished successfully.

**Comment by AhyoungRyu** [comment]
@agura Yes I know it's not related with this PR's CI status, but I thought it's good to do for anyone who is contributing to Zeppelin :)

**Comment by agura** [comment]
@AhyoungRyu :) I agree wih you. But I sure that GUI tests don't make sense for this change because interpreter implementation isn't changed, interface between interpreter and front-end is still the same and unit tests show that returned data set is the same.

**Comment by AhyoungRyu** [comment]
Yeah makes sense. LGTM 👍

**Comment by agura** [comment]
Could somebody merge it?

**Comment by AhyoungRyu** [comment]
Merge into master and branch-0.7 if there are no more comments

**Comment by agura** [comment]
Thanks a lot!

**Pull request closed without merging**
