### PR TITLE
Remove multple artifactId - hadoop-common

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
Remove multple artifactId - hadoop-common in JDBC

### What type of PR is it?
[Refactor | Minor]

### Todos
* [ ] - N/A

### What is the Jira issue?
* [ZEPPELIN-1989](https://issues.apache.org/jira/browse/ZEPPELIN-1989)

### How should this be tested?
Just a small refactor. 
CI should be green.

### Screenshots (if appropriate)
N/A

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by jongyoul** [comment]
LGTM

**Comment by astroshim** [comment]
LGTM!

**Comment by felixcheung** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
