### PR TITLE
[ZEPPELIN-1657] Private/public mode for user note creation/import

### PR DESCRIPTION
**Pull request by khalidhuseynov**
### What is this PR for?
In multi-user environment when users create a notebook normally they would expect that notebook be listed only in their list/workbench. Currently Zeppelin creates/imports notes as public by default. There should be at least a way to pass through configuration to make this behaviour private be default. Should discuss whether it's public or private by default.

### What type of PR is it?
Improvement

### Todos
* [x] - set permissions on create/import
* [x] - test
* [x] - review, feedback, decide whether public/private by default
* [x] - pass through env. config

### What is the Jira issue?
[ZEPPELIN-1657](https://issues.apache.org/jira/browse/ZEPPELIN-1657)

### How should this be tested?
1. set `zeppelin.notebook.public` property as false in `zeppelin-site.xml`
2. login as user1 and create noteA, note should appear in your list of notes
3. logout and login as user2, shouldn't be able to see noteA

### Screenshots (if appropriate)
TBD

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? maybe

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
CI is green and ready for review. @Leemoonsoo feedback would be appreciated, especially regarding the naming of say `zeppelin.notebook.public` and `isPublic`. another way would be to name them as private, e.g. `zeppelin.notebook.public` and `isPrivate` with opposite values. let me know what you think in general

**Comment by Leemoonsoo** [comment]
Thanks @khalidhuseynov for the contribution.
I think make permission public by default make sense, while it is current behavior.

Could you add new configuration to `docs/install/install.md#apache-zeppelin-configuration`, too?

**Comment by khalidhuseynov** [comment]
@Leemoonsoo thanks for review, addressed comments in fc91b2f15725e91db1cbdf0439e8dd8779fc4f68. also rebased and resolved conflicts since `docs/install/install.md` was recently changed.

**Comment by Leemoonsoo** [comment]
@khalidhuseynov Can you make CI green?

**Comment by khalidhuseynov** [comment]
@Leemoonsoo fixed the test failure coming from rebase. all profiles pass except the last selenium test failure with:
```

Results :

Tests in error: 
  ParagraphActionsIT.testEditOnDoubleClick:443 » ElementNotVisible Element is no...

Tests run: 17, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by khalidhuseynov** [comment]
@Leemoonsoo CI is finally green!

**Comment by Leemoonsoo** [comment]
Thank you for the contribution!
LGTM and merge to master if there're no further discussions.

**Pull request closed without merging**
