### PR TITLE
[MINOR] Refactor to modern apis

### PR DESCRIPTION
**Pull request by DrIgor**
### What is this PR for?
Use modern api to write less and try-with-resources to close file in case of errors

### What type of PR is it?
Refactoring

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@DrIgor Thanks for the contribution!
CI fails with known flaky test https://issues.apache.org/jira/browse/ZEPPELIN-1856. @DrIgor Could you trigger ci again and see if it passes?

**Comment by DrIgor** [comment]
@Leemoonsoo Of course! Unfortunately, build log is truncated and I can't find out why it failed

**Comment by DrIgor** [comment]
```
Tests in error: 
  InterpreterRestApiTest.testRestartInterpreterPerNote:303 NullPointer
```

It's a known bug https://issues.apache.org/jira/browse/ZEPPELIN-1856

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no more comment.

**Pull request closed without merging**
