### PR TITLE
[ZEPPELIN-1379] Flink interpreter is missing scala libraries

### PR DESCRIPTION
**Pull request by lresende**
### What is this PR for?
On Flink interpreter, remove provided scope from scala libraries to enable copying them to interpreter location.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-1379](https://issues.apache.org/jira/browse/ZEPPELIN-1379)

### CODE REVIEW

**Comment by lresende** [comment]
After the fix, performed a full build and compared scala libraries from flink and ignite

$ cd flink/
$ ls scala*
-rw-r--r--  1 lresende  staff    14M Aug 26 12:39 scala-compiler-2.10.5.jar
-rw-r--r--  1 lresende  staff   6.8M Aug 26 12:39 scala-library-2.10.5.jar
-rw-r--r--  1 lresende  staff   3.1M Aug 26 12:39 scala-reflect-2.10.5.jar
$ cd ..
$ cd ignite/
$ ls scala*
-rw-r--r--  1 lresende  staff    14M Aug 26 12:39 scala-compiler-2.10.5.jar
-rw-r--r--  1 lresende  staff   6.8M Aug 26 12:39 scala-library-2.10.5.jar
-rw-r--r--  1 lresende  staff   3.1M Aug 26 12:39 scala-reflect-2.10.5.jar

**Comment by bzz** [comment]
Looks good to me, thank you @lresende 

BTW, from my experience, postin CI failure helps to speed up a review process.

CI fails on Spark 2.0 profile \w `ZeppelinSparkClusterTest.zRunTest` which looks like a flaky test, not relevant to the changes.
```
[INFO] Zeppelin: Server ................................... FAILURE [04:11 min]

Failed tests: 
  ZeppelinSparkClusterTest.zRunTest:204 expected:<FINISHED> but was:<ERROR>

00:32:54,193  INFO org.apache.zeppelin.interpreter.InterpreterFactory:665 - Create interpreter instance md for note 2BW956553
00:32:54,193  INFO org.apache.zeppelin.interpreter.InterpreterFactory:696 - Interpreter org.apache.zeppelin.markdown.Markdown 578260863 created
00:32:54,194  INFO org.apache.zeppelin.notebook.Paragraph:295 - run paragraph 20160828-003254_783795023 using md org.apache.zeppelin.interpreter.LazyOpenInterpreter@22778f7f
00:32:54,195  INFO org.apache.zeppelin.interpreter.remote.RemoteInterpreterManagedProcess:116 - Run interpreter process [..//bin/interpreter.sh, -d, ../interpreter/md, -p, 46521, -l, ..//local-repo/2BUN9SMBJ]
00:32:54,195  INFO org.apache.zeppelin.socket.NotebookServer:115 - New connection from null : 0
00:32:54,196  INFO org.apache.zeppelin.socket.NotebookServer:115 - New connection from null : 0
00:32:54,198  INFO org.apache.zeppelin.socket.NotebookServer:529 - New operation from null : 0 : anonymous : GET_NOTE : 2BW956553
00:32:54,209  INFO org.apache.zeppelin.socket.NotebookServer:529 - New operation from null : 0 : anonymous : GET_NOTE : 2BW956553
00:32:54,210 ERROR org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess:234 - Remote interpreter process not started
java.lang.NullPointerException
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess.updateRemoteAngularObject(RemoteInterpreterProcess.java:229)
	at org.apache.zeppelin.interpreter.remote.RemoteAngularObject.set(RemoteAngularObject.java:48)
	at org.apache.zeppelin.interpreter.remote.RemoteAngularObject.set(RemoteAngularObject.java:40)
	at org.apache.zeppelin.socket.NotebookServer.angularObjectUpdated(NotebookServer.java:841)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:221)
	at org.apache.zeppelin.socket.NotebookServerTest.testMakeSureNoAngularObjectBroadcastToWebsocketWhoFireTheEvent(NotebookServerTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

00:32:54,216 ERROR org.apache.zeppelin.interpreter.remote.RemoteAngularObjectRegistry:111 - Error
java.lang.NullPointerException
	at org.apache.zeppelin.interpreter.remote.RemoteAngularObjectRegistry.removeAndNotifyRemoteProcess(RemoteAngularObjectRegistry.java:105)
	at org.apache.zeppelin.interpreter.remote.RemoteAngularObjectRegistry.removeAllAndNotifyRemoteProcess(RemoteAngularObjectRegistry.java:123)
	at org.apache.zeppelin.notebook.Notebook.removeNote(Notebook.java:326)
	at org.apache.zeppelin.socket.NotebookServerTest.testMakeSureNoAngularObjectBroadcastToWebsocketWhoFireTheEvent(NotebookServerTest.java:147)
```

Merging to _master_ and _branch-0.6_ if there is no further discussion.

**Comment by lresende** [comment]
@bzz Anything else needed here ?

**Comment by felixcheung** [comment]
I'll merge it today, thanks!

**Pull request closed without merging**
