### PR TITLE
ZEPPELIN-2674 Ignite version upgraded up to 2.0

### PR DESCRIPTION
**Pull request by agura**
### What is this PR for?
Apache Ignite 2.0 brings many improvements and new SQL related functionality. This PR upgrades Ignite version for Ignite interpreter.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2674

### How should this be tested?
Unit-tests are enough.

### CODE REVIEW

**Comment by 1ambda** [comment]
Hi, could you setup CI? 

- http://zeppelin.apache.org/contribution/contributions.html#continuous-integration
- the forked repository name must be `zeppelin`

**Comment by 1ambda** [comment]
@agura If you have a problem to set up CI, we can discuss here. Please leave comments.

**Comment by agura** [comment]
@1ambda I'll try a little bit later.

**Comment by agura** [comment]
@1ambda Hi! I still don't have time for set up CI on my laptop. But my changes are so small and related with Ignite interpreter only. All Ignite interpreter tests are passed. Could you please merge this PR?

Thanks for comment about fork name. I'll create new fork for future PRs.

**Comment by 1ambda** [comment]
@agura Hi, you don't need to setup CI on your laptop.

1. Signup travis-ci.org
2. Change your repository incubator-zeppelin to `zeppelin`: https://github.com/agura?tab=repositories
3. Configure forked repository `zeppelin`in travis CI
4. Close and reopen this PR.

it takes 5-10 mins.

**Comment by 1ambda** [comment]
Hi @agura I guess you didn't setup travis CI for the forked repository.

- https://builds.apache.org/job/zeppelin-pull-request/2647/console

image

**Comment by agura** [comment]
@1ambda I didn't update commit. I've updated the commit and check failed with other problem.

**Comment by agura** [comment]
Hi, @1ambda. How should I handle this situation on CI servers?

```
The following packages have unmet dependencies:

 r-base-dev : Depends: r-base-core (>= 3.2.5-1precise0) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.

apt-get.diagnostics

apt-get install failed

$ cat ~/apt-get-update.log

Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 InRelease

Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease

Hit:4 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release

Ign:5 http://cran.rstudio.com/bin/linux/ubuntu precise/ InRelease

Get:6 http://cran.rstudio.com/bin/linux/ubuntu precise/ Release [3,074 B]

Ign:3 http://toolbelt.heroku.com/ubuntu ./ InRelease

Get:7 http://cran.rstudio.com/bin/linux/ubuntu precise/ Release.gpg [473 B]

Hit:8 http://dl.google.com/linux/chrome/deb stable Release

Hit:9 http://toolbelt.heroku.com/ubuntu ./ Release

Hit:11 http://dl.hhvm.com/ubuntu trusty InRelease

Hit:12 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease

Ign:13 http://archive.ubuntu.com/ubuntu trusty InRelease

Hit:14 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease

Hit:15 http://archive.ubuntu.com/ubuntu trusty-updates InRelease

Hit:16 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty InRelease

Get:18 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2/multiverse i386 Packages [29 B]

Hit:19 http://archive.ubuntu.com/ubuntu trusty-security InRelease

Ign:20 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease

Get:10 http://dl.bintray.com/apache/cassandra 39x InRelease [3,168 B]

Hit:21 http://archive.ubuntu.com/ubuntu trusty Release

Hit:22 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease

Hit:23 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty InRelease

Get:24 http://cran.rstudio.com/bin/linux/ubuntu precise/ Packages [300 kB]

Hit:25 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty InRelease

Hit:26 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease

Hit:27 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release

Hit:30 https://packagecloud.io/basho/riak/ubuntu trusty InRelease

Get:31 http://dl.hhvm.com/ubuntu trusty/main i386 Packages [20 B]

Hit:32 https://packagecloud.io/computology/apt-backport/ubuntu trusty InRelease

Hit:33 https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease

Get:34 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty/main i386 Packages [1,716 B]

Hit:35 https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease

Get:36 http://apt.postgresql.org/pub/repos/apt trusty-pgdg/main i386 Packages [120 kB]

Get:37 http://archive.ubuntu.com/ubuntu trusty-updates/main i386 Packages [1,197 kB]

Get:38 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty/main i386 Packages [1,611 B]

Get:39 http://archive.ubuntu.com/ubuntu trusty-updates/restricted i386 Packages [20.9 kB]

Get:40 http://archive.ubuntu.com/ubuntu trusty-updates/multiverse i386 Packages [16.1 kB]

Get:41 http://archive.ubuntu.com/ubuntu trusty-updates/universe i386 Packages [545 kB]

Get:42 http://archive.ubuntu.com/ubuntu trusty-security/main i386 Packages [750 kB]

Get:43 http://archive.ubuntu.com/ubuntu trusty-security/restricted i386 Packages [17.6 kB]

Get:44 http://archive.ubuntu.com/ubuntu trusty-security/multiverse i386 Packages [4,183 B]

Get:45 http://archive.ubuntu.com/ubuntu trusty-security/universe i386 Packages [231 kB]

Get:46 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages [682 B]

Get:48 http://archive.ubuntu.com/ubuntu trusty/main i386 Packages [1,739 kB]

Get:49 http://archive.ubuntu.com/ubuntu trusty/restricted i386 Packages [16.4 kB]

Get:50 http://archive.ubuntu.com/ubuntu trusty/multiverse i386 Packages [172 kB]

Get:51 http://archive.ubuntu.com/ubuntu trusty/universe i386 Packages [7,597 kB]

Get:52 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty/main i386 Packages [3,464 B]

Get:53 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty/main i386 Packages [4,392 B]

Get:54 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [445 B]

Get:55 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty/main i386 Packages [3,145 B]

Get:57 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty/main i386 Packages [985 B]

Fetched 12.7 MB in 5s (2,157 kB/s)

Reading package lists...

W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)

W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install r-base-dev" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by 1ambda** [comment]
Hi, what is your base branch? Could you rebase using current master?

**Comment by agura** [comment]
@1ambda Hi! All checks are passed after rebase. Thanks for help. Could you please merge this PR?

**Comment by 1ambda** [comment]
LGTM, merge if no more discussion.

**Comment by agura** [comment]
Should I change JIRA ticket status to Resolved or something else in in order to get this PR merged?

**Pull request closed without merging**
