### PR TITLE
[ZEPPELIN-1875] permission dialog code is not stable

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
The code for the notification pop-up is not stable.
Sometime when response to slow for backend.
Then the permission box and the dialogue open together.

### What type of PR is it?
Bug Fix , Improvement

### Todos
- [x] changed method name  (getBlockNotAuthenticatedUserErrorMsg)
- [x] permission dialog pop-up change logic.
- [x] added check logic for anonymous user in checkIfUserIsAnon method

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1875

### How should this be tested?
1. when you do have turn on the shiro and login and click to note permission button.
2. or turn off the shiro.
### Screenshots (if appropriate)
dialog

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@cloverhearts Thanks for quick fixing and improvement. I think it's my bad.. Let me test this! 

But Selenium test failure looks relevant with this change like below. Could you take a look? 

```
Results :

Tests in error: 
  AuthenticationIT.testGroupPermission:192->AbstractZeppelinIT.pollingWait:96 Â» Timeout

Tests run: 18, Failures: 0, Errors: 1, Skipped: 0
```

This is the screenshot taken when the error occurs
copy

**Comment by cloverhearts** [comment]
@AhyoungRyu Okay, I will check it.
Thank you for your feedback.

**Comment by cloverhearts** [comment]
fixed.
@AhyoungRyu Could you please review again? :)

**Comment by AhyoungRyu** [comment]
@cloverhearts yup. Thanks!

**Comment by AhyoungRyu** [comment]
Tested this branch and checked the verbose forbidden error messages(my bad..) are totally gone when I turned off Shiro. Thanks @cloverhearts! 
LGTM 👍

**Comment by Leemoonsoo** [comment]
Tested and LGTM

**Comment by AhyoungRyu** [comment]
Then will merge into master if there are no more comments

**Pull request closed without merging**
