### PR TITLE
[HOTFIX] Add warning for sh interpreter

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Adding warning message when using sh interpreter

### What type of PR is it?
Documentation

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* Put link here, and add [ZEPPELIN-*Jira number*] in PR title, eg. [ZEPPELIN-533]

### How should this be tested?
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the license files need to update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Good to make this more explicit!

Of course many other interpreters that have equivalent power: the language-based ones (Groovy, Java, Python) trivially so. Are you planning on disabling those by default as well?

My only concern with this wording is that by saying "`sh` interpreter can access the local shell and execute arbitrary commands", you might give people the incorrect impression that the other interpreters cannot provide this access. Perhaps you could try something like: 

"All interpreters should be assumed to be able to access the local shell and execute arbitrary commands with the privileges of the user running the Zeppelin server. As generic interpreters such as `sh`, `Groovy`, `Java` and `Python` make this especially trivial, we plan to disable the `sh` interpreter by default from version 0.11.1 onward.

**Review by Reamer — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Maybe we should add a DISClAIMER like another notebook [polynote](https://polynote.org/latest/docs/installation/) does?

**Comment by jongyoul** [comment]
@raboof Thank you for the detailed suggestions. I'll change it on the repository of zeppelin-site.

@pan3793 It looks good idea :-)

**Comment by jongyoul** [comment]
BTW, I added it on https://github.com/apache/zeppelin-site/commit/da2424181cb7e907eb2f34afd166db59fcf0f543. I forgot to change the way to deploy the site. I'll also remove gh-pages soon because https://github.com/apache/zeppelin-site already has all the histories.

**Pull request closed without merging**
