### PR TITLE
[ZEPPELIN-2229] Providing workaround for nvd3 voronoi

### PR DESCRIPTION
**Pull request by Remilito**
### What is this PR for?
After bumping nvd3 to 1.8.5, an error was spotted due to a bug in nvd3. This PR provides a workaround until the proper nvd3 fix is released. 
* create a jitter and deduplicate data
* adapt axis tick format to hide the jitter
* add y label for non-numeric value
* this code can be safely removed after nvd3 [#1934](https://github.com/novus/nvd3/pull/1934) is released ( >
  1.8.5) and bumped in zeppelin project

### What type of PR is it?
Bug Fix

### Todos
* [ ] - When bumping nvd3 to a version > 1.8.5, remove the code marked with TODO

### What is the Jira issue?
[ZEPPELIN-2229](https://issues.apache.org/jira/browse/ZEPPELIN-2229)

### How should this be tested?
See [#2186](https://github.com/apache/zeppelin/pull/2186). Switch between any chart and scatter chart with a large number of rows.

### Screenshots (if appropriate)
See [#2186](https://github.com/apache/zeppelin/pull/2186).

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by soralee** [comment]
@Remilito Sounds great! It looks good to me.
With this PR, we can keep on using the latest version of the nvd3. Personally, I like your annotations per code spot. Because it can keep remind us and it would be comfortable when bump up version.
Anyway, I'll check and test it out!

**Comment by soralee** [comment]
Tested it out and it works very well! 
z_for_bumpup_check

**Comment by soralee** [comment]
I checked the similar issue ["TypeError: Cannot read property '1' of undefined" in the bar chart](https://issues.apache.org/jira/browse/ZEPPELIN-2273) we have. 
This error is occured when changing radio button from `Grouped` to `Stacked` like the following screenshot.
z_stack_error


But, Fortunately, there is no problem in this branch so, we can also resolve it with this PR!
z2273_no_error

z2273_no_error2

**Comment by minahlee** [comment]
Thank you for the contribution @Remilito. Merging it into master and branch-0.7.

**Pull request closed without merging**
