### PR TITLE
[ZEPPELIN-4775]. Sometimes sql text is not highlighted

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

This PR is to fix the highlight issue. The root cause is in the magic parsing logic in frontend. This PR just move the magic logic from frontend to backend. So that we use the consistent parsing logic. 

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4775

### How should this be tested?
* CI pass

### Screenshots (if appropriate)

Before
image

After

image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@alexott No test for this, it is pretty hard to test the highlight feature in frontend.

**Comment by alexott** [comment]
I meant for parsing on the server side, not for highlighting...

**Comment by zjffdu** [comment]
The server side test is already in. https://github.com/apache/zeppelin/blob/master/zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/ParagraphTextParserTest.java

**Comment by alexott** [comment]
great! thank you - I don't have any more comments

**Pull request closed without merging**
