### PR TITLE
[ZEPPELIN-4515] Have Jetty Server support multiple wars

### PR DESCRIPTION
**Pull request by fred521**
### What is this PR for?
We have a new UI with version angular 8, which will be retiring the old angularjs.
both of the angular frameworks may need to co-exist for a while until the new UI is stable.
Have the Jetty server support multiple wars with different port (8080 and 9090)

### What type of PR is it?
[Feature ]

### Todos
retire angularJS completely in the future. 

### What is the Jira issue?
* [ZEPPELIN-4515](https://issues.apache.org/jira/browse/ZEPPELIN-4515) Have Jetty Server support multiple wars
Add multiple war support for the Zeppelin Server.
two ports (default is 8080 and 9090) will be living for a while until we are comfortable with the new UI.

### How should this be tested?
The default port for new UI is 9090, testing via http://localhost:9090

### Questions:
* Does the licenses files need update? **No**
* Is there breaking changes for older versions? **No**
* Does this needs documentation? **No**

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks for the contribution @fred521 
Could you create a ticket for it ? And Do you want to contribute your presto note tutorial to Zeppelin ? 😄

**Comment by fred521** [comment]
> Thanks for the contribution @fred521
> Could you create a ticket for it ? And Do you want to contribute your presto note tutorial to Zeppelin ? 😄

add the Jira link to the PR.

Would love to share anything, presto note tutorial means presto notebook that created by our users ?

**Comment by zjffdu** [comment]
@fred521 Could you update the PR title and description, please follow the contribution guildeline here. http://zeppelin.apache.org/community.html

Regarding the presto, I mean you added presto note in this PR. 😄

**Comment by fred521** [comment]
> Regarding the presto, I mean you added presto note in this PR. 😄

haha, that was a mistake, thanks 😄😄😄

**Comment by zjffdu** [comment]
@fred521 I tried this PR, but could not open the new angular ui. Anything else need to configure ?

image

**Comment by zjffdu** [comment]
@fred521 I can make it work by changing this line to following https://github.com/apache/zeppelin/pull/3571/files#diff-179ea3a816210bb9904baabec1a552e4R825

```
ZEPPELIN_ANGULAR_WAR("zeppelin.angular.war", "zeppelin-web-angular/dist/zeppelin"),
```

Thanks @hsuanxyz for the hint.

**Comment by zjffdu** [comment]
Thanks @fred521 LGTM , will merge if no more comment

**Comment by zjffdu** [comment]
@fred521 I have merged it, could you close this PR ?

**Pull request closed without merging**
