### PR TITLE
Bump up version to 0.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Bump up version to 0.8.0-SNAPSHOT

### CODE REVIEW

**Comment by jongyoul** [comment]
@minahlee You need to change `helium-dev`, too.

**Comment by prabhjyotsingh** [comment]
Yes, expect `helium-dev/pom.xml`, LGTM!
Thanks for taking care of this.

**Comment by minahlee** [comment]
@jongyoul I made this branch before helium-dev separation PR merged, almost missed it! Thank you for pointing out.

**Comment by jongyoul** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
@minahlee Can we take care of followings as well?

[zeppelin-web/src/app/tabledata/package.json](https://github.com/apache/zeppelin/blob/master/zeppelin-web/src/app/tabledata/package.json)
[zeppelin-web/src/app/visualization/package.json](https://github.com/apache/zeppelin/blob/master/zeppelin-web/src/app/visualization/package.json)

**Comment by Leemoonsoo** [comment]
LGTM. Since branch-0.7 is already created, shell we merge this guy asap?

**Pull request closed without merging**
