### PR TITLE
[ZEPPELIN-2177] ZEPPELIN_INTP_CLASSPATH should contain ZEPPELIN_CONF_DIR

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
ZEPPELIN_INTP_CLASSPATH should contain ZEPPELIN_CONF_DIR so if in case of "core-site.xml", "hbase-site.xml" etc. present locally can be read from there itself.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
* [ZEPPELIN-2177](https://issues.apache.org/jira/browse/ZEPPELIN-2177)

### How should this be tested?
After running any of the paragraph 
then on doing a `ps aux | grep interpreter.sh` in "-cp" observe Zeppelin's conf directory path

<pre>
$ ps aux | grep interpreter.sh
prabhjyotsingh   25175   0.1  0.5  5015500  78976 s001  S    11:52AM   0:00.93 /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -Dlog4j.configuration=file:///Users/prabhjyotsingh/ps-zeppelin/conf/log4j.properties -Dzeppelin.log.file=/Users/prabhjyotsingh/ps-zeppelin/logs/zeppelin-interpreter-sh-prabhjyotsingh-HW11610.local.log -Xms1024m -Xmx1024m -XX:MaxPermSize=512m -cp ::/Users/prabhjyotsingh/ps-zeppelin/interpreter/sh/*:/Users/prabhjyotsingh/ps-zeppelin/zeppelin-interpreter/target/lib/*::/Users/prabhjyotsingh/ps-zeppelin/zeppelin-interpreter/target/classes:/Users/prabhjyotsingh/ps-zeppelin/zeppelin-interpreter/target/test-classes:/Users/prabhjyotsingh/ps-zeppelin/zeppelin-zengine/target/test-classes:<b>/Users/prabhjyotsingh/ps-zeppelin/conf</b> org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer 62196
prabhjyotsingh   25186   0.0  0.0  2442028    820 s001  S+   11:52AM   0:00.00 grep interpreter.sh
prabhjyotsingh   25174   0.0  0.0  2462072    760 s001  S    11:52AM   0:00.00 /bin/bash /Users/prabhjyotsingh/ps-zeppelin/bin/interpreter.sh -d /Users/prabhjyotsingh/ps-zeppelin/interpreter/sh -p 62196 -l /Users/prabhjyotsingh/ps-zeppelin/local-repo/2C8YBAR9B
prabhjyotsingh   25166   0.0  0.0  2452856   1280 s001  S    11:52AM   0:00.01 /bin/bash /Users/prabhjyotsingh/ps-zeppelin/bin/interpreter.sh -d /Users/prabhjyotsingh/ps-zeppelin/interpreter/sh -p 62196 -l /Users/prabhjyotsingh/ps-zeppelin/local-repo/2C8YBAR9B
</pre>

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by jongyoul** [comment]
AFAIK, it was removed before because someone blame log4j.properties location. Do you know the history? Personally, I agree that it includes conf.

**Comment by prabhjyotsingh** [comment]
Sure, let me check. I wasn't aware.

**Comment by prabhjyotsingh** [comment]
Sure, let me check. I wasn't aware.

**Comment by prabhjyotsingh** [comment]
I think you are right. I'll close this, and use `ZEPPELIN_INTP_CLASSPATH_OVERRIDES` and use a different path where ever it is really required.

**Comment by prabhjyotsingh** [comment]
Thank you @felixcheung  and @jongyoul  for the quick feedback.

**Pull request closed without merging**
