### PR TITLE
[ZEPPELIN-5920] Fix deprecation warnings

### PR DESCRIPTION
**Pull request by matthias-koch**
### What is this PR for?
If z.show is used with a Panda DataFrame that has a timestamp as index, then a DeprecationWarning appears for every row in the data frame.
This issue was fixed.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5920

### How should this be tested?
* A new unit test was added

### Questions:
* Does the license files need to update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by Reamer** [comment]
Do you think it would be smart to ignore all the warnings?

**Comment by matthias-koch** [comment]
I could limit it to DeprecationWarnings.
Another option would be to check the type of index. However to do this I would have to import numpy in zeppelin_context.py, which I wanted to avoid.

**Comment by Reamer** [comment]
It seems that the data types are different. What do you think about simply counting down?
```
rowNumber = min(len(rows), len(df.index.values)) 
for idx, row in zip(index, rows):
    rowNumber = rowNumber - 1;
    if (rowNumber == 0)
       body_buf.write("\n")
```

A screenshot of my reproduction
grafik

**Comment by Reamer** [comment]
Let's wait for the tests.

**Pull request merged**
