### PR TITLE
[ZEPPELIN-4338] Fix docker image build error

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR fixes docker image build error using /script/docker/zeppelin/bin/Dockerfile

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-4338

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @felixcheung. merge to master and branch-0.8

**Comment by resdevd** [comment]
apache/zeppelin:0.8.2 from docker hub still failing

**Comment by zjffdu** [comment]
@resdevd What do you mean failing ? I see the docker image is built successfully on docker hub. Do you mean you fail to start zeppelin ?

**Comment by resdevd** [comment]
@zjffdu Yes, I can launch the container with command:-
docker run -p 8080:8080 --rm --name zeppelin apache/zeppelin:0.8.2

However web server would never start at localhost:8080. Tried every possible thing including clearing cache, trying in different browsers/different servers (linux and mac). Interestingly 0.8.1 docker image works fine without any issues. 

Below are logs from the 0.8.2 docker container (container doesn't fail, just webserver would not show up in localhost:8080)


Nov 03, 2019 6:20:30 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.CredentialRestApi.getCredentials(java.lang.String) throws java.io.IOException,java.lang.IllegalArgumentException, should not consume any entity.
WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.InterpreterRestApi.listInterpreter(java.lang.String), should not consume any entity.
WARNING: The (sub)resource method createNote in org.apache.zeppelin.rest.NotebookRestApi contains empty path annotation.
WARNING: The (sub)resource method getNoteList in org.apache.zeppelin.rest.NotebookRestApi contains empty path annotation.

**Comment by zjffdu** [comment]
@resdevd You need to pass env ZEPPELIN_ADDR='0.0.0.0', otherwise it would listen on 127.0.0.1. Will update the document

**Comment by resdevd** [comment]
@zjffdu That's it. It's working now. Thanks.

**Pull request closed without merging**
