### PR TITLE
[ZEPPELIN-1061] Select default interpreter while creating note

### PR DESCRIPTION
**Pull request by kavinkumarks**
### What is this PR for?

This handles setting the default interpreter on creating a note through the zeppelin UI.
### What type of PR is it?

Feature
### Todos

NA
### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-1061
### How should this be tested?
- Go to the 'Create Note' dialog and provide the name with the default interpreter selected.After clicking on the Create button, the selected interpreter should be shown properly in the interpreter binding section.
- If there is no interpreter selected, then the system default will be used.
### Screenshots (if appropriate)

zeppelin-1061
### Questions:
- Does the licenses files need update? No
- Is there breaking changes for older versions? No
- Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
WIP?

**Comment by kavinkumarks** [comment]
The changes are done.

**Comment by jongyoul** [comment]
@kavinkumarks I'm looking into this.

**Comment by kavinkumarks** [comment]
@jongyoul any udpates on this?

**Comment by jongyoul** [comment]
@kavinkumarks Backend codes looks good to me. @corneadoug Could you please look into it?

**Comment by AhyoungRyu** [comment]
@kavinkumarks Thanks for your contribution. Tested and it works well! 

Can we reset the selected interpreter in the note creation page? Currently the dialog keeps the previously selected one.
interpreter_selection

**Comment by kavinkumarks** [comment]
@jongyoul & @AhyoungRyu thanks for reviewing it. @AhyoungRyu I will look into the issue.
@corneadoug any updates on this?

Thanks,
Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by AhyoungRyu** [comment]
@kavinkumarks Currently there are some conflicts in here. Can you resolve them? :)

**Comment by kavinkumarks** [comment]
@AhyoungRyu I have resolved the conflicts and also fixed the issue "Can we reset the selected interpreter in the note creation page? Currently the dialog keeps the previously selected one."

Waiting for the travis build to be success.

Thanks,
Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by kavinkumarks** [comment]
The travis build is green after fixing the test case failure.

Thanks,
Kavin
MailTo: kavin.kumar@imaginea.com

**Comment by AhyoungRyu** [comment]
@kavinkumarks Tested and it works well as expected! Thanks again :)
Merging this into master if there are no more discussions.

**Pull request closed without merging**
