### PR TITLE
[ZEPPELIN-1850] Remove grunt-contrib-clean (grunt)

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Replaced `grunt-contrib-clean` to [rimraf](https://github.com/isaacs/rimraf) 

- to remove `Gruntfile.js`
- to have npm managed scripts in `package.json` for running `rm -rf` in multiple platforms including windows
- Also, fixed invalid `prestart` npm command to `predev`

This PR related to

- https://github.com/apache/zeppelin/pull/1812 (Using yarn)
- https://github.com/apache/zeppelin/pull/1818 (Removing jscs)

### What type of PR is it?

[Improvement]

### Todos

Done at once

### What is the Jira issue?

[ZEPPELIN-1850](https://issues.apache.org/jira/browse/ZEPPELIN-1850)

### How should this be tested?

- `npm run test`, `npm run build`, `npm run dev` should work

### Screenshots (if appropriate)

None

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
`mvn clean` in `zeppelin-web` module now removes [`bower_components`](https://github.com/apache/zeppelin/blob/master/zeppelin-web/pom.xml#L180).
what do you think about making `mvn clean` run `npm run clean` as well?

**Comment by 1ambda** [comment]
@Leemoonsoo Thanks for review!

Now `mvn clean` will execute `npm run clean` (8baaea2)

```
$ zeppelin-web git:(ZEPPELIN-1850/remove-grunt-clean) mvn clean
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in8.0
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Zeppelin: web Application 0.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ zeppelin-web ---
[INFO] Deleting /Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web/target
[INFO]
[INFO] --- frontend-maven-plugin:1.3:npm (npm clean) @ zeppelin-web ---
[INFO] Running 'npm run clean' in /Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web
[INFO]
[INFO] > zeppelin-web@0.0.0 clean /Users/lambda/github/apache-zeppelin/zeppelin-master/zeppelin-web
[INFO] > rimraf dist && rimraf .tmp
```

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if there're no further discussions.

**Comment by Leemoonsoo** [comment]
Since this PR merge, [first CI test profile fails](https://travis-ci.org/apache/zeppelin/jobs/188757727) with

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:npm (npm clean) on project zeppelin-web: Failed to run task: 'npm run clean' failed. java.io.IOException: Cannot run program "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" (in directory "/home/travis/build/apache/zeppelin/zeppelin-web"): error=2, No such file or directory -> [Help 1]
```

@1ambda Could you take a look?

**Pull request closed without merging**
