### PR TITLE
ZEPPELIN-2151. Add integration test for livy cancel api

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

Just add integration test for livy cancel api. Only do it for livy 0.3 as the cancel api is only available in livy 0.3

### What type of PR is it?
[ Improvement]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2151

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@felixcheung @prabhjyotsingh Please help review. CI failure is not relevant.

```
Failed tests: 
  NotebookTest.testPublicPrivateNewNote:1173 expected:<2C[A7GB62Y]> but was:<2C[8XKNFD4]>
  NotebookTest.testAuthorizationRoles:759 expected:<false> but was:<true>
```

**Comment by felixcheung** [comment]
looks good, hmm, but the livy 0.3 test is failing 
https://travis-ci.org/zjffdu/zeppelin/builds/204166190
and you are saying it's not related to this? shall we kick it off one more time to see?

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by zjffdu** [comment]
CI continue fail in the same place. But this is not livy relevant, as I didn't change any code outside livy interpreter. I have created ticket ZEPPELIN-2155 for this 

```
Failed tests: 
  NotebookTest.testPublicPrivateNewNote:1173 expected:<2C[B7YJQ16]> but was:<2C[A45Z6X7]>
  NotebookTest.testAuthorizationRoles:759 expected:<false> but was:<true>
```

**Comment by Leemoonsoo** [comment]
Even though test is not directly related to this PR
I have experienced some code change or additional test may break other test, because of resource consumption or other unexpected reason.

Once master branch CI fails, it'll impact all other pullrequest review/verification.

If it change is not super urgent, i suggest we first figure out CI problem and then merge this code after the fix.

**Comment by felixcheung** [comment]
one failure: https://travis-ci.org/zjffdu/zeppelin/jobs/204447551

**Comment by zjffdu** [comment]
ping @felixcheung CI is passed

**Comment by felixcheung** [comment]
merged to master

**Pull request closed without merging**
