### PR TITLE
[ZEPPELIN-1256][BUILD] Build distribution package with Spark 2.0 and Scala 2.11

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
- build distribution package with Spark 2.0 and Scala 2.11
- change travis profile to use spark 2.0 instead of 2.0.0-preview by removing `-Dspark.version=2.0.0-preview` property
- Change profile activation rule 
  * current way of profile activation is not proper for supporting more than three scala version
  * -Pscala-2.11 activates both scala-2.10 and scala-2.11 profile without this patch

### What type of PR is it?
Build

### What is the Jira issue?
[ZEPPELIN-1256](https://issues.apache.org/jira/browse/ZEPPELIN-1256)

### How should this be tested?

**Before**
Run `mvn help:active-profiles -Pscala-2.11`:
   ```
Active Profiles for Project 'org.apache.zeppelin:zeppelin:pom:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-interpreter:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-zengine:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-display_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-display_2.11:0.7.0-SNAPSHOT)
 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-spark-dependencies_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - spark-2.0 (source: org.apache.zeppelin:zeppelin-spark-dependencies_2.11:0.7.0-SNAPSHOT)
 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-spark_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - exclude-sparkr (source: org.apache.zeppelin:zeppelin-spark_2.11:0.7.0-SNAPSHOT)
 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-markdown:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-angular:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-shell:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-livy:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-hbase:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-postgresql:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-jdbc:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-file:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-flink_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-ignite_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-kylin:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-python:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-lens:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-cassandra_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-elasticsearch:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-alluxio:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-web:war:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-server:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-server:0.7.0-SNAPSHOT)
 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-distribution:pom:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-distribution:0.7.0-SNAPSHOT)
 - scala-2.10 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
```

**After**
Run `mvn help:active-profiles -Dscala-2.11`:
   ```
Active Profiles for Project 'org.apache.zeppelin:zeppelin:pom:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-interpreter:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-zengine:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-display_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-display_2.11:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-spark-dependencies_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - spark-2.0 (source: org.apache.zeppelin:zeppelin-spark-dependencies_2.11:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-spark_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - exclude-sparkr (source: org.apache.zeppelin:zeppelin-spark_2.11:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-markdown:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-angular:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-shell:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-livy:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-hbase:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-postgresql:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-jdbc:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-file:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-flink_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-ignite_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-kylin:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-python:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-lens:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-cassandra_2.11:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-elasticsearch:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-alluxio:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-web:war:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-server:jar:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-server:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)



Active Profiles for Project 'org.apache.zeppelin:zeppelin-distribution:pom:0.7.0-SNAPSHOT':

The following profiles are active:

 - scala-2.11 (source: org.apache.zeppelin:zeppelin-distribution:0.7.0-SNAPSHOT)
 - scala-2.11 (source: org.apache.zeppelin:zeppelin:0.7.0-SNAPSHOT)
```

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? yes (for scala 2.11 build)

### CODE REVIEW

**Comment by felixcheung** [comment]
shouldn't we only change scala version to Spark 2.0.0? I think earlier spark releases have limited support for scala 2.11.

**Comment by minahlee** [comment]
@felixcheung I added description 99d91bf for the user who uses Spark version earlier than 2.0.0. And planning to add [zeppelin-spark_2.10 installation link](https://github.com/minahlee/zeppelin/blob/99d91bf1a508c5f398cb4775ef5e374245172c37/docs/manual/interpreterinstallation.md#install-spark-interpreter-built-with-scala-2.10) in download page too.
What do you think?

**Comment by bzz** [comment]
Looks great to me! Thank you @minahlee

**Comment by minahlee** [comment]
I made some changes in maven profile activation rule in ff034c6 and updated description. Can someone review this?

**Comment by anthonycorbacho** [comment]
LGTM

**Comment by minahlee** [comment]
Merge if there is no further discussion

**Pull request closed without merging**
