### PR TITLE
[ZEPPELIN-1274]Write "Spark SQL" in docs rather than "SparkSQL"

### PR DESCRIPTION
**Pull request by sarutak**
### What is this PR for?
Some of the doc files say "SparkSQL" but the collect spelling is "Spark SQL" (need a white space between "Spark" and "SQL").
Lets's replace it with the collect one.

### What type of PR is it?
Improvement 

### Todos
* [x] - Replace all of "SparkSQL" in some files into "Spark SQL". 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1274

### How should this be tested?
Check the changes by some people.

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@sarutak Thanks for fixing this. I found more `SparkSQL` in the below 2 files. 
 - [docs/manual/dynamicform.md#using-form-templates](https://github.com/apache/zeppelin/blob/master/docs/manual/dynamicform.md#using-form-templates)
 - [docs/interpreter/livy.md#configuration](https://github.com/apache/zeppelin/blob/master/docs/interpreter/livy.md#configuration)

Could you change them as well? :)

**Comment by sarutak** [comment]
@AhyoungRyu Thanks for the notification. I'll fix them soon.

**Comment by AhyoungRyu** [comment]
@sarutak Looks good. Thanks!

**Comment by jongyoul** [comment]
Merging if there's no more discussion

**Pull request closed without merging**
