### PR TITLE
[MINOR] Enable pyspark test in local mode

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Enabling test for pyspark in local mode

### What type of PR is it?
[Improvement]

### Todos
* [x] - Add spark configuration and
* [x] - Edit a logic for finding spark home 

### What is the Jira issue?
N/A

### How should this be tested?
1. Download spark under {ZEPPELIN_HOME}
1. run `testing/startSparkCluster.sh`
1. `mvn clean package -Pspark-1.6 -Ppyspark -Pyarn -DskipTests`
1. Run `ZeppelinSparkClusterTest`

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me!

CI fails on
```
[INFO] Zeppelin: Display system apis ...................... FAILURE [ 24.426 s]

[31m- should provide onclick method *** FAILED ***[0m
[31m  The code passed to eventually never returned normally. Attempted 1 times over 361.487655 milliseconds. Last failure message: 0 was not equal to 1. (AbstractAngularElemTest.scala:72)[0m
[32mAngularElem[0m

[36mTests: succeeded 17, failed 1, canceled 0, ignored 0, pending 0[0m
[31m*** 1 TEST FAILED ***[0m
```

Have you seen this before is it completely random flaky test?

**Comment by jongyoul** [comment]
I've seen it for the first time. Do you have any hint to deal with?

**Comment by Leemoonsoo** [comment]
LGTM. 

CI failure is flaky one. i've seen it couple of times.

**Comment by jongyoul** [comment]
Thanks. I'll merge it

**Pull request closed without merging**
