### PR TITLE
ZEPPELIN-4377 (0.8) Interpreter doesn't start if its name has space

### PR DESCRIPTION
**Pull request by alexott**
### What is this PR for?

We can create new interpreters based on existing ones, but we don't enforce its name, so
it's possible to enter it with space and other characters, that aren't handled correctly
by Bash.

This PR fixes this problem.

### What type of PR is it?
Bug Fix

### What is the Jira issue?

* ZEPPELIN-4377

### How should this be tested?

* Tested manually

### CODE REVIEW

**Comment by alexott** [comment]
build for 0.8 branch: https://travis-ci.org/alexott/zeppelin/builds/597227676

**Comment by zjffdu** [comment]
@alexott Some tests are failed, probably due to flaky test, could you re-trigger them ?

**Comment by alexott** [comment]
@zjffdu it's still failing at the same test:

```
Failed tests: 
  PersonalizeActionsIT.testGraphAction:251 The output of graph mode is not changed
Expected: "fa fa-bar-chart"
     but: was "fa fa-table"
```

but it shouldn't have a relation to my change (imho)

**Comment by zjffdu** [comment]
@alexott I have merged this PR, could you close it ?

**Pull request closed without merging**
