### PR TITLE
[HOTFIX] fix build spark and R interpreters

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Fix build interpreters (apark and R) which broken after https://github.com/apache/zeppelin/pull/2592 and 
https://github.com/apache/zeppelin/pull/2596

### What type of PR is it?
[Hot Fix]

### How should this be tested?
build interpreters

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
@necosta @zjffdu @felixcheung 
pls help with review

**Comment by jongyoul** [comment]
LGTM. I'll merge it as a hotfix. BTW, I think it would be better to divide two different PR by fixing bug and refactoring somethings.

**Comment by felixcheung** [comment]
Ok thanks for fixing this.

**Comment by zjffdu** [comment]
Thanks @tinkoff-dwh for fixing this. Could you let me know how SparkRInterpreter is broken, I am curious to know why our CI didn't catch this.

**Comment by jongyoul** [comment]
I’m also curious about it. It’s very basic error when compiling without symbol.

**Comment by tinkoff-dwh** [comment]
@jongyoul @zjffdu 
after merge https://github.com/apache/zeppelin/pull/2596
https://github.com/apache/zeppelin/pull/2596/files#diff-dbda0c4083ad9c59ff05f0273b5e760fR935

`property.getProperty...`

**Comment by jongyoul** [comment]
Yes, what I wondered is how that PR passed our CI. `property` doesn't exist in the class and it shouldn't have passed CI. May we have a hole on our CI?

**Comment by tinkoff-dwh** [comment]
@jongyoul 
this branch has no conflicts with branch master. In CI all ok, because branch of PR has field property. After merge jobs falls (CI, branch master) https://travis-ci.org/apache/zeppelin/builds/291922211?utm_source=github_status&utm_medium=notification

**Comment by jongyoul** [comment]
Yes, I know the current situation and this PR solves what kind of problem, but our merge script uses squash merge from PR branch and it means if that PR branch has `property` in that branch, it would have been merged by our merge script, otherwise if that PR branch doesn't have `property` in that branch, CI would fail. But AFAIK, that branch doesn't have `property` but CI passed. I just wanted to know how it happens.

**Pull request closed without merging**
