### PR TITLE
[ZEPPELIN-1637] Add button for "create next block as copy of this block"

### PR DESCRIPTION
**Pull request by krskoondra**
### What is this PR for?
Added new buttton "Copy paragraph" near run button. This new button create copy of current paragraph and insert it below current paragraph. For this function is also added new keyboard shortcut ctrl+shift+c.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1637

### How should this be tested?
Write something into paragraph and click on button "Copy paragraph".

### Screenshots (if appropriate)
screanshot
Click on button “Clone this paragraph” to create copy of this paragraph and insert it below this paragraph with opened editor:
screanshot 2
And keyboard shortcuts:
screanshot shortcut

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Top right corner of each paragraph was pretty crowded in early days of Zeppelin.
Run, Move up, Move down, Delete, Show title, Show codes, Hides output, and so on.

Because it was too crowded, we decided to move most of them under dropdown menu of the paragraph. 

Shell we move this button into dropdown menu and assign keyboard short cut instead?

**Comment by AhyoungRyu** [comment]
Thanks for updatding description! 
Agree with @Leemoonsoo. And FYI, you can refer #1686 for assigning keyboard shortcut :D

**Comment by krskoondra** [comment]
OK, @Leemoonsoo, the button is now in the dropdown menu of the paragraph and new keyboard shortcut ctrl+shift+c is added.

**Comment by epahomov** [comment]
Yeaaa, I love it!

**Comment by Leemoonsoo** [comment]
Thanks @krskoondra for the contribution.
LGTM.

merge to master if there're no more discussions.

**Comment by krskoondra** [comment]
Someone help me. How can I resolve "This branch has conflicts that must be resolved"?
I'm beginner with opensorce and github.
Thanks.

**Comment by Leemoonsoo** [comment]
If i assume your remote name for Zeppelin repository is `apache-github` (you can check it by running `git remote -v`), 

First, fetch Zeppelin repo (to get latest master) with `git fetch apache-github`, and then rebase or merge the master branch to your branch `git rebase apache-github/master` or `git merge apache-github/master`. Then git will ask you resolve conflict. After resolve all the conflicts you can push the new commit in this branch.

**Comment by Leemoonsoo** [comment]
CI test failed with 
```
Results :

Tests in error: 
  ParagraphActionsIT.testRemoveButton:155->AbstractZeppelinIT.clickAndWait:131 » ElementNotVisible
  ParagraphActionsIT.testMoveUpAndDown:200->AbstractZeppelinIT.clickAndWait:131 » ElementNotVisible
  ParagraphActionsIT.testCreateNewButton:85 » ElementNotVisible Element is not c...
  ZeppelinIT.testAngularDisplay:157->AbstractZeppelinIT.waitForText:84 » StaleElementReference

Tests run: 18, Failures: 0, Errors: 4, Skipped: 0
```
screenshot from ci server
image

I don't think this PR caused the error but to make sure, could you trigger CI build again?
You can add commit or close/open this pullrequest to trigger CI build.

**Comment by Leemoonsoo** [comment]
@krskoondra Thanks for the nice feature.
Merge to master if there're no further discussions.

**Comment by Leemoonsoo** [comment]
@krskoondra Could you let me know you apache JIRA id? 
so i can assign you in this https://issues.apache.org/jira/browse/ZEPPELIN-1637 issue and resolve.

**Comment by krskoondra** [comment]
@Leemoonsoo my id is krskoondra.

**Pull request closed without merging**
