### PR TITLE
[ZEPPELIN-3263] Do not use Firefox >=55 for integration testing

### PR DESCRIPTION
**Pull request by mephi42**
### What is this PR for?
According to https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide , Firefox versions 55+ do not work with Selenium, so I would like to propose to skip them when creating the WebDriver.

### What type of PR is it?
Improvement

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3263

### How should this be tested?
* Run zeppelin-integration tests on the machine, where Firefox 55+ is installed.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@mephi42 It still fails, could you help take a look at it ? The selenium test is flaky, very appreciated you could help on that.

**Comment by mephi42** [comment]
@zjffdu I'm currently trying to stabilize them on my local machine. There are still a couple things that need debugging - the worst one being that sometimes click() on e.g. Login button produces no effect.

@felixcheung, to me this is a useful safeguard when running locally and new Firefox is by accident in $PATH.

**Comment by mephi42** [comment]
I just pushed my WIP branch. With those changes things look better locally, but there are still issues.

**Comment by zjffdu** [comment]
Thanks @mephi42 looking forward more progress.

**Comment by prabhjyotsingh** [comment]
I understand Selenium, Gecko, WebExtensions are constantly evolving. However, with this (https://github.com/apache/zeppelin/pull/2826/files), I'm able to make all the Selenium test case pass on FF-58. This PR is still work in progress. 

Also, there is stuff that will get fixed with FF-59.

**Comment by mephi42** [comment]
Another update. This is now more than just FF>=55 disablement, so maybe I should rename the pull request. I tried to split the work into meaningful chunks, so if you think some commits are worth integrating right away, I can send them as separate pull requests.

**Comment by jongyoul** [comment]
ping @mephi42

**Comment by jongyoul** [comment]
@mephi42 ping. Do you have any progress on it?

**Comment by mephi42** [comment]
Hi @jongyoul, sorry, I'm afraid I won't have time to finish this anytime soon. That said, the first 7 patches, which improve stability and performance of the test suite, are ready as far as I'm concerned. Maybe you could give them a try and get them in in case they look good?

**Pull request closed without merging**
