### PR TITLE
ZEPPELIN-1063: fix flaky python interpreter test

### PR DESCRIPTION
**Pull request by bzz**
### What is this PR for?
fix flaky python interpreter test

### What type of PR is it?
Bug Fix

### Todos
* [x] cleanup test code
* [x] fix flaky open port check

### What is the Jira issue?
[ZEPPELIN-1063](https://issues.apache.org/jira/browse/ZEPPELIN-1063)

### How should this be tested?
`mvn "-Dtest=org.apache.zeppelin.python.PythonInterpreterTest" test -pl python`

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
Ready to be merged, \cc @minahlee @prabhjyotsingh for review.

CI failure is being taken care of under #1092

**Comment by bzz** [comment]
Rebased on latest master, after #1092 got merged

**Comment by bzz** [comment]
CI fails on Integration tests, and failure looks different from #1091 and #1092 

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 143.455 sec - in org.apache.zeppelin.integration.ZeppelinIT

Results :

Tests in error: 
  ParagraphActionsIT.testClearOutputButton:285->AbstractZeppelinIT.waitForParagraph:70->AbstractZeppelinIT.pollingWait:96 Â» Timeout

Tests run: 15, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by bzz** [comment]
CI failure is not related and handled under [ZEPPELIN-1073](https://issues.apache.org/jira/browse/ZEPPELIN-1073)
Merging if there is no further disucssion

**Comment by prabhjyotsingh** [comment]
Yes, I've seen this, this happens when spark takes longer that 60sec to start up. 
Will open up a new jira and fix this as well.

**Pull request closed without merging**
