### PR TITLE
[ZEPPELIN-4152]. Use spark 2.2 as the default profile

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Trivial PR to use spark 2.2 as the default profile so that the default build command can pass

```
mvn clean package -DskipTests
```

### What type of PR is it?
[ Improvement ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4152

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Unfortunately, spark 2.3 doesn't support scala 2.10 which is default profile.

**Comment by felixcheung** [comment]
hm. I guess we need a plan to move to 2.11

**Comment by zjffdu** [comment]
I tried to do that, but some other interpreters don't support scala-2.11. So it would take much more time to support scala-2.11 fully in zeppelin. I plan to move some interpreter out of zeppelin project to subproject, so that each interpreter can has its own build environment and dependency. This PR is a temporary solution before that

**Comment by felixcheung** [comment]
sure, this could be a big problem...

**Comment by felixcheung** [comment]
LGTM

**Pull request closed without merging**
