### PR TITLE
Add force layout visualization in paragraphs for SQL queries

### PR DESCRIPTION
**Pull request by davidtzoor**
### What is this PR for?
Add force layout (graph) visualization to the existing set of visualizations in Zeppelin Web notp. 

### What type of PR is it?
[Feature]

### What is the Jira issue?
[ZEPPELIN-1011]

### How should this be tested?
The testes are incorporated within the existing test suite. 

### Screenshots (if appropriate)
eeffbb58-3238-11e6-92ea-148a4063d353

### Questions:
* Does the licenses files need update?
No.
* Is there breaking changes for older versions?
No.
* Does this needs documentation?
We can add some documentation explaining about the different fields that need to be selected in order to generate the force layout component.

### CODE REVIEW

**Comment by davidtzoor** [comment]
@corneadoug I recreated the PR after doing the rebasing from scratch and it now has no conflict. Hope it works out this time.

**Comment by corneadoug** [comment]
@davidtzoor Thank you.
You might have the problem again considering you made your PR based on your master branch.
Using a custom branch is usually safer, for example right now until this PR is merged, you should not add any changes that differ from Apache Zeppelin source code and is non-related to this PR.

If you do have to do a rebase again, try doing this while in your master:
* `git fetch zeppelinOriginalRepo`
* `git rebase zeppelinOrignalRepo/master`
* resolve conflicts
* `git push`or `git push -f`

**Comment by corneadoug** [comment]
@davidtzoor Seems it is really not working, please create a branch for your PR
(`git checkout -b nameOfMyBranch`)

**Comment by bzz** [comment]
Now this PR contains some commits that do not belong here, and it either needs to be re-created from a separate branch as @corneadoug points out, or interactively rebased with keeping only good commits here

**Comment by davidtzoor** [comment]
Sorry for the mess. I will create a new branch with the commits and reopen a new pull request. Thank you for your help

**Comment by davidtzoor** [comment]
@corneadoug I created a new pull request (#1044) from a different branch (not `master`).
I am closing this issue. Thank you for your patience and help :smile_cat:

**Pull request closed without merging**
