### PR TITLE
[ZEPPELIN-5693] IPythonInterpreterTest.testIPythonPlotting fails due to jinjia2 version upgrade

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

Specify the jinjia2 version explicitly so that we won't get the error described in the jira. 

### What type of PR is it?
[Bug Fix ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5693

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Review by jongyoul — APPROVED** [review]

**Comment by zjffdu** [comment]
Thanks for  the review @jongyoul , will merge it soon as it block other PRs

**Comment by jongyoul** [comment]
BTW, for merging it, we are still using our script instead of using `Squash and merge`?

**Comment by zjffdu** [comment]
I think both approaches work, do you notice any problems? @jongyoul

**Comment by jongyoul** [comment]
Nope. I didn't find any trouble but I just would like to confirm which one we are using it. Thank you for clarifying it.

**Pull request closed without merging**
