### PR TITLE
[ZEPPELIN-6110][FOLLOWUP] Regenerate `package-lock.json`

### PR DESCRIPTION
**Pull request by pan3793**
### What is this PR for?

`package-lock.json` content changed after performing `npm install`.

### What type of PR is it?

Improvement

### What is the Jira issue?

ZEPPELIN-6110

### How should this be tested?

Pass CI.

### Questions:
* Does the license files need to update? No.
* Is there breaking changes for older versions? No.
* Does this needs documentation? No.

### CODE REVIEW

**Review by tbonelee — APPROVED** [review]
LGTM. I ran `npm i` and confirmed that the updated `package-lock.json` matches the version in the PR.

**Comment by pan3793** [comment]
@tbonelee thank you for taking a look. I appreciate your expertise in the frontend stack, do you have an opportunity to investigate upgrading angular to a modern version?

**Comment by tbonelee** [comment]
@pan3793 I'm not super familiar with Angular, but I'm happy to give it a shot. I'll try to make some time soon to look into it.

**Comment by pan3793** [comment]
@tbonelee thank you in advance, btw, apache flink uses the same fe stack and is well maintained, there may be something we can refer to.

**Comment by jongyoul** [comment]
@tbonelee @pan3793 Yeah ~ I are always welcome FE improvement :-) Thank you all

**Review by jongyoul — APPROVED** [review]

**Comment by pan3793** [comment]
Merged to master/0.12

**Pull request merged**
