### PR TITLE
[HOTFIX] fix interpreter.cmd script

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
interpreter.cmd works incorrect after https://github.com/apache/zeppelin/pull/2562

### What type of PR is it?
Bug Fix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
@jongyoul @zjffdu 
can you help with review?

**Comment by jongyoul** [comment]
LGTM

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by zjffdu** [comment]
Merge if no more discussion

**Pull request closed without merging**
