### PR TITLE
Lens Interpreter

### PR DESCRIPTION
**Pull request by praagarw**

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
This is really great work!

One comment, you probably want to add Lens interpreter in conf/zeppelin-site.xml.template, zeppelin.interpreters property.

**Comment by Leemoonsoo** [comment]
@praagarw, Everything looks good and only missing thing i think is adding `org.apache.zeppelin.lens.LensInterpreter` into conf/zeppelin-site.xml.template. If you could add it, i think it's ready to go.

Please don't worry about code conflict with current master branch. I can take care when merging the code.

**Comment by praagarw** [comment]
@Leemoonsoo  I added org.apache.zeppelin.lens.LensInterpreter to  conf/zeppelin-site.xml.template. Howerver tests are failing. Can you please take this forward.

**Comment by Leemoonsoo** [comment]
@praagarw I have clean up the branch and created new PR #114. If you think everything is good, let's close this PR and merge #114

**Comment by simhan** [comment]
getting following error with latest build .
Zeppelin: Apache Ignite interpreter ................ SUCCESS [  0.370 s]
[INFO] Zeppelin: Lens interpreter ......................... FAILURE [  0.049 s]
[INFO] Zeppelin: web Application .......................... SKIPPED
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.540 s
[INFO] Finished at: 2015-07-19T04:50:14+00:00
[INFO] Final Memory: 97M/980M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project zeppelin-lens: Could not resolve dependencies for project org.apache.zeppelin:zeppelin-lens:jar:0.6.0-incubating-SNAPSHOT: The following artifacts could not be resolved: org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT, org.apache.lens:lens-client:jar:2.2.0-beta-incubating-SNAPSHOT: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project zeppelin-lens: Could not resolve dependencies for project org.apache.zeppelin:zeppelin-lens:jar:0.6.0-incubating-SNAPSHOT: The following artifacts could not be resolved: org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT, org.apache.lens:lens-client:jar:2.2.0-beta-incubating-SNAPSHOT: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.apache.zeppelin:zeppelin-lens:jar:0.6.0-incubating-SNAPSHOT: The following artifacts could not be resolved: org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT, org.apache.lens:lens-client:jar:2.2.0-beta-incubating-SNAPSHOT: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT, org.apache.lens:lens-client:jar:2.2.0-beta-incubating-SNAPSHOT: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT, org.apache.lens:lens-client:jar:2.2.0-beta-incubating-SNAPSHOT: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.apache.lens:lens-cli:jar:2.2.0-beta-incubating-SNAPSHOT in https://github.com/InMobi/mvn-repo/raw/master/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of inmobi.snapshots has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-lens

**Comment by btiernay** [comment]
Yep, I'm getting the same on master

**Comment by praagarw** [comment]
Fixed the build failure is pull request https://github.com/apache/incubator-zeppelin/pull/159

**Comment by jongyoul** [comment]
@praagarw Could you please this PR?

**Pull request closed without merging**
