### PR TITLE
[ZEPPELIN-5572] resolve the websocket deadlock problem 

### PR DESCRIPTION
**Pull request by xiejiajun**
### What is this PR for?
- The org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint#blockingWrite method has been to ensure that the websocket sends messages serially by `ReentrantLock` and `WriteBlocket`, so the NotebookSocket.send method does not need to be locked.
- If we lock the NotebookSocket.send method, the NotebookServer#onClose method will be triggered when the NotebookSocket.send method sends a message abnormally. At this time, if there are other threads that need to send messages through the current Websocket Session to preempt the noteSocketMap lock in the ConnectionManager,  It will trigger a deadlock.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* [ZEPPELIN-5572](https://issues.apache.org/jira/browse/ZEPPELIN-5572)

### How should this be tested?
* CI

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Reamer** [comment]
Please rebase to the current master. I have added a hotfix.

**Comment by xiejiajun** [comment]
> Please rebase to the current master. I have added a hotfix.

done

**Comment by Reamer** [comment]
I also found deadlocks in the application after JSR356 was adapted for Websocket.
I think the synchronised is a relic from the [old code](https://github.com/apache/zeppelin/commit/575df6890ea0349314c8f23a5c19c758779ea9f7#diff-dec5ec785ce8a55940664b101105bccd19b2d8c3c335eef5432eb4f8edf063faL69).

I checked the `WebSocketRemoteEndpoint` implementation and you should be right.

This PR LGTM

**Comment by Reamer** [comment]
If no further comments are received, I will merge this PR into the master on Thursday.

**Review by Reamer — APPROVED** [review]

**Pull request closed without merging**
