### PR TITLE
[ZEPPELIN-4934] add jars to sys.path as done in pyspark shell

### PR DESCRIPTION
**Pull request by dbanda**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html

Some jars include python code. These must be added to sys.path to support importing those packages in python.

pyspark include these jars to the path at context initialization. From the spark repo see:

* core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
* python/pyspark/context.py
* python/pyspark/shell.py

In pyspark, the jars passed with "–packages" are passed onto "spark.submit.pyFiles" (in prepareSubmitEnvironment function) and then added to sys.path by the context initialization.

### What type of PR is it?

Bug Fix

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-4934

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by zjffdu** [comment]
LGTM

**Comment by zjffdu** [comment]
@dbanda It would be better to add unit test in `ZeppelinSparkClusterTest`

**Comment by zjffdu** [comment]
Thanks @dbanda for adding the unit test, could you paste the travis CI link ? Need to make sure CI pass before emerging

**Comment by dbanda** [comment]
@zjffdu https://travis-ci.org/github/dbanda/zeppelin/builds/705285429 some of the other tests are flaky and fail from time to time. I hope you are aware of that. I see there is an open issue task https://issues.apache.org/jira/browse/ZEPPELIN-1981

**Comment by zjffdu** [comment]
@dbanda Right，this is flaky test, CI LGTM, will merge if no more comment

**Pull request closed without merging**
