### PR TITLE
[ZEPPELIN-1876] smart psql autocomplition

### PR DESCRIPTION
**Pull request by sotnich**
### What is this PR for?
This PR changes autocompletion behaviour in postgresql interpeter.
There are some changes:
* [main change] autocompletion now depends on what are you typing. Now there are four types of competion: schema, table, column and keywords. If you typing new word then autocompetion suggests only keywords and schema names. If you are typing after schema name with point then you get list of tables in that schema. Also if you typing a name after point after a table name you will get a list of column names of this table.
* autocomption now supports aliases in sql. If you write alias for a table you will get a list of columns of an aliased table if you write down the alias and a point.
* new option are availble for postgresql interpreter: postgresql.completer.schema.filter. It allows filter schema names loaded into autocompletion (no more garbage schema names).
* autocompletion now load keywords only in low case (otherwise there are so many keywords in a list of autocompletion that it is becomes uncomfortable)

### What type of PR is it?
Improvement

### Todos
* [ ] - sort names in the output of autocompletion
* [ ] - list only schema names if we are typing a schema name (for example after keywork FROM)
* [ ] - add description in autocompletion list for schema names - schema, for table names - table and so

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1876

### How should this be tested?
Outline the steps to test the PR here.

### Screenshots (if appropriate)
https://issues.apache.org/jira/secure/attachment/12845228/auto1.JPG
https://issues.apache.org/jira/secure/attachment/12845229/auto2.JPG
https://issues.apache.org/jira/secure/attachment/12845230/auto3.JPG

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by sotnich** [comment]
Looks like CI error does not have any relation with my PR. Could anyone confirm that?

**Comment by jongyoul** [comment]
@sotnich Thanks for the contribution. We, however, merged all functions of PSQLInterpreter into JDBCInterpreter and will remove PSQLInterpreter sooner. I'm very happy to adopt this function into JDBCInterpreter. Do you mind handling it?

**Comment by sotnich** [comment]
@jongyoul , sure, I will do it. I'll close this PR and will open a new one.

**Comment by jongyoul** [comment]
@sotnich Thanks!! Please link this issue into the new PR.

**Pull request closed without merging**
