### PR TITLE
[ZEPPELIN-1363] Note level dynamic form

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Added dynamic forms for Note. All paragraphs has access to note forms. 

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1363

### How should this be tested?
Create global interpreter JDBC and Spark. Create note with 2 paragraphs
```
%pyspark

print("Textbox paragraph " + z.textbox('input', 'default'))
print("Textbox note " + z.noteTextbox('note_input', 'default_note'))

print("Select paragraph " +  z.select("sel", [("1","opt1"), ("2","opt2"), ("3","opt3")]))
print("Select note " +  z.noteSelect("sel_note", [("1","noteOpt1"), ("2","noteOpt2"), ("3","noteOpt3")]))

options = [("key1","Name1"), ("key2","Name2")]
print("Checkbox paragraph "+ " and ".join(z.checkbox("chk", options, ["key1"])))
print("Checkbox note "+ " and ".join(z.noteCheckbox("chk_note", options, ["key1","key2"])))
```
```
%jdbc

select '$${checkbox:chk_note=key1|key2,key1|key2}   $${note_input} ${note_input=sameName}'
```

### Screenshots (if appropriate)
1) native forms

2) remove 

3) simple forms

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
@Leemoonsoo 
Pls help review it

**Comment by Leemoonsoo** [comment]
Cool! @tinkoff-dwh Thanks for the new feature!

I tried and it works well. I have some comments on it's behavior.

1. form value is not updated without pressing 'ENTER'
zeppelin_note_dynamic

When there're changes on note level form, run any paragraph reset those changes. I think applying change on paragraph run more make sense?

2. Run on 'ENTER'
zeppelin_note_dynamic_2

Paragraph level dynamic form by default run paragraph on 'ENTER'.
Note level dynamic form does not run note on 'ENTER'. I think this behavior is little bit inconsistent. 
What do you think?

**Comment by tinkoff-dwh** [comment]
yep. 
Note level forms works like as paragraph forms, but action 'Save changes' except `Run paragraph'.

Paragrap input (Enter) -> Note input (Enter)
run paragraph -> save changes of note input 


Paragrap select (select value) -> Note select (select value)
run paragraph -> save changes of note select

Start all paragraphs can be long, so I think it is better to delegate this action (run all or one paragraph) to the user.


Paragrap checkbox (select check) -> Note checkbox (check)
run paragraph -> save changes of note checkbox

**Comment by tinkoff-dwh** [comment]
@Leemoonsoo 
yep.
Note level forms works like as paragraph forms, but action 'Save changes' except `Run paragraph'.

Paragrap input (Enter) -> Note input (Enter)
run paragraph -> save changes of note input

Paragrap select (select value) -> Note select (select value)
run paragraph -> save changes of note select

Start all paragraphs can be long, so I think it is better to delegate this action (run all or one paragraph) to the user.

Paragrap checkbox (select check) -> Note checkbox (check)
run paragraph -> save changes of note checkbox

**Comment by Leemoonsoo** [comment]
1. Input dynamic form create
2. Update dynamic form value (without ENTER)
3. Run paragraph

Paragraph level dynamic form run paragraph with updated value. But Note level dynamic form reset update and run paragraph with previous value. I think it make more sense to note level dynamic form also run paragraph with updated value in this case.

> Start all paragraphs can be long, so I think it is better to delegate this action (run all or one paragraph) to the user.

I agree. 

It would be more convenient if Note level dynamic form displays "Save (dynamic form change)", "Run notebook", "Reset (dynamic form change)" buttons when user update Note level dynamic form.

Currently, user need to discover and learn default behavior different between paragraph level and note level dynamic form by trial. And this trial may take some time depend on people. Showing those buttons give informations about expected behavior of note level dynamic form and helps understand behavior immediately after user make changes on the form value. What do you think?

**Comment by tinkoff-dwh** [comment]
@Leemoonsoo 
I propose to do:
 - auto save for all forms (select, checkbox, textbox)
 - add short description in header 
    (Note forms)
    You can use these forms in your paragraphs

Adding buttons would be a duplicate (we have autosave of forms and there is a button to Run all paragraphs)

**Comment by Leemoonsoo** [comment]
@tinkoff-dwh sounds like a plan!

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by Leemoonsoo** [comment]
Merge to master if no further review.

**Comment by mjmeyer** [comment]
Built 0.8.0 and see this working in md and pyspark interpreters. 

```
%md
projectName: $${projectName}  
```

```
%pyspark
print("ProjectName " + z.noteTextbox('projectName'))
```

How to reference a note level form field from spark or spark.sql interpreters???
```
%spark
println("Hello:" + z.noteTextbox("projectName"))
```
Causes a paragraph level input field to be rendered  in this para, ignoring the one with same name at the top of the note.

**Pull request closed without merging**
