### PR TITLE
[ZEPPELIN-5193] describe table with full table name in flink sql can not work

### PR DESCRIPTION
**Pull request by fforever14**
### What is this PR for?
fix bug: Describe table using full table name in FlinkSQL can not work

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5193

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks for the contribution @fforever14  Could you add one unit test here ? I think you can just call `describe default.source_table`
https://github.com/apache/zeppelin/blob/master/flink/interpreter/src/test/java/org/apache/zeppelin/flink/SqlInterpreterTest.java#L251

**Comment by zjffdu** [comment]
ping @fforever14

**Comment by fforever14** [comment]
Sorry. I didn't check github these days due to recent work.
I will add test code this weekend.

**Comment by zjffdu** [comment]
Thanks @fforever14

**Comment by fforever14** [comment]
I have added the test code. But I'm in trouble with running it.
When I run maven test, it will download some metadatas from apache repository in 0.9.1-SNAPSHOT directory, but I checked the url, It didn't contain this directory.
Could you provide any document about how to run the test?

**Comment by zjffdu** [comment]
> I have added the test code. But I'm in trouble with running it.
> When I run maven test, it will download some metadatas from apache repository in 0.9.1-SNAPSHOT directory, but I checked the url, It didn't contain this directory.
> Could you provide any document about how to run the test?

Try to install it locally first via the following command:
```
mvn clean install -pl zeppelin-server -am
```

Then run the following command to run flink test, enable different flink profile for each flink version (e.g. -Pflink-1.10, -Pflink-1.11, -Pflink-1.12):
```
mvn package -pl flink/interpreter -am  
```

**Comment by fforever14** [comment]
Thank you. I will try it.

**Comment by fforever14** [comment]
I run test with follow command: 

> mvn package -pl flink/interpreter -am -Pflink-111 -Dmaven.gitcommitid.skip=true

but there is a exception when run sql test. the log shot is here:
image

Have I missed some profile or dependency? I haven't a Hadoop nor a Hive environment in my computer, should I install them?

**Comment by zjffdu** [comment]
> I run test with follow command:
> 
> > mvn package -pl flink/interpreter -am -Pflink-111 -Dmaven.gitcommitid.skip=true
> 
> but there is a exception when run sql test. the log shot is here:
> image
> 
> Have I missed some profile or dependency? I haven't a Hadoop nor a Hive environment in my computer, should I install them?

This is a bug which is fixed recently, could you do a rebase and run test again ?

**Comment by zjffdu** [comment]
ping @fforever14

**Comment by fforever14** [comment]
I did a rebase but I got some other dependency errors.
My computer was not with me these days. 😓  
I will show the error today.

**Comment by fforever14** [comment]
I did a rebase but I got this error
image

I think it's a guava dependency error.

**Comment by zjffdu** [comment]
@fforever14 Which command do you run the UT ?

**Comment by fforever14** [comment]
the same as before:

> mvn package -pl flink/interpreter -am -Pflink-111 -Dmaven.gitcommitid.skip=true

**Comment by zjffdu** [comment]
@fforever14 Sorry for late response，It seems you need do it in 2 steps
* run the following command to build flink interpreter module
```
mvn clean install -pl flink/interpreter -Pflink-111 -am -Dmaven.gitcommitid.skip=true -DskipRat
```
* run test
```
mvn test -pl flink/interpreter -Pflink-111 -Dmaven.gitcommitid.skip=true -Dtest=FlinkBatchSqlInterpreterTest -DfailIfNoTests=false -DskipRat
```

BTW, I notice your PR is based on branch-0.9, could you do it based on master ?

**Comment by fforever14** [comment]
I will give a try.
I once asked which branch to resolve bug in 0.9 release version in the DingTalk group.
I will fix this in master branch and open a new pull request after I finish the unit test

**Comment by fforever14** [comment]
open a new PR on master branch, close this one.

**Pull request closed without merging**
