### PR TITLE
[MINOR][ZEPPELIN-2100] Enable to go back to zeppelin.apache.org in docs site 

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
Currently there is no link to go back to [zeppelin.apache.org](https://zeppelin.apache.org) in each docs site. It's a bit inconvenient. 

e.g. In [https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/](https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/), if I click Zeppelin main logo, it keeps me staying in docs main page not the root: [zeppelin.apache.org](https://zeppelin.apache.org).

So I separated main logo in navbar to "Zeppelin" and "version". And linked [production_url](https://github.com/apache/zeppelin/blob/master/docs/_config.yml#L34) and [BASE_PATH](https://github.com/apache/zeppelin/blob/master/docs/_config.yml#L62) to each of them. Please see the below screenshot img.

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZEPPELIN-2100](https://issues.apache.org/jira/browse/ZEPPELIN-2100)

### How should this be tested?
Run docs site locally under `ZEPPELIN_HOME/docs` as described in here: [Run website locally](https://github.com/apache/zeppelin/blob/master/docs/README.md#run-website-locally)

### Screenshots (if appropriate)
In [https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/](https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/),

 - Before 

 - After

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
ah, but that's not very obvious though?

**Comment by AhyoungRyu** [comment]
@felixcheung Yeah agree. But I don't have better idea than this way for now. Will be appreciated if you (or anyone) can suggest :)

**Comment by felixcheung** [comment]
yea not sure. what if we add a new menu next to Quick Start menu?

**Comment by AhyoungRyu** [comment]
Thanks for your suggestion! But as you can see, currently there is no much space between the "version" and "Quick Start" menu.
screen shot 2017-02-13 at 9 04 23 pm

So just using exist main logo and version text is more practical(?) than one more menu button to go back to root page I think. What do you think? :)

**Comment by felixcheung** [comment]
I'm good with either way.
:)

**Comment by AhyoungRyu** [comment]
@felixcheung Thanks anyway for your feedback. 
Then will merge this into branch-0.7 and master if there are no comments!

**Pull request closed without merging**
