### PR TITLE
[ZEPPELIN-1078] Does not show the text result in the paragraph sometimes.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes the problem that does not show the text result in the paragraph sometimes.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1078

### How should this be tested?
Try run python code constantly like screenshot.

### Screenshots (if appropriate)
  - before
before

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by astroshim** [comment]
It seems that the CI fail is related to https://github.com/apache/zeppelin/pull/1084.

**Comment by astroshim** [comment]
re-trigger CI

**Comment by astroshim** [comment]
re-trigger CI

**Comment by bzz** [comment]
So you think `resultRefreshed ` condition is not useful check any more?

\cc @felizbear @corneadoug for review

**Comment by astroshim** [comment]
@bzz Thank you for reviewing.
I think ```resultRefreshed``` condition causes bug and I don't know why it needs.
@corneadoug @felizbear please review.

**Comment by corneadoug** [comment]
I'm currently writing a giant review as I'm testing things

**Comment by corneadoug** [comment]
@bzz @astroshim 
Took me quite some time to dig into this.

Removing `resultRefreshed` would have negative performances effect, its original goal is to not re-render things if there was no change. however its condition isn't that great and a better one would be: `!angular.equals(data.paragraph.result, $scope.paragraph.result);`

A quick fix is indeed to remove `resultRefreshed`, but from this condition only `else if (newType === 'TEXT' && resultRefreshed) {`

The overall issue is that the implementation of the streaming feature in interpreters for the TEXT result type is not consistent.

And since the issue is complex and need of lot of explanations, I will create a separate issue.

We can keep this PR as a quick fix

**Comment by astroshim** [comment]
@corneadoug 
I thought it might be impacted but I didn't find a problem so I was waiting these great review! 

The implementation of the streaming feature in interpreters for the TEXT result type is already a problem because the paragraph results are cleared before rendering result in the ```$scope.renderText = function() { ``` function.

Then in this PR, can I just remove ```resultRefreshed``` from ```else if (newType === 'TEXT' && resultRefreshed) {```?

**Comment by corneadoug** [comment]
@astroshim Yes, its the best way for now

**Comment by astroshim** [comment]
@corneadoug Thank you for making clear. I fixed the code as you advised.

**Comment by astroshim** [comment]
re-trigger CI

**Comment by corneadoug** [comment]
LGTM

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by bzz** [comment]
Thank you for great feedback @corneadoug and prompt fixes @astroshim 

Looks great to me!

**Comment by corneadoug** [comment]
@astroshim Can you rebase with master?

**Comment by astroshim** [comment]
@corneadoug I rebased. thanks.

**Pull request closed without merging**
