### PR TITLE
Fixing zeppelin-2281 by clearing output when data is available

### PR DESCRIPTION
**Pull request by SachinJanani**
### What is this PR for?
Fixing ZEPPELIN-2281 by clearing previous when new data is available

### What type of PR is it?
[Bug Fix]

### Todos
* [x] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-2281

### How should this be tested?
* Execute a paragraph and see the output
* Execute the same paragraph again but abort it before completion and see the output.Paragraph is clear and previous output is lost

### Questions:
* Does the licenses files need update?    NA
* Is there breaking changes for older versions? NA
* Does this needs documentation? NA

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @SachinJanani for contribution.
Could you try setup CI and see it this PR passes the CI build?

```
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
And then make sure 'Build branch updates' option is enabled in the settings https://travis-ci.org/SachinJanani/zeppelin/settings.

To trigger CI after setup, you will need ammend your last commit with
git commit --amend
git push your-remote HEAD --force

See http://zeppelin.apache.org/contribution/contributions.html#continuous-integration.
```

**Comment by SachinJanani** [comment]
@Leemoonsoo  Thanks for the review.Have started the travis build. @felixcheung With this change it will not clear the output if the execution fails and keep the previous output.But if there any exception then it will print them

**Comment by SachinJanani** [comment]
This build is failing due to some environment issue in jenkins can someone please help me out.

**Comment by Leemoonsoo** [comment]
Not sure why CI is failing. @SachinJanani Have you tried restart failed job?

**Comment by SachinJanani** [comment]
Yes @Leemoonsoo I have tried restarting failed job but it didn't succeed :(

**Comment by SachinJanani** [comment]
@Leemoonsoo  Merging the upstream and restarting the travis build did the trick.Here is the travis link for this PR-https://travis-ci.org/SachinJanani/zeppelin/builds/265444667.Can you please merge this PR if there are no more comments

**Comment by Leemoonsoo** [comment]
Thanks @SachinJanani for the fix!

Merge to master and branch-0.7 if no further comments.

**Pull request closed without merging**
