### PR TITLE
[ZEPPELIN-5885] Solve the concurrency clone note

### PR DESCRIPTION
**Pull request by qinbo12**
### What is this PR for?

This pull request migrates solve the concurrency problem caused by multiple concurrent calls to note clone.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?

- [[ZEPPELIN-5885](https://issues.apache.org/jira/browse/ZEPPELIN-5885)]

### How should this be tested?

- Try to build module zeppelin-zengine by command
./mvnw -B -pl 'zeppelin-server,zeppelin-zengine,zeppelin-common,zeppelin-interpreter,zeppelin-jupyter' clean package - 
 DskipTests -Pbuild-distr -Pinclude-hadoop -Phadoop3 -Pweb-angular

### CODE REVIEW

**Comment by Reamer** [comment]
Please open a JIRA ticket. A stack trace of the error would be good in the ticket. It would also be good if you use the pull request template.

**Comment by qinbo12** [comment]
> Please open a JIRA ticket. A stack trace of the error would be good in the ticket. It would also be good if you use the pull request template.

Hello, I have JIRA sheet and provided test case and stack information

**Review by Reamer — APPROVED** [review]
LGTM

**Comment by youshaojun** [comment]
hi~, I tried to use the above modifications, but now occasionally throw java.nio.file.NoSuchFileException
```
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeppelin-0.10.1-bin-all/conf/notebook-authorization.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:60)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:71)
	at org.apache.zeppelin.storage.LocalConfigStorage.save(LocalConfigStorage.java:71)
	at org.apache.zeppelin.notebook.AuthorizationService.saveNoteAuth(AuthorizationService.java:109)
	at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:258)
	at org.apache.zeppelin.service.NotebookService.createNote(NotebookService.java:168)
```
whether this method requires a lock ?

**Comment by youshaojun** [comment]
hi~, I tried to use the above modifications, but now occasionally throw java.nio.file.NoSuchFileException
```
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeppelin-0.10.1-bin-all/conf/notebook-authorization.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:60)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:71)
	at org.apache.zeppelin.storage.LocalConfigStorage.save(LocalConfigStorage.java:71)
	at org.apache.zeppelin.notebook.AuthorizationService.saveNoteAuth(AuthorizationService.java:109)
	at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:258)
	at org.apache.zeppelin.service.NotebookService.createNote(NotebookService.java:168)
```
whether this method requires a lock ?

**Comment by youshaojun** [comment]
hi~, I tried to use the above modifications, but now occasionally throw java.nio.file.NoSuchFileException
```
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeppelin-0.10.1-bin-all/conf/notebook-authorization.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:60)
	at org.apache.zeppelin.util.FileUtils.atomicWriteToFile(FileUtils.java:71)
	at org.apache.zeppelin.storage.LocalConfigStorage.save(LocalConfigStorage.java:71)
	at org.apache.zeppelin.notebook.AuthorizationService.saveNoteAuth(AuthorizationService.java:109)
	at org.apache.zeppelin.notebook.Notebook.createNote(Notebook.java:258)
	at org.apache.zeppelin.service.NotebookService.createNote(NotebookService.java:168)
```
whether this method requires a lock ?

**Comment by Reamer** [comment]
Are you sure it is because of this change?
I think you have another concurrency problem.

**Comment by youshaojun** [comment]
Thanks for your reply.
This pull request migrates solve the concurrency problem caused by multiple concurrent calls to `org.apache.zeppelin.notebook.AuthorizationService#saveNoteAuth`, but this can result in concurrent modifications to `notebook authorization.json`.

image

image

**Comment by Reamer** [comment]
A `synchronized` at the `saveNoteAuth` method should fix the problem. What do you think?

**Comment by youshaojun** [comment]
Yes, i also think.

**Comment by Reamer** [comment]
Feel free to prepare a PullRequest with JIRA ticket. Your StackTrace should be included in the JIRA ticket.

**Comment by youshaojun** [comment]
Mybe a synchronized at the `org.apache.zeppelin.util.FileUtils#atomicWriteToFile(java.lang.String, java.io.File, java.util.Set<java.nio.file.attribute.PosixFilePermission>)`   is a better option.

**Comment by youshaojun** [comment]
Thanks for your reply. I understand.

**Pull request merged**
