### PR TITLE
ZEPPELIN-3207. fix search content not appearing

### PR DESCRIPTION
**Pull request by swkimme**
### What is this PR for?
For some reason search content is not appearing. 
This PR fixes this issue.

### What type of PR is it?
Bug Fix

### Todos
- 

### What is the Jira issue?
ZEPPELIN-3207

### How should this be tested?
try searching with some sentence like 'bank' (it should be included in tutorial notebook)
see search contents is appearing or not

### Screenshots (if appropriate)
screen shot 2018-02-07 at 6 04 52 pm
screen shot 2018-02-07 at 6 06 31 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by swkimme** [comment]
I'm not a web guy, and not sure why 
```_editor.getSession().setValue(lines.join('\n'))```
this part is broken. 

At least I know now it's working with my changes, any comments or help would be appreciated

**Comment by Leemoonsoo** [comment]
Tested and fix works well. But it's getting build failure with following error.

```
[INFO] 
[INFO] /zeppelin/zeppelin-web/src/app/search/result-list.controller.js
[INFO]   151:32  error  Extra semicolon  semi
[INFO] 
```

Could you try remove semicolon?

**Comment by swkimme** [comment]
@Leemoonsoo now it's good to go!

**Comment by Leemoonsoo** [comment]
LGTM! Merge to master and branch-0.8 if no further discussions.

**Pull request closed without merging**
