### PR TITLE
[ZEPPELIN-1202] Documentation typo under writing interpreter docs

### PR DESCRIPTION
**Pull request by zmhassan**
### What is this PR for?
To correct typo found in documentation

### What type of PR is it?
 Documentation

### Todos
* [x] - Replace sentence with incorrect english docs with correction.

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1202

### How should this be tested?
Build docs and see correct docs on `https://zeppelin.apache.org/docs/latest/development/writingzeppelininterpreter.html`
### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
Good catch! I found one more typo in here.
```
[
  {
    "group": "your-group",
    "name": "your-name",
    "className": "your.own.interpreter.class",
    "properties": {
      "propertiies1": {
        "envName": null,
        "propertyName": "property.1.name",
        "defaultValue": "propertyDefaultValue",
        "description": "Property description"
      },
      "properties2": {
        "envName": PROPERTIES_2,
        "propertyName": null,
        "defaultValue": "property2DefaultValue",
        "description": "Property 2 description"
      }, ...
    }
  },
  {
    ...
  } 
]
```

If you don't mind, could you change `propertiies1` -> `properties1` as well?

**Comment by zmhassan** [comment]
Thank you. I believe all pending work on this is complete.

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Comment by minahlee** [comment]
LGTM. CI failure is irrelevant, merge into branch-0.6 and master if there is no more discussion

**Pull request closed without merging**
