### PR TITLE
Adding PySparkInterpreterTest for better test coverage.

### PR DESCRIPTION
**Pull request by bpmcd**
The new test class was modeled after the SparkInterpreterTest and
SparkSqlInterpreterTest classes.

https://issues.apache.org/jira/browse/ZEPPELIN-100

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Awesome. Really great work.

FYI, Recently test for pyspark has been added here https://github.com/apache/incubator-zeppelin/blob/master/zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinSparkClusterTest.java

unlike ZeppelinSparkClusterTest, If we can have test inside of spark interpreter module, it would be great.

**Comment by bpmcd** [comment]
So, are you saying I should move the test methods in PySparkInterpreterTest class to SparkInterpreter class?

**Comment by Leemoonsoo** [comment]
@bpmcd Not really, because of the test methods in ZeppelinSparkClusterTest calls REST api to run the test against running ZeppelinServer. it's not available in spark module. So i was meaning more like it would be good if spark module can have test without REST api and ZeppelinServer running.

**Comment by bpmcd** [comment]
@Leemoonsoo Sounds good.  I will clean up the Travis failures and update the PR.

**Comment by bpmcd** [comment]
@Leemoonsoo For these tests to pass, the SPARK_HOME variable needs to be absolute.  Any thoughts on how to get the Travis configuration to expand the SPARK_HOME path?

**Comment by Leemoonsoo** [comment]
@bpmcd I'm not sure but, according to travis [documentation](http://docs.travis-ci.com/user/environment-variables/), something like `SPARK_HOME=$TRAVIS_BUILD_DIR/incubator-zeppelin/spark-1.3.1-bin-hadoop2.3` or `SPARK_HOME=$TRAVIS_BUILD_DIR/spark-1.3.1-bin-hadoop2.3` (looks like you already tried this one) should work.

**Pull request closed without merging**
