### PR TITLE
[ZEPPELIN-1926] Remove grunt googlefonts task

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

There is no reason to download fonts files whenever we build.

- Google font doesn't change frequently.
- We can use google fonts in open source (https://developers.google.com/fonts/faq)

> Yes. The open source fonts in the Google Fonts catalog are published under licenses that allow you to use them on any website, whether it’s commercial or personal. 

For reviewer, please review `Gruntfile.js` and `package.json`. Other 49 file changes are just about adding font resources.

### What type of PR is it?
[Improvement]

### Todos

Fixed at once

### What is the Jira issue?

[ZEPPELIN-1926](https://issues.apache.org/jira/browse/ZEPPELIN-1926)

### How should this be tested?

1. Run zeppelin-web dev mode
2. Open browser and check 404

### Screenshots (if appropriate)

None

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
This PR makes zeppelin source distribution package contains font files.
Therefore, related font license should be moved from [`/zeppelin-distribution/src/bin-license/LICENSE`](https://github.com/apache/zeppelin/blob/master/zeppelin-distribution/src/bin_license/LICENSE) to [`/LICENSE`](https://github.com/apache/zeppelin/blob/master/LICENSE).

And license of each font may different. So each license of font need to be listed in [`/LICENSE`](https://github.com/apache/zeppelin/blob/master/LICENSE) file. 

@1ambda Could you take care of license?

**Comment by 1ambda** [comment]
@Leemoonsoo Thanks for detailed explanation. I will take a look.

**Comment by jongyoul** [comment]
@1ambda Does it reduce the build time of web module?

**Comment by 1ambda** [comment]
@jongyoul small amount of :) 

if you want to reduce time for `npm install`, you can use `yarn install` instead of. It will decrease 20~50 secs.
And https://github.com/apache/zeppelin/pull/1812 was merged recently so it is applied to `zeppelin-web` module now.

**Comment by jongyoul** [comment]
Honestly, I want to compole web in 30 secs. Do you make it possible? Kkkkkkkk

**Comment by 1ambda** [comment]
@Leemoonsoo I moved all font-related licenses from `bin_license` to `/LICENSE`
Aldo remove rat exclusion in `zeppeiln-web/pom.xml` for `google-fonts.css` because it is managed by us now.

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no more discussions

**Comment by felixcheung** [comment]
hmm, it doesn't break RAT tests for all these binaries? :)

**Comment by 1ambda** [comment]
@felixcheung 

I think it's ok since all LICENSEs will be merged into a single file

- https://github.com/apache/zeppelin/blob/master/dev/create_release.sh#L93-#L96

**Pull request closed without merging**
