### PR TITLE
[DOC] Zeppelin 0.6.1 release

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
- Add release note for 0.6.1
- Update download page with the latest version to 0.6.1

_Should wait until mirror link is synced before merging and publishing this docs_

### What type of PR is it?
Documentation

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Comment by bzz** [comment]
Looks great to me

**Comment by minahlee** [comment]
Confirm that download mirror is synced. Merge if there is no further discussion

**Comment by Leemoonsoo** [comment]
LGTM!

**Pull request closed without merging**
