### PR TITLE
Rewrite of "Quick Start" page.

### PR DESCRIPTION
**Pull request by rfilmyer**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - https://github.com/apache/zeppelin/blob/master/CONTRIBUTING.md

This is a rewrite of the "Quick Start" page, fixing syntax/grammar issues while trying to keep to the original content. I may look at other pages, but I wanted my first PR to be very small.

### What type of PR is it?
Documentation

### Todos
Verify the accuracy of the configuration settings section

### What is the Jira issue?
(Does this apply to documentation PRs?)

### How should this be tested?
Do documentation changes like this need to be tested?
If so, is the github preview sufficient for these changes? How is Zeppelin's markdown interpreter different than Github's?
If Github's MD preview isn't sufficient, is it possible to build the documentation locally?

### Questions:
* Since this is my first PR on the project, I limited the scope of my changes. Is there any desire to  change the content of these pages in any way? Do we have documentation conventions?

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
Hi @rfilmyer, thanks for your first contribution to Zeppelin! I've just looked through the changes, definitely better. So LGTM I think 👍  

Since this change is just for syntax/grammar fixing, github preview will be enough I guess. But If you want to check another docs pages, [Contributing to Documentation](http://zeppelin.apache.org/contribution/documentation.html) will guide you. This page will give you the answer about most of your questions that you might be wondered(e.g. Do we have documentation conventions?)

Ah, I can answer to you about this question directly in here.
> is it possible to build the documentation locally?

Yes it is. Please see "Dev Mode" section in the guide page I linked. 
Please feel free to ask if you have any other questions. Zeppelin community will be happy to help you :D

**Comment by rfilmyer** [comment]
Thanks for the feedback! If I want to make more contributions, should I do it in this PR, or should I make a new one.

**Comment by AhyoungRyu** [comment]
@rfilmyer Actually it's up to you. If the changes that you want to contribute are also related to "Fixing syntax/grammar error", you can just push them here. Then the PR title needs to be updated accordingly. Maybe "Fix syntax/grammar errors in some documentations" ?

**Comment by Leemoonsoo** [comment]
Thanks @rfilmyer for the great contribution!
Like @AhyoungRyu explained, you can either add more commits here or create new PR depending on further contribution you want to make.

LGTM

**Comment by rfilmyer** [comment]
Alright. I'm probably going to make some more changes on this PR. (Probably 2 or 3 more pages).

**Comment by AhyoungRyu** [comment]
@rfilmyer Do you need any help? :D

**Comment by rfilmyer** [comment]
I've been busy and sort of fallen into the trap that I was trying to avoid
by leaving this PR dead. This weekend I'm going to try to finish another
page, close this PR, and make other changes on a fresh one.

**Comment by AhyoungRyu** [comment]
@rfilmyer Yeah thanks for sharing your plain :) Then merging this one into master if there are no more discussions.

**Comment by AhyoungRyu** [comment]
@rfilmyer Ah if you want to make another changes, how about creating a [Jira issue](https://issues.apache.org/jira/browse/ZEPPELIN/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel) for that? 
 
>What is the Jira issue?
(Does this apply to documentation PRs?)

Yes it does. Every Zeppelin-related issues can be reported in Jira. It's not a mandatory for now, but it's good to have one even if it's a minor issue. Also you can create another patch not in your `master` branch but sth like `ZEPPELIN-(Jira issue number)` branch.

**Pull request closed without merging**
