### PR TITLE
Fonted download chinese garbled  fix

### PR DESCRIPTION
**Pull request by cquptEthan**
### What is this PR for?
Fix chinese garbled open with Excel #714 

### What type of PR is it?
Bug Fix

### Todos
* [x] - Add Bom Header

### What is the Jira issue?
[ZEPPELIN-672](https://issues.apache.org/jira/browse/ZEPPELIN-672)

### How should this be tested?
create a paragraph with chinses chars data in %table view.
download with CSV format and open with Excel.

### Questions:
* Does the licenses files need update?
 No
* Is there breaking changes for older versions? 
No
* Does this needs documentation? 
No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested and confirmed it fixes the problem.

@cquptEthan thanks for the contribution.
Do you mind create a jira issue for it?
Then I'd like to mark fix version 0.6.1 and merge it into master, branch-0.6.

**Comment by cquptEthan** [comment]
@Leemoonsoo  Thanks.
I've created [ZEPPELIN-1138](https://issues.apache.org/jira/browse/ZEPPELIN-1138) for it

**Comment by Leemoonsoo** [comment]
Thanks @cquptEthan. I'm merging it into master and branch-0.6 if there is no more discussion.

**Comment by cquptEthan** [comment]
@Leemoonsoo  OK .

**Comment by ebuildy** [comment]
Hello, the Jira issue is still opened https://issues.apache.org/jira/browse/ZEPPELIN-1137 ?

**Comment by 1ambda** [comment]
Closed. Thanks for the reporting.

**Pull request closed without merging**
