### PR TITLE
ZEPPELIN-1225. Errors before the last shell command are ignored

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
The problem is that command "bash -c <shell scripts>" will always return 0 as long as the last line of shell script run correctly. e.g the following command will run correctly without any error message.
```
hello
pwd
``` 
This PR will redirect stderr and stdout to the same place, and will display both the stderr and stdout to frontend just like what user see in the native shell terminal. So the output of above command will be as following
```
bash: hello: command not found
/Users/jzhang/github/zeppelin
```

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1225

### How should this be tested?
Unit test is added and also manually verify it on zeppelin notebook. 

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Find ShellInterpreterTest has some format issue (it is windows format), I have changed it to unix format in this PR as well.

**Comment by zjffdu** [comment]
After checking ShellInterpreter.java, I found other 2 issues. 
* Should remove entry from executors after the shell execution is done otherwise it would accumulate more and more. 
* executors should be ConcurrentHashMap as it would be accessed in 2 threads (interpret & cancel will be in 2 threads if I understand correctly) 

I push another commit to fix these 2 issues, let me know if it is better to do it another ticket.

**Comment by zjffdu** [comment]
Travis build fails due to network issue I think, 
```
[INFO] bower@1.7.2 node_modules/bower
[INFO] └── semver-utils@1.1.1
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! Callback called more than once.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/zeppelin/zeppelin-web/npm-debug.log
```

**Comment by zjffdu** [comment]
@Leemoonsoo, mind to take look at it ? Thanks

**Comment by Leemoonsoo** [comment]
@zjffdu sure let me take a look

**Comment by Leemoonsoo** [comment]
Thanks @zjffdu for the contribution.
LGTM. Tested, CI failure irrelevant. 

Merge it into master and branch-0.6

**Comment by Leemoonsoo** [comment]
Merged into master. However, it wasn't able to be merged in branch-0.6 with conflict.
So @zjffdu I'm resolving issue [ZEPPELIN-1225](https://issues.apache.org/jira/browse/ZEPPELIN-1225) with fixversion 0.7.0.

You can always create PR to branch-0.6, when you think this patch should be included in branch-0.6.

**Pull request closed without merging**
