### PR TITLE
[ZEPPELIN-1908] Invalid Typo Method name

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
Invalid Typo Method name

closeAndRmoveAllInterpreterGroups -> closeAndRemoveAllInterpreterGroups

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1908

### Questions: no
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by soralee** [comment]
Looks good to me 👍

**Comment by AhyoungRyu** [comment]
LGTM 
CI failed only in Selenium test and it looks irrelevant to this change
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 55.46 sec <<< FAILURE! - in org.apache.zeppelin.integration.InterpreterIT
testShowDescriptionOnInterpreterCreate(org.apache.zeppelin.integration.InterpreterIT)  Time elapsed: 55.197 sec  <<< ERROR!
org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
```

**Comment by felixcheung** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
Merge if there are no more comments on this

**Pull request closed without merging**
