### PR TITLE
[MINOR] Optimize watchers of paragraph results

### PR DESCRIPTION
**Pull request by cuspymd**
### What is this PR for?
It's to optimize watchers of paragraph results
In the 'Zeppelin Tutorial / R (SparkR)' note, the number of watchers decreases by 1000.

### What type of PR is it?
[Refactoring]

### What is the Jira issue?
N/A

### How should this be tested?
Check the basic actions of the note.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Thanks for the contribution, one minor issue:

Before:
screen shot 2016-12-22 at 2 03 26 pm

After:
screen shot 2016-12-22 at 1 38 24 pm


Rest LGTM.

**Comment by 1ambda** [comment]
Hard to figure out what is different at first. See border of the icons.

**Comment by cuspymd** [comment]
In the process of modifying the above issue, I divided the buttons of the chart selector into two groups.
The role of the two button groups seems to be slightly different.

- First group: Chart selection buttons
- Second group: App selection buttons

**Comment by Leemoonsoo** [comment]
Tested and LGTM. Thanks @cuspymd for the nice optimization!

Merge to master if no more discussions.

**Pull request closed without merging**
