### PR TITLE
[DOCS] Reflect changed default storage to doc

### PR DESCRIPTION
**Pull request by tae-jun**
### What is this PR for?
Reflect effects caused by changing the default notebook storage VFSNotebookRepo to GitNotebookRepo.

### What type of PR is it?
[Documentation]

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@khalidhuseynov If you don't mind, could you help review this docs changes? :)

**Comment by khalidhuseynov** [comment]
thanks for keeping docs uptodate, LGTM

**Comment by tae-jun** [comment]
@AhyoungRyu @khalidhuseynov Thanks! 😄

**Comment by AhyoungRyu** [comment]
CI failure is irrelevant to this docs update. Merge into master and branch-0.7 if there are no more comments.

**Pull request closed without merging**
