### PR TITLE
[gh-pages][ZEPPELIN-1216] Add a matrix table for "Zeppelin version X available interpreters"

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
I added a matrix table for "Zeppelin version X available interpreters(with specific version)" to [zeppelin.apache.org/download.html](zeppelin.apache.org/download.html). Please see the attached screenshot images :)

### What type of PR is it?
Improvement & Documentation

### Todos
* [x] - Change `_site` -> `_site/` in `.gitignore`
* [x] - Update `safe_yaml` version 0.9.7 -> 1.0.4 like `master` branch
* [x] - Add `0.6.1` column

### What is the Jira issue?
[ZEPPELIN-1216](https://issues.apache.org/jira/browse/ZEPPELIN-1216)

### Screenshots (if appropriate)
matrix

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@Leemoonsoo Can you review this one? I updated the PR description :)

**Comment by minahlee** [comment]
Looks great! 
How about move recent release to left?
FYI, Geode is not included in binary package like scalding.

**Comment by AhyoungRyu** [comment]
@minahlee Yeah it makes sense.  
>How about move recent release to left?

It would be better since this table becomes wider. I addressed it. And also `Geode` :)

**Comment by Leemoonsoo** [comment]
Looks good. Shell we merge it?

**Comment by Leemoonsoo** [comment]
LGTM and Merge if there're no further discussions.

**Comment by AhyoungRyu** [comment]
Since Zeppelin is about to release `0.6.1` version, I'll add `0.6.1` column as well.

**Comment by Leemoonsoo** [comment]
👌

**Comment by AhyoungRyu** [comment]
@Leemoonsoo I removed `0.5.0` column instead of adding `0.6.1 (latest)` one. Please check the updated gif image in the PR description :)

**Comment by AhyoungRyu** [comment]
Using this PR I updated Spark logo to new one as #1279 did.

**Comment by Leemoonsoo** [comment]
LGTM. Merge to gh-pages branch if there're no more discussions.
Thanks @AhyoungRyu for great work!

**Pull request closed without merging**
