### PR TITLE
[ZEPPELIN-5223] - K8s+docker document format is not correct

### PR DESCRIPTION
**Pull request by omrisk**
Added formatting (to avoid escaping each `_` occurrence, I couldn't find a style guide for documentation or other examples that would suggest another method.
I noticed this also happens in the `docker.md` so I fixed that as well

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @omrisk for the quick fix, LGTM.
BTW, have you tried to build the docs ? Here's the documentation guide.  https://github.com/apache/zeppelin/blob/master/docs/README.md

**Comment by omrisk** [comment]
@zjffdu , I will try, I'm working on macos-bigsur and ruby is quite broken.
I will update once I get it working (hopefully)

**Comment by omrisk** [comment]
@zjffdu , I was able to get this to work locally, but only after wrapping in docker due to conflicts on my local machine (and with help from @danielRicardo ).

Would you like me to add the needed `Dockerfile` + `docker-compose` and instructions ?
This would allow building the documentation locally without installing any dependencies. 

image
image

**Comment by zjffdu** [comment]
What kind of conflict do you meet ? As I remember it only works with python2.7 and (I use rvm for ruby environment, usually I use ruby 2.3.7)

**Comment by omrisk** [comment]
Mostly `gem install bundler` on Ruby 2.0, you have to be > 2.3 - but then other packages fail there, additionally issue with installing `iff`. 
`An error occurred while installing yajl-ruby (1.1.0), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.1.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 10, which depends on
    jekyll was resolved to 1.3.0, which depends on
      pygments.rb was resolved to 0.5.4, which depends on
        yajl-ruby
`
I think adding a containerised method may make it easier for future contributors, WDYT?

**Comment by zjffdu** [comment]
Sure, docker approach might be easier for users.

**Comment by omrisk** [comment]
Cool, would you like me to add that here or in a separate PR ?

**Comment by Reamer** [comment]
A separate PR would be better.

**Comment by omrisk** [comment]
@Reamer , thanks opened #4054

**Comment by Reamer** [comment]
LGTM

**Comment by zjffdu** [comment]
LGTM

**Pull request closed without merging**
