### PR TITLE
[ZEPPELIN-2516] Set offset, tolerance for navbar, actionbar hiding

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Set offset, tolerance for navbar, actionbar hiding. See the attached screenshots.

### What type of PR is it?
[Bug Fix]

### Todos

NONE

### What is the Jira issue?

[ZEPPELIN-2516](https://issues.apache.org/jira/browse/ZEPPELIN-2516)

### How should this be tested?

Refer the screenshots.

#### Before

2516_before

#### After

2516_after

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
CI failed but irrelevant. 

- https://travis-ci.org/1ambda/zeppelin/jobs/230235896

Found the same errors in 4 different PRs

- https://travis-ci.org/1ambda/zeppelin/jobs/230590633
- https://travis-ci.org/1ambda/zeppelin/jobs/230549655
- https://travis-ci.org/1ambda/zeppelin/jobs/230235896
- https://travis-ci.org/1ambda/zeppelin/jobs/230215694

might be related with https://github.com/apache/zeppelin/pull/2300

**Comment by 1ambda** [comment]
@soralee please help review this.

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no further comment

**Comment by soralee** [comment]
@1ambda Sorry for my late test!
Tested and LGTM!

**Pull request closed without merging**
