### PR TITLE
[ZEPPELIN-4918] Add Table of Contents to Sidebar

### PR DESCRIPTION
**Pull request by pranavtharoor**
### What is this PR for?
This PR adds a Table of Contents (ToC) to the new Zeppelin UI. The ToC allows quick navigation through long notebooks. The ToC is generated based on the presence of Heading tags in the results. 

### What type of PR is it?
Improvement

### Todos
* [ ] - N/A

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-4918

### How should this be tested?
Travis CI: https://travis-ci.com/github/pranavtharoor/zeppelin/builds/173370001
Manual steps:
1. Create a notebook
2. Add different levels of Markdown headings or other inline HTML heading tags
3. Run the paragraphs so that the result is shown
4. Click the ToC icon in the sidebar ribbon to open the ToC. The ToC should be generated/refreshed
5. Try clicking on the ToC rows to scroll to the respective paragraph

### Screenshots (if appropriate)
Screenshot 2020-06-28 at 8 04 31 PM

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@pranavtharoor Thanks for the contribution!

I tested this branch and it works very well, really cool!

Found two behaviors around empty Note.
 - When switch to empty Note after Sidebar ToC is open with non-empty Note, the ToC still shows previous Note
    toc_edited


 - Open empty Note (or switch to empty Note and refresh) gives some broken elements
   image

Could you take a look?

**Comment by pranavtharoor** [comment]
@Leemoonsoo Thanks for the review! I've fixed these issues and pushed.

**Comment by Leemoonsoo** [comment]
Tested the last commit and everything works smoothly.
Thank @pranavtharoor for the cool feature!

LGTM and will merge to master and branch-0.9 when no further comments.

**Comment by pranavtharoor** [comment]
Okay. Thank you!

**Pull request closed without merging**
