### PR TITLE
[ZEPPELIN-1628] Enable renaming note from the main page

### PR DESCRIPTION
**Pull request by tae-jun**
### What is this PR for?
Now users can rename a note from the main page! This new feature will improve UX.

I divided [ZEPPELIN-1598](https://issues.apache.org/jira/browse/ZEPPELIN-1598) into sub-tasks since renaming folder gonna be huge. I will open PR for [ZEPPELIN-1629](https://issues.apache.org/jira/browse/ZEPPELIN-1629) after merging this PR.

By the way, I have a question! Does a `writer` can rename a note? Currently, only an owner can rename a note.

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1628

### Screenshots (if appropriate)
rename_note

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@tae-jun Awesome!  
I tested this patch but seems it needs to prevent blank title when we rename the note. Please see the below gif img. 
edit_notename

**Comment by tae-jun** [comment]
@AhyoungRyu Thanks for the quick review! You are right! I will fix it. Please wait 😄

**Comment by tae-jun** [comment]
@AhyoungRyu I fixed it! It took some time to improve UX 😄

Now when an input text is not valid, users can't click the button and the modal shows error message

rename_note_validation

**Comment by tae-jun** [comment]
CI is green!

**Comment by AhyoungRyu** [comment]
@tae-jun Thanks for your prompt response. The latest change looks good to me 👍

**Comment by tae-jun** [comment]
@AhyoungRyu Thanks for the review! :)

**Comment by Leemoonsoo** [comment]
Thanks @tae-jun for useful feature contribution.
LGTM and merge to master if there're no further comments.

**Pull request closed without merging**
