### PR TITLE
[ZEPPELIN-1740] Focus next paragraph after paragraph deletion

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
This PR is for moving focus next paragraph after paragraph deletion using Ctrl-Alt-D.
After paragraph is removed by keyboard shortcut Ctrl-Alt-D, focus is gone.
We have to move mouse and click the next paragraph to get focus.

### What type of PR is it?
[Improvement]

### Todos
* None

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1740

### How should this be tested?
Check the focus after pressing Ctrl-Alt-D in paragraph.

### Screenshots (if appropriate)
z1740_1

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @soralee for the nice improvement.
Tested and LGTM.

**Comment by cloverhearts** [comment]
Good feature!
LGTM

**Comment by tae-jun** [comment]
LGTM 👍

**Comment by astroshim** [comment]
LGTM!

**Comment by Leemoonsoo** [comment]
Merge to master if there're no more discussions.

**Pull request closed without merging**
