### PR TITLE
[ZEPPELIN-2846] Add selenium test case for AnyOfRolesAuthorizationFilter

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This is to test the new feature that was brought in with ZEPPELIN-2825 (org.apache.zeppelin.utils.AnyOfRolesAuthorizationFilter)

### What type of PR is it?
[Improvement]

### What is the Jira issue?
* [ZEPPELIN-2846](https://issues.apache.org/jira/browse/ZEPPELIN-2846)

### How should this be tested?
CI should be green

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Ready for review, https://travis-ci.org/prabhjyotsingh/zeppelin/builds/263300475. 439.2 Failed which is unrelated (have restarted it).

**Comment by prabhjyotsingh** [comment]
@1ambda @Leemoonsoo @VipinRathor Please help review this.

**Comment by VipinRathor** [comment]
Reviewed. Looks good to me.

**Comment by prabhjyotsingh** [comment]
Thanks for the review will merge this if no more discussion.

**Pull request closed without merging**
