### PR TITLE
ZEPPELIN-1107 ] Doesn't work autocompletion for jdbc interpreter

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
Doesn't work autocompletion for jdbc interpreter
'Completion' There is a problem with the return type of implementation.

```
org.apache.zeppelin.interpreter.InterpreterException: org.apache.thrift.transport.TTransportException
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.completion(RemoteInterpreter.java:396)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.completion(LazyOpenInterpreter.java:122)
	at org.apache.zeppelin.notebook.Paragraph.completion(Paragraph.java:216)
	at org.apache.zeppelin.notebook.Note.completion(Note.java:488)
	at org.apache.zeppelin.socket.NotebookServer.completion(NotebookServer.java:729)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:202)
	at org.apache.zeppelin.socket.NotebookSocket.onWebSocketText(NotebookSocket.java:56)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:65)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:161)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:632)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:480)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.recv_completion(RemoteInterpreterService.java:346)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client.completion(RemoteInterpreterService.java:330)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreter.completion(RemoteInterpreter.java:392)

```

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1107

### How should this be tested?
try to completion for jdbc interpreter paragraph.

### Screenshots (if appropriate)
jdbc

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by astroshim** [comment]
Nice catch!!
Do you mind create test case for this?

**Comment by cloverhearts** [comment]
@astroshim 
Thank you for your opinion.
i'll check to it.

**Comment by bzz** [comment]
Looks great, 👍  for tests if it's possible.
\cc @jongyoul as person who recently worked most on JDBC interpreters for a review

**Comment by bzz** [comment]
@cloverhearts will you add a test, as part of this PR?

Other then that, it looks good to me

**Comment by jongyoul** [comment]
@cloverhearts Thanks for catching up it. LGTM

**Comment by bzz** [comment]
Looks great to me 👍  for having tests!

Merging if there is no further discussion

**Comment by cloverhearts** [comment]
@bzz @jongyoul 
Thank you!
ci passed

**Comment by bzz** [comment]
CI failure is not related to this changes 


On ALL profiles we have  `[INFO] Zeppelin: web Application .......................... FAILURE [05:49 min]`

```
[INFO] make: Entering directory `/home/travis/build/apache/zeppelin/zeppelin-web/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
[INFO]   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
[INFO]   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
[INFO]   COPY Release/bufferutil.node
[INFO]   CXX(target) Release/obj.target/validation/src/validation.o
[INFO]   SOLINK_MODULE(target) Release/obj.target/validation.node
[INFO]   COPY Release/validation.node
[INFO] make: Leaving directory `/home/travis/build/apache/zeppelin/zeppelin-web/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz
[ERROR] npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
[ERROR] npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
[ERROR] npm ERR! fetch failed https://registry.npmjs.org/batch/-/batch-0.5.0.tgz
```

Looks like a networking issue with npm.. @cloverhearts could you try re-triggering CI today please?

**Pull request closed without merging**
