### PR TITLE
available_interpreters.png replace.

### PR DESCRIPTION
**Pull request by kimjmin**
### What is this PR for?
Change `docs/assets/themes/zeppelin/img/available_interpreters.png` file.
replace old `elasticsearch` logo to new one.

### What type of PR is it?
Documentation

### Todos
* [x] - replace old `elasticsearch` logo to new one on `available_interpreters.png` file.

### What is the Jira issue?
N/A

### How should this be tested?
N/A

### Questions:
* Does the licenses files need update? N.
* Is there breaking changes for older versions? N.
* Does this needs documentation? N.

### CODE REVIEW

**Comment by jongyoul** [comment]
Thanks for the contribution. LGTM. Merge it sooner

**Comment by jongyoul** [comment]
@AhyoungRyu Can you help to deploy it to the web?

**Comment by jongyoul** [comment]
@kimjmin Can you check the site? I updated it

**Comment by kimjmin** [comment]
@jongyoul 
Thanks. Page looks beautiful. 👍

**Pull request closed without merging**
