### PR TITLE
[ZEPPELIN-3306] Web e2e test fails

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This is one of the flaky tests that fails with "should have a welcome message" because Z-Server did not start by the time test started executing.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [ZEPPELIN-3306](https://issues.apache.org/jira/browse/ZEPPELIN-3306)

### How should this be tested?
* CI should pass

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@zjffdu 
Can you help review this? Looks like this was actually because of the latest version of chrome (65.0.3325.146) and had to update webdriver-manager's chrome version.

**Comment by zjffdu** [comment]
Thanks @prabhjyotsingh , LGTM, the selenium test still fails due to corrupted scala jars, could you clean travis cache and rebuild it again to make sure all the test pass ?

**Comment by prabhjyotsingh** [comment]
CI green https://travis-ci.org/prabhjyotsingh/zeppelin/builds/351259448.

**Comment by zjffdu** [comment]
Awesome, thanks @prabhjyotsingh

**Comment by prabhjyotsingh** [comment]
Will merge this soon.

**Comment by prabhjyotsingh** [comment]
@felixcheung it doesn't happen always but at times before could Zeppelin-server start test case starts executing, and by making `spawn="false"` maven waits for the command (./bin/zeppelin-daemon.sh start) to complete, and `CI=true` make zeppelin-daemon to wait for localhost:8080 to be active.

**Pull request closed without merging**
