### PR TITLE
[ZEPPELIN-1808] disable shortcut key of window created by link this paragraph

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
If using a `Link this paragraph`, new window works the keyboard shortcut. 
Keyboard shortcut should not work in "Link this paragraph" URL.

### What type of PR is it?
[ Improvement ]

### What is the Jira issue?
[ZEPPELIN-1808](https://issues.apache.org/jira/browse/ZEPPELIN-1808)

### How should this be tested?
1. Click `Link this paragraph` or Use `Ctrl+Alt(command)+w` in a paragraph.
2. Use some keyboard shortcut in new window which is created by `Link this paragraph`.
3. Check text and title shape of the paragraph.

### Screenshots (if appropriate)
[ Before ]
* When trying to use keyboard shortcut`(Ctrl+Alt/Command+t)` in paragraph of new window.
1808_b

* Text and title are misaligned
1808_b

[ After ]
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by soralee** [comment]
@Leemoonsoo Could you review this PR as JIRA issue reporter?

**Comment by Leemoonsoo** [comment]
Thanks @soralee for the fix.
Tested manually and it works well as expected.
LGTM.

Master branch is little bit different from branch-0.7 so i can not apply this patch to branch-0.7. So, @soralee Can you create separate PR that disables keyboard shortcut for branch-0.7, too? 
So the patch can be included in 0.7.1 release.


It's out of this issue scope, but 'Link this paragraph' is designed to user embed a paragraph in the website. So i think it's better not having any boarder or margin.
image
@soralee what do you think removing border and margin (marked in blue and red arrow) in a separate issue?

**Comment by soralee** [comment]
Thanks @Leemoonsoo for taking care of this PR and testing it out :)
Sure, Let me separate and create two issues that are branch-0.7 and shape of window.

**Comment by soralee** [comment]
Hi @Leemoonsoo,
I opened two issue as your comment (#2045, #2054) so it would be nice if you could check some PRs. Furthermore this CI is green now :)

**Pull request closed without merging**
