### PR TITLE
[BugFix] Tutorial note json format.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
Since https://github.com/apache/zeppelin/pull/1658, the output format had changed but note.json of Tutorials didn't changed.

### What type of PR is it?
Bug Fix

### How should this be tested?
Please make sure there is no `result` field in note.json file.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
I imported (using url) this new format of notes to my Zeppelin, but seems they don't show the result by default like below.
screen shot 2016-12-17 at 8 05 28 pm
screen shot 2016-12-17 at 8 05 19 pm

**Comment by astroshim** [comment]
@AhyoungRyu Thank you for review and let me check that problem.

**Comment by astroshim** [comment]
In my case, It's normal output of results. @AhyoungRyu Did you build this PR?

**Comment by AhyoungRyu** [comment]
@astroshim I checked again and it's working well. Sorry for any confusions, it was my bad. 
So LGTM 👍

**Comment by bzz** [comment]
Looks great to me.

CI fails here though. I know it's annoying but @astroshim, as PR author, could you please post failure build logs here, so we can see if it is something that already have a JIRA issue, or a new one should be created? 

Again, sorry for bothering, but this helps improving CI stability a lot and sets a good example of NOT ignoring the CI failures for other contributors.

**Comment by astroshim** [comment]
@bzz I agree with you and I will follow your word! 
Thanks.

**Comment by astroshim** [comment]
CI has passed after rebase.

**Comment by AhyoungRyu** [comment]
Nice! Then will merge into master if there are no more comments :)

**Comment by astroshim** [comment]
@AhyoungRyu Thanks.

**Pull request closed without merging**
