### PR TITLE
[ZEPPELIN-2577] No graphs visible on IE11

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR fixes issue described in https://issues.apache.org/jira/browse/ZEPPELIN-2577 by adding .endsWith method.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2577

### How should this be tested?
Build this PR and make sure built-in visualization is displayed in ie11

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by 1ambda** [comment]
LGTM.

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by Leemoonsoo** [comment]
Thanks @1ambda @prabhjyotsingh for the review. Merge to master and branch-0.7 if no further comments.

**Comment by 1ambda** [comment]
@Leemoonsoo I think we don't need to merge this PR into master. because the master branch supports IE9+

```
 "browsers": ["last 5 version", "> 5%", "edge >= 12", "ie >= 9", "safari 7", "chrome 47", "firefox 31"]
```

- https://github.com/apache/zeppelin/blob/master/zeppelin-web/.babelrc#L8

**Comment by Leemoonsoo** [comment]
Tested the Master branch in IE11. and got different error.

image

@1ambda Do you know reason why master branch and branch-0.7 has different .babelrc?

**Comment by 1ambda** [comment]
https://github.com/apache/zeppelin/pull/2273 was merged into master only.

**Comment by 1ambda** [comment]
Regarding to Promsie polyfill, we need to turn on the `useBuiltIn` option in babel-preset-env

- https://github.com/babel/babel-preset-env#usebuiltins
- https://github.com/babel/babel-preset-env/issues/203

**Comment by Leemoonsoo** [comment]
I tried `useBuiltIn` in master branch. but it didn't help. Anyway, that can be handled in another issue.

I'll merge this PR to branch-0.7

**Comment by jongyoul** [comment]
After merging this PR, let's proceed to release 0.7.2

**Comment by Leemoonsoo** [comment]
Merged to IE11

**Pull request closed without merging**
