### PR TITLE
[ZEPPELIN-1518] Fix for: Lambda expressions are not working on CDH 5.7.x Spark

### PR DESCRIPTION
**Pull request by mvitaly**
### What is this PR for?
Lambda expressions are not working on CDH 5.7.x Spark because of the backported RpcEnv and elimination of class server.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1518

### How should this be tested?
The following paragraph should work with SPARK_HOME pointing to CDH 5.7x spark:
`val rdd = sc.parallelize(Seq(1,2,3,4,5))
rdd.filter(_ > 3).count()`

### Questions:
* Does the licenses files need update? n
* Is there breaking changes for older versions? n
* Does this needs documentation? n

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @mvitaly for the contribution!

Looks good to me!

**Comment by minahlee** [comment]
Tested, it fixes the bug. Btw do we need this patch only in branch-0.6 not to master?

**Comment by Leemoonsoo** [comment]
I think master also needs this patch.

**Comment by minahlee** [comment]
Merging to master and branch-0.6 if there is no more discussion

**Pull request closed without merging**
