### PR TITLE
[ZEPPELIN-4505] Save notebook on clear all paragraph output 

### PR DESCRIPTION
**Pull request by amakaur**
### What is this PR for?
Currently clear all paragraph output changes are only stored in memory. So, when zeppelin is restarted all of the output is displayed again on all of the notebooks.

This PR saves the changes made to notebook and updates are reflected also on a restart. So there's no inconsistencies before and after a restart.

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-4505

### How should this be tested?
- Create a notebook using Spark interpreter
- Create any output
- Trigger clear all paragraph output 
- Restart zeppelin and paragraph output will be erased as expected.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @amakaur PR LGTM.
2 Minor comments:
* Please change the title as [ZEPPELIN-xx] jira tilte
* Could you paste the travis link

**Comment by amakaur** [comment]
build

**Comment by amakaur** [comment]
@zjffdu i had to create a new PR to trigger travis build since i didn't turn on travis integration for the previous branches. 

Here's a temp PR: https://github.com/apache/zeppelin/pull/3573
Travis link for temp PR: https://travis-ci.org/amakaur/zeppelin/builds/629825383

**Comment by zjffdu** [comment]
@amakaur Some travis test are failed, Could you do a rebase to retrigger the travis ?

**Comment by amakaur** [comment]
@zjffdu sure.

**Comment by amakaur** [comment]
@zjffdu i did rebase with master and build is failing on an existing test case ```Tests in error: 
  ParagraphActionsIT.testWidth:327->AbstractZeppelinIT.waitForParagraph:75->AbstractZeppelinIT.pollingWait:101 » Timeout```
https://travis-ci.org/amakaur/zeppelin/builds/630097911?utm_medium=notification&utm_source=email

**Comment by zjffdu** [comment]
@amakaur This kind of error is usually due to flaky test, you can restart that by click this button.
image

**Comment by amakaur** [comment]
@zjffdu looks like all of the builds have succeeded https://travis-ci.org/amakaur/zeppelin/builds/630097911?utm_medium=notification&utm_source=email

**Comment by zjffdu** [comment]
Thanks @amakaur will merge if no more comment

**Comment by amakaur** [comment]
@zjffdu perfect. thanks

**Pull request closed without merging**
