### PR TITLE
[ZEPPELIN-3289] Table not using full height after paragraph height has been changed

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
Changing paragraph height does not work correctly anymore in conjunction with table output. Refer screen shot:
image

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
* [ZEPPELIN-3289](https://issues.apache.org/jira/browse/ZEPPELIN-3289)
* [ZEPPELIN-3272](https://issues.apache.org/jira/browse/ZEPPELIN-3272)

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@weand  @r-kamath  Can you help review this PR.

**Comment by prabhjyotsingh** [comment]
@Tagar This PR fixes [ZEPPELIN-3272](https://issues.apache.org/jira/browse/ZEPPELIN-3272) as well, can you help review this.

**Comment by weand** [comment]
height issue is solved. thanks.

but now got the bahvior, that results are duplicated:
[https://ibin.co/3trkDDqHas5m.gif](https://ibin.co/3trkDDqHas5m.gif)

and the following is logged into console:
`result.controller.js?55cc:685` 
```
Graph drawing error TypeError: Cannot read property 'core' of undefined
    at TableVisualization.refresh (eval at <anonymous> (app.bundle.js:1968), <anonymous>:172:26)
    at TableVisualization.activate (eval at <anonymous> (app.bundle.js:1962), <anonymous>:108:14)
    at afterLoaded (eval at <anonymous> (app.bundle.js:2172), <anonymous>:699:31)
    at retry (eval at <anonymous> (app.bundle.js:2172), <anonymous>:235:7)
    at angular.js:19374
    at completeOutstandingRequest (angular.js:5955)
    at angular.js:6234
```

**Comment by Tagar** [comment]
@weand I just logged in https://issues.apache.org/jira/browse/ZEPPELIN-3292 for data duplication )
I don't think it's related to this PR?

**Comment by prabhjyotsingh** [comment]
Have made a fix for both.

**Comment by weand** [comment]
LGTM. no errors in console and ZEPPELIN-3292 data duplication fixed as well.

**Comment by r-kamath** [comment]
LGTM

**Comment by prabhjyotsingh** [comment]
Thanks for the review will merge this if no more discussion.

**Pull request closed without merging**
