### PR TITLE
[MINOR] Show properties ordered alphabetically

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Showing properties sorted in the interpreter tab 

### What type of PR is it?
[Improvement]

### Todos
* [x] - Change the np-repeat block

### What is the Jira issue?
N/A

### Screenshots (if appropriate)
screen shot 2016-06-20 at 6 10 38 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
@corneadoug Could you please review this PR? It has very simple change but I don't know where the right position of that function is.

**Comment by corneadoug** [comment]
@jongyoul seems to be working, the gracious way would have been to use an orderBy filter (https://docs.angularjs.org/api/ng/filter/orderBy), but it only applies to Array, and we are using an Object for some reason.

Maybe you could do a custom filter

**Comment by jongyoul** [comment]
@corneadoug Thanks for the quick reply. I've googled `orderBy` and tried it first but this was not applied by map as you told me. I'll try to do with custom filter with keys. I have another question about the location of filter. Where is a proper position to create filter? May I create `interpreter.filter.js`? or just add `interpreter.controller.js`?

**Comment by corneadoug** [comment]
Would be better in a separated file

**Comment by jongyoul** [comment]
@corneadoug How about it?

**Comment by corneadoug** [comment]
Tested, LGTM

**Comment by jongyoul** [comment]
Will merge if there's no more discussion.

**Pull request closed without merging**
