### PR TITLE
[ZEPPELIN-1314] dump out the R command in debug mode

### PR DESCRIPTION
**Pull request by snowch**
### What is this PR for?

When diagnosing issues executing R, it would be useful to view the command that is being run so that command can be manually executed and debugged.
### What type of PR is it?

Improvement
### Todos
- [ ] - Task
### What is the Jira issue?
- https://issues.apache.org/jira/browse/ZEPPELIN-1314
### How should this be tested?

N/A
### Screenshots (if appropriate)

N/A
### Questions:
- Does the licenses files need update? No
- Is there breaking changes for older versions? No
- Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
@snowch Sorry for the delay,
I'm actually not an R expert so I'm not sure what this change bring.

Could you maybe provide a paragraph code example or before/after screenshot example to understand a bit more?

Also you can probably rebase your branch to have a green CI

**Comment by zjffdu** [comment]
@snowch Not sure how much dumping out the R command would help diagnose. Do you meet any case that failed to launch the R process ? If you want to diagnose the R process after it is launched. You can refer SparkOutputStream which will print output in debug level.  You just need add the following line in log4j.properties.
```
log4j.logger.org.apache.zeppelin.spark.SparkOutputStream=DEBUG
```

**Comment by snowch** [comment]
The R process launched, but I received an error.  I would like to be able to execute the R command manually which is why I want to dump out how R is being called.

**Comment by Leemoonsoo** [comment]
@snowch Thanks for explanation. Make sense. 
CI is failing with

```
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle-fail-build) @ zeppelin-spark_2.11 ---
/home/travis/build/apache/zeppelin/spark/src/main/java/org/apache/zeppelin/spark/ZeppelinR.java:148:5: unexpected token: executor
[INFO] 
[INFO] There are 1 checkstyle errors.
[ERROR] ZeppelinR.java[149:5] (extension) TreeWalker: Got an exception - expecting EOF, found 'outputStream'
```

Could you take a look and make CI green?

**Comment by snowch** [comment]
Damn, I had deleted my forked repository.  I've created a new PR here: https://github.com/apache/zeppelin/pull/1531

**Pull request closed without merging**
