### PR TITLE
[Minor] Remove hardcoded key in zeppelinhub.

### PR DESCRIPTION
**Pull request by yanboliang**
### What is this PR for?
Hardcoded seed/key may cause security issue, so remove potential risk.

### What type of PR is it?
[Improvement]

### Todos
No.

### What is the Jira issue?
No jira created.

### CODE REVIEW

**Comment by yanboliang** [comment]
@prabhjyotsingh Please help review.

**Comment by khalidhuseynov** [comment]
LGTM

**Comment by felixcheung** [comment]
@Leemoonsoo

**Comment by krishna-pandey** [comment]
We need to consider below while removing the key. Are we relying on any such behaviour by specifying the seed value?
"If two instances of Random are created with the same seed, and the same sequence of method calls is made for each, they will generate and return identical sequences of numbers."

Refer: http://docs.oracle.com/javase/8/docs/api/java/util/Random.html

**Comment by krishna-pandey** [comment]
LGTM.
It seems we are using SecureRandom which does not require seed explicitly to initialise and hence hardcoded key can be removed, unless we intentionally wanted a deterministic output.

**Comment by prabhjyotsingh** [comment]
Merging this if no more discussion.

**Pull request closed without merging**
