### PR TITLE
[Zeppelin-2718] Find and replace code in note

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Add feature for find and replace code in all paragraphs of note

### What type of PR is it?
[Feature]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2718

### How should this be tested?
Try to find and replace code in note (with help of search element)
find3

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by 1ambda** [comment]
Thanks for implementing such a great feature! 

1. Could you rebase against the current master? Since filenames were changes, it would be easier to review after rebasing
2. Regarding UX

- It would be nice to provide shortcut to trigger this feature (overriding `CTRL+F`, `CMD+F` or using a different key)
- It would be great if cursor move to the next search result if I stroke `enter` key like other editor do.
- Can we provide the search result count? (refer the screenshot)

image

**Comment by tinkoff-dwh** [comment]
@1ambda 
Added tests, search result count, `Ctrl-F` shortcut and move cursor by enter
Ready to review

**Comment by 1ambda** [comment]
@tinkoff-dwh Thank you for the update.

1. Can we add the shortcut into 

image

2. Can we use more thin border color?

image

Sorry for the late feedback.

**Comment by tinkoff-dwh** [comment]
@1ambda 
Shortcut added, borders width reduced

**Comment by 1ambda** [comment]
@tinkoff-dwh 

1. I realized that `CTRL+F` is bound to `Moving cursor` in paragraphs. Can we use `CTRL + OPT + F` (`ALT` in case of windows OS) or another key what you think better

2. If you change browser size, can't see other buttons like `<`, `replace` and so on. Could you move the find and replace dialog? 
(I used the half-sized browser)

image

**Comment by tinkoff-dwh** [comment]
@1ambda 
I have not found any command to which `Ctrl-F` is bounded in List of shortcut or in code. Could you give a link?

**Comment by 1ambda** [comment]
@tinkoff-dwh It's the default binding in emacs mode.

## in default modes 

https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

image

# in emacs mode

https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/emacs.js#L363

**Comment by tinkoff-dwh** [comment]
@1ambda 
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by 1ambda** [comment]
LGTM merge if no more discussion.

**Pull request closed without merging**
