### PR TITLE
[gh-pages] update contribution/webapplication.html

### PR DESCRIPTION
**Pull request by soralee**
### What is this PR for?
This PR is for matching current web environment. 
I changed `dev mode` part from `./grunt serve` to `yarn run dev` and fixed some typo.

### What type of PR is it?
[ Documentation]

### What is the Jira issue?
* None

### How should this be tested?
* build `gh-pages` branch and then check [webapplication.html](http://localhost:4000/contribution/webapplication.html) page.

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by soralee** [comment]
@AhyoungRyu @1ambda Could you review this, please whether I missed something or not?

**Comment by AhyoungRyu** [comment]
I found another typo in [contribution/zeppelinweb/goodPracticeGuide04.html](http://zeppelin.apache.org/contribution/zeppelinweb/goodPracticeGuide04.html). Could you fix this one as well? It should be `ng-bing` -> `ng-bind` :)

**Comment by 1ambda** [comment]
Hi @soralee :)

I would like to suggest using `'ngInject'l` instead of `$inject = ['$location'];` as like https://github.com/apache/zeppelin/pull/1994

> http://zeppelin.apache.org/contribution/zeppelinweb/goodPracticeGuide01.html

**Comment by soralee** [comment]
Thanks for review! @AhyoungRyu @1ambda 
I'll update this soon!

**Comment by soralee** [comment]
Hi~ @AhyoungRyu @1ambda 
I updated this as your comment! 
Thanks for that could you review again, please? :smiley:

**Comment by 1ambda** [comment]
Looks nice :)

**Comment by Leemoonsoo** [comment]
Looks good to me.

**Comment by AhyoungRyu** [comment]
Merge into `gh-pages` if there are no more comments.

**Pull request closed without merging**
