### PR TITLE
CI test for 1689

### PR DESCRIPTION
**Pull request by 1ambda**
This is a comparison group for #1689

### CODE REVIEW

**Comment by bzz** [comment]
Spark 2.0 profile fails with very stragne

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-fail-build) on project zeppelin: Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream - Element type "html" must be declared.:6:26 -> [Help 1]
[ERROR] 
```

**Comment by 1ambda** [comment]
@bzz That's because invalid `_tools/checkstyle.xml`. I'v just updated sorry for distraction :)

**Comment by 1ambda** [comment]
Asked to travis CI team.

https://github.com/travis-ci/travis-ci/issues/6950

**Comment by bzz** [comment]
I have asked ASF on another side as well [INFRA-12996](https://issues.apache.org/jira/browse/INFRA-12996)

**Comment by 1ambda** [comment]
I will rebase this

**Comment by bzz** [comment]
rebasing on #1709 should solve the CI issue

**Comment by 1ambda** [comment]
This will be closed (duplicated with #1689)

**Pull request closed without merging**
