### PR TITLE
[ZEPPELIN-3204] FIX: cursor in paragraph editor jumps

### PR DESCRIPTION
**Pull request by Savalek**
### What is this PR for?
Sometimes when a user enters text in the paragraph field the lower part of the paragraph starts to jump. This PR fixes this.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-3204](https://issues.apache.org/jira/browse/ZEPPELIN-3204)

### Screenshots
gif

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by zjffdu** [comment]
Awesome，I hit this issue as well. Thanks for fixing this.

**Comment by zjffdu** [comment]
BTW, is the screenshot the behavior before fixing ?

**Comment by zjffdu** [comment]
BTW, is the screenshot the behavior before fixing ?

**Comment by Savalek** [comment]
@zjffdu 
Here is an example of work after a fix:
gif_after

**Comment by timovwb** [comment]
This does not fix ZEPPELIN-3131, it's a different issue (see the video there).

**Comment by Savalek** [comment]
@timovwb sorry about this. I change the task number.

**Pull request closed without merging**
