### PR TITLE
ZEPPELIN-2833 JDBC Interpreter doesn't follow JDBC specification when…

### PR DESCRIPTION
**Pull request by ss77892**
… getting the results.

### What is this PR for?

Fix for ZEPPELIN-2833. JDBC Interpreter uses result set next() method after it's already reached the end. According the JDBC documentation that may cause SQL exception.

### What type of PR is it?
Bug Fix

### Todos
None

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-2833

### How should this be tested?

Use Phoenix 4.7+ select * query for tables that have less than 1000 records. Without patch an exception about closed Result set will be thrown.

### Questions:
* Does the licenses files need update?
No
* Is there breaking changes for older versions?
No
* Does this needs documentation?
No

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
Tested on local (for hive and phoenix) works as expected. LGTM!

**Comment by ss77892** [comment]
@felixcheung As I mentioned in the JIRA the default jdbc driver that is used in tests has different behavior ( allows to make call next() even if the result set is already at the end). Not sure how to develop a test in this case.

**Comment by ss77892** [comment]
@felixcheung all the tests that doesn't reach maxCount may be considered as the test that calls resultSet.next() multiple time (if the default jdbc would be Phoenix they would produce this exception) and there is a test testSelectQueryMaxResult that tests that the limit has been reached.

**Comment by prabhjyotsingh** [comment]
Will merge this if no more discussion.

**Pull request closed without merging**
