### PR TITLE
[ZEPPELIN-1273] Use Math.abs to determine if custom formatter should be called for y axis values

### PR DESCRIPTION
**Pull request by prasadwagle**
### What is this PR for?
Use Math.abs to determine if custom formatter should be called for y axis values.

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
[ZEPPELIN-1273] https://issues.apache.org/jira/browse/ZEPPELIN-1273

### How should this be tested?
Create simple table with two columns - date in one and large negative numbers like -10000000 in other. Display line chart and see that the y axis values are formatted like -10M.

### Questions:
* Does the licenses files need update? 
No
* Is there breaking changes for older versions?
No
* Does this needs documentation?
No

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me, thank you @praagarw 
Merging to only to master, if there is no further discussion

Or do you think we should also apply this to upcoming 0.6.1 as well?

**Comment by prasadwagle** [comment]
> Or do you think we should also apply this to upcoming 0.6.1 as well?
I can do that. What branch should I use for 0.6.1?

I merged with latest master this morning. Two checks in the build failed. Any ideas how to fix? I am going to restart the build in case they are due to flaky tests.

```
https://travis-ci.org/apache/zeppelin/jobs/149535074

Results :

Failed tests:
  ZeppelinSparkClusterTest.zRunTest:204 expected:<FINISHED> but was:<ERROR>


https://travis-ci.org/apache/zeppelin/jobs/149535075

Tests in error:
  SparkInterpreterTest.setUp:93 Â» NullPointer
  SparkInterpreterTest.shareSingleSparkContext:245 Â» NullPointer
  SparkInterpreterTest.testBasicIntp:136 Â» NullPointer
  SparkInterpreterTest.testCreateDataFrame:182 Â» NullPointer
  SparkInterpreterTest.testDisableImplicitImport:280 Â» NullPointer
  SparkInterpreterTest.testEnableImplicitImport:264 Â» NullPointer
  SparkInterpreterTest.testEndWithComment:171 Â» NullPointer
  SparkInterpreterTest.testListener:176 Â» NullPointer
  SparkInterpreterTest.testNextLineComments:160 Â» NullPointer
  SparkInterpreterTest.testNextLineCompanionObject:166 Â» NullPointer
  SparkInterpreterTest.testNextLineInvocation:155 Â» NullPointer
  SparkInterpreterTest.testReferencingUndefinedVal:220 Â» NullPointer
  SparkInterpreterTest.testSparkSql:200 Â» NullPointer
  SparkInterpreterTest.testZShow:193 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
```

**Comment by Leemoonsoo** [comment]
@prasadwagle Thanks for the fix!
LGTM. I don't think it's blocker for 0.6.1 release, but it will be nice if we can include it in 0.6.1 release.

**Comment by Leemoonsoo** [comment]
merge into master and branch-0.6 if there're no more discussions.

**Comment by bzz** [comment]
Let's merge! :Shipit:

**Pull request closed without merging**
