### PR TITLE
[ZEPPELIN-1964] Layout info is lost after refresh

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes layout info is lost after refreshing issue.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1964

### How should this be tested?
Please do resize paragraph and then refresh browser. 

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by 1ambda** [comment]
I will review and give you feedback soon. Thanks for fixing bug @astroshim!

**Comment by soralee** [comment]
Thanks @astroshim for fixing this!
Tested and it works well like below! LGTM :+1: 
z_1964_a_check

**Comment by AhyoungRyu** [comment]
Tested and it works well as expected. LGTM

**Comment by AhyoungRyu** [comment]
Merge into branch-0.7 and master if there are no more comments

**Comment by AhyoungRyu** [comment]
@astroshim This patch just merged into master, but couldn't automatically cherrypicked to branch-0.7 since master's `paragraph.controller.js` is a bit different with branch-0.7's after SPELL is merged. Could you create separated PR based on `branch-0.7` so that this can be included to next 0.7.1 release?

**Pull request closed without merging**
