### PR TITLE
ZEPPELIN-3286. Run All Paragraphs stops if there is a disabled paragraph mid-run

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
Trivial fix that just skip the disable paragraph when run all paragraphs. 

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3286

### How should this be tested?
* Manually tested

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
@Tagar Could you help verify this PR ? Thanks

**Comment by Tagar** [comment]
thanks Jeff! will validate a bit later today.

**Comment by zjffdu** [comment]
ping @Tagar

**Comment by Tagar** [comment]
Tested manually - this patch fixes issue described in ZEPPELIN-3286
Thank you @zjffdu

**Pull request closed without merging**
