### PR TITLE
add zeppelin.dep.localrepo in zeppelin config

### PR DESCRIPTION
**Pull request by oeegee**
<property>
  <name>zeppelin.dep.localrepo</name>
  <value>local-repo</value>
  <description>Local repository for dependency loader</description>
</property>

### What is this PR for?
I wanted to change the default directory somewhere else.
and then property input 'zeppelin.dep.localrepo'.

And I refer to the Zeppelin document and change the location as shown in the screenshot below.
reference : https://zeppelin.apache.org/docs/latest/interpreter/spark.html

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/
* Put link here, and add [ZEPPELIN-*Jira number*] in PR title, eg. [ZEPPELIN-533]

### How should this be tested?
Outline the steps to test the PR here.

### Screenshots (if appropriate)
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@oeegee Thank you for the contribution. If we can change this property value via zeppelin-site.xml, then how about adding this property info to [this configuration table](https://zeppelin.apache.org/docs/0.8.0-SNAPSHOT/install/configuration.html#zeppelin-properties) as well? This file is located in [here](https://github.com/apache/zeppelin/blob/master/docs/install/configuration.md) :)

**Comment by oeegee** [comment]
If you refer to the source below, it should be added as ZEPPELIN_DEP_LOCALREPO ".

https://github.com/apache/zeppelin/blob/master/zeppelin-zengine/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
---------------------------------------------------------------------------
608 : ZEPPELIN_DEP_LOCALREPO("zeppelin.dep.localrepo", "local-repo"),
---------------------------------------------------------------------------

**Comment by AhyoungRyu** [comment]
@oeegee Not sure I got your point well, but I just suggested you to update [this config file](https://github.com/apache/zeppelin/blob/master/docs/install/configuration.md#zeppelin-properties) accordingly.

**Comment by AhyoungRyu** [comment]
Thanks @oeegee Looks good to me. 
Merge into branch-0.7 and master if there are no comments on this.

**Pull request closed without merging**
