### PR TITLE
[ZEPPELIN-3335] trim property name of interpreter settings

### PR DESCRIPTION
**Pull request by rockiee281**
### What is this PR for?
trim property name of interpreter settings

### What type of PR is it?
Improvement 

### Todos
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3335

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by felixcheung** [comment]
can you check https://travis-ci.org/rockiee281/zeppelin/builds/353672192

**Comment by rockiee281** [comment]
@felixcheung  Hi, I check the build errors but seems those error was caused by other codes on the master branch. Should I wait until others resolve those problems?

**Comment by zjffdu** [comment]
could you do a rebase first ?

**Comment by rockiee281** [comment]
Hi， @zjffdu   rebase done

**Comment by zjffdu** [comment]
@rockiee281  seems you didn't do rebase correctly , or you can create another PR

**Comment by rockiee281** [comment]
Sorry, I'm not familiar with git rebase ,create PR  #2884  instead

**Pull request closed without merging**
