### PR TITLE
[ZEPPELIN-2683] fix: should provide horizontal scrollbar for table

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

fixed to use a more broad column width (150+)

- the default width is 150
- if column.length * 10 > 150, use it

additionally, I tried [ui-grid-auto-fit-columns](https://www.npmjs.com/package/ui-grid-auto-fit-columns) but doesn't work.

### What type of PR is it?
[Improvement]

### Todos

DONE

### What is the Jira issue?

[ZEPPELIN-2583](https://issues.apache.org/jira/browse/ZEPPELIN-2683)

### How should this be tested?

Execute these paragraphs sequentially

```scala
%spark

import org.apache.commons.io.IOUtils
import java.net.URL
import java.nio.charset.Charset

// Zeppelin creates and injects sc (SparkContext) and sqlContext (HiveContext or SqlContext)
// So you don't need create them manually

// load bank data
val bankText = sc.parallelize(
    IOUtils.toString(
        new URL("https://s3.amazonaws.com/apache-zeppelin/tutorial/bank/bank.csv"),
        Charset.forName("utf8")).split("\n"))

case class Bank(
    age: Integer, 
    job: String, 
    marital: String, 
    education: String, 
    balance: Integer,
    housing: String,
    loan: String,
    contact: String,
    day: Int,
    month: String,
    duration: Int,
    campaign: String,
    pdays: Int,
    previous: Int,
    poutcome: String,
    y: String
)

val bank = bankText.map(s => s.split(";")).filter(s => s(0) != "\"age\"").map(
    s => Bank(s(0).toInt, 
        s(1).replaceAll("\"", ""),
        s(2).replaceAll("\"", ""),
        s(3).replaceAll("\"", ""),
        s(5).replaceAll("\"", "").toInt,
        s(6).replaceAll("\"", ""),
        s(7).replaceAll("\"", ""),
        s(8).replaceAll("\"", ""),
        s(9).replaceAll("\"", "").toInt,
        s(10).replaceAll("\"", ""),
        s(11).replaceAll("\"", "").toInt,
        s(12).replaceAll("\"", ""),
        s(13).replaceAll("\"", "").toInt,            
        s(14).replaceAll("\"", "").toInt,            
        s(15).replaceAll("\"", ""),
        s(16).replaceAll("\"", "")
    )
).toDF()

bank.registerTempTable("bank")
```

```sql
%sql

select 
    age as age,
    job as job,
    marital as marital_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    education as education_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    balance as balance_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    housing as housing_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    loan as loan_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    contact as contact_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    day as days_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    month as month_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    duration as duration_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    campaign as compaign_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    pdays as pdays_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    previous as previous_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    poutcome as poutcome_ABCDEFGHIJKLMNOPQRSTUVWXYZ,
    y as y_ABCDEFGHIJKLMNOPQRSTUVWXYZ
    
from bank
```

#### Before

image

#### After

2683_after

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
Ready to review.

**Comment by tinkoff-dwh** [comment]
Tested, good improvment. LGTM

**Comment by 1ambda** [comment]
@tinkoff-dwh Thanks for the review. Merge if no more discussion.

**Comment by soralee** [comment]
Cool! LGTM

**Pull request closed without merging**
