### PR TITLE
Env variable to configure maven central repo

### PR DESCRIPTION
**Pull request by andreaTP**
### What is this PR for?
When deploying Zeppelin in private Cloud or within closed networks, it happens that Maven Central isn't directly reachable, so we want to configure our own proxy and do not have to wait for minutes long timeouts when importing external libraries. It is anyhow worth to let user configure maven central repo instead of hardcoding the URL.

### What type of PR is it?
Improvement

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by andreaTP** [comment]
updated travis access, could you run tests again please?

**Comment by felixcheung** [comment]
try close and reopen this PR to trigger Travis

**Comment by prabhjyotsingh** [comment]
Did you switch on 'zeppelin' repository from  https://travis-ci.org/profile  (https://zeppelin.apache.org/contribution/contributions.html#continuous-integration) ? 

Also after that goto https://travis-ci.org/andreaTP/zeppelin/settings and switch on "Build pushes" and "Build pull requests".

**Comment by andreaTP** [comment]
I reopen this

**Pull request closed without merging**
