### PR TITLE
[HOTFIX] change 1.5-SNAPSHOT to 1.5-20160502.230123-45

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
This is to fix CI which is mostly failing for resource org.apache.apache.resources:apache-jar-resource-bundle:1.5-SNAPSHOT, until the resource is generated in https://repository.apache.org/content/groups/snapshots/org/apache/apache/resources/apache-jar-resource-bundle/1.5-SNAPSHOT/

### What type of PR is it?
[Hot Fix]

### How should this be tested?
CI should be green

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@Leemoonsoo should we have this change, to make CI green ?

**Comment by Leemoonsoo** [comment]
@prabhjyotsingh Thanks for addressing CI issue.

I'm not sure changing `1.5-SNAPSHOT` to `1.5-20160502.230123-45` is proper way of accessing SNAPSHOT artifact.

Shell we try

```
<project>
  ...
  <build>
    <plugins>
      <!-- Turn this into a lifecycle -->
      <plugin>
        <artifactId>maven-remote-resources-plugin</artifactId>
        <version>1.5</version>
        <executions>
          <execution>
            <id>process-remote-resources</id>
            <goals>
              <goal>process</goal>
            </goals>
            <configuration>
              <resourceBundles>
                <resourceBundle>org.apache:apache-jar-resource-bundle:1.0</resourceBundle>
              </resourceBundles>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  ...
</project>
```
?
which is proposed usage in http://maven.apache.org/plugins/maven-remote-resources-plugin/usage.html, if it does the same thing that current plugin configuration does.

**Comment by prabhjyotsingh** [comment]
Sure let me try that as well.

**Comment by minahlee** [comment]
Seems like this PR fixes `apache-jar-resource-bundle` download issue. Shall we merge it as hot fix?

**Comment by prabhjyotsingh** [comment]
have triggered CI again, I'll merge this as a HOTFIX if it doesn't fail for `apache-jar-resource-bundle`.

**Pull request closed without merging**
