### PR TITLE
Add more unit tests for notebook controller

### PR DESCRIPTION
**Pull request by r-kamath**

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
:+1:  more unit test

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by corneadoug** [comment]
Looks good.
Its printing a lot of: ``LOG: 'Send >> %o, %o', 'GET_NOTE', Object{op: 'GET_NOTE', data: Object{id: undefined}}`` when tests are running

**Comment by r-kamath** [comment]
@corneadoug those logs are caused by the function calls from tests. Will see if there is a way to ignore the console logs from karma config (similar to `drop_console ` in Gruntfile)

**Comment by corneadoug** [comment]
I tried using this option:
```
client: {
  captureConsole: false
},
```
But it doesn't change anything

**Comment by r-kamath** [comment]
@corneadoug `captureConsole` isn't working for me too. Two options I can think of are,
1) Let the tests print the log messages on console
2) Remove `console.log`, anyway these logs are same as what we get from Network -> WS -> Frames. And the js can be debugged on Chrome/FF

**Comment by corneadoug** [comment]
Found that also while searching:

> For those looking for a quick and dirty fix for now, putting the following line:
> ``console.log = function() {}``
> at the top of your spec file will suppress all console.log statements in your code. Alternatively, you could redefine it to do anything else, such as a write to a file.

**Comment by r-kamath** [comment]
re-defining`console.log = function() {}` in main.js works! We can use this till we get `captureConsole: false` working.
Thank you

**Pull request closed without merging**
