### PR TITLE
[HOTFIX] [ZEPPELIN-2286] Fix CI and split some test matrix that often exceeds time limits (50min)

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR optimize CI test matrix while keeping the same test coverage. 

from
1. RAT (1~2min)
2. All modules with -Pbuild-distr flag, spark 2.1 and scala 2.11 (40~50min)
3. All modules with -Pbuild-distr flag, spark 2.0 and scala 2.11 (40~50min)
4. spark 1.6 and scala 2.10 (7~9min)
5. spark 1.6 and scala 2.11 (7~8min)
7. Selenium (20~23min)
8. python2 (6~7min)
9. python3 (6 ~7min)
Total. 128 ~156min

to
1. RAT  (1~2min)
2. Core modules without interpreters (14~15min)
3. Selenium (20~23min)
4. All interpreters except for spark, livy (9~11min)
5. Spark 2.1 and scala 2.11, livy (7~9min)
6. Spark 2.0 and scala 2.11 (7~8min)
7. Spark 1.6 and scala 2.10 (7~8min)
8. Spark 1.6 and scala 2.11 (7~8min)
9. python2 (6~7min)
10. python3 (6 ~7min)
Total. (84 ~98min)

### What type of PR is it?
Improvement | Hot fix.

### Todos
* [x] - Optimize CI test matrix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2286

### How should this be tested?
CI green

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
LGTM

**Comment by sravan-s** [comment]
Hi,
Recently, I have been facing two issues in the CI
First one is CI getting timed out, which is getting addressed here
The other one is: 
`  NotebookTest.testAngularObjectRemovalOnInterpreterRestart:699 expected null, but was:<AngularObject{noteId='2CB425J2J', paragraphId='null', object=object1, name='o1'}>
`
from job-3 in the test matrix. Is it getting addressed in this pull request? It is mentioned in the comments of #2154

**Comment by Leemoonsoo** [comment]
@sravan-s Test failure `NotebookTest.testAngularObjectRemovalOnInterpreterRestart:699` is already addressed in the commit  https://github.com/apache/zeppelin/commit/00e6aed0c7bc514bc270703b188b841b6835defd#diff-470a9a96b665c7eb7a4d8f2888c3a2ba.
Also created an issue for future followup https://issues.apache.org/jira/browse/ZEPPELIN-2284.

**Comment by Leemoonsoo** [comment]
I rebased to current master and CI becomes green!
Merge this PR to master and branch-0.7 as a hotfix while it significantly reduce chance of failing 2nd and 3rd test matrix by timeout.

**Pull request closed without merging**
