### PR TITLE
ZEPPELIN-999 Support alias for JDBC properties

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
In case of using JdbcInterpreter, you should use %jdbc(prefix) if you set multiple configurations. This PR makes you use %prefix only. 

### What type of PR is it?
[Improvement]

### Todos
* [x] - Change %prefix to %jdbc(prefix) during running paragraph

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-999

### Screenshots (if appropriate)
screen shot 2016-06-15 at 12 42 32 am
screen shot 2016-06-15 at 12 42 49 am

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
Nice! Can this be generalized to not just jdbc?

**Comment by jongyoul** [comment]
@felixcheung I also have a plan to generalize this feature after 0.6.0 releases. :-)

**Comment by bzz** [comment]
Thank you @jongyoul, 👍  for having tests!
Improving this further by generalizing to other interpreters after a release sounds like a very good plan.

Looks great to me.

**Comment by jongyoul** [comment]
@bzz I'll merge it into master and branch-0.6

**Comment by jongyoul** [comment]
I also made a PR as a generalized version. https://issues.apache.org/jira/browse/ZEPPELIN-1012

**Pull request closed without merging**
