### PR TITLE
Fix Travis build error with ls command

### PR DESCRIPTION
**Pull request by felixcheung**
### What is this PR for?
Fix error with

```
$ ls -la .spark-dist ${HOME}/.m2/repository/.cache/maven-download-plugin
ls: cannot access /home/travis/.m2/repository/.cache/maven-download-plugin: No such file or directory
.spark-dist:
total 4
drwxr-xr-x  2 travis travis    6 Nov 25 19:27 .
drwxr-xr-x 47 travis travis 4096 Nov 25 19:27 ..
The command "ls -la .spark-dist ${HOME}/.m2/repository/.cache/maven-download-plugin" failed and exited with 2 during .
Your build has been stopped.
```
https://travis-ci.org/apache/zeppelin/jobs/178918031

### What type of PR is it?
Bug Fix

### How should this be tested?
CI

### Questions:
* Does the licenses files need update? None
* Is there breaking changes for older versions? None
* Does this needs documentation? None

### CODE REVIEW

**Comment by felixcheung** [comment]
@Leemoonsoo please have a look, thanks!

**Comment by felixcheung** [comment]
output looks fine
```
0.01s$ ls -la .spark-dist ${HOME}/.m2/repository/.cache/maven-download-plugin || true
/home/travis/.m2/repository/.cache/maven-download-plugin:
total 0
drwxr-xr-x 2 travis travis  6 Nov  5 03:03 .
drwxr-xr-x 3 travis travis 34 Nov 20 20:13 ..
.spark-dist:
total 4
drwxr-xr-x  2 travis travis    6 Nov  5 03:03 .
drwxr-xr-x 47 travis travis 4096 Nov 25 20:57 ..
```

**Comment by Leemoonsoo** [comment]
LGTM!

**Comment by felixcheung** [comment]
thanks!

**Pull request closed without merging**
