### PR TITLE
[MINOR] Resolve bower dependency conflict, hang (zeppelin-web)

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Due to angular dependency conflict, `bower install` command doesn't proceed further. It causes the whole build fail. (even in local)

```
62 silly postinstall zeppelin-web@0.0.0 /Users/jl/local/src/g/zeppelin/zeppelin-web/zeppelin-web-cca93801
63 info lifecycle zeppelin-web@0.0.0~postinstall: zeppelin-web@0.0.0
64 verbose lifecycle zeppelin-web@0.0.0~postinstall: unsafe-perm in lifecycle true
65 verbose lifecycle zeppelin-web@0.0.0~postinstall: PATH: /Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/bin/node-gyp-bin:/Users/jl/local/src/g/zeppelin/zeppelin-web/node_modules/.bin:/Users/jl/local/src/g/zeppelin/zeppelin-web/node:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
66 verbose lifecycle zeppelin-web@0.0.0~postinstall: CWD: /Users/jl/local/src/g/zeppelin/zeppelin-web
67 silly lifecycle zeppelin-web@0.0.0~postinstall: Args: [ '-c', 'bower install --silent' ]
68 silly lifecycle zeppelin-web@0.0.0~postinstall: Returned: code: 1  signal: null
69 info lifecycle zeppelin-web@0.0.0~postinstall: Failed to exec postinstall script
70 verbose stack Error: zeppelin-web@0.0.0 postinstall: `bower install --silent`
70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/lib/utils/lifecycle.js:255:16)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at EventEmitter.emit (events.js:191:7)
70 verbose stack     at ChildProcess.<anonymous> (/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/lib/utils/spawn.js:40:14)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at ChildProcess.emit (events.js:191:7)
70 verbose stack     at maybeClose (internal/child_process.js:877:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
71 verbose pkgid zeppelin-web@0.0.0
72 verbose cwd /Users/jl/local/src/g/zeppelin/zeppelin-web
73 error Darwin 16.1.0
74 error argv "/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node" "/Users/jl/local/src/g/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install"
75 error node v6.9.1
76 error npm  v3.10.8
77 error code ELIFECYCLE
78 error zeppelin-web@0.0.0 postinstall: `bower install --silent`
78 error Exit status 1
79 error Failed at the zeppelin-web@0.0.0 postinstall script 'bower install --silent'.
79 error Make sure you have the latest version of node.js and npm installed.
79 error If you do, this is most likely a problem with the zeppelin-web package,
79 error not with npm itself.
79 error Tell the author that this fails on your system:
79 error     bower install --silent
79 error You can get information on how to open an issue for this project with:
79 error     npm bugs zeppelin-web
79 error Or if that isn't available, you can get their info via:
79 error     npm owner ls zeppelin-web
79 error There is likely additional logging output above.
80 verbose exit [ 1, true ]
```

##### Small Details

you can get this `resolutions` field by executing `bower install --force`

```
"resolutions": {
    "angular": ">=1.2.15 <1.6"
  }
```

but we are using angular 1.5.0+ the resolution will cause errors like

```
[INFO]  undefined
       ERROR: 'Error: [$injector:unpr] Unknown provider: $$forceReflowProvider <- $$forceReflow <- $$animateQueue <- $animate <- $compile <- $$animateQueue
[INFO] http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24forceReflowProvider%20%3C-%20%24%24forceReflow%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue

...
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 69 of 69 (34 FAILED) (0.236 secs / 0.269 secs)
[INFO] Warning: Task "karma:unit" failed. Use --force to continue.
```

So we need to specify 1.5.0 as the min angular version

### What type of PR is it?
[Bug Fix | Hot Fix]

### Todos
* [x] - Task

### What is the Jira issue?

Minor

### How should this be tested?

CI will do that :)

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
Already tested on my own travis: https://travis-ci.org/1ambda/zeppelin/builds/181105470

\cc @bzz @khalidhuseynov

**Comment by AhyoungRyu** [comment]
I've tested this patch and finally it works now. Tested both whole build `mvn clean package -DskipTests` and `npm run build` under `zeppelin-web`. 
Thanks for the quick fix!

**Comment by Leemoonsoo** [comment]
Thanks for the fix. 
Confirmed it fixes build problem if i remove node_modules bower_components directories. LGTM.

While the bug breaks build, merge this patch to master as a hotfix.

**Comment by Leemoonsoo** [comment]
@soralee reported that branch-0.6 is also failing with this problem.

And i confirmed branch-0.6 build fails with the same problem and this fixes the problem.
So i'm going to back port this patch to branch-0.6.

**Comment by soralee** [comment]
For the more information, I faced this error log in branch-0.6 on Ubuntu
```
[ERROR] bower                                  ECONFLICT Unable to find suitable version for angular
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.178 s
[INFO] Finished at: 2016-12-06T12:14:51+09:00
[INFO] Final Memory: 19M/254M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:bower (bower install) on project zeppelin-web: Failed to run task: 'bower --allow-root install' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:bower (bower install) on project zeppelin-web: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:66)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower --allow-root install' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:59)
	at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:31)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:64)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Pull request closed without merging**
