### PR TITLE
[ZEPPELIN-4448] delete unused variable in ZeppelinServer.java

### PR DESCRIPTION
**Pull request by iamabug**
### What is this PR for?
delete an unused variable in ZeppelinServer.java

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZEPPELIN-4448] https://issues.apache.org/jira/browse/ZEPPELIN-4448

### How should this be tested?
Travis CI

### Questions:
* Does the licenses files need update?
no
* Is there breaking changes for older versions?
no
* Does this needs documentation?
no

### CODE REVIEW

**Comment by zjffdu** [comment]
@iamabug Could you update the PR description ?

**Comment by iamabug** [comment]
> @iamabug Could you update the PR description ?

Is it ok now ?

**Comment by zjffdu** [comment]
Please add prefix  [ZEPPELIN-XXXX] to the PR title

**Comment by iamabug** [comment]
> Please add prefix [ZEPPELIN-XXXX] to the PR title

Done.

**Comment by zjffdu** [comment]
Thanks @iamabug one last thing, could you paste the travis link here ?

**Comment by iamabug** [comment]
https://travis-ci.org/iamabug/zeppelin

Is this the right link ?

**Comment by zjffdu** [comment]
That's right, thanks for the contribution @iamabug 
The failed test is due hadoop-lzo issue which is being fixed in another PR. I will let you know when that PR is merged, then you can rebase your PR and trigger the CI again.

**Comment by iamabug** [comment]
Sure. Thanks for your guidance.

**Comment by zjffdu** [comment]
@iamabug The hadoop lzo issue is fixed, could you do a rebase and trigger the travis CI again ?

**Comment by iamabug** [comment]
@zjffdu Travis CI has run again but two of them failed, is there something wrong ?

**Comment by zjffdu** [comment]
These issues are fixing somewhere else, will merge this PR if no more comments

**Pull request closed without merging**
