### PR TITLE
ZEPPELIN-2947 Ignite version is updated up to 2.2.0

### PR DESCRIPTION
**Pull request by agura**
### What is this PR for?
Apache Ignite version is updated up to 2.2.0 for Apache Ignite interpreter.

### What type of PR is it?
[Improvement]

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2947

### How should this be tested?
Unit-tests.

### CODE REVIEW

**Comment by agura** [comment]
Should I restart tests?

**Comment by felixcheung** [comment]
any error related to this PR? https://travis-ci.org/agura/zeppelin/builds/278262889
if not, feel free to restart

**Comment by agura** [comment]
I've restarted tests and have failed checks again. As I can see there are no wails that is related with changes.

**Comment by Leemoonsoo** [comment]
Error looks not related to this change.

LGTM and merge to master if no further comment!

**Pull request closed without merging**
