### PR TITLE
[DOC] Release Apache Zeppelin 0.6.2

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
- Add release note for 0.6.2
- Update download page with the latest version to 0.6.2

### What type of PR is it?
Documentation

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @minahlee preparing the release note.

zeppelin-0.6.1 was built with spark-2.0/scala-2.11 and required to rebuild from source to use spark 1.6/scala-2.10.

zeppelin-0.6.2 now have binary compatibility to spark-2.0/scala-2.11 and spark-1.6/scala-2.10, doesn't require rebuild and even different spark versions can be used simultaneously.

@minahlee Could you emphasis this change?

**Comment by minahlee** [comment]
@Leemoonsoo Thank you for reviewing. Could you review again if the last change is good?

**Comment by anthonycorbacho** [comment]
LG*reat*TM

**Comment by Leemoonsoo** [comment]
LGTM!

**Comment by minahlee** [comment]
Merging if there is no more discussion

**Pull request closed without merging**
