### PR TITLE
[ZEPPELIN-1085] Make dropdown menu scrollbar always visible

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
In Zeppelin docs website, there are 4 dropdown menus(Quick Start, Interpreters, Display System and More) in the navbar. Especially **Interpreters** and **More** menu have lots of lists so I made this dropdown menu scrollable in #1004.
Originally the scroll bar is shown up when  a user is trying to scroll down. That's why it's hard to notice there are more menus in the dropdown menu.  See [this issue](https://issues.apache.org/jira/browse/ZEPPELIN-1085).

So I made this scroll bar always visible. But only for chrome & safari. Unfortunately, Firefox doesn't support custom scroll bar. See [here](http://stackoverflow.com/questions/18317634/force-visible-scrollbar-in-firefox-on-mac-os-x).
In short, it says
>There is no way to actually "force" Firefox render the old-style scrollbar since the default scrollbar used in the system is predefined by the OS itself (note that you can modify which scrollbar you want in System Preferences).

### What type of PR is it?
Improvement

### TODO
- [x] : test this in major browsers

### What is the Jira issue?
[ZEPPELIN-1085](https://issues.apache.org/jira/browse/ZEPPELIN-1085)

### How should this be tested?
[Build the Zeppelin docs website](https://github.com/apache/zeppelin/tree/master/docs#build-documentation) in your local and check the dropdown menu in navbar. The scrollbae has to be shown right after you click **Interpreters** or **More** menu.

### Screenshots (if appropriate)
 - Before : scrollbar is only shown up when you are trying to scroll up & down
before

 - After : always visible
after

 - In case of IE, you can always see the scrollbar. So it's not a problem originally. 
screen shot 2016-07-07 at 5 41 27 pm

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@jeffsteinmetz It will be appreciate if you can review this PR as a reporter of this issue :)

**Comment by Leemoonsoo** [comment]
Thanks @AhyoungRyu for improvement.
Tested with Chrome and Safari. LGTM

**Comment by prabhjyotsingh** [comment]
LGTM

**Comment by jeffsteinmetz** [comment]
LGTM
At least in Firefox, the scroll bar now displays for a few seconds (doesn't stay, but its an improvement).
Chrome and Safari work as expected.

Tested with:
 - Chrome on OSX: Version 51.0.2704.103 (64-bit)
 - Safari: Version 9.1.1 (10601.6.17)
 - Firefox on OSX: 47.0.1

**Comment by Leemoonsoo** [comment]
Merge it into master if there is no more discussion

**Comment by AhyoungRyu** [comment]
@jeffsteinmetz Right. So Firefox users can know they can scroll down and there is more menus even though this PR couldn't be applied to Firefox. 
Thanks for testing this @Leemoonsoo @jeffsteinmetz :)

**Pull request closed without merging**
