### PR TITLE
[ZEPPELIN-1178] Tooltip: Show chart type when hovering over chart icon

### PR DESCRIPTION
**Pull request by vensant**
### What is this PR for?
A usability improvement: Added tooltips for the chart icons in Zeppelin paragraphs, showing the chart types when hovering over the chart icons.

### What type of PR is it?
Improvement

### Todos
NA

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1178

### How should this be tested?
1. Deploy Zeppelin and navigate to zeppelin tutorial
2. Run a paragraph and hover over the chart icon buttons to see the tooltip getting displayed.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by bzz** [comment]
@vensant thank you for contributing improvement!

With GUI changes, in my experience, adding simple screenshots to the PR itself (drag'n'drop to description) before\after usually helps to speed up the review process a lot.

CI failure seems not related, look lik networking issue on Travis side :\

```
[INFO] Zeppelin: web Application .......................... FAILURE [01:20 min]
[INFO] grunt-ng-annotate@0.10.0 node_modules/grunt-ng-annotate
[ERROR] npm ERR! argv "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! Callback called more than once.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/zeppelin/zeppelin-web/npm-debug.log
```

**Comment by corneadoug** [comment]
Tested, LGTM
However maybe the tooltip names could be changed to something more simple:
* Multi Bar Chart -> Bar Chart
* Stacked Area Chart -> Area Chart
* Line With Focus Chart -> Line Chart

**Comment by Leemoonsoo** [comment]
+1 for @corneadoug 's comment. Shorter name is actually more clear and easier to understand.

**Comment by vensant** [comment]
Hi all,

I will change the tool tip names as suggested.

Thank you all

Regards,
Venkat

**Comment by prabhjyotsingh** [comment]
+1 for @corneadoug, rest LGTM!

**Comment by vensant** [comment]
Code changes done as per the review comment.

**Comment by corneadoug** [comment]
@vensant Thank you! Merging if there is no more discussions

**Comment by vinayshukla** [comment]
Thanks @vensant

**Pull request closed without merging**
