### PR TITLE
[ZEPPELIN-1818] Absolute local repo path in dependency downloader

### PR DESCRIPTION
**Pull request by DrIgor**
### What is this PR for?
Allow dependency resolver to use absolute path for local repo

### What type of PR is it?
Bug Fix

### What is the Jira issue?
[ZEPPELIN-1818](https://issues.apache.org/jira/browse/ZEPPELIN-1818)

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

Old implementation expected localRepoPath to be relative to ZEPPELIN_HOME.
It created broken path with absolute localRepoPath
(e.g. C:\Users\User\AppData\Local\Temp\..\C:\......)

Huge amount of tests passed absolute path to newRepositorySystemSession.

Path.resolve(...) works fine if parameter is absolute path

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks for the contribution.
Could you check CI build failure? Most test profile fails with

```
Tests in error: 
  SparkInterpreterTest.setUp:92 Â» NullPointer
  SparkInterpreterTest.shareSingleSparkContext:244 Â» NullPointer
  SparkInterpreterTest.testBasicIntp:125 Â» NullPointer
  SparkInterpreterTest.testCreateDataFrame:172 Â» NullPointer
  SparkInterpreterTest.testDisableImplicitImport:282 Â» NullPointer
  SparkInterpreterTest.testEnableImplicitImport:264 Â» NullPointer
  SparkInterpreterTest.testEndWithComment:160 Â» NullPointer
  SparkInterpreterTest.testNextLineComments:149 Â» NullPointer
  SparkInterpreterTest.testNextLineCompanionObject:155 Â» NullPointer
  SparkInterpreterTest.testNextLineInvocation:144 Â» NullPointer
  SparkInterpreterTest.testReferencingUndefinedVal:219 Â» NullPointer
  SparkInterpreterTest.testSparkSql:198 Â» NullPointer
  SparkInterpreterTest.testZShow:185 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
  SparkSqlInterpreterTest.setUp:61 Â» NullPointer
  PySparkInterpreterTest.setUp:87 Â» NullPointer
  PySparkInterpreterTest.setUp:94 Â» Interpreter java.lang.NullPointerException

Tests run: 25, Failures: 1, Errors: 18, Skipped: 0
```

**Comment by DrIgor** [comment]
@Leemoonsoo Thank you for reply!

I forgot about tests, it's my fault.

Tests didn't pass `zeppelin.dep.localrepo` property to interpreter. That's why DependecyResolver got `null`. Old implementation used string "null" as folder name =)

I think it's better not to pass null as repo path. I fixed tests to pass temporary folder as repo path


Now apt-get is failing, I promise it wasn't me :-)

**Comment by DrIgor** [comment]
Ready to review

One test failed, but it seems to be irrelevant

**Comment by Leemoonsoo** [comment]
Thanks for the fix @DrIgor!
LGTM and merge to master if there're no further comments

**Pull request closed without merging**
