### PR TITLE
[ZEPPELIN-675] "No data available" in invalid graph types for sql queries

### PR DESCRIPTION
**Pull request by snaveenp**
### What is this PR for?
Overriding graph message 'No data available' to 'Invalid Data, check graph settings'

### What type of PR is it?
Improvement

### Todos
* For Table and Map in graphs 'No data available' message is not shown, Maybe we want to implement this.

### What is the Jira issue?
[ZEPPELIN-675]  "No data available" in invalid graph types for sql queries

### How should this be tested?
Step 1: Run a sql query which will return 1 column or no records.
Step 2: Choose pie chart / bar chart
Verification: Earlier the message is "No data available", It should have been changed to 'Invalid Data, check graph settings'

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by snaveenp** [comment]
All checks have passed.

**Comment by corneadoug** [comment]
@snaveenp Thanks, let me do a quick test

**Comment by corneadoug** [comment]
Tested, LGTM

**Comment by snaveenp** [comment]
@corneadoug Could you merge this?

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by corneadoug** [comment]
@snaveenp Could you tell me your JIRA id?

**Comment by snaveenp** [comment]
my jira id is naveenimaginea

**Pull request closed without merging**
