### PR TITLE
[ZEPPELIN-1446] Fix broken layout of `Create new interpreter` UI.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes broken layout of `Create new interpreter` UI.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1446

### How should this be tested?
- Try to create new interpreter on the Interpreters menu.

### Screenshots (if appropriate)
- before
image

- after
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@astroshim I think it was handled already in #1395. This is what I can see in the latest master branch :)
screen shot 2016-09-17 at 11 11 36 am

**Comment by AhyoungRyu** [comment]
@astroshim Good catch and looks better! 
Can we make "A" and "B" have same space? Need more space to "A" :)
screenshot

**Comment by astroshim** [comment]
@AhyoungRyu Thank you for your kind review. I just fix the space.

**Comment by corneadoug** [comment]
@astroshim 

Could we maybe try to keep the same spacing style as the interpreter edit?

#### Interpreter Edit:
screen shot 2016-09-19 at 3 21 26 pm

#### Interpreter Create:
screen shot 2016-09-19 at 3 20 40 pm

**Comment by AhyoungRyu** [comment]
@corneadoug Actually I did that work in [here](https://github.com/apache/zeppelin/pull/1434/files#diff-52843fa71a36ded9162a8bbb812459bcR234)... :)

**Comment by corneadoug** [comment]
@AhyoungRyu I was talking about the spacing below `Option`, `Properties` and `Dependencies`.
 It stayed the same in your PR

**Comment by astroshim** [comment]
Thank you @AhyoungRyu and @corneadoug . 
I just fixed space problems.

**Comment by AhyoungRyu** [comment]
@corneadoug Ah I got it. I'll do the same work as @astroshim did in my PR then :D
@astroshim Thanks for your quick response!

**Comment by corneadoug** [comment]
Tested LGTM
@astroshim Can you just rebase? That should make the CI green

**Comment by astroshim** [comment]
I rebased but build failed.

**Comment by astroshim** [comment]
re-build CI

**Comment by astroshim** [comment]
re-build CI

**Comment by AhyoungRyu** [comment]
CI is green now! LGTM 👍

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
