### PR TITLE
[ZEPPELIN-1622] Remove %dep interpreter deprecated message

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
%dep interpreter was going to be deprecated, but we had feedback from many users that this feature provide different advantage over dependency loading via GUI so we want to keep supporting it. This PR remove deprecated message when users use %dep interpreter.

### Todos
- [x] Fix test

### What type of PR is it?
Documentation

### What is the Jira issue?
[ZEPPELIN-1622](https://issues.apache.org/jira/browse/ZEPPELIN-1622)

### How should this be tested?
Run %dep interpreter such as `z.load('/your/library.jar)` and see if deprecated message is gone.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by bzz** [comment]
Looks great to me, thank you @minahlee for cleaning up in order to avoiding user confusion!
💯  for having a test

**Comment by minahlee** [comment]
@bzz @Leemoonsoo thank you for review! I will fix test to use `%dep`, I need to make time to fix it :/

**Comment by minahlee** [comment]
@bzz @Leemoonsoo Ready for review

**Comment by Leemoonsoo** [comment]
@minahlee Thanks for the update and unittest.
LGTM and merge to master if there're no further comments.

**Pull request closed without merging**
