### PR TITLE
[ZEPPELIN-1679] Invalid thrift implementation (developer critical)

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?

Recently, zeppelin added some amazing features. 
https://github.com/apache/zeppelin/pull/1613 
You can easily access spark ui from the zeppelin web.
However, in the implementation of the function, the Thrift interface seems to have arbitrarily modified the automatically generated code.
So if you recreate the Thift interface by calling genthrift.sh.
Zeppelin is not built.
I modified this to get the same result with auto-generated code.

### What type of PR is it?
Bug Fix

### Todos
- [x] add event META_INFOS in RemoteInterpreterService.thrift
- [x] import generate code 

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1679

### How should this be tested?
1. First you need to install thift 0.9.2.
2. Run zeppelin-interpreter / src / main / thrift / generate_thrift.sh.
3. Build full zeppelin.
4. After build, please check the interpreter spark setting in our web ui.
5. Try using the spark ui button.

If everything is running normally, it is a success.
Problems occur in the current master 3.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
The reason why travis failed is irrelevant to my pr.

```
09:44:43,974  INFO org.apache.zeppelin.ZeppelinITUtils:33 - Caller: org.apache.zeppelin.integration.ZeppelinIT.testAngularDisplay(ZeppelinIT.java:187)
09:44:44,074  INFO org.apache.zeppelin.ZeppelinITUtils:41 - Finished.
09:44:44,074  INFO org.apache.zeppelin.integration.ZeppelinIT:189 - testCreateNotebook Test executed
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 126.934 sec - in org.apache.zeppelin.integration.ZeppelinIT

Results :

Tests in error: 
  ParagraphActionsIT.testEditOnDoubleClick:443 » ElementNotVisible Element is no...

Tests run: 17, Failures: 0, Errors: 1, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ zeppelin-server ---
Discovery starting.
Nov 17, 2016 9:44:46 AM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 10555
Nov 17, 2016 9:44:46 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Nov 17, 2016 9:44:46 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Nov 17, 2016 9:44:46 AM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Nov 17, 2016 9:44:46 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Discovery completed in 3 seconds, 131 milliseconds.
Run starting. Expected test count is: 1
Zeppelin is already running
WelcomePageSuite:
- Welcome sign is correct
Zeppelin stop [  OK  ]
Run completed in 18 seconds, 840 milliseconds.
Total number of tests run: 1
Suites: completed 3, aborted 0
Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (stop-zeppelin) @ zeppelin-server ---
[INFO] Executing tasks

main:
     [exec] Zeppelin is not running
[INFO] Executed tasks
[INFO] 
```

**Comment by Leemoonsoo** [comment]
Thanks @cloverhearts for taking care.
LGTM and merge to master as a hotfix.

**Comment by karup1990** [comment]
@cloverhearts Thanks for taking care of this. Will be careful next time

**Comment by cloverhearts** [comment]
@karup1990 👍 Thank you for making great features.

**Pull request closed without merging**
