### PR TITLE
[gh-pages][ZEPPELIN-990] Add header anchor to gh-pages branch

### PR DESCRIPTION
**Pull request by AhyoungRyu**
### What is this PR for?
I applied header anchor to Zeppelin's docs website with #995 . It'll be good if `gh-pages` also has this header anchor. 

### What type of PR is it?
Improvement 

### What is the Jira issue?
[ZEPPELIN-990](https://issues.apache.org/jira/browse/ZEPPELIN-990)

### How should this be tested?
Run this branch locally as described in [here](http://zeppelin.apache.org/contribution/documentation.html) and hover the mouse over any titles.

### Screenshots (if appropriate)
anchor

### Questions:
* Does the licenses files need update? no 
* Is there breaking changes for older versions? no 
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested, When i anchor click the link, that goes under the menubar. I think that need to be adjusted.

**Comment by AhyoungRyu** [comment]
@Leemoonsoo Yeah didn't noticed that. I fixed it in my last commit. Could you check this out again? :D
scroll

**Comment by Leemoonsoo** [comment]
Tested and LGTM

**Comment by Leemoonsoo** [comment]
Merge if there're no further discussions.

**Pull request closed without merging**
