### PR TITLE
[ZEPPELIN-5869] Remove Incubating from Kyuubi reference

### PR DESCRIPTION
**Pull request by pan3793**
### What is this PR for?

This PR is proposes to remove incubating from Kyuubi reference, since the ASF board has approved a resolution to graduate Kyuubi into a full Top Level Project. 

https://github.com/apache/kyuubi/issues/4020

### What type of PR is it?

Documentation

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-5869

### How should this be tested?
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

It's docs only change.

### Questions:
* Does the license files need to update? No.
* Is there breaking changes for older versions? No.
* Does this needs documentation? No.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @zjffdu @huage1994

**Review by Reamer — APPROVED** [review]
PR looks good to me.
Do we want to wait until artifacts also lose the incubating suffix before making the change?

**Review by jongyoul — APPROVED** [review]

**Review by huage1994 — APPROVED** [review]

**Comment by jongyoul** [comment]
@huage1994 Could you please merge this PR if you have a permission now? 😃

**Comment by huage1994** [comment]
> @huage1994 Could you please merge this PR if you have a permission now? 😃 of course, after all reviews finish.

Yeah sure. I'll merge this PR after all reviews finish.

**Comment by huage1994** [comment]
> PR looks good to me. Do we want to wait until artifacts also lose the incubating suffix before making the change?

Hi @pan3793.  Does Kyuubi Community plan to release a new version without `-incubating` suffix for `org.apache.kyuubi:kyuubi-hive-jdbc-shaded`  in the very near future？

**Comment by huage1994** [comment]
> > PR looks good to me. Do we want to wait until artifacts also lose the incubating suffix before making the change?
> 
> Hi @pan3793. Does Kyuubi Community plan to release a new version without `-incubating` suffix for `org.apache.kyuubi:kyuubi-hive-jdbc-shaded` in the very near future？

If not, I tend to merge this PR first.   @Reamer WDYT ?

**Comment by jongyoul** [comment]
For the above issue, we need to wait for releasing non-incubating version so that we could build ours without errors.

**Comment by pan3793** [comment]
> Hi @pan3793. Does Kyuubi Community plan to release a new version without `-incubating` suffix for `org.apache.kyuubi:kyuubi-hive-jdbc-shaded` in the very near future？

maybe after one month

> ... we need to wait for releasing non-incubating version so that we could build ours without errors.

Will this cause build failure?

**Comment by jongyoul** [comment]
oh.. Sorry, I misunderstand. It's totally not to break our build.

**Comment by huage1994** [comment]
Will merge if no more comment

**Comment by smileyboy2019** [comment]
This PR is proposes to remove incubating from Kyuubi reference, since the ASF board has approved a resolution to graduate Kyuubi into a full Top Level Project.

**Pull request merged**
