### PR TITLE
[ZEPPELIN-3180] BUGFIX - save operation on interpreter add whitespace to permissions

### PR DESCRIPTION
**Pull request by Savalek**
### What is this PR for?
This PR fixes a bug when unnecessary spaces are added to the permissions.

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-3180](https://issues.apache.org/jira/browse/ZEPPELIN-3180)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by weand** [comment]
any progress here?

**Comment by zjffdu** [comment]
@weand Could you rerun the test ?

**Comment by weand** [comment]
LGTM @felixcheung what do you think?

**Comment by felixcheung** [comment]
doesn't seem like the test failure is related https://api.travis-ci.org/v3/job/339570673/log.txt

@Savalek could you rebase this PR?

**Comment by Savalek** [comment]
@felixcheung, I did a rebase.
An error in the tests of the Travis is the same as in master's branch.

**Comment by felixcheung** [comment]
merging if no more comment

**Comment by weand** [comment]
*no more comment*, we really would like to see this feature in master and branch-0.8 branches

**Pull request closed without merging**
