### PR TITLE
[ZEPPELIN-5896]feat:add sql debug feature

### PR DESCRIPTION
**Pull request by zhugezifang**
### What is this PR for?
This pull request add sql debug feat into zeppelin

### What type of PR is it?
Feature

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-5896

### How should this be tested?
* CI

### Questions:
* Does the license files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by zhugezifang** [comment]
@Reamer hi,i haved developed the feature of sql debug and add a pull request, could you help me to review it？

**Comment by zjffdu** [comment]
@zhugezifang Is this feature only apply to any specific database? Because I see you have a sql parser. And is it only for jdbc interpreter? Can it been applied to spark sql?

**Comment by zhugezifang** [comment]
> @zhugezifang Is this feature only apply to any specific database? Because I see you have a sql parser. And is it only for jdbc interpreter? Can it been applied to spark sql?

hi @zjffdu i think it can also aplied to spark sql, but could we use it in jdbc database fristly?

**Comment by Reamer** [comment]
I see code a lot, one file even has over 28000 lines of new code. Was this code generated or did you write it yourself?

I don't see myself being able to do a review here as there are too many changes.

**Comment by zhugezifang** [comment]
> I see code a lot, one file even has over 28000 lines of new code. Was this code generated or did you write it yourself?
> 
> I don't see myself being able to do a review here as there are too many changes.

the file in antrl4 path of sql parser  is generated by antrl4

**Comment by zhugezifang** [comment]
> I see code a lot, one file even has over 28000 lines of new code. Was this code generated or did you write it yourself?
> 
> I don't see myself being able to do a review here as there are too many changes.

yes , it change a lot , and could you give me some advices to do it?

**Comment by zjffdu** [comment]
@zhugezifang Is it possible to generate these code via maven plugin? If so, then it is not necessary to include it in this PR.

**Comment by zhugezifang** [comment]
> @zhugezifang Is it possible to generate these code via maven plugin? If so, then it is not necessary to include it in this PR.

hi, @zjffdu ,the code generated by antrl4 can be generatede via maven plugin，but the use of it must has the generated ,otherwise the code cannot run correctly

**Comment by Reamer** [comment]
We should definitely go for the Maven plugin.
Everything else makes maintainability more difficult.

The Maven plugin doesn't look that complicated.

Change required in the parent `pom.xml`.
```
<project>
  ...
   <properties>
       ...
       <antlr4.maven.version>4.3</antrl4.maven.version>
       ...
   </properties>
...
    <build>
   ....
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.antlr</groupId>
          <artifactId>antlr4-maven-plugin</artifactId>
          <version>${antlr4.maven.version}</version>
        </plugin>
      ....
```

Inside the zeppelin-interpreter `pom.xml`
```
<project>
  ...
  <build>
   ....
    <plugins>
      <plugin>
        <groupId>org.antlr</groupId>
        <artifactId>antlr4-maven-plugin</artifactId>
      </plugin>
      ...
    </plugins>
  </build>
  ...
</project>
```

Binds by default to the [lifecycle phase](http://maven.apache.org/ref/current/maven-core/lifecycles.html): generate-sources

All you need are grammar files inside `src/main/antlr4` and a "link" implementation of zeppelin-interpreter to the generated source code.

**Comment by zhugezifang** [comment]
> 



> We should definitely go for the Maven plugin. Everything else makes maintainability more difficult.
> 
> The Maven plugin doesn't look that complicated. https://www.antlr.org/api/maven-plugin/latest/antlr4-mojo.html Change required in the parent `pom.xml`.
> 
> ```
> <project>
>   ...
>    <properties>
>        ...
>        <antlr4.maven.version>4.3</antrl4.maven.version>
>        ...
>    </properties>
> ...
>     <build>
>    ....
>     <pluginManagement>
>       <plugins>
>         <plugin>
>           <groupId>org.antlr</groupId>
>           <artifactId>antlr4-maven-plugin</artifactId>
>           <version>${antlr4.maven.version}</version>
>         </plugin>
>       ....
> ```
> 
> Inside the zeppelin-interpreter `pom.xml`
> 
> ```
> <project>
>   ...
>   <build>
>    ....
>     <plugins>
>       <plugin>
>         <groupId>org.antlr</groupId>
>         <artifactId>antlr4-maven-plugin</artifactId>
>       </plugin>
>       ...
>     </plugins>
>   </build>
>   ...
> </project>
> ```
> 
> Binds by default to the [lifecycle phase](http://maven.apache.org/ref/current/maven-core/lifecycles.html): generate-sources
> 
> All you need are grammar files inside `src/main/antlr4` and a "link" implementation of zeppelin-interpreter to the generated source code.

ok ,thanks for your advice,i will try it

**Pull request closed without merging**
