### PR TITLE
[ZEPPELIN-1414] Remove CONTRIBUTING.md files

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
Following the PR #1356, we now have the contribution documentation to on Apache Zeppelin Website.

We can now remove the contributing files from the repository, and replace the links to that documentation.

### What type of PR is it?
Documentation

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1414

### How should this be tested?
Just check if there is other CONTRIBUTING.md files and if there is other links to replace

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@corneadoug There is one more "how to contribute" link - [http://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/#100-opensource](http://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/#100-opensource) :)

**Comment by corneadoug** [comment]
@AhyoungRyu Yes, this one could also be replaced.
There is actually a few pages of content inside the docs directory that we may want to move to the website later, so maybe we should create a JIRA issue for that migration too.

**Comment by jongyoul** [comment]
Good! I like it!

**Comment by felixcheung** [comment]
Not sure if it's important, the thing with having a file called Contributing.md is that github actually automatically notify the person creating a PR:
image

**Comment by AhyoungRyu** [comment]
@felixcheung Yeah right. It makes sense. Then how about putting root `CONTRIBUTING.md` back and providing this link [https://zeppelin.apache.org/contribution/contributions.html](https://zeppelin.apache.org/contribution/contributions.html) with proper message in that page? We can just let users know that our contribution guide is in Zeppelin website :)

**Comment by corneadoug** [comment]
@felixcheung Right, this message is showing if you have a CONTRIBUTING.md file in the root of the repository.
But we are also using the PR_TEMPLATE that github supports, and we have pretty much the same sentence inside of it: `First time? Check out the contributing guide - https://zeppelin.apache.org/contribution/contributions.html`

**Comment by felixcheung** [comment]
right, I'm not sure if that makes a difference to us

**Comment by corneadoug** [comment]
As long as it's still shown somewhere during the PR process, I think its fine?
Should we merge this then?

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Pull request closed without merging**
