### PR TITLE
[ZEPPELIN-3882] Neo4jInterpreter - Support Point and Date Types

### PR DESCRIPTION
**Pull request by conker84**
### What is this PR for?
Add the support for Point and Date data types introduced since Neo4j 3.4

### What type of PR is it?
[Improvement] In order to allow users to use the Neo4j Interpreter with the last introduced Data types

### Todos
* [x] - Bumped Neo4j dependecies version
* [x] - Added new data types to test

### What is the Jira issue?
* Put link here, and add [ZEPPELIN-3882](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-3882)

### How should this be tested?
* Execute the unit tests

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by conker84** [comment]
Hi @felixcheung the driver is compatible with all Neo4j version >= 3 (the last one is the 3.5). Actually in the documentation there is no mention about the minimum supported version. Do you want that I'll update it?

**Comment by felixcheung** [comment]
perhaps we should have a min version compatible in the interpreter doc?
otherwise I think it's fine not to have tested version, supported version etc in doc since then we'd need to keep updating them

**Comment by conker84** [comment]
Documentation updated!

**Comment by felixcheung** [comment]
can you check the failed tests?

**Comment by conker84** [comment]
Now there are two failing that I think are not related to this PR

**Comment by conker84** [comment]
I found a bug, I'll keep you posted.

**Pull request closed without merging**
