### PR TITLE
Bump up version to 0.7.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Bump up version to 0.7.0-SNAPSHOT

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@minahlee great!

Could you also take care of 

https://github.com/apache/zeppelin/blob/master/docs/_config.yml#L24
https://github.com/apache/zeppelin/blob/master/docs/_config.yml#L62

?

**Comment by minahlee** [comment]
@Leemoonsoo it's already there

**Comment by Leemoonsoo** [comment]
Oops i've confused you already took care! thanks!

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by minahlee** [comment]
no problem!

**Comment by darionyaphet** [comment]
Have any plan to release 0.6 ?

**Comment by bzz** [comment]
@minahlee looks great, let's merge it

@darionyaphet all release-related question are discussed on dev@ mailing list and tracked under [ZEPPELIN-889](https://issues.apache.org/jira/browse/ZEPPELIN-889)

**Comment by felixcheung** [comment]
I don't want to side track this... is it a bit pre-mature to move to 0.7.0 instead of, say, 0.6.1?

**Comment by Leemoonsoo** [comment]
In my understanding, Once `0.6.0` is released from `branch-0.6`, `branch-0.6` will be bumped up to `0.6.1-SNAPSHOT` and `0.6.1`, `0.6.2` ... will be released from `branch-0.6` if necessary.
Meanwhile, `master` branch becomes `0.7.0-SNAPSHOT`.

**Comment by minahlee** [comment]
@Leemoonsoo Thanks for the explanation!
@felixcheung as @Leemoonsoo said, branch-0.6 will be bumped up to 0.6.1-SNAPSHOT once I create v0.6.0-rc1 tag. We have documented this versioning policy in [wiki](https://cwiki.apache.org/confluence/display/ZEPPELIN/Preparing+Zeppelin+Release#PreparingZeppelinRelease-Createreleasebranch) few months ago. Bug fixes will keep being merged both in master and branch-0.6 and I hope we deliver those maintenance release in one or two month so many users can take advantage of it.

**Comment by felixcheung** [comment]
ok, thanks for clarification. It's a bit different from our release process (ie. 0.5.5, 0.5.6) before, but I like this better.

**Comment by minahlee** [comment]
Merging it to publish 0.7.0-SNAPSHOT document as 0.6.0 release vote passed

**Comment by jongyoul** [comment]
Go for it!!

**Comment by Leemoonsoo** [comment]
LGTM. Actually I think bump up to 0.6.0 could be done right after the branch-0.6 creation. 

by the way, #836 has merged. Could you rebase/merge master and take care of following files, too?

[zeppelin-examples/pom.xml](https://github.com/apache/zeppelin/blob/master/zeppelin-examples/pom.xml)
[zeppelin-examples/zeppelin-example-horizontalbar/pom.xml](https://github.com/apache/zeppelin/blob/master/zeppelin-examples/zeppelin-example-horizontalbar/pom.xml)
[zeppelin-examples/zeppelin-example-clock/pom.xml](https://github.com/apache/zeppelin/blob/master/zeppelin-examples/zeppelin-example-clock/pom.xml)
[zeppelin-examples/zeppelin-example-clock/zeppelin-example-clock.json](https://github.com/apache/zeppelin/blob/master/zeppelin-examples/zeppelin-example-clock/zeppelin-example-clock.json)
[zeppelin-examples/zeppelin-example-horizontalbar/zeppelin-example-horizontalbar.json](https://github.com/apache/zeppelin/blob/master/zeppelin-examples/zeppelin-example-horizontalbar/zeppelin-example-horizontalbar.json)

**Pull request closed without merging**
