### PR TITLE
[ZEPPELIN-2482] added font size for paragraph

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
1. Added possibilty to change font size of paragraph text
2. Fixed cloneParagraphAction (immediately after the cloning is incorrectly displayed a new paragraph)
3. Fixed paragraph settings into Firefox

### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2482

### How should this be tested?
1. Open note
2. Add some text to paragraph
3. Open settings of paragraph and chenge "Font size"

### Screenshots (if appropriate)
1. Font size and clone 

BEFORE
before_clone

AFTER
after_clone

2. Fix for Firefox
BEFORE
before_float_firefox
AFTER
after_float_firefox

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
CI red -> AuthenticationIT.testGroupPermission

**Comment by soralee** [comment]
Thanks @tinkoff-dwh and nice feature!
Let me test and come back here.

**Comment by soralee** [comment]
In `Font size and clone` and firefox browser case, I tested and it's work well. LGTM.

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by jongyoul** [comment]
LGTM. @1ambda Can you verify it?

**Comment by 1ambda** [comment]
@tinkoff-dwh @jongyoul sorry for the late reply. 

I will test and comment in few hours.

**Comment by 1ambda** [comment]
This feature will be helpful when displaying in the report mode but want to increase font-size. 

- need to be rebased. base branch is outdated.
- *+1* reindent DOMs and having a test

LGTM. Thanks for the contribution @tinkoff-dwh.

**Comment by jongyoul** [comment]
@1ambda Thanks. @tinkoff-dwh Please catch up the comment.

**Comment by tinkoff-dwh** [comment]
@1ambda 
save changes by change font size works fine
peek 2017-06-12 16-08

**Comment by 1ambda** [comment]
@tinkoff-dwh saving works. but it's not automatically propagated to other web-browsers.

**Comment by tinkoff-dwh** [comment]
@1ambda 
can you provide a link to the code where it is implemented to **colWidth**?

**Comment by 1ambda** [comment]
I attached a GIF.

pr2309

**Comment by 1ambda** [comment]
@tinkoff-dwh Do you still need a link? or just wanted to check the behavior?

**Comment by tinkoff-dwh** [comment]
@1ambda 
no, thx. it's clear

**Comment by tinkoff-dwh** [comment]
@1ambda 
done
peek 2017-06-12 22-09

ci red because fall other tests (not mine)

**Comment by 1ambda** [comment]
Looks good. I guess the failed job in https://travis-ci.org/tinkoff-dwh/zeppelin/builds/242104908 is due to a flaky test. But just to make sure, could you restart it so that CI will be green?

**Comment by tinkoff-dwh** [comment]
the same errors

```
ParagraphActionsIT.testSingleDynamicFormSelectForm:624 » NoSuchElement Cannot ...
ParagraphActionsIT.testMultipleDynamicFormsSameType:707 » NoSuchElement Cannot...
ParagraphActionsIT.testRunOnSelectionChange:282 » NoSuchElement Cannot locate ...
```

**Comment by tinkoff-dwh** [comment]
sorry it is my fault. i added new dropdown menu (font size) so order of elements (select) is changed

**Comment by 1ambda** [comment]
LGTM

**Comment by tinkoff-dwh** [comment]
thx for review.

@jongyoul 
can you init merge?

**Comment by jongyoul** [comment]
I'll merge it if there's no more discussion.

**Comment by tinkoff-dwh** [comment]
@jongyoul 
?

**Comment by jongyoul** [comment]
Missed. I'll merge it now.

**Pull request closed without merging**
