### PR TITLE
pip install with wrong parameter format

### PR DESCRIPTION
**Pull request by pzghost**
maybe misspelling(`intake-parquet=0.2.2 altair=3.2.0` should be `intake-parquet==0.2.2 altair==3.2.0`)

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks for the fix @pzghost Could you just update the PR title to be more clear what is this PR doing

**Comment by pzghost** [comment]
@zjffdu  Updated title. THX.

**Comment by Reamer** [comment]
@pzghost Please take a look into [Contribution Guide](https://zeppelin.apache.org/contribution/contributions.html)

**Comment by epugh** [comment]
I just ran into this same issue.   Would be great to get it merged.

**Comment by Leemoonsoo** [comment]
LGTM merge to master

**Pull request closed without merging**
