### PR TITLE
implementation test case for connect to exists interpreter process

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
We need test case for remote interpreter process ( connect to exists process)

### What type of PR is it?
[TEST case]

### What is the Jira issue?
none (jira problem now)

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by jongyoul** [comment]
Looks good

**Comment by jongyoul** [comment]
LGTM. will merge it

**Comment by cloverhearts** [comment]
@jongyoul 
This PR had a problem with travis.
So, I will modify this PR further.

**Comment by jongyoul** [comment]
I've missed it. I thought it was flaky tests. Got it.

**Pull request closed without merging**
