### PR TITLE
[Zeppelin-2572] multiple paragraphs actions

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
This **PR** adds the ability to perform actions on several paragraphs simultaneously. He adds the checkbox to each paragraph. When you select at least one paragraph in the action bar, buttons appear that perform actions on the selected paragraphs.

### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2572

### How should this be tested?
**1.** Select several paragraphs (In the actinBar appear buttons with actions for these paragraphs)
**2.** Perform several actions on paragraphs (by pressing the buttons)
**3.** Click "Reset selection" button

### Screenshot

gif

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by Tagar** [comment]
Just noticed this.. I think it's a great feature! 

In Jupyter we can also select multiple paragraphs.
Although it is made more seamless.. I believe you could Ctrl+click anywhere on a cell to select it.
So no separate UI element was necessary (like a checkbox that you have).
Selected cells are just slightly highlighted then. 
Two pros for this approach:
- easier to select multiple cells as you could click anywhere on a cell to add it to a selection;
- no additional UI elements 
- easier to find what cells were selected.

**Comment by tinkoff-dwh** [comment]
Will reopen soon.

**Pull request closed without merging**
