### PR TITLE
[MINOR] Add trivial cosmetic changes on STYLE.md

### PR DESCRIPTION
**Pull request by HyukjinKwon**
### What is this PR for?

This PR proposes a little bit of cosmetic changes on `STYLE.md`.

**Before**

```
                  "src-noconflict/mode-sql.js",
                  "src-noconflict/mode-markdown.js",
                  "src-noconflict/keybinding-emacs.js",
                 "src-noconflict/ext-language_tools.js",
+                 "src-noconflict/theme-github.js"],
       "version": "1.1.8",
       "name": "ace-builds"
    },
    "highlightjs": {
        "main": ["highlight.pack.js",
+                 "styles/github.css"],
      "version": "8.4.0",
      "name": "highlightjs"
     }
```

```
-      $scope.editor.setTheme('ace/theme/github');
+      $scope.editor.setTheme('ace/theme/monokai');
```

```
-                 "src-noconflict/theme-github.js"],
+                 "src-noconflict/theme-monokai.js"],
```

**After**

```diff
                  "src-noconflict/mode-sql.js",
                  "src-noconflict/mode-markdown.js",
                  "src-noconflict/keybinding-emacs.js",
                  "src-noconflict/ext-language_tools.js",
+                 "src-noconflict/theme-github.js"],
       "version": "1.1.8",
       "name": "ace-builds"
    },
    "highlightjs": {
        "main": ["highlight.pack.js",
+                 "styles/github.css"],
      "version": "8.4.0",
      "name": "highlightjs"
     }
```

```diff
-      $scope.editor.setTheme('ace/theme/github');
+      $scope.editor.setTheme('ace/theme/monokai');
```

```diff
-                 "src-noconflict/theme-github.js"],
+                 "src-noconflict/theme-monokai.js"],
```

### What type of PR is it?
[Documentation]

### What is the Jira issue?
MINOR

### How should this be tested?
Manually checked the rendering 

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @felixcheung, it seems the last change was by you. Could you please take a look? I think I am not used to this and also not sure if this change is good or not but just decided to submit this as it just looks a little bit prettier apparently.

**Comment by AhyoungRyu** [comment]
@HyukjinKwon Thanks for your contribution. Looks nice 👍

**Comment by HyukjinKwon** [comment]
Thank you, @AhyoungRyu.

**Comment by felixcheung** [comment]
nice!

**Comment by HyukjinKwon** [comment]
Thanks @fellixcheng, would I maybe have to retrigger the build for the green?

**Comment by felixcheung** [comment]
CI failure is not related, since this is a .md that is not part of the doc build

**Comment by felixcheung** [comment]
merged

**Pull request closed without merging**
