### PR TITLE
[ZEPPELIN-1673] Reduce CI log size and make it faster

### PR DESCRIPTION
**Pull request by 1ambda**
#### 1. APT is now cached (saving almost **15 secs** per build)

(before)
screen shot 2016-11-17 at 11 39 39 am

(after)
screen shot 2016-11-17 at 11 39 51 am

#### 2. R packages are now cached (almost **250 secs per** build)

(before)
screen shot 2016-11-17 at 12 04 20 pm

(after)
screen shot 2016-11-17 at 12 37 19 pm
screen shot 2016-11-17 at 12 37 34 pm

#### 3. Log size is reduced (at least 30%, removing useless maven info logs)

actually, we reduced even more because we cached apt and R :)

```bash
// (before result) https://api.travis-ci.org/jobs/176574582/log.txt?deansi=true
// (before build) https://travis-ci.org/apache/zeppelin/builds/176574580

// (after result) https://api.travis-ci.org/jobs/176576354/log.txt?deansi=true
// (after build) https://travis-ci.org/apache/zeppelin/builds/176576351

$ ls
build8414_profile2.log build8416_profile2.log

$ ls -alh
total 10232
drwxr-xr-x   4 lambda  staff   136B Nov 17 12:47 .
drwxr-xr-x  13 lambda  staff   442B Nov 17 02:49 ..
-rw-r--r--   1 lambda  staff   3.0M Nov 17 12:46 build8414_profile2.log
-rw-r--r--   1 lambda  staff   2.0M Nov 17 12:47 build8416_profile2.log

$ cat build8414_profile2.log | grep Download | wc -l
    7186
$ cat build8416_profile2.log | grep Download | wc -l
       6
```

#### Long Motivations

Sometimes build fails due to log size for example, 

```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in org.apache.zeppelin.ticket.TicketContainerTest
Running org.apache.zeppelin.security.SecurityUtilsTest


The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

we can prevent this kind of failure by removing useless maven log such as 

```
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.13/maven-checkstyle-plugin-2.13.pom (13 KB at 1233.1 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.13/maven-checkstyle-plugin-2.13.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.13/maven-checkstyle-plugin-2.13.jar (112 KB at 4858.2 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.pom (8 KB at 627.2 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.7/maven-resources-plugin-2.7.jar (31 KB at 2048.3 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom (12 KB at 860.4 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar (150 KB at 5342.7 KB/sec)
```

```sh
$  CI cat 176445046.log | grep Download | wc -l
    7044
$  CI cat 176445046.log | wc -l
   38046
$  CI cat 176445046.log| grep -v Download > filtered.log
$  CI ls -alh
total 7.7M
drwxr-xr-x  4 lambda staff  136 Nov 17 02:50 .
drwxr-xr-x 13 lambda staff  442 Nov 17 02:49 ..
-rw-r--r--  1 lambda staff 4.3M Nov 17 02:49 176445046.log
-rw-r--r--  1 lambda staff 3.4M Nov 17 02:50 filtered.log
```

### What type of PR is it?
[Improvement]

### What is the Jira issue?

[ZEPPELIN-1673](https://issues.apache.org/jira/browse/ZEPPELIN-1673)

### How should this be tested?

Checkout CI log and see if there are `Downloading` `Downloaded` log

(see also https://api.travis-ci.org/jobs/176445045/log.txt?deansi=true)

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by 1ambda** [comment]
Commit: 06c006e, CI Build: https://travis-ci.org/apache/zeppelin/builds/176457703

**Comment by 1ambda** [comment]
@bzz 

Could you review this PR? 

This comment is result summary for this PR (how much time we can save)

### 1. APT cache (almost 15 secs per

(before)
screen shot 2016-11-17 at 11 39 39 am

(after)
screen shot 2016-11-17 at 11 39 51 am

### 2. R cache (almost 250 secs per build)

(before)
screen shot 2016-11-17 at 12 04 20 pm

(after)
screen shot 2016-11-17 at 12 37 19 pm
screen shot 2016-11-17 at 12 37 34 pm

### 3. Log size is reduced (almost 30%, removing useless maven info logs)

```bash
// (before result) https://api.travis-ci.org/jobs/176574582/log.txt?deansi=true
// (before build) https://travis-ci.org/apache/zeppelin/builds/176574580

// (after result) https://api.travis-ci.org/jobs/176576354/log.txt?deansi=true
// (after build) https://travis-ci.org/apache/zeppelin/builds/176576351

$ ls
build8414_profile2.log build8416_profile2.log

$ ls -alh
total 10232
drwxr-xr-x   4 lambda  staff   136B Nov 17 12:47 .
drwxr-xr-x  13 lambda  staff   442B Nov 17 02:49 ..
-rw-r--r--   1 lambda  staff   3.0M Nov 17 12:46 build8414_profile2.log
-rw-r--r--   1 lambda  staff   2.0M Nov 17 12:47 build8416_profile2.log

$ cat build8414_profile2.log | grep Download | wc -l
    7186
$ cat build8416_profile2.log | grep Download | wc -l
       6
```

**Comment by 1ambda** [comment]
CI failure due to the selenium test in zeppelin-server not the this change. 

```
ests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 157.128 sec <<< FAILURE! - in org.apache.zeppelin.integration.ParagraphActionsIT
testEditOnDoubleClick(org.apache.zeppelin.integration.ParagraphActionsIT)  Time elapsed: 35.73 sec  <<< ERROR!
```

- (failed build profile) https://travis-ci.org/apache/zeppelin/jobs/176587997
- (raw log for it) https://api.travis-ci.org/jobs/176587997/log.txt?deansi=true

**Comment by 1ambda** [comment]
Now CI is green. Could anyone review this PR? Please :)

**Comment by 1ambda** [comment]
@Leemoonsoo @bzz 

I think this can help others to pass CI faster. Could you review this PR?

**Comment by Leemoonsoo** [comment]
Great work @1ambda !!

LGTM and merge to master if there's no more comment

**Pull request closed without merging**
