### PR TITLE
[ZEPPELIN-1781] Failed to run the script 'test_zeppelin_pr.py' on Windows 10

### PR DESCRIPTION
**Pull request by cuspymd**
### What is this PR for?
Fix failure of script execution on Windows 10

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-1781](https://issues.apache.org/jira/browse/ZEPPELIN-1781)

### How should this be tested?
Run 'test_zeppelin_pr.py' on Windows 10.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by felixcheung** [comment]
Looks like the Python2 CI test failed, could you take a look?
```
16/12/09 15:15:01 INFO PySparkInterpreter: File /tmp/zeppelin_pyspark-9170445727539307406.py created
16/12/09 15:15:01 INFO SparkInterpreter: Sending metainfos to Zeppelin server: {url=http://172.17.0.14:4040}
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 132.031 sec <<< FAILURE! - in org.apache.zeppelin.spark.PySparkInterpreterTest
testBasicIntp(org.apache.zeppelin.spark.PySparkInterpreterTest)  Time elapsed: 129.658 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<ERROR>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.apache.zeppelin.spark.PySparkInterpreterTest.testBasicIntp(PySparkInterpreterTest.java:128)

```

**Comment by cuspymd** [comment]
@felixcheung 
I opened the PR again, but there was errors elsewhere. Zeppelin test seems unstable.

**Comment by felixcheung** [comment]
So there were 2 runs

The older run https://travis-ci.org/apache/zeppelin/jobs/182613697 failed with Spark cluster tests
The newer run https://travis-ci.org/apache/zeppelin/builds/183250971 failed with cassandra tests

Given that and no code changes between, I think we could attribute the failures to flaky test.

**Comment by felixcheung** [comment]
@cuspymd have you tested this with Python 2.x and Python 3.x? I'm not sure we have automated test covered for Python + Spark on both.

**Comment by cuspymd** [comment]
@felixcheung The script 'test_zeppelin_pr.py' could be run on only Python 2 before this PR.
Anyway, I made additional modifications to run in python 3 as well.
And  the script 'test_zeppelin_pr.py' is for development, not for ptyhon interpreter.
I can't found a unit test about the scripts of 'dev' folder.
Can you let me know if it exists, or do you think you need to test the scripts of 'dev' folder in the future?

**Comment by felixcheung** [comment]
ah, sorry for missing this earlier. I didn't realize this is dev/test_* - these are test scripts that do not have automated tests

**Comment by felixcheung** [comment]
sorry I didnt see this. LGTM, CI passed, 
merging if no more comment

**Comment by felixcheung** [comment]
merged to master. thanks!

**Pull request closed without merging**
