### PR TITLE
[ZEPPELIN-1984] Capture stdin/stdout on interpreter process creation and propagate to front-end when error

### PR DESCRIPTION
**Pull request by Leemoonsoo**
### What is this PR for?
This PR captures stdin/stdout on interpreter process creation and propagate to front-end when error.

### What type of PR is it?
Improvement

### Todos
* [x] - Capture and propagate stdin/stdout
* [x] - unittest

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1984

### How should this be tested?
Outline the steps to test the PR here.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
LGTM

**Comment by Tagar** [comment]
Thanks a lot @Leemoonsoo . 
ps. PR title misspelled ZEPPELIN-1894 -> ZEPPELIN-1984

**Comment by Leemoonsoo** [comment]
Thanks @felixcheung @Tagar reviewing it.
Merge to master if no further comments

**Comment by Tagar** [comment]
Tested today's master merged with #1931 and #1921 and it works great. LGTM 
Thanks again.

**Pull request closed without merging**
