### PR TITLE
[MINOR]Removed some codes using interpreterClassList

### PR DESCRIPTION
**Pull request by jongyoul**
### What is this PR for?
Removing dependency from interpreterClassList because this prevent new interpreter without interpreterClassList from registering in Zeppelin.

### What type of PR is it?
[Bug Fix | Refactoring]

### Todos
* [x] - Removed codes

### What is the Jira issue?
N/A

### How should this be tested?
It doesn't have any change on user level.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Iterating interpreterClassList is mainly for keeping order of interpreters defined in `zeppelin.interpreters` property.

Therefore this PR will not only refactoring the code but also bring some user level behavior changes.

**Comment by jongyoul** [comment]
@Leemoonsoo Could you please describe in details? Do you mean the order of interpreter tab?

**Comment by jongyoul** [comment]
@Leemoonsoo I've figured out what you said. This PR changes the way to find a default interpreter, isn't it?

**Comment by Leemoonsoo** [comment]
@jongyoul Yes, i thought so.

**Comment by jongyoul** [comment]
@Leemoonsoo My last commit solves ordering interpreters.

**Pull request closed without merging**
