### PR TITLE
[ZEPPELIN-1710] Ace Editor upgrade

### PR DESCRIPTION
**Pull request by cloverhearts**
### What is this PR for?
The current version of the ace editor is too old.
You should also fix a bug that improperly typed non-English typing in Chrome.
The latest ace editor has been modified.

### What type of PR is it?
Improvement

### Todos
- [x]  import ui-ace
- [x] 1.25 version of conformity check and paragraph form correction.
- [x]  import ace editor new version. (v 1.26)

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1710

#### before
typing2
#### after

typing

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by cloverhearts** [comment]
There is an input problem other than English, such as Japanese and Korean.
To solve this problem, Zeppelin needs to upgrade the Ace editor.
We have responded to the latest ace editor first.
Actually the version for troubleshooting is currently awaiting release from the ace community.
This PR is completed when a new version is released from the ace community.

**Comment by tae-jun** [comment]
@cloverhearts Nice! Hope the new version will be released soon :)

**Comment by cloverhearts** [comment]
Thank you very much, @tae-jun

**Comment by cloverhearts** [comment]
typing

Fix and upgrade done.

please, review

**Comment by cloverhearts** [comment]
ace editor 1.2.6 upgrade done.
resolved korean typing issue.

**Comment by tae-jun** [comment]
Cool! LGTM 👍 Korean Zeppelin community will love this :)

**Comment by Leemoonsoo** [comment]
Tested and LGTM. Thanks @cloverhearts for the fix!
Could you resolve the conflict?

**Comment by cloverhearts** [comment]
fixed conflict with master branch.
but, i found bug. does not work auto save for paragraphs.
I'll fix this problem.

**Comment by cloverhearts** [comment]
After checking, the automatic save will actually work.
However, it can not be expressed only on the UI.

**Comment by cloverhearts** [comment]
fix-ui

i was resolved UI problem.
:)

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if there're no more discussions.
Great work @cloverhearts !

**Pull request closed without merging**
