### PR TITLE
ZEPPELIN-3734. Remove runtimeinfo from note.json

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
This is refactoring PR. Just remove runtimeInfo from note.json, because it doesn't make sense to store it into note.json especially when runtimeInfo contains any confidential info.  Besides that this PR also remove runtimeInfo in InterpreterSetting and also some code refactoring. 

### What type of PR is it?
[Improvement | Refactoring]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3734

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Tagar** [comment]
Can this be an option? Perhaps that's on by default to make it compatible with current Zeppelin release. 
Our users find it useful to compare paragraph runtimes and who ran it from last time.
Thanks.

**Comment by Tagar** [comment]
Yep, what I meant are fields like

      "dateCreated": "2018-07-12 13:53:34.479",
      "dateStarted": "2018-07-23 16:27:18.751",
      "dateFinished": "2018-07-23 16:27:55.416",

under "results"

And also

      "user": "rdautkhanov@corp.epsilon.com",
      "dateUpdated": "2018-07-23 16:27:18.714",

at the root of paragraph json data.

This information is used to render the string `Took {runtime} sec. Last updated by {user} at {dateUpdated}.` at the end of each paragraph, correct? I thought this PR removes persisting some of this information, so after zeppelin restart this information will get lost, isn't it?

Thanks

**Comment by zjffdu** [comment]
No, these fields won't be removed. Only the spark job url is removed.

**Comment by zjffdu** [comment]
Will merge if no more comments

**Pull request closed without merging**
