### PR TITLE
ZEPPELIN-621 - Bump Java version to Java 8

### PR DESCRIPTION
**Pull request by alexott**
### What is this PR for?

This PR switches the project to use Java 8 - we already have dependency on Spark 2.2.0 that is Java 8+ only.

### What type of PR is it?

Improvement

### What is the Jira issue?

https://issues.apache.org/jira/browse/ZEPPELIN-621

### CODE REVIEW

**Comment by zjffdu** [comment]
We also need to update .travis.yml to use only java 8

**Comment by jongyoul** [comment]
I have a simple question. Is `Vargrant` related to JDK8 directly?

**Comment by zjffdu** [comment]
@alexott Travis fails, could you help check that ?

**Comment by alexott** [comment]
@jongyoul JDK is configured there as well, so I was going to change it everywhere, so people who develop using Vagrant, won't get problems...

**Comment by alexott** [comment]
@zjffdu I forgot to enable CI, and test is now running, although some tests are failed - will investigate over weekend...

**Comment by zjffdu** [comment]
You need to first rebase your PR ( I disable some flaky test recently).

**Comment by zjffdu** [comment]
@alexott  The last build in travis fails, could you rerun it ?

**Comment by alexott** [comment]
Ok, it looks like it's working now, but really not sure what was wrong with configuration...

**Comment by zjffdu** [comment]
There's still some flaky test that may fails due to networks issue or other issues. 
LGTM

**Comment by jongyoul** [comment]
Wow~~ Now, we can use JDK8's wonderful features!!!! GREAT!!

**Pull request closed without merging**
