### PR TITLE
[ZEPPELIN-3075]Fix unqiue algo for the web side in pivot.js file.

### PR DESCRIPTION
**Pull request by liguohuicmss**
### What is this PR for?
unique() algorithm is not correct in pivot.js file.
If the input is `[2, 3, 3, 3, 4, 5]` and the output will be `[2, 3, 3, 4, 5]`. The number `3` is still duplicated.

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3075   [ZEPPELIN-3075]

### How should this be tested?
This is very easy and no need test.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by liguohuicmss** [comment]
Thanks. The test is as following.
First. When dragging item in chart settings. The item `still` cannot duplicated in the same groups:
untitled project

Second. I test this method in nodejs environment: 
201711240311281511507488261_small

**Comment by liguohuicmss** [comment]
Hello @felixcheung  , I have add the test above. Can you review this patch for me? Thank you.

**Comment by felixcheung** [comment]
thanks, that's useful.

could you look into if we could add a test in https://github.com/apache/zeppelin/blob/master/zeppelin-web/src/app/tabledata/tabledata.test.js
?

**Comment by liguohuicmss** [comment]
@felixcheung  Thank you very much. I have add the unit test as you pointing

**Comment by felixcheung** [comment]
```
Looks like travis-ci is not configured for your fork.
Please setup by swich on 'zeppelin' repository at https://travis-ci.org/profile and travis-ci.
```

**Comment by felixcheung** [comment]
could you check the failed tests?

**Comment by liguohuicmss** [comment]
@felixcheung Thank you. I have fix the code problem and the CI is all succeed. 

https://travis-ci.org/liguohuicmss/zeppelin

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no further review.

**Pull request closed without merging**
