### PR TITLE
[Zeppelin-2964] Stop execution on schedule if the note has been moved to the trash

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
When you put the note (or folder) in the trash, the note continues to run on schedule.
This PR fixes this. Now when you put the note into the trash, the task is removed, and when you restore the note, it runs again.

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZEPPELIN-3007](https://issues.apache.org/jira/browse/ZEPPELIN-3007)

### How should this be tested?
- Create a scheduled launch for the note.
- Put the note in the trash.
- Look through the logs. 
- Note must stop running.
- Restore the note from the trash.
- Running on a schedule should continue again.

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Tested manually. Thanks @tinkoff-dwh for the improvement.
LGTM and merge to master if no further discussions.

**Comment by tinkoff-dwh** [comment]
@Leemoonsoo 
merge?

**Comment by tinkoff-dwh** [comment]
@Leemoonsoo @felixcheung 

there are no the comments a long time, need to merge

**Comment by felixcheung** [comment]
merged

**Comment by felixcheung** [comment]
@tinkoff-dwh I think this has the wrong JIRA number...

**Pull request closed without merging**
