### PR TITLE
ZEPPELIN-3225: Add a bunch of missing annotations to ActiveDirectoryGroupRealm.java.

### PR DESCRIPTION
**Pull request by monsieurp**
### What is this PR for?
Add a bunch of missing annotations to ActiveDirectoryGroupRealm.java. Those annotations are missing and generate a lot of warnings in my IDE (NetBeans).

### What type of PR is it?
Improvement.

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3225

### How should this be tested?
There's not much to test.

### Questions:
* Does the licenses files need update? No.
* Is there breaking changes for older versions? No.
* Does this needs documentation? No.

### CODE REVIEW

**Comment by mebelousov** [comment]
Our team uses AD. I have tested.
Seems that it works good.

**Comment by monsieurp** [comment]
Hey @mebelousov! We also use Active Directory at work. We don't go through the AD connector though but instead rely on the LDAP connector.

By the way, there are many improvements that are to be made to this class. Would the Zeppelin contributors accept a PR to document the class for instance?

Thanks!

**Comment by zjffdu** [comment]
@monsieurp welcome any contribution including document

**Comment by monsieurp** [comment]
Hi @zjffdu! Cool. I will file another PR after this one. 

I made a mistake, amended my commit and forced pushed it, which is why the CI build failed. How can I get Jenkins to start a build again?

**Comment by zjffdu** [comment]
Just close and reopen this PR

**Comment by monsieurp** [comment]
Alright.

**Comment by monsieurp** [comment]
Ok something is up. I'm going to file a new PR.

**Pull request closed without merging**
