### PR TITLE
[ZEPPELIN-1964] Layout info is lost after refresh

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR is for `branch-0.7` of https://github.com/apache/zeppelin/pull/2053.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1964

### How should this be tested?
Please do resize paragraph and then refresh browser. 

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by astroshim** [comment]
@AhyoungRyu Could you help to review?

**Comment by AhyoungRyu** [comment]
Tested and it also works well like master branch. Thanks again! 
record

LGTM

**Comment by AhyoungRyu** [comment]
Merge into branch-0.7 if there are no more comments on this.

**Comment by Leemoonsoo** [comment]
@astroshim This PR has been [merged](https://github.com/apache/zeppelin/commit/f9630a58a86a4a456a8024c0bae73525634aa22c). Somehow it's not closed by @asfgit. Could you manually close this PR ?

**Comment by astroshim** [comment]
@Leemoonsoo I did. thanks.

**Pull request closed without merging**
