### PR TITLE
[ZEPPELIN-1766] Improve Interpreter Binding UI better (frontend)

### PR DESCRIPTION
**Pull request by 1ambda**
### What is this PR for?

Current Interpreter Binding UI

- *is too long so that users should scroll down to just close binding UI*
- *doesn't have filter*
- *hard to find the default interpreter*
- *has restart button which can be designed better*

As the result of this PR the, binding UI would be better due to

- **small size, not distracted UI**
- **well noticed the default binding (green color)**
- **simplicity by hiding restart button. even we can utilise the dropbox buttons to add more features for bindings** (e.g adding link to go to a specific interpreter)

### What type of PR is it?
[Improvement | Feature]

### Todos
* [x] - Improve binding UI
* [x] - Add binding filter
* [x] - Highlight default binding
* [x] - Remove useless text and stress important message in binding usage
* [x] - DON'T Highlight when filtering bindings

### What is the Jira issue?

[ZEPPELIN-1766](https://issues.apache.org/jira/browse/ZEPPELIN-1766)

### How should this be tested?

Open interpreter binding UI and manipulate it. 

- insert filter keyword
- click restart buttons

### Screenshots (if appropriate)

feature

### Questions:
* Does the licenses files need update? - NO
* Is there breaking changes for older versions? - NO
* Does this needs documentation? - NO

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @1ambda for working on UX improvement.

Personally, i'd prefer keep items in 1 column. Because it displays interpreter names (e.g. %spark, %pyspark, etc) at predictable location. i.e. beginning of each rows.

This change doesn't newline after each item and each item has variable length and it's hard to quickly read interpreter through eyes, even though there's filter. IMO.

Scrollbar will be there anyway when user have enough numbers of interpreter settings. Or when user have small screen size. 

For this reason, how about think other way to help user easily find 'save' button?

**Comment by 1ambda** [comment]
@Leemoonsoo Thanks for your opinion! 

That's true there will be scrollbar anyway if we have many bindings.  
So What about adding scroll bar to the binding list? so that users can find **save**, **close** button easily (I attached GIF)

scrollbar

**Comment by Leemoonsoo** [comment]
@1ambda that looks more make sense to me.
fyi, a related PR https://github.com/apache/zeppelin/pull/423

**Comment by 1ambda** [comment]
@Leemoonsoo 

I'v just fixed as commented above and updated GIF in the PR description

**Comment by cloverhearts** [comment]
I like a green button for default interpreter feedback.
especially, it seems to be a good choice for separating roles of interpreter.

**Comment by AhyoungRyu** [comment]
@1ambda Great initiative for improving interpreter binding page UI! I also agree that current binding page is getting longer (thanks to the Zeppelin contributors :D) and getting hard to find. Definitely needs to be improved. I tested this branch and checked the improvement. Let me share my thought about this patch in here.

 - Currently the restart button is exposed so that ppl can know "I can restart this interpreter by clicking this button" by instinct. But \w this patch, ppl need to click "Carrot" button to open the dropdown menu and need to click "Restart" button to restart interpreter. And the user need to click at least one time to know about this. 

 - Seems don't need another tooltip in here since there is already the text "Restart"
screen shot 2016-12-09 at 4 30 48 pm

 - The color change for default interpreter is good idea i think! But the color is gone when it comes out as a result. 
search_interpreter

 - Shirking overall size also good idea. Was quite verbose. But the thing that interpreter button has smaller height than dropdown menu is quite awkward to me. 
screen shot 2016-12-09 at 4 50 01 pm

 - How about "Search bindable interpreters(?)" instead of "Search interpreter Bindings"? :D 
screen shot 2016-12-09 at 4 48 59 pm

Most of them in the above are just my personal opinion. So surely you don't need to apply all of them. And thanks again for your effort to improve the UI!

**Comment by 1ambda** [comment]
Thanks for detailed review @AhyoungRyu 

### 1. Fixed Inputbox placeholder

screen shot 2016-12-13 at 2 10 58 pm

### 2. Fixed dropdown button size, Removed tooltip

screen shot 2016-12-13 at 2 10 51 pm

### 3. Apply the green color to binding even when filtered

filter

**Comment by 1ambda** [comment]
- Selenium tests passed by fixing https://github.com/apache/zeppelin/pull/1734/commits/c377cf8f255fa714d4b65061daf5239e86e8f641
- The profile 3 (scala 2.10, spark 1.6.3) failed but irrelevant with this PR

```
// https://api.travis-ci.org/jobs/183520147/log.txt?deansi=true

Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.646 sec <<< FAILURE! - in org.apache.zeppelin.dep.DependencyResolverTest
testLoad(org.apache.zeppelin.dep.DependencyResolverTest)  Time elapsed: 0.633 sec  <<< ERROR!
org.sonatype.aether.RepositoryException: Cannot fetch dependencies for com.databricks:spark-csv_2.10:1.3.0
	at org.apache.zeppelin.dep.DependencyResolver.getArtifactsWithDep(DependencyResolver.java:181)
	at org.apache.zeppelin.dep.DependencyResolver.loadFromMvn(DependencyResolver.java:131)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:79)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:96)
	at org.apache.zeppelin.dep.DependencyResolver.load(DependencyResolver.java:88)
	at org.apache.zeppelin.dep.DependencyResolverTest.testLoad(DependencyResolverTest.java:77)


Results :

Tests in error: 
  DependencyResolverTest.testLoad:77 » Repository Cannot fetch dependencies for ...
```

@AhyoungRyu @Leemoonsoo please let me know if there is anything to be fixed. Thanks!

**Comment by zjffdu** [comment]
I also notice this failed test in travis. I think there're several jiras tracking the flaky test.  The flaky test waste every developer's time. I think we should spend some time to fix them. What do you think ? \cc @Leemoonsoo  @AhyoungRyu @1ambda

**Comment by 1ambda** [comment]
Totally agree with @zjffdu's opinion. [Here are unresolved flaky tests](https://issues.apache.org/jira/issues/?jql=project%20%3D%20ZEPPELIN%20AND%20text%20~%20flaky%20ORDER%20BY%20status%20ASC)

**Comment by AhyoungRyu** [comment]
Thanks @1ambda. Seems it much better! Let me test again. 
So true. Currently the CI test result makes us more confused and really hard to find what the problem is :(

**Comment by bzz** [comment]
Guys, if I may, I would suggest keep the discussion in PR focused on the subject of the PR and move general topics of project's CI stability to the public dev@ mailing list and appropriate JIRA issues. Main reason beeing that people in community, who are interested in the subject of CI stability have hirer chanced on collaborating and fixing it together that way.

Here is JIRA for the CI failing on `spark-csv` - [ZEPPELIN-1797](https://issues.apache.org/jira/browse/ZEPPELIN-1797), \w some logs and failure examples.

**Comment by 1ambda** [comment]
Hi all, Let me know if anything needed to be changed from design to code style! 

Thanks :)

**Comment by 1ambda** [comment]
Hi all, This PR looks like unbacked from the point of view design. I will close this issue. :)

**Pull request closed without merging**
