### PR TITLE
Jenkins CI test

### PR DESCRIPTION
**Pull request by Leemoonsoo**
will not be merged.
for test purpose.

### CODE REVIEW

**Comment by jongyoul** [comment]
Why doesn't our travis work for now?

**Comment by Leemoonsoo** [comment]
I have no good idea. https://issues.apache.org/jira/browse/INFRA-14005.

**Comment by jongyoul** [comment]
I saw the status of Zeppelin's PR builder in builds.a.o and it doesn't seems to work properly.

**Comment by Leemoonsoo** [comment]
PR builder triggered and run normally. But somehow github page does not display build state.

**Pull request closed without merging**
