### PR TITLE
[ZEPPELIN-5791] Update hbase interpreter version from 1.0.0 to 2.4.12

### PR DESCRIPTION
**Pull request by gbnam**
### What is this PR for?
Update hbase interpreter version from 1.0.0 to 2.4.12

### What type of PR is it?
Refactoring

### Todos

- [x] update hbase interpreter version

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5791

### How should this be tested?
* CI should pass

### Questions:
* Does the licenses files need to update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by jongyoul** [comment]
Could you please check what happens when you building it?

```
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  0.375 s]
[INFO] Zeppelin: Livy interpreter ......................... SUCCESS [ 13.572 s]
[INFO] Zeppelin: HBase interpreter ........................ FAILURE [ 12.142 s]
[INFO] Zeppelin: JDBC interpreter ......................... SKIPPED
[INFO] Zeppelin: File System Interpreters ................. SKIPPED
```

**Comment by gbnam** [comment]
Error occured when maven download some libs blocked http request.
I solved it by editing the maven settings in local env. (https://gist.github.com/vegaasen/1d545aafeda867fcb48ae3f6cd8fd7c7)

Any ideas or related issues to solve this problem?

**Comment by gbnam** [comment]
I solved error by exclusion glassfish. Please let me know if there is anything else I should do.
Thanks!

**Comment by jongyoul** [comment]
Thank you for checking it. Let's see how it goes on :-). BTW, `hbase-server` might not be used by the code level so I guess we can remove the dependency itself.

**Comment by gbnam** [comment]
Removed `hbase-server` dependency from hbase interpreter.
Please check the commits. Thanks!

**Review by jongyoul — APPROVED** [review]

**Pull request merged**
