### PR TITLE
[ZEPPELIN-5266]: Enable extension of flexmark in markdown interpreter

### PR DESCRIPTION
**Pull request by EricGao888**
### What is this PR for?
* Enable extension of flexmark in markdown interpreter

### What type of PR is it?
Improvement

### Todos
* [ ] - Make emoji auto-scale according to the size of text 

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5266

### How should this be tested?
* Create a cell of markdown type, set the interpreter to be flexmark and type in an emoji code, e.g. :joy:

### Screenshots (if appropriate)
image
image

### Questions:
* None

### CODE REVIEW

**Comment by Reamer** [comment]
Where did you find the emoji images? I think it's better to download the emojis during the build and not put them all in our git repository.

**Comment by EricGao888** [comment]
> Where did you find the emoji images? I think it's better to download the emojis during the build and not put them all in our git repository.

Good suggestion, may I ask how I can download the emojis to the web assets folder during the build process? BTW, I found a link to https://www.webfx.com/tools/emoji-cheat-sheet/ in flexmark docs where I got those images. : )

**Comment by zjffdu** [comment]
@EricGao888 You can use `download-maven-plugin` to download these images and put them in the zeppelin-web module. 
See the example here https://github.com/apache/zeppelin/blob/master/spark/interpreter/pom.xml#L361

**Comment by EricGao888** [comment]
> Where did you find the emoji images? I think it's better to download the emojis during the build and not put them all in our git repository.

I found that unicode can be used instead of images for emojis. I think it's a better way.

**Comment by Reamer** [comment]
> > Where did you find the emoji images? I think it's better to download the emojis during the build and not put them all in our git repository.
> 
> I found that unicode can be used instead of images for emojis. I think it's a better way.

Unicode should be sufficient. It would be nice if you would update your image.

LGTM

**Comment by EricGao888** [comment]
> > > Where did you find the emoji images? I think it's better to download the emojis during the build and not put them all in our git repository.
> > 
> > 
> > I found that unicode can be used instead of images for emojis. I think it's a better way.
> 
> Unicode should be sufficient. It would be nice if you would update your image.
> 
> LGTM

Sure, will update the images just in case the unicode stuff breaks.

**Review by cuspymd — APPROVED** [review]
Looks good!!

**Comment by zjffdu** [comment]
LGTM

**Comment by zjffdu** [comment]
Will merge if no more comment

**Pull request closed without merging**
