### PR TITLE
trim property name of interpreter settings

### PR DESCRIPTION
**Pull request by rockiee281**
### What is this PR for?
trim property name of interpreter settings

### What type of PR is it?
Improvement 

### Todos
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3335

### How should this be tested?
* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update?
* Is there breaking changes for older versions?
* Does this needs documentation?

### CODE REVIEW

**Comment by r-kamath** [comment]
@rockiee281 Thanks for the update PR
Please close #2870

**Comment by rockiee281** [comment]
Hi, @r-kamath  the duplicated PR closed now。 Please review this PR. thanks

**Comment by zjffdu** [comment]
LGTM, will merge if no more comments

**Comment by jongyoul** [comment]
I've found a bug in this PR. if the value is not a string, it occurs error. e.g.

```
"zeppelin.python": {
          "name": "zeppelin.python",
          "value": "python",
          "type": "string"
        },
```

our properties look like this.

**Pull request closed without merging**
