### PR TITLE
ZEPPELIN-3142. Fixed Checkstyle errors and warnings in the livy module

### PR DESCRIPTION
**Pull request by HorizonNet**
### What is this PR for?
Fixed the Checkstyle errors and warnings in the **livy** module.

### What type of PR is it?
Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-3142

### How should this be tested?
* CI pass

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by HorizonNet** [comment]
Did a rerun of the failing builds. They are now green.

**Comment by masyan** [comment]
you can reopen PR (for update jenkins status)

**Comment by HorizonNet** [comment]
@masyan Thanks for the tip.

**Comment by zjffdu** [comment]
@HorizonNet I don't see the green build, could you point me the link ?

**Comment by HorizonNet** [comment]
@zjffdu Here's the [link](https://travis-ci.org/ultratendency/zeppelin/builds/339087714). I had to rebase this PR due to recent changes.

**Comment by HorizonNet** [comment]
Reverted `zeppelin-web/package-lock.json` to the one from the `master` branch.

**Comment by zjffdu** [comment]
LGTM

**Pull request closed without merging**
