### PR TITLE
[ZEPPELIN-2320] fixing test + modifying map browsing

### PR DESCRIPTION
**Pull request by Remilito**
### What is this PR for?
fixing String comparison and improving map browsing

### What type of PR is it?
Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
[ZEPPELIN-2320](https://issues.apache.org/jira/browse/ZEPPELIN-2320)

### How should this be tested?
build with tests.

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by jongyoul** [comment]
@astroshim Can you merge it into master and branch-0.7?

**Comment by astroshim** [comment]
LGTM..
Sorry for late catch..
Merge if there is no more discussion.

**Comment by astroshim** [comment]
@Remilito Ping~

**Comment by Remilito** [comment]
@astroshim Why?

**Comment by astroshim** [comment]
@Remilito Could you make this PR based on branch-0.7 branch?

**Comment by Remilito** [comment]
@astroshim: why? does that mean I also need to do https://github.com/apache/zeppelin/pull/2099 based on branch-0.7 ?

**Comment by AhyoungRyu** [comment]
@Remilito yeah you're right. Normally if the PR is for bug fixing or minor update, committers merge it both into master and branch-0.x. But since #2099 was merged into master only, you don't need to.

**Comment by Remilito** [comment]
thanks for the clarification @AhyoungRyu

**Pull request closed without merging**
