### PR TITLE
[ZEPPELIN-5446] SparkInterpreterLauncher#detectSparkScalaVersion may return wrong scala version

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?

This issue happens when user set `SPARK_HOME` in zeppelin spark interpreter setting, but zeppelin server host has `SPARK_CONF_DIR` which point to another version of spark.  In this case, even when user set `SPARK_CONF_DIR` explicitly, `SparkInterpreterLauncher#detectSparkScalaVersion` would still return the scala version of the spark version of `SPARK_CONF_DIR` point to.

This PR would pass the envs built from interpreter setting to the process of `detectSparkScalaVersion`

### What type of PR is it?
[Bug Fix ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-5446

### How should this be tested?
* Manually tested

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
Will merge if no more comment

**Comment by Reamer** [comment]
In my eyes, an env (environment) contains multiple values. Why do you change the variable name to envs?

**Comment by zjffdu** [comment]
> In my eyes, an env (environment) contains multiple values. Why do you change the variable name to envs?

You are right, let me revert that.

**Review by Reamer — APPROVED** [review]
LGTM

**Pull request closed without merging**
