### PR TITLE
[ZEPPELIN-1102] ElasticSearch interpreter auto completion doesn't work.

### PR DESCRIPTION
**Pull request by astroshim**
### What is this PR for?
This PR fixes bug of elasticsearch auto completion.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1102

### How should this be tested?
Test auto completion code like as http://zeppelin.apache.org/docs/0.6.0-SNAPSHOT/interpreter/elasticsearch.html.

### Screenshots (if appropriate)
 - before
image

 - after
image

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by astroshim** [comment]
re-trigger CI

**Comment by bzz** [comment]
👍  for adding a test!

Looks great to me, merging if there is no more dicsussion

**Comment by astroshim** [comment]
re-trigger CI

**Comment by bzz** [comment]
ping @astroshim 
To help making CI more stable, could you please re-base on the latest master?

**Comment by astroshim** [comment]
pong @bzz 
I just re-based. Thanks.

**Comment by bzz** [comment]
CI is green now, looks great to me. 
Can you please next time make sure JIRA issue is assigned to you as well? Let me know if there are any troubles with JIRA on doing so (i.e it's not editable or you can not assign to yourself, etc)

Merging if there is no discussion

**Pull request closed without merging**
