### PR TITLE
[ZEPPELIN-2442] button to create note into folder (navbar)

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Added button to create new note into folder (navbar)

### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2442

### Screenshots (if appropriate)
peek 2017-04-21 15-48

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
cool - perhaps `+` icon is a bit confusing? though we have `+` for new note anyway

**Comment by tinkoff-dwh** [comment]
@felixcheung  thanks for review
Yes, but unfortunately the tooltip does not work correctly in this menu. I'll think how to fix it.

**Comment by tinkoff-dwh** [comment]
@felixcheung 
added tooltip
peek 2017-04-25 16-33

**Comment by felixcheung** [comment]
cool, love the hover and tooltip

**Comment by soralee** [comment]
I tested long folder name and LGTM!
check_long_name

**Comment by Leemoonsoo** [comment]
LGTM and merge to master if no further discussions

**Pull request closed without merging**
