### PR TITLE
ZEPPELIN-1311. Typo in ZEPPELIN-1197

### PR DESCRIPTION
**Pull request by zjffdu**
### What is this PR for?
My bad, it should be `Exception` rather than `Execution`

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-1311

### How should this be tested?
Tested manually. 

### Screenshots (if appropriate)
Here's the new log after this fix.
image

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by zjffdu** [comment]
\cc @Leemoonsoo @minahlee Is it possible to merge it into 0.6.1 ?

**Comment by minahlee** [comment]
@zjffdu let me merge it as hotfix

**Comment by zjffdu** [comment]
Thanks @minahlee, the CI fail should be irrelevant, it is due to network issue.
```
[INFO] └── semver-utils@1.1.1
[ERROR] npm ERR! Linux 3.13.0-40-generic
[ERROR] npm ERR! argv "/home/travis/build/apache/zeppelin/zeppelin-web/node/node" "/home/travis/build/apache/zeppelin/zeppelin-web/node/node_modules/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.13
[ERROR] npm ERR! npm  v2.15.0
[ERROR] 
[ERROR] npm ERR! Callback called more than once.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/travis/build/apache/zeppelin/zeppelin-web/npm-debug.log
```

**Comment by zjffdu** [comment]
@minahlee  Please hold the commit, I will have another improvement soon.

**Comment by zjffdu** [comment]
Done, now it would print the full stack stace
image

**Comment by minahlee** [comment]
Change looks good to me. Merging to master and branch-0.6

**Comment by bzz** [comment]
Looks great to me

**Comment by zjffdu** [comment]
oh, sorry, I didn't realize `ZEPPELIN-1197` is not in 0.6. Then let's merge this to master only.

**Pull request closed without merging**
