### PR TITLE
[HOTFIX] fix checkstyle errors

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
### What is this PR for?
There are some checkstyle errors in branch-0.8, this is to fix all those errors.

### What type of PR is it?
[Hot Fix]

### How should this be tested?
* CI should be green.

### Questions:
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
@r-kamath @zjffdu  Please help review this.

**Comment by Leemoonsoo** [comment]
LGTM

**Comment by zjffdu** [comment]
Thanks @prabhjyotsingh , I have already started one hotfix PR for building issue of branch-0.8, there's more issues except code style, do you mind to close this PR and I will fix it in one PR.

https://github.com/zjffdu/zeppelin/commit/0ef79d1807599d2fbc74e8eeb3e18d0997aa7b85

**Comment by prabhjyotsingh** [comment]
@zjffdu sure, no problem.

**Pull request closed without merging**
