### PR TITLE
[ZEPPELIN-4926] Fix null pointer exception when the repository's url protocol is http

### PR DESCRIPTION
**Pull request by morningmemo**
### What is this PR for?
This PR is to fix null pointer exception when the interpreter repository's url protocol is http.

### What type of PR is it?
[ Bug Fix ]

### Todos
* [ ] - Task

### What is the Jira issue?
* https://issues.apache.org/jira/browse/ZEPPELIN-4926

### How should this be tested?
* Travis-CI : https://travis-ci.org/github/morningmemo/zeppelin
* Unit test is added.

### Questions:
* Does the licenses files need update? NO
* Is there breaking changes for older versions? NO
* Does this needs documentation? NO

### CODE REVIEW

**Comment by alexott** [comment]
Can you please add the travis-ci build info?

**Comment by morningmemo** [comment]
> Can you please add the travis-ci build info?

* Travis-CI : https://travis-ci.org/github/morningmemo/zeppelin

**Comment by zjffdu** [comment]
LGTM

**Comment by alexott** [comment]
closing it as merged...

**Pull request closed without merging**
