### PR TITLE
[ZEPPELIN-2228] precode for SparkRInterpreter

### PR DESCRIPTION
**Pull request by tinkoff-dwh**
### What is this PR for?
Added parameter zeppelin.pyspark.precode to SparkRInterpreter. This is snippet of code which executes when interpreter initialize.

### What type of PR is it?
Feature

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-2228

### How should this be tested?
1. Set parameter zeppelin.R.precode precodeVar=1+2
2. Run
```
%r
print(precodeVar)
```

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
Ready to review

**Comment by dgskv** [comment]
LGTM

**Comment by echarles** [comment]
Would be good to generalize this precode execution to all interprerters, having methods like `prerun`, `postrun`...  at `Interpeter` interface level.

**Comment by tinkoff-dwh** [comment]
@echarles 
https://issues.apache.org/jira/browse/ZEPPELIN-2216

**Comment by tinkoff-dwh** [comment]
CI green, https://travis-ci.org/tinkoff-dwh/zeppelin/builds/208970773 , commit is correct 8323392,
but status failed (tried reopen) failed.

**Comment by tinkoff-dwh** [comment]
#2221 general solution

**Pull request closed without merging**
