### PR TITLE
[ZEPPELIN-3285] Refine the style of Notebook title

### PR DESCRIPTION
**Pull request by milooy**
### What is this PR for?
Refine the style of Notebook title
(Ellipsis by character, 100% width under medium width browser, align delete button)

(Before)
before

(After)
after

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3285

### How should this be tested?
**1. Run webapp** 
```vi
cd zeppelin-web
yarn run dev
```
**2. Check the title have ellipsis by character, not looks cut.**
image
(before / after)

**3. Check 'delete button' is aligned**
image
image
(before / after)

**4. Check the title with is 100% under the window width 650px**
image
(before / after)

* First time? Setup Travis CI as described on https://zeppelin.apache.org/contribution/contributions.html#continuous-integration
* Strongly recommended: add automated unit tests for any new or changed behavior
* Outline any manual steps to test the PR here.

### Questions:
* Does the licenses files need update? N
* Is there breaking changes for older versions? N
* Does this needs documentation? N

### CODE REVIEW

**Comment by r-kamath** [comment]
@milooy Thanks for the contribution. Please resolve the conflicts.

**Comment by Savalek** [comment]
@milooy, thanks. Could you take into account the mistakes corrected by this PR  [2983](https://github.com/apache/zeppelin/pull/2983)

**Comment by milooy** [comment]
@r-kamath 
Resolved with rebase :) thank you.

@Savalek 
image
Checked the visibility of title in report and juno theme with unhovered / hovered state.
Thank you for the referencing the PR. It was helpful 👍

**Comment by milooy** [comment]
@r-kamath @Leemoonsoo 
What do I need to do more to merge the PR?

**Comment by r-kamath** [comment]
will merge this if there are no more discussions

**Pull request closed without merging**
