### PR TITLE
ZEPPELIN-1170 Handsontable fails to display data on second run

### PR DESCRIPTION
**Pull request by r-kamath**
### What is this PR for?
Handsontable fails to display data on second run if first run did not render table due to an error in the query.
Fix for a render issue caused by #1059

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1170

### How should this be tested?
Please ref the screenshots

### Screenshots (if appropriate)
**Before**
old

**After**
new

### Questions:
* Does the licenses files need update? n/a
* Is there breaking changes for older versions? n/a
* Does this needs documentation? n/a

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
@r-kamath Thanks for the fix. How this fix is different from #1171 ?

**Comment by prabhjyotsingh** [comment]
LGTM!

This has been happening in my machine as well for quite some time. Thanks @r-kamath for the fix.

@corneadoug, @Leemoonsoo Please review will merge this a hot fix.

**Comment by r-kamath** [comment]
@Leemoonsoo if  #1171 is ready to merge. Please feel free to discard this PR and mark the jira issue as duplicate. Thanks :)

**Comment by Leemoonsoo** [comment]
I think we can merge #1171 and then merge #1182, while this PR includes different improvements. (`$scope.hot = null` and `updateSettings`)

I didn't marked #1171 as a hotfix, but let me merge #1171 quickly, and then let's merge #1182.

**Comment by prabhjyotsingh** [comment]
@Leemoonsoo Yes, I agree, we should merge #1171.

**Comment by bzz** [comment]
So what is the consensus, shall we actually *rebase* this one on master and merge, or just close, as soon as #1171 is merged?

**Comment by corneadoug** [comment]
#1171 is merged already, and this one has been rebased

**Comment by bzz** [comment]
@corneadoug from what you say, it's still not clear what's the plan with this one.

I do not think it was rebased, where `rebased = git rebase` - that way all the commits would show up AFTER the conversation as history get's re-written. 

Also we would not have commit messages like "Merge remote-tracking branch 'upstream/master' into ZEPPELIN-1170" in case of rebase.

**Comment by corneadoug** [comment]
Tested, LGTM

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Pull request closed without merging**
