### PR TITLE
[HOTFIX][DOC] Fix image path again

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Realized that #1020 doesn't do the job. This PR does fix the issue of broken image on website and already deployed on the website

### What type of PR is it?
Bug Fix

### CODE REVIEW

**Comment by corneadoug** [comment]
Yes, we fixed the `/assets` type of links a few times before.

The best way to check the image link it to use the 'sources' tab in the developer tools to see the file tree.
screen shot 2016-06-16 at 1 23 31 pm

LGTM

**Comment by minahlee** [comment]
Thank you for the tip! wont make same mistake again...

**Comment by corneadoug** [comment]
@minahlee Should it be merged also in 0.6.0 branch?

**Comment by minahlee** [comment]
@corneadoug yes, the doc for 0.6.0 will be published based on branch-0.6

**Comment by minahlee** [comment]
@corneadoug FYI you don't need to push it to svn since I already did.

**Comment by corneadoug** [comment]
@minahlee I think you can merge it :)

**Comment by minahlee** [comment]
Ok let me merge it then :)

**Pull request closed without merging**
