### PR TITLE
[ZEPPELIN-3864] Fix Travis tests

### PR DESCRIPTION
**Pull request by Savalek**
### What is this PR for?
Maven `frontend plugin v1.4` incorrectly processed `npm` messages with error.
This PR update `frontend plugin` to 1.6 from 1.4.

### What type of PR is it?
Bug Fix

### What is the Jira issue?
[ZEPPELIN-3864](https://issues.apache.org/jira/browse/ZEPPELIN-3864),
[ZP-70]

### Questions:
* Does the licenses files need update? no
* Is there breaking changes for older versions? no
* Does this needs documentation? no

### CODE REVIEW

**Comment by felixcheung** [comment]
this test failed? https://travis-ci.org/TinkoffCreditSystems/zeppelin/jobs/458386760

**Comment by Savalek** [comment]
@felixcheung, yes.

**Comment by Savalek** [comment]
Any progress here?

**Comment by Savalek** [comment]
@felixcheung, these tests should fall, because `maven` incorrectly handled errors when testing through `npm`. This PR is only the first part of fixing problems. The second part is the correction of those tests that have been falling for a long time, but because of the bug of the `frontend maven plugin 1.4`, `travis` shows that the `npm` tests have passed, but in fact this is not the case.

**Comment by felixcheung** [comment]
Can you please fix the tests then. We can’t merge anything that will cause all PRs to fail in Travis.

Even when they “should” be

**Comment by Savalek** [comment]
@felixcheung, I'm trying to fix the tests but I can't even run `npm run test` in `zeppelin-web` because the file `webpack.config.js` made for version `webpack 1` but the current version `4`. 
They are not compatible between. 
In addition, I counted at least 33 broken tests.
And i'm not strong in the frontend.

**Comment by Savalek** [comment]
@felixcheung, i managed to fix the tests.

**Comment by Savalek** [comment]
What about merge?

**Pull request merged**
