### PR TITLE
[ZEPPELIN-1047] Add filter to handle upper case

### PR DESCRIPTION
**Pull request by suvam97**
### What is this PR for?
The notebook filter in navbar does not filter the results of note if note name is given in upper case .

### What type of PR is it?
[Bug Fix]

### What is the Jira issue?
[ZEPPELIN-1047](https://issues.apache.org/jira/browse/ZEPPELIN-1047)

### How should this be tested?
1.Open the notebook filter under navbar -> Notebook menu.
2.Search for any note by giving name in upper case.
3.You should be able to search all the note book names irrespective of case. 

### Screenshots (if appropriate)

**BEFORE:**
http://g.recordit.co/jqo7DYXStI.gif

**AFTER:**
http://g.recordit.co/uuCT79uEti.gif

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by corneadoug** [comment]
@suvam97 Maybe you should try building from master and cleaning your cache.
Current filtering is working perfectly for me
notebookisrunnable

**Comment by corneadoug** [comment]
@suvam97 Sorry, I was actually testing your branch :)
Works, great, could you then delete the `notebookFilter` since it is not being used?

**Comment by suvam97** [comment]
@corneadoug : sorry for late response ! Changes updated.

**Comment by corneadoug** [comment]
LGTM

**Comment by minahlee** [comment]
@suvam97 Could you rebase master and resolve conflicts?

**Comment by suvam97** [comment]
@minahlee Conflict resolved.

**Comment by suvam97** [comment]
@minahlee Conflict Resolved

**Comment by minahlee** [comment]
Merge if there is no more dicussion

**Pull request closed without merging**
