### PR TITLE
[ZEPPELIN-1088] Add Htmlhint

### PR DESCRIPTION
**Pull request by corneadoug**
### What is this PR for?
Adding Htmlhint to check our HTML files.
This is mainly helping with making sure HTML tags are closed correctly

### What type of PR is it?
Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1088

### How should this be tested?
Remove a closing tag and see an error being shown in the terminal

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by prabhjyotsingh** [comment]
LGTM!

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by Leemoonsoo** [comment]
If i checkout `ee51a84e856aed3ca60dd13099db0bce66e9b93e` (commit that merges this PR) and build zeppelin-web, then i get following errors

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Zeppelin: web Application 0.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle-fail-build) @ zeppelin-web ---
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ zeppelin-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce) @ zeppelin-web ---
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node and npm) @ zeppelin-web ---
[INFO] Node v0.12.13 is already installed.
[INFO] Found NPM version 2.15.0
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:npm (npm install) @ zeppelin-web ---
[INFO] Running 'npm install --color=false' in /Users/moon/Projects/zeppelin/zeppelin-web
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:bower (bower install) @ zeppelin-web ---
[INFO] Running 'bower --allow-root install' in /Users/moon/Projects/zeppelin/zeppelin-web
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.25:grunt (grunt build) @ zeppelin-web ---
[INFO] Running 'grunt build --no-color' in /Users/moon/Projects/zeppelin/zeppelin-web
[INFO] Running "jshint:all" (jshint) task
[INFO] 
[INFO] ✔ No problems
[INFO] 
[INFO] 
[INFO] Running "htmlhint:src" (htmlhint) task
[INFO]    src/main/webapp/404.html
[INFO]       L13 |...<!DOCTYPE html> <html lang="en"> <head> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta c...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...iv="X-UA-Compatible" content="IE=edge"> <meta charset="utf-8"> <title>Page Not Found :(</title> <styl...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L145 |...roxy/lh/wm/fixurl.js"></script> </div>  
[INFO]                                                        ^ Tag must be paired, missing: [ </body></head></html> ], open tag match failed [ <body> ] on line 145. (tag-pair)
[INFO] 
[INFO]    src/main/webapp/index.html
[INFO]       L13 |...roller="MainCtrl" class="no-js"> <head> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta c...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...iv="X-UA-Compatible" content="IE=edge"> <meta charset="utf-8"> <title></title> <!-- disable caches fo...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...<!-- disable caches for all browser --> <meta http-equiv="cache-control" content="max-age=0"> <meta h...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...iv="cache-control" content="max-age=0"> <meta http-equiv="cache-control" content="no-cache"> <meta ht...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...uiv="cache-control" content="no-cache"> <meta http-equiv="cache-control" content="no-store"> <meta ht...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...uiv="cache-control" content="no-store"> <meta http-equiv="expires" content="0"> <meta http-equiv="exp...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...<meta http-equiv="expires" content="0"> <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 ...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...content="Tue, 01 Jan 1980 1:00:00 GMT"> <meta http-equiv="pragma" content="no-cache"> <meta name="des...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...http-equiv="pragma" content="no-cache"> <meta name="description" content=""> <meta name="viewport" co...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |..."> <meta name="description" content=""> <meta name="viewport" content="width=device-width"> <!-- Plac...
[INFO]                                                       ^ The empty tag : [ meta ] must be self closed. (tag-self-close)
[INFO]       L13 |...ouch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.css"> <link rel="s...
[INFO]                                                       ^ The empty tag : [ link ] must be self closed. (tag-self-close)
[INFO]       L13 |...="stylesheet" href="styles/vendor.css"> <link rel="stylesheet" href="styles/main.css"> <link rel="sty...
[INFO]                                                       ^ The empty tag : [ link ] must be self closed. (tag-self-close)
[INFO]       L13 |...el="stylesheet" href="styles/main.css"> <link rel="stylesheet" ng-href="styles/looknfeel/{{looknfeel}...
[INFO]                                                       ^ The empty tag : [ link ] must be self closed. (tag-self-close)
[INFO]       L15 |...tton> <a class="navbar-brand" href="#/"><img style="margin-top: -7px;s" src="images/zepLogoW.png" wid...
[INFO]                                                       ^ The empty tag : [ img ] must be self closed. (tag-self-close)
[INFO]       L17 |...ipt src="scripts/scripts.js"></script>  
[INFO]                                                       ^ Tag must be paired, missing: [ </body></head></html> ], open tag match failed [ <body ng-class="{'bodyAsIframe': asIframe}"> ] on line 13. (tag-pair)
[INFO] 
[INFO]    src/main/webapp/views/interpreter.html
[INFO]       L13 |...ettingAdd" ng-show="showAddNewSetting"> <hr> <h4>Create new interpreter</h4> <div class="form-group" ...
[INFO]                                                       ^ The empty tag : [ hr ] must be self closed. (tag-self-close)
[INFO]       L13 |...group" style="width:200px"> <b>Name</b> <input id="newInterpreterSettingName" input pu-elastic-input ...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L13 |...rs" value="{{groupName}}">{{groupName}} </select> </div> <b>Properties</b> <table class="table table-...
[INFO]                                                       ^ Tag must be paired, missing: [ </option> ], start tag match failed [ <option ng-repeat="(groupName, interpreterGroup) in availableInterpreters" value="{{groupName}}"> ] on line 13. (tag-pair)
[INFO]       L13 |...reterProperty(key)"> </div>   <tr> <td> <input pu-elastic-input pu-elastic-input-minwidth="180px" ng-...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L13 |..."addNewInterpreterProperty()"> </div>   </table> <span class="btn btn-primary" ng-click="addNewInterp...
[INFO]                                                       ^ Tag must be paired, missing: [ </td></td></td></td></tr></td></td></td></td></tr></th></th></th></th></tr> ], start tag match failed [ <td> ] on line 13. (tag-pair)
[INFO]       L14 |...> remove</button> </span> </div> </div> <br> <div class="row interpreter"> <div class="col-md-12"> <b...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L14 |...   <tr ng-if="valueform.$visible"> <td> <input ng-model="setting.propertyKey" pu-elastic-input pu-ela...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L14 |...erpreterProperty(setting.id)"> </div>   </table> <form editable-form name="valueform" onaftersave="up...
[INFO]                                                       ^ Tag must be paired, missing: [ </td></td></td></tr></td></td></td></tr></th></th></th></tr> ], start tag match failed [ <td> ] on line 14. (tag-pair)
[INFO] 
[INFO]    src/main/webapp/views/main.html
[INFO]       L13 |...that enables interactive data analytics.<br>You can make beautiful data-driven, interactive, collabor...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...e document with SQL, code and even more!<br> <div class="row"> <div class="col-md-4"> <h4>Notebook</h...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...rget="_blank">Zeppelin documentation</a><br> <h4>Community</h4> Please feel free to help us to improv...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...el free to help us to improve Zeppelin, <br> Any contribution are welcome!<br><br> <a style="text-dec...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...elin, <br> Any contribution are welcome!<br><br> <a style="text-decoration: none" href="http://zeppel...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |..., <br> Any contribution are welcome!<br><br> <a style="text-decoration: none" href="http://zeppelin.i...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...lass="fa fa-users"></i> Mailing list</a><br> <a style="text-decoration: none" href="https://issues.ap...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...ass="fa fa-bug"></i> Issues tracking</a><br> <a style="text-decoration: none" href="https://github.co...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...b"></i> Github</a> </div> </div> </div> <br><br><br> </div>
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |.../i> Github</a> </div> </div> </div> <br><br><br> </div>
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...Github</a> </div> </div> </div> <br><br><br> </div>
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO] 
[INFO]    src/main/webapp/views/notebooks.html
[INFO]       L13 |... && !paragraphUrl"> <h3 class="new_h3"> <input type="text" class="form-control2" placeholder="{{note....
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L13 |... with cron scheduler. Either choose from<br>preset or write your own <a href="http://www.quartz-sched...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...r" target="_blank">cron expression</a>. <br><br> <span>- Preset</span> <a ng-repeat="cr in cronOption...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...arget="_blank">cron expression</a>. <br><br> <span>- Preset</span> <a ng-repeat="cr in cronOption" ty...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...pointer" dropdown-input>{{cr.name}}</a> <br><br> <span>- Cron expression</span> <input type="text" ng...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...ter" dropdown-input>{{cr.name}}</a> <br><br> <span>- Cron expression</span> <input type="text" ng-mod...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...<br><br> <span>- Cron expression</span> <input type="text" ng-model="note.config.cron" ng-change="set...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L13 |...etting"> <div> <h4>Settings</h4> </div> <hr> <div> <h5>Interpreter binding</h5> <p> Bind interpreter ...
[INFO]                                                       ^ The empty tag : [ hr ] must be self closed. (tag-self-close)
[INFO]       L13 |... Drag and drop to reorder interpreters. <br> The first interpreter on the list becomes default. To cr...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO]       L13 |...pan></small></div> </div> </div> </div> <br> <div> <button class="btn btn-primary" ng-click="saveSett...
[INFO]                                                       ^ The empty tag : [ br ] must be self closed. (tag-self-close)
[INFO] 
[INFO]    src/main/webapp/views/paragraph.html
[INFO]       L13 |..."{{paragraph.id}}_title" class="title"> <input type="text" placeholder="Edit title" ng-model="paragra...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L17 |...e.name}}</label> <div class="col-sm-3"> <input class="form-control input-sm" ng-if="!paragraph.settin...
[INFO]                                                       ^ The empty tag : [ input ] must be self closed. (tag-self-close)
[INFO]       L27 |...adResultType(paragraph.result)"> </div> <img id="{{paragraph.id}}_img" ng-if="paragraph.result.type =...
[INFO]                                                       ^ The empty tag : [ img ] must be self closed. (tag-self-close)
[INFO] 
[INFO] >> 50 errors in 6 files
[INFO] Warning: Task "htmlhint:src" failed. Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.
[INFO] 
[INFO] 
[INFO] Execution Time (2016-07-07 19:42:36 UTC)
[INFO] loading tasks  214ms  ▇▇▇▇▇▇▇ 13%
[INFO] jshint:all      1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 80%
[INFO] htmlhint:src   106ms  ▇▇▇▇ 7%
[INFO] Total 1.6s
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.481 s
[INFO] Finished at: 2016-07-07T12:42:37-07:00
[INFO] Final Memory: 21M/228M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:grunt (grunt build) on project zeppelin-web: Failed to run task: 'grunt build --no-color' failed. (error code 3) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by Leemoonsoo** [comment]
nevermind, errors gone after i remove `zeppelin-web/src/main/webapp` dir

**Pull request closed without merging**
