### PR TITLE
ZEPPELIN-3061: Updated the SecurityUtils to add Shiro's custom realm functionality

### PR DESCRIPTION
**Pull request by jithinchandranj**
security functionality for CAS implementation.

### What is this PR for?
Updated the security functionality to retrieve roles for a logged in user, when the security is implemented using Shiro's custom realm implementation.

### What type of PR is it?
Improvement

### Todos
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-3061

### How should this be tested?
Unit tests have been added

### CODE REVIEW

**Comment by tinkoff-dwh** [comment]
Thanks @jithinchandranj. Could you add test case for new functionality?

**Comment by jithinchandranj** [comment]
Hi @tinkoff-dwh ,
Attached test case for the custom realm functionality.

**Comment by tinkoff-dwh** [comment]
check jobs in Jenkins. try to merge the latest changes from master.

**Comment by jithinchandranj** [comment]
Thank @tinkoff-dwh , latest commits are merged to the branch, and the PR is updated but one jenkins job is still failing for some reason that is not relevant I guess.

**Comment by felixcheung** [comment]
@prabhjyotsingh

**Comment by prabhjyotsingh** [comment]
This looks OK to me.
@jithinchandranj  can you add some a small note [here](https://github.com/apache/zeppelin/blob/master/docs/setup/security/shiro_authentication.md#configure-realm-optional), on how to use CAS as well.

**Comment by jithinchandranj** [comment]
Hi @prabhjyotsingh ,

Note is updated and PR is raised:
https://github.com/apache/zeppelin/pull/2720

**Comment by prabhjyotsingh** [comment]
Looks good.

**Pull request closed without merging**
