### PR TITLE
[minor]  fix typo

### PR DESCRIPTION
**Pull request by Trevor-zhang**
spelling mistake

### CODE REVIEW

**Comment by zjffdu** [comment]
Thanks @Trevor-zhang for the contribution, could you update the title as [minor][what does this PR do]

**Comment by Trevor-zhang** [comment]
change LuceneSearch.java   spelling mistake
`logger.error("Failed to updaet index of notebook {}", noteId, e);`
to
logger.error("Failed to update index of notebook {}", noteId, e);

**Comment by Trevor-zhang** [comment]
> Thanks @Trevor-zhang for the contribution, could you update the title as [minor][what does this PR do]

done

**Comment by zjffdu** [comment]
Thanks @Trevor-zhang will merge it soon

**Pull request closed without merging**
