### PR TITLE
[MINOR] Small ui modification in notebook actionbar

### PR DESCRIPTION
**Pull request by minahlee**
### What is this PR for?
Small ui improvements
 - Change keyboard shortcut icon
 - Modify commit container style
 - Change table asc/desc icon
 - Change interpreter create button font

### What type of PR is it?
Improvement

### Screenshots (if appropriate)
**Before**
screen shot 2016-06-13 at 12 55 41 pm

**After**
screen shot 2016-06-13 at 12 55 54 pm

**Before**
screen shot 2016-06-13 at 1 07 15 pm

**After**
screen shot 2016-06-13 at 1 07 26 pm

**Before**
screen shot 2016-06-18 at 11 08 20 am

**After**
screen shot 2016-06-21 at 2 17 38 am

**Before**
screen shot 2016-06-14 at 4 43 58 pm

**After**
screen shot 2016-06-14 at 4 43 20 pm

**Before**
screen shot 2016-06-14 at 9 38 05 pm

**After**
screen shot 2016-06-14 at 9 37 34 pm

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? Screenshot needs to be updated

### CODE REVIEW

**Comment by khalidhuseynov** [comment]
thanks for fixing this UI issues! LGTM

**Comment by corneadoug** [comment]
LGTM

**Comment by astroshim** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
LGTM 👍

**Comment by minahlee** [comment]
I made one more change in table ascending, descending icon. Please review.

**Comment by AhyoungRyu** [comment]
@minahlee Tested it and looks good :)

**Comment by corneadoug** [comment]
Merging if there is no more discussions

**Comment by minahlee** [comment]
Rebased master and updated screenshot in description

**Comment by minahlee** [comment]
Selenium test passes after rebasing master

**Pull request closed without merging**
