### PR TITLE
[ZEPPELIN-1831] Fix paragraph control dropdown alignment

### PR DESCRIPTION
**Pull request by marchpig**
### What is this PR for?
Paragraph control dropdown is displayed outside when the browser width is small.
To fix this problem, this PR uses `.dropdown-menu-right` bootstrap css class to make the dropdown right aligned with its parent so that it is always displayed inside of the paragraph.

ref. http://v4-alpha.getbootstrap.com/components/dropdowns/#menu-alignment

### What type of PR is it?
Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/ZEPPELIN-1831

### How should this be tested?
Decrease browser width and click a paragraph control icon.

### Screenshots (if appropriate)
[Before]
paragraph-dropdown-before

[After]
paragraph-dropdown-after

### Questions:
* Does the licenses files need update? No
* Is there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by astroshim** [comment]
Thanks for contribution!
Looks great to me.

**Comment by AhyoungRyu** [comment]
CI has been failed only in [Selenium test](https://travis-ci.org/apache/zeppelin/jobs/184584526) like below.
```
[36mTests: succeeded 17, failed 1, canceled 0, ignored 0, pending 0[0m
[31m*** 1 TEST FAILED ***[0m
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project zeppelin-display_2.10: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zeppelin-display_2.10
```
Looks irrelevant with this change. LGTM 👍

**Comment by prabhjyotsingh** [comment]
@marchpig can you resolve conflicting file ?

**Comment by marchpig** [comment]
@prabhjyotsingh I resolved the conflict.

**Comment by Leemoonsoo** [comment]
Tested and LGTM.

Merge to master if there're no further comments.

**Pull request closed without merging**
