### PR TITLE
[ZEPPELIN-2309] Backport maven and npm repo config to 0.7

### PR DESCRIPTION
**Pull request by andreaTP**
### What is this PR for?
Backport configuration settings for maven central and npm repository to 0.7.

### What type of PR is it?
Improvement

### What is the Jira issue?
[ZEPPELIN-2309]

### CODE REVIEW

**Comment by Leemoonsoo** [comment]
Thanks @andreaTP.
LGTM and merge to branch-0.7 if no further discussions.

**Comment by andreaTP** [comment]
Great! Thanks

**Comment by Leemoonsoo** [comment]
Just merged to branch 0.7. but @asfgit did not automatically closed this PR. @andreaTP could you close this PR manually?

**Comment by andreaTP** [comment]
Sure. Thanks

**Pull request closed without merging**
